vocab = [
  { hanzi: '他们的爱情很美好', pinyin: 'Tāmen de àiqíng hěn měihǎo', meaning: 'Tình yêu của họ rất đẹp' },
{ hanzi: '我已经安排好了行程', pinyin: 'Wǒ yǐjīng ānpái hǎo le xíngchéng', meaning: 'Tôi đã sắp xếp xong hành trình' },
{ hanzi: '这个地方很安全', pinyin: 'Zhège dìfāng hěn ānquán', meaning: 'Nơi này rất an toàn' },
{ hanzi: '我们必须按时完成任务', pinyin: 'Wǒmen bìxū ànshí wánchéng rènwù', meaning: 'Chúng ta phải hoàn thành nhiệm vụ đúng giờ' },
{ hanzi: '请按照说明操作', pinyin: 'Qǐng ànzhào shuōmíng cāozuò', meaning: 'Vui lòng làm theo hướng dẫn' },
{ hanzi: '他的考试成绩是百分之九十', pinyin: 'Tā de kǎoshì chéngjī shì bǎifēn zhī jiǔshí', meaning: 'Điểm thi của anh ấy là 90%' },
{ hanzi: '你真棒！', pinyin: 'Nǐ zhēn bàng!', meaning: 'Bạn thật tuyệt!' },
{ hanzi: '我喜欢吃包子', pinyin: 'Wǒ xǐhuān chī bāozi', meaning: 'Tôi thích ăn bánh bao' },
{ hanzi: '我们要保护环境', pinyin: 'Wǒmen yào bǎohù huánjìng', meaning: 'Chúng ta cần bảo vệ môi trường' },
{ hanzi: '我保证完成任务', pinyin: 'Wǒ bǎozhèng wánchéng rènwù', meaning: 'Tôi cam đoan hoàn thành nhiệm vụ' },
{ hanzi: '我报名参加了比赛', pinyin: 'Wǒ bàomíng cānjiā le bǐsài', meaning: 'Tôi đã đăng ký tham gia cuộc thi' },
{ hanzi: '他抱了我', pinyin: 'Tā bào le wǒ', meaning: 'Anh ấy đã ôm tôi' },
{ hanzi: '很抱歉，我来晚了', pinyin: 'Hěn bàoqiàn, wǒ lái wǎn le', meaning: 'Xin lỗi, tôi đến muộn' },
{ hanzi: '价格翻了两倍', pinyin: 'Jiàgé fān le liǎng bèi', meaning: 'Giá cả tăng gấp đôi' },
{ hanzi: '本来我不想去的', pinyin: 'Běnlái wǒ bù xiǎng qù de', meaning: 'Ban đầu tôi không muốn đi' },
{ hanzi: '他有点笨，但很努力', pinyin: 'Tā yǒudiǎn bèn, dàn hěn nǔlì', meaning: 'Anh ấy hơi ngốc, nhưng rất nỗ lực' },
{ hanzi: '比如说，苹果和香蕉', pinyin: 'Bǐrú shuō, píngguǒ hé xiāngjiāo', meaning: 'Ví dụ như, táo và chuối' },
{ hanzi: '他今年大学毕业了', pinyin: 'Tā jīnnián dàxué bìyè le', meaning: 'Năm nay anh ấy tốt nghiệp đại học' },
{ hanzi: '这本书我看三遍了', pinyin: 'Zhè běn shū wǒ kàn sān biàn le', meaning: 'Tôi đã đọc cuốn sách này ba lần' },
{ hanzi: '他的中文发音很标准', pinyin: 'Tā de Zhōngwén fāyīn hěn biāozhǔn', meaning: 'Phát âm tiếng Trung của anh ấy rất chuẩn' },
{ hanzi: '请填写这张表格', pinyin: 'Qǐng tiánxiě zhè zhāng biǎogé', meaning: 'Vui lòng điền vào mẫu đơn này' },
{ hanzi: '他表示同意', pinyin: 'Tā biǎoshì tóngyì', meaning: 'Anh ấy biểu thị đồng ý' },
{ hanzi: '她的表演很精彩', pinyin: 'Tā de biǎoyǎn hěn jīngcǎi', meaning: 'Màn biểu diễn của cô ấy rất xuất sắc' },
{ hanzi: '老师表扬了他', pinyin: 'Lǎoshī biǎoyáng le tā', meaning: 'Thầy giáo khen ngợi anh ấy' },
{ hanzi: '我喜欢吃饼干', pinyin: 'Wǒ xǐhuān chī bǐnggān', meaning: 'Tôi thích ăn bánh quy' },
{ hanzi: '她聪明并且努力', pinyin: 'Tā cōngmíng bìngqiě nǔlì', meaning: 'Cô ấy thông minh và chăm chỉ' },
{ hanzi: '他是一个博士', pinyin: 'Tā shì yīgè bóshì', meaning: 'Anh ấy là một tiến sĩ' },
{ hanzi: '我不得不去工作', pinyin: 'Wǒ bùdébù qù gōngzuò', meaning: 'Tôi không thể không đi làm' },
{ hanzi: '不管天气如何，我都会去', pinyin: 'Bùguǎn tiānqì rúhé, wǒ dōu huì qù', meaning: 'Bất kể thời tiết thế nào, tôi cũng sẽ đi' },
{ hanzi: '不过，这样更好', pinyin: 'Bùguò, zhèyàng gèng hǎo', meaning: 'có điều, như vậy tốt hơn' },
{ hanzi: '他不仅聪明，而且很努力', pinyin: 'Tā bùjǐn cōngmíng, érqiě hěn nǔlì', meaning: 'Anh ấy không chỉ thông minh mà còn rất chăm chỉ' },
{ hanzi: '这只是问题的一部分', pinyin: 'Zhè zhǐshì wèntí de yī bùfèn', meaning: 'Đây chỉ là một phần của vấn đề' },
{ hanzi: '请把桌子擦干净', pinyin: 'Qǐng bǎ zhuōzi cā gānjìng', meaning: 'Hãy lau sạch bàn' },
{ hanzi: '我猜他不会来', pinyin: 'Wǒ cāi tā bù huì lái', meaning: 'Tôi đoán anh ấy sẽ không đến' },
{ hanzi: '请准备好材料', pinyin: 'Qǐng zhǔnbèi hǎo cáiliào', meaning: 'Hãy chuẩn bị sẵn tài liệu' },
{ hanzi: '我们要去参观博物馆', pinyin: 'Wǒmen yào qù cānguān bówùguǎn', meaning: 'Chúng ta sẽ đi tham quan bảo tàng' },
{ hanzi: '我们在餐厅吃饭', pinyin: 'Wǒmen zài cāntīng chīfàn', meaning: 'Chúng tôi ăn ở nhà hàng' },
{ hanzi: '厕所在那边', pinyin: 'Cèsuǒ zài nà biān', meaning: 'Nhà vệ sinh ở đằng kia' },
{ hanzi: '我们差不多同岁', pinyin: 'Wǒmen chàbùduō tóng suì', meaning: 'Chúng ta gần bằng tuổi nhau' },
{ hanzi: '我们参观了长城', pinyin: 'Wǒmen cānguān le Chángchéng', meaning: 'Chúng tôi đã tham quan Vạn Lý Trường Thành' },
{ hanzi: '长江是中国最长的河流', pinyin: 'Chángjiāng shì Zhōngguó zuì cháng de héliú', meaning: 'Trường Giang là con sông dài nhất Trung Quốc' },
{ hanzi: '你尝过这道菜吗？', pinyin: 'Nǐ cháng guò zhè dào cài ma?', meaning: 'Bạn đã từng thử món này chưa?' },
{ hanzi: '这场比赛很重要', pinyin: 'Zhè chǎng bǐsài hěn zhòngyào', meaning: 'Trận đấu này rất quan trọng' },
{ hanzi: '他超过了我', pinyin: 'Tā chāoguò le wǒ', meaning: 'Anh ấy vượt qua tôi' },
{ hanzi: '她终于成功了', pinyin: 'Tā zhōngyú chénggōng le', meaning: 'Cuối cùng cô ấy đã thành công' },
{ hanzi: '他想成为医生', pinyin: 'Tā xiǎng chéngwéi yīshēng', meaning: 'Anh ấy muốn trở thành bác sĩ' },
{ hanzi: '他是个诚实的人', pinyin: 'Tā shì gè chéngshí de rén', meaning: 'Anh ấy là người thật thà' },
{ hanzi: '我们乘坐飞机去北京', pinyin: 'Wǒmen chéngzuò fēijī qù Běijīng', meaning: 'Chúng tôi đi máy bay đến Bắc Kinh' },
{ hanzi: '她的消息让我很吃惊', pinyin: 'Tā de xiāoxi ràng wǒ hěn chījīng', meaning: 'Tin tức của cô ấy làm tôi rất ngạc nhiên' },
{ hanzi: '我重新开始学习中文', pinyin: 'Wǒ chóngxīn kāishǐ xuéxí Zhōngwén', meaning: 'Tôi bắt đầu học lại tiếng Trung' },
{ hanzi: '请不要在这里抽烟', pinyin: 'Qǐng bùyào zài zhèlǐ chōuyān', meaning: 'Vui lòng không hút thuốc ở đây' },
{ hanzi: '他经常出差', pinyin: 'Tā jīngcháng chūchāi', meaning: 'Anh ấy thường đi công tác' },
{ hanzi: '我们早上七点出发', pinyin: 'Wǒmen zǎoshang qī diǎn chūfā', meaning: 'Chúng tôi khởi hành lúc 7 giờ sáng' },
{ hanzi: '我在越南出生', pinyin: 'Wǒ zài Yuènán chūshēng', meaning: 'Tôi sinh ra ở Việt Nam' },
{ hanzi: '问题突然出现了', pinyin: 'Wèntí tūrán chūxiàn le', meaning: 'Vấn đề đột nhiên xuất hiện' },
{ hanzi: '她在厨房做饭', pinyin: 'Tā zài chúfáng zuòfàn', meaning: 'Cô ấy nấu ăn trong bếp' },
{ hanzi: '请发送传真', pinyin: 'Qǐng fāsòng chuánzhēn', meaning: 'Vui lòng gửi fax' },
{ hanzi: '窗户开着', pinyin: 'Chuānghu kāizhe', meaning: 'Cửa sổ đang mở' },
{ hanzi: '请学习这些词语', pinyin: 'Qǐng xuéxí zhèxiē cíyǔ', meaning: 'Vui lòng học những từ này' },
{ hanzi: '我从来没见过他', pinyin: 'Wǒ cónglái méi jiànguò tā', meaning: 'Tôi chưa bao giờ gặp anh ấy' },
{ hanzi: '他做事很粗心', pinyin: 'Tā zuòshì hěn cūxīn', meaning: 'Anh ấy làm việc rất cẩu thả' },
{ hanzi: '我在银行存了钱', pinyin: 'Wǒ zài yínháng cún le qián', meaning: 'Tôi gửi tiền vào ngân hàng' },
{ hanzi: '这是我们的错误', pinyin: 'Zhè shì wǒmen de cuòwù', meaning: 'Đây là lỗi của chúng tôi' },
{ hanzi: '这是正确的答案', pinyin: 'Zhè shì zhèngquè de dá\'àn', meaning: 'Đây là đáp án đúng' },
{ hanzi: '她打扮得很漂亮', pinyin: 'Tā dǎbàn de hěn piàoliang', meaning: 'Cô ấy trang điểm rất đẹp' },
{ hanzi: '对不起，打扰一下', pinyin: 'Duìbùqǐ, dǎrǎo yīxià', meaning: 'Xin lỗi, làm phiền một chút' },
{ hanzi: '请帮我打印这份文件', pinyin: 'Qǐng bāng wǒ dǎyìn zhè fèn wénjiàn', meaning: 'Vui lòng in giúp tôi tài liệu này' },
{ hanzi: '他向我打招呼', pinyin: 'Tā xiàng wǒ dǎzhāohū', meaning: 'Anh ấy chào tôi' },
{ hanzi: '商店正在打折', pinyin: 'Shāngdiàn zhèngzài dǎzhé', meaning: 'Cửa hàng đang giảm giá' },
{ hanzi: '我不喜欢打针', pinyin: 'Wǒ bù xǐhuān dǎzhēn', meaning: 'Tôi không thích tiêm' },
{ hanzi: '他大概十岁', pinyin: 'Tā dàgài shí suì', meaning: 'Cậu ấy khoảng mười tuổi' },
{ hanzi: '我们去了大使馆', pinyin: 'Wǒmen qùle dàshǐguǎn', meaning: 'Chúng tôi đã đến đại sứ quán' },
{ hanzi: '他们大约八点到', pinyin: 'Tāmen dàyuē bā diǎn dào', meaning: 'Họ đến khoảng tám giờ' },
{ hanzi: '张大夫在医院工作', pinyin: 'Zhāng dàifū zài yīyuàn gōngzuò', meaning: 'Bác sĩ Trương làm việc ở bệnh viện' },
{ hanzi: '她戴着一顶帽子', pinyin: 'Tā dàizhe yī dǐng màozi', meaning: 'Cô ấy đội một chiếc mũ' },
{ hanzi: '我当老师', pinyin: 'Wǒ dāng lǎoshī', meaning: 'Tôi làm giáo viên' },
{ hanzi: '当时我在学校', pinyin: 'Dāngshí wǒ zài xuéxiào', meaning: 'Lúc đó tôi đang ở trường' },
{ hanzi: '请小心那把刀', pinyin: 'Qǐng xiǎoxīn nà bǎ dāo', meaning: 'Hãy cẩn thận với con dao đó' },
{ hanzi: '导游带我们参观了城市', pinyin: 'Dǎoyóu dài wǒmen cānguān le chéngshì', meaning: 'Hướng dẫn viên đã dẫn chúng tôi tham quan thành phố' },
{ hanzi: '我们到处找你', pinyin: 'Wǒmen dàochù zhǎo nǐ', meaning: 'Chúng tôi tìm bạn khắp nơi' },
{ hanzi: '你到底在做什么？', pinyin: 'Nǐ dàodǐ zài zuò shénme?', meaning: 'Rốt cuộc bạn đang làm gì vậy?' },
{ hanzi: '他把茶倒在了桌子上', pinyin: 'Tā bǎ chá dào zài le zhuōzi shàng', meaning: 'Anh ấy đổ trà lên bàn' },
{ hanzi: '我向你道歉', pinyin: 'Wǒ xiàng nǐ dàoqiàn', meaning: 'Tôi xin lỗi bạn' },
{ hanzi: '他很得意自己的成绩', pinyin: 'Tā hěn déyì zìjǐ de chéngjī', meaning: 'Anh ấy rất tự hào về thành tích của mình' },
{ hanzi: '她学汉语学得很好', pinyin: 'Tā xué Hànyǔ xué de hěn hǎo', meaning: 'Cô ấy học tiếng Hán rất giỏi' },
{ hanzi: '请拿好你的登机牌', pinyin: 'Qǐng ná hǎo nǐ de dēngjīpái', meaning: 'Vui lòng giữ kỹ thẻ lên máy bay của bạn' },
{ hanzi: '我喜欢听音乐、看电影等等', pinyin: 'Wǒ xǐhuān tīng yīnyuè, kàn diànyǐng, děng děng', meaning: 'Tôi thích nghe nhạc, xem phim,vv..' },
{ hanzi: '一场大雨过后，地势低的地方积满了雨水', pinyin: 'Yī chǎng dàyǔ guòhòu, dìshì dī dì dìfāng jī mǎnle yǔshuǐ', meaning: 'Sau 1 trận mưa lớn, nơi địa thế thấp tích đầy nước mưa' },
{ hanzi: '快到年底时谁都忙起来', pinyin: 'Kuài dào niándǐ shí shéi dōu máng qǐlái', meaning: 'Lúc sắp đến cuối năm ai cũng trở nên bận rộn' },
{ hanzi: '会议地点在这里', pinyin: 'Huìyì dìdiǎn zài zhèlǐ', meaning: 'Địa điểm cuộc họp ở đây' },
{ hanzi: '地球是圆的', pinyin: 'Dìqiú shì yuán de', meaning: 'Trái đất là hình tròn' },
{ hanzi: '请告诉我你的地址', pinyin: 'Qǐng gàosu wǒ nǐ de dìzhǐ', meaning: 'Hãy cho tôi biết địa chỉ của bạn' },
{ hanzi: '我们需要进行调查', pinyin: 'Wǒmen xūyào jìnxíng diàochá', meaning: 'Chúng tôi cần tiến hành điều tra' },
{ hanzi: '他掉了钥匙', pinyin: 'Tā diào le yàoshi', meaning: 'Anh ấy làm rơi chìa khóa' },
{ hanzi: '我的书丢了', pinyin: 'Wǒ de shū diū le', meaning: 'Sách của tôi bị mất rồi' },
{ hanzi: '他的动作很快', pinyin: 'Tā de dòngzuò hěn kuài', meaning: 'Hành động của anh ấy rất nhanh' },
{ hanzi: '上班时间常常堵车', pinyin: 'Shàngbān shíjiān chángcháng dǔchē', meaning: 'Giờ đi làm thường hay tắc đường' },
{ hanzi: '我肚子疼', pinyin: 'Wǒ dùzi téng', meaning: 'Tôi đau bụng' },
{ hanzi: '他发了一条短信', pinyin: 'Tā fā le yī tiáo duǎnxìn', meaning: 'Anh ấy gửi một tin nhắn' },
{ hanzi: '他们在进行对话', pinyin: 'Tāmen zài jìnxíng duìhuà', meaning: 'Họ đang đối thoại' },
{ hanzi: '银行在街的对面', pinyin: 'Yínháng zài jiē de duìmiàn', meaning: 'Ngân hàng ở phía đối diện của đường' },
{ hanzi: '对于这个问题，我有不同的看法', pinyin: 'Duìyú zhège wèntí, wǒ yǒu bùtóng de kànfǎ', meaning: 'Đối với vấn đề này, tôi có quan điểm khác' },
{ hanzi: '儿童需要很多关爱', pinyin: 'Értóng xūyào hěn duō guān\'ài', meaning: 'Trẻ em cần nhiều sự quan tâm' },
{ hanzi: '他聪明而且努力', pinyin: 'Tā cōngmíng érqiě nǔlì', meaning: 'Anh ấy thông minh và chăm chỉ' },
{ hanzi: '事故晚上发生', pinyin: 'Shìgù wǎnshàng fāshēng', meaning: 'Tai nạn xảy ra vào buổi tối' },
{ hanzi: '城市在快速发展', pinyin: 'Chéngshì zài kuàisù fāzhǎn', meaning: 'Thành phố đang phát triển nhanh chóng' },
{ hanzi: '每个人都应该遵守法律', pinyin: 'Měi gèrén dōu yīnggāi zūnshǒu fǎlǜ', meaning: 'Mỗi người đều nên tuân thủ pháp luật' },
{ hanzi: '请把它翻译成越南语', pinyin: 'Qǐng bǎ tā fānyì chéng Yuènán yǔ', meaning: 'Làm ơn dịch nó sang tiếng Việt' },
{ hanzi: '我有些烦恼', pinyin: 'Wǒ yǒu xiē fánnǎo', meaning: 'Tôi có chút phiền muộn' },
{ hanzi: '他反对这个计划', pinyin: 'Tā fǎnduì zhège jìhuà', meaning: 'Anh ấy phản đối kế hoạch này' },
{ hanzi: '他有很多方法', pinyin: 'Tā yǒu hěn duō fāngfǎ', meaning: 'Anh ấy có nhiều phương pháp' },
{ hanzi: '我们在这个方面有很多经验', pinyin: 'Wǒmen zài zhège fāngmiàn yǒu hěn duō jīngyàn', meaning: 'Chúng tôi có nhiều kinh nghiệm trong lĩnh vực này' },
{ hanzi: '我们向北走，方向正确', pinyin: 'Wǒmen xiàng běi zǒu, fāngxiàng zhèngquè', meaning: 'Chúng tôi đi về phía bắc, hướng đi đúng' },
{ hanzi: '房东每天早上都来', pinyin: 'Fángdōng měitiān zǎoshang dōu lái', meaning: 'Chủ nhà đến mỗi buổi sáng' },
{ hanzi: '他放弃了这个机会', pinyin: 'Tā fàngqì le zhège jīhuì', meaning: 'Anh ấy đã từ bỏ cơ hội này' },
{ hanzi: '我们放暑假了', pinyin: 'Wǒmen fàng shǔjià le', meaning: 'Chúng tôi đã nghỉ hè' },
{ hanzi: '放松一下，别紧张', pinyin: 'Fàngsōng yīxià, bié jǐnzhāng', meaning: 'Thư giãn một chút, đừng căng thẳng' },
{ hanzi: '这是一份礼物', pinyin: 'Zhè shì yī fèn lǐwù', meaning: 'Đây là một món quà' },
{ hanzi: '他有丰富的经验', pinyin: 'Tā yǒu fēngfù de jīngyàn', meaning: 'Anh ấy có kinh nghiệm phong phú' },
{ hanzi: '你得早点起床，否则会迟到', pinyin: 'Nǐ děi zǎodiǎn qǐchuáng, fǒuzé huì chídào', meaning: 'Bạn phải dậy sớm, nếu không sẽ bị trễ' },
{ hanzi: '你的答案符合要求', pinyin: 'Nǐ de dá\'àn fúhé yāoqiú', meaning: 'Câu trả lời của bạn đáp ứng yêu cầu' },
{ hanzi: '我的父亲很勤劳', pinyin: 'Wǒ de fùqīn hěn qínláo', meaning: 'Bố tôi rất chăm chỉ' },
{ hanzi: '我们可以用信用卡付款', pinyin: 'Wǒmen kěyǐ yòng xìnyòngkǎ fùkuǎn', meaning: 'Chúng ta có thể thanh toán bằng thẻ tín dụng' },
{ hanzi: '他负责这项工作', pinyin: 'Tā fùzé zhè xiàng gōngzuò', meaning: 'Anh ấy phụ trách công việc này' },
{ hanzi: '请帮我复印这份文件', pinyin: 'Qǐng bāng wǒ fùyìn zhè fèn wénjiàn', meaning: 'Vui lòng photo giúp tôi tài liệu này' },
{ hanzi: '这个问题很复杂', pinyin: 'Zhège wèntí hěn fùzá', meaning: 'Vấn đề này rất phức tạp' },
{ hanzi: '他们家很富', pinyin: 'Tāmen jiā hěn fù', meaning: 'Nhà họ rất giàu' },
{ hanzi: '我们需要改变计划', pinyin: 'Wǒmen xūyào gǎibiàn jìhuà', meaning: 'Chúng ta cần thay đổi kế hoạch' },
{ hanzi: '为我们的成功干杯！', pinyin: 'Wèi wǒmen de chénggōng gānbēi!', meaning: 'Cạn ly vì thành công của chúng ta!' },
{ hanzi: '我们必须赶上火车', pinyin: 'Wǒmen bìxū gǎn shàng huǒchē', meaning: 'Chúng ta phải kịp chuyến tàu' },
{ hanzi: '我不敢说', pinyin: 'Wǒ bù gǎn shuō', meaning: 'Tôi không dám nói' },
{ hanzi: '她的故事让我很感动', pinyin: 'Tā de gùshì ràng wǒ hěn gǎndòng', meaning: 'Câu chuyện của cô ấy làm tôi rất cảm động' },
{ hanzi: '我感觉很累', pinyin: 'Wǒ gǎnjué hěn lèi', meaning: 'Tôi cảm thấy rất mệt' },
{ hanzi: '他们之间有很深的感情', pinyin: 'Tāmen zhī jiān yǒu hěn shēn de gǎnqíng', meaning: 'Giữa họ có tình cảm rất sâu đậm' },
{ hanzi: '非常感谢你的帮助', pinyin: 'Fēicháng gǎnxiè nǐ de bāngzhù', meaning: 'Rất cảm ơn sự giúp đỡ của bạn' },
{ hanzi: '天气干燥', pinyin: 'Tiānqì gānzào', meaning: 'Thời tiết khô ráo' },
{ hanzi: '我刚到家', pinyin: 'Wǒ gāng dào jiā', meaning: 'Tôi vừa về đến nhà' },
{ hanzi: '我们在高速公路上开车', pinyin: 'Wǒmen zài gāosù gōnglù shàng kāichē', meaning: 'Chúng tôi lái xe trên đường cao tốc' },
{ hanzi: '我的胳膊疼', pinyin: 'Wǒ de gēbo téng', meaning: 'Cánh tay của tôi đau' },
{ hanzi: '各种水果都很好吃', pinyin: 'Gè zhǒng shuǐguǒ dōu hěn hǎochī', meaning: 'Các loại trái cây đều rất ngon' },
{ hanzi: '他每个月的工资很高', pinyin: 'Tā měi gè yuè de gōngzī hěn gāo', meaning: 'Lương hàng tháng của anh ấy rất cao' },
{ hanzi: '我们走了一公里', pinyin: 'Wǒmen zǒu le yī gōnglǐ', meaning: 'Chúng tôi đã đi được một kilomet' },
{ hanzi: '他功夫很好', pinyin: 'Tā gōngfu hěn hǎo', meaning: 'Anh ấy giỏi võ' },
{ hanzi: '我们有共同的兴趣爱好', pinyin: 'Wǒmen yǒu gòngtóng de xìngqù àihào', meaning: 'Chúng tôi có sở thích chung' },
{ hanzi: '我喜欢购物', pinyin: 'Wǒ xǐhuān gòuwù', meaning: 'Tôi thích mua sắm' },
{ hanzi: '这些水果够我们吃了', pinyin: 'Zhèxiē shuǐguǒ gòu wǒmen chī le', meaning: 'Những trái cây này đủ cho chúng ta ăn' },
{ hanzi: '我估计他今天不会来了', pinyin: 'Wǒ gūjì tā jīntiān bù huì lái le', meaning: 'Tôi đoán anh ấy sẽ không đến hôm nay' },
{ hanzi: '他经常鼓励我', pinyin: 'Tā jīngcháng gǔlì wǒ', meaning: 'Anh ấy thường khích lệ tôi' },
{ hanzi: '他故意不回答我的问题', pinyin: 'Tā gùyì bù huídá wǒ de wèntí', meaning: 'Anh ấy cố tình không trả lời câu hỏi của tôi' },
{ hanzi: '这个商店的顾客很多', pinyin: 'Zhège shāngdiàn de gùkè hěn duō', meaning: 'Cửa hàng này có nhiều khách hàng' },
{ hanzi: '请把衣服挂起来', pinyin: 'Qǐng bǎ yīfu guà qǐlái', meaning: 'Vui lòng treo quần áo lên' },
{ hanzi: '这是问题的关键', pinyin: 'Zhè shì wèntí de guānjiàn', meaning: 'Đây là điểm mấu chốt của vấn đề' },
{ hanzi: '观众们都很满意', pinyin: 'Guānzhòngmen dōu hěn mǎnyì', meaning: 'Khán giả đều rất hài lòng' },
{ hanzi: '他负责管理这个项目', pinyin: 'Tā fùzé guǎnlǐ zhège xiàngmù', meaning: 'Anh ấy phụ trách quản lý dự án này' },
{ hanzi: '我们都吃光了你才来', pinyin: 'Wǒmen dōu chī guāngle nǐ cái lái', meaning: 'Tụi tôi ăn hết rồi bạn mới tới' },
{ hanzi: '我每天听广播', pinyin: 'Wǒ měitiān tīng guǎngbò', meaning: 'Tôi nghe đài phát thanh mỗi ngày' },
{ hanzi: '电视上有很多广告', pinyin: 'Diànshì shàng yǒu hěn duō guǎnggào', meaning: 'Trên TV có rất nhiều quảng cáo' },
{ hanzi: '我喜欢逛街', pinyin: 'Wǒ xǐhuān guàngjiē', meaning: 'Tôi thích đi dạo phố' },
{ hanzi: '我们需要遵守规定', pinyin: 'Wǒmen xūyào zūnshǒu guīdìng', meaning: 'Chúng ta cần tuân thủ quy định' },
{ hanzi: '你的国籍是什么？', pinyin: 'Nǐ de guójí shì shénme?', meaning: 'Quốc tịch của bạn là gì?' },
{ hanzi: '这是一个国际会议', pinyin: 'Zhè shì yī gè guójì huìyì', meaning: 'Đây là một hội nghị quốc tế' },
{ hanzi: '我喜欢喝果汁', pinyin: 'Wǒ xǐhuān hē guǒzhī', meaning: 'Tôi thích uống nước ép trái cây' },
{ hanzi: '整个过程很复杂', pinyin: 'Zhěnggè guòchéng hěn fùzá', meaning: 'Toàn bộ quá trình rất phức tạp' },
{ hanzi: '海洋很广阔', pinyin: 'Hǎiyáng hěn guǎngkuò', meaning: 'Đại dương rất rộng lớn' },
{ hanzi: '他很害羞', pinyin: 'Tā hěn hàixiū', meaning: 'Anh ấy rất ngại ngùng' },
{ hanzi: '寒假我们去旅行', pinyin: 'Hánjià wǒmen qù lǚxíng', meaning: 'Kỳ nghỉ đông chúng tôi đi du lịch' },
{ hanzi: '他流了很多汗', pinyin: 'Tā liú le hěn duō hàn', meaning: 'Anh ấy đổ rất nhiều mồ hôi' },
{ hanzi: '我们的航班延误了', pinyin: 'Wǒmen de hángbān yánwù le', meaning: 'Chuyến bay của chúng tôi bị hoãn' },
{ hanzi: '这样做有很多好处', pinyin: 'Zhèyàng zuò yǒu hěn duō hǎochù', meaning: 'Làm như vậy có rất nhiều lợi ích' },
{ hanzi: '他好像生病了', pinyin: 'Tā hǎoxiàng shēngbìng le', meaning: 'Anh ấy hình như bị ốm' },
{ hanzi: '请告诉我你的电话号码', pinyin: 'Qǐng gàosù wǒ nǐ de diànhuà hàomǎ', meaning: 'Hãy cho tôi biết số điện thoại của bạn' },
{ hanzi: '他的成绩很合格', pinyin: 'Tā de chéngjì hěn hégé', meaning: 'Thành tích của anh ấy đạt yêu cầu' },
{ hanzi: '这件衣服很合适', pinyin: 'Zhè jiàn yīfú hěn héshì', meaning: 'Bộ quần áo này rất hợp' },
{ hanzi: '他打开了盒子', pinyin: 'Tā dǎkāi le hézi', meaning: 'Anh ấy mở cái hộp ra' },
{ hanzi: '我后悔没去旅行', pinyin: 'Wǒ hòuhuǐ méi qù lǚxíng', meaning: 'Tôi hối hận vì đã không đi du lịch' },
{ hanzi: '这本书很厚', pinyin: 'Zhè běn shū hěn hòu', meaning: 'Cuốn sách này rất dày' },
{ hanzi: '互联网改变了我们的生活', pinyin: 'Hùliánwǎng gǎibiàn le wǒmen de shēnghuó', meaning: 'Internet đã thay đổi cuộc sống của chúng ta' },
{ hanzi: '他们互相帮助', pinyin: 'Tāmen hùxiāng bāngzhù', meaning: 'Họ giúp đỡ lẫn nhau' },
{ hanzi: '护士很辛苦', pinyin: 'Hùshì hěn xīnkǔ', meaning: 'Y tá rất vất vả' },
{ hanzi: '我怀疑他在撒谎', pinyin: 'Wǒ huáiyí tā zài sāhuǎng', meaning: 'Tôi nghi ngờ anh ấy đang nói dối' },
{ hanzi: '这些都是美好的回忆', pinyin: 'Zhèxiē dōu shì měihǎo de huíyì', meaning: 'Đây đều là những kỷ niệm đẹp' },
{ hanzi: '学校组织了很多活动', pinyin: 'Xuéxiào zǔzhī le hěn duō huódòng', meaning: 'Trường học tổ chức nhiều hoạt động' },
{ hanzi: '她很活泼', pinyin: 'Tā hěn huópō', meaning: 'Cô ấy rất hoạt bát' },
{ hanzi: '火很危险', pinyin: 'Huǒ hěn wēixiǎn', meaning: 'Lửa rất nguy hiểm' },
{ hanzi: '他获得了奖学金', pinyin: 'Tā huòdé le jiǎngxuéjīn', meaning: 'Anh ấy đã nhận được học bổng' },
{ hanzi: '我们应该积极面对生活', pinyin: 'Wǒmen yīnggāi jījí miànduì shēnghuó', meaning: 'Chúng ta nên tích cực đối mặt với cuộc sống' },
{ hanzi: '他积累了很多经验', pinyin: 'Tā jīlěi le hěn duō jīngyàn', meaning: 'Anh ấy tích lũy được rất nhiều kinh nghiệm' },
{ hanzi: '基础知识很重要', pinyin: 'Jīchǔ zhīshì hěn zhòngyào', meaning: 'Kiến thức cơ bản rất quan trọng' },
{ hanzi: '听到这个消息我很激动', pinyin: 'Tīngdào zhège xiāoxī wǒ hěn jīdòng', meaning: 'Nghe tin này tôi rất xúc động' },
{ hanzi: '他及时完成了任务', pinyin: 'Tā jíshí wánchéng le rènwù', meaning: 'Anh ấy hoàn thành nhiệm vụ đúng giờ' },
{ hanzi: '即使下雨我们也去', pinyin: 'Jíshǐ xiàyǔ wǒmen yě qù', meaning: 'Dù trời mưa chúng ta cũng đi' },
{ hanzi: '我们需要制定计划', pinyin: 'Wǒmen xūyào zhìdìng jìhuà', meaning: 'Chúng ta cần lập kế hoạch' },
{ hanzi: '记者在现场报道', pinyin: 'Jìzhě zài xiànchǎng bàodǎo', meaning: 'Phóng viên đang tường thuật tại hiện trường' },
{ hanzi: '他对技术很感兴趣', pinyin: 'Tā duì jìshù hěn gǎn xìngqù', meaning: 'Anh ấy rất hứng thú với công nghệ' },
{ hanzi: '既然你来了，就一起吃饭吧', pinyin: 'Jìrán nǐ lái le, jiù yīqǐ chīfàn ba', meaning: 'Đã bạn đến rồi, cùng ăn cơm nhé' },
{ hanzi: '我们继续学习', pinyin: 'Wǒmen jìxù xuéxí', meaning: 'Chúng ta tiếp tục học' },
{ hanzi: '他给朋友寄了封信', pinyin: 'Tā gěi péngyǒu jì le fēng xìn', meaning: 'Anh ấy gửi một bức thư cho bạn' },
{ hanzi: '他常常加班', pinyin: 'Tā chángcháng jiābān', meaning: 'Anh ấy thường làm thêm giờ' },
{ hanzi: '我们在加油站加油', pinyin: 'Wǒmen zài jiāyóuzhàn jiāyóu', meaning: 'Chúng tôi đổ xăng tại trạm xăng' },
{ hanzi: '这家店卖很多家具', pinyin: 'Zhè jiā diàn mài hěn duō jiājù', meaning: 'Cửa hàng này bán rất nhiều đồ nội thất' },
{ hanzi: '这个是假货', pinyin: 'Zhè ge shì jiǎ huò', meaning: 'Đây là hàng giả' },
{ hanzi: '这个产品的价格很高', pinyin: 'Zhè ge chǎnpǐn de jiàgé hěn gāo', meaning: 'Giá của sản phẩm này rất cao' },
{ hanzi: '我每天坚持跑步', pinyin: 'Wǒ měitiān jiānchí pǎobù', meaning: 'Tôi kiên trì chạy bộ mỗi ngày' },
{ hanzi: '她正在努力减肥', pinyin: 'Tā zhèngzài nǔlì jiǎnféi', meaning: 'Cô ấy đang cố gắng giảm cân' },
{ hanzi: '我们应该减少浪费', pinyin: 'Wǒmen yīnggāi jiǎnshǎo làngfèi', meaning: 'Chúng ta nên giảm lãng phí' },
{ hanzi: '我有一个建议', pinyin: 'Wǒ yǒu yī ge jiànyì', meaning: 'Tôi có một đề xuất' },
{ hanzi: '将来我要当医生', pinyin: 'Jiānglái wǒ yào dāng yīshēng', meaning: 'Tương lai tôi muốn trở thành bác sĩ' },
{ hanzi: '公司给了他奖金', pinyin: 'Gōngsī gěi le tā jiǎngjīn', meaning: 'Công ty đã thưởng tiền cho anh ấy' },
{ hanzi: '他们降低了价格', pinyin: 'Tāmen jiàngdī le jiàgé', meaning: 'Họ đã giảm giá' },
{ hanzi: '飞机准时降落', pinyin: 'Fēijī zhǔnshí jiàngluò', meaning: 'Máy bay hạ cánh đúng giờ' },
{ hanzi: '我交了作业', pinyin: 'Wǒ jiāo le zuòyè', meaning: 'Tôi đã nộp bài tập' },
{ hanzi: '我们经常交流经验', pinyin: 'Wǒmen jīngcháng jiāoliú jīngyàn', meaning: 'Chúng tôi thường trao đổi kinh nghiệm' },
{ hanzi: '交通很拥挤', pinyin: 'Jiāotōng hěn yōngjǐ', meaning: 'Giao thông rất tắc nghẽn' },
{ hanzi: '我住在郊区', pinyin: 'Wǒ zhù zài jiāoqū', meaning: 'Tôi sống ở ngoại ô' },
{ hanzi: '他很骄傲', pinyin: 'Tā hěn jiāo\'ào', meaning: 'Anh ấy rất tự hào' },
{ hanzi: '我喜欢吃饺子', pinyin: 'Wǒ xǐhuān chī jiǎozi', meaning: 'Tôi thích ăn bánh bao' },
{ hanzi: '他是大学教授', pinyin: 'Tā shì dàxué jiàoshòu', meaning: 'Anh ấy là giáo sư đại học' },
{ hanzi: '教育很重要', pinyin: 'Jiàoyù hěn zhòngyào', meaning: 'Giáo dục rất quan trọng' },
{ hanzi: '我接受了他的邀请', pinyin: 'Wǒ jiēshòu le tā de yāoqǐng', meaning: 'Tôi đã nhận lời mời của anh ấy' },
{ hanzi: '接着，我们去吃饭吧', pinyin: 'Jiēzhe, wǒmen qù chīfàn ba', meaning: 'Tiếp theo, chúng ta đi ăn nhé' },
{ hanzi: '春节是中国的传统节日', pinyin: 'Chūnjié shì Zhōngguó de chuántǒng jiérì', meaning: 'Tết Nguyên đán là ngày lễ truyền thống của Trung Quốc' },
{ hanzi: '我们要节约用水', pinyin: 'Wǒmen yào jiéyuē yòng shuǐ', meaning: 'Chúng ta phải tiết kiệm nước' },
{ hanzi: '结果他成功了', pinyin: 'Jiéguǒ tā chénggōng le', meaning: 'Kết quả là anh ấy đã thành công' },
{ hanzi: '他解释了这个问题', pinyin: 'Tā jiěshì le zhè ge wèntí', meaning: 'Anh ấy đã giải thích vấn đề này' },
{ hanzi: '尽管下雨，他还是来了', pinyin: 'Jǐnguǎn xiàyǔ, tā háishì lái le', meaning: 'Dù trời mưa, anh ấy vẫn đến' },
{ hanzi: '我感到很紧张', pinyin: 'Wǒ gǎndào hěn jǐnzhāng', meaning: 'Tôi cảm thấy rất căng thẳng' },
{ hanzi: '我们正在进行讨论', pinyin: 'Wǒmen zhèngzài jìnxíng tǎolùn', meaning: 'Chúng tôi đang tiến hành thảo luận' },
{ hanzi: '这里禁止吸烟', pinyin: 'Zhèlǐ jìnzhǐ xīyān', meaning: 'Ở đây cấm hút thuốc' },
{ hanzi: '我喜欢看京剧', pinyin: 'Wǒ xǐhuān kàn Jīngjù', meaning: 'Tôi thích xem Kinh kịch' },
{ hanzi: '经济发展很快', pinyin: 'Jīngjì fāzhǎn hěn kuài', meaning: 'Kinh tế phát triển rất nhanh' },
{ hanzi: '他有丰富的经历', pinyin: 'Tā yǒu fēngfù de jīnglì', meaning: 'Anh ấy có nhiều kinh nghiệm' },
{ hanzi: '他的经验很丰富', pinyin: 'Tā de jīngyàn hěn fēngfù', meaning: 'Kinh nghiệm của anh ấy rất phong phú' },
{ hanzi: '比赛非常精彩', pinyin: 'Bǐsài fēicháng jīngcǎi', meaning: 'Trận đấu rất xuất sắc' },
{ hanzi: '山上的景色很美', pinyin: 'Shānshàng de jǐngsè hěn měi', meaning: 'Cảnh trên núi rất đẹp' },
{ hanzi: '警察在调查案件', pinyin: 'Jǐngchá zài diàochá ànjiàn', meaning: 'Cảnh sát đang điều tra vụ án' },
{ hanzi: '公司之间竞争激烈', pinyin: 'Gōngsī zhī jiān jìngzhēng jīliè', meaning: 'Cạnh tranh giữa các công ty rất khốc liệt' },
{ hanzi: '他竟然赢了比赛', pinyin: 'Tā jìngrán yíng le bǐsài', meaning: 'Anh ấy vậy mà lại chiến thắng trận đấu' },
{ hanzi: '镜子里有个陌生人', pinyin: 'Jìngzi lǐ yǒu gè mòshēng rén', meaning: 'Trong gương có một người lạ' },
{ hanzi: '究竟发生了什么事？', pinyin: 'Jiūjìng fāshēng le shénme shì?', meaning: 'Rốt cuộc đã xảy ra chuyện gì?' },
{ hanzi: '他举手回答问题', pinyin: 'Tā jǔshǒu huídá wèntí', meaning: 'Anh ấy giơ tay trả lời câu hỏi' },
{ hanzi: '学校举办了一个音乐会', pinyin: 'Xuéxiào jǔbàn le yī gè yīnyuè huì', meaning: 'Trường tổ chức một buổi hòa nhạc' },
{ hanzi: '会议在北京举行', pinyin: 'Huìyì zài Běijīng jǔxíng', meaning: 'Hội nghị được tổ chức tại Bắc Kinh' },
{ hanzi: '他拒绝了我的邀请', pinyin: 'Tā jùjué le wǒ de yāoqǐng', meaning: 'Anh ấy từ chối lời mời của tôi' },
{ hanzi: '学校到我们家的距离很远', pinyin: 'Xuéxiào dào wǒmen jiā de jùlí hěn yuǎn', meaning: 'Trường học cách nhà chúng tôi rất xa' },
{ hanzi: '我们下个星期有个聚会', pinyin: 'Wǒmen xià gè xīngqī yǒu gè jùhuì', meaning: 'Tuần sau chúng tôi có một buổi họp mặt' },
{ hanzi: '他喜欢开玩笑', pinyin: 'Tā xǐhuān kāiwánxiào', meaning: 'Anh ấy thích đùa giỡn' },
{ hanzi: '今天我很开心', pinyin: 'Jīntiān wǒ hěn kāixīn', meaning: 'Hôm nay tôi rất vui' },
{ hanzi: '你的看法是什么？', pinyin: 'Nǐ de kànfǎ shì shénme?', meaning: 'Quan điểm của bạn là gì?' },
{ hanzi: '我会考虑你的建议', pinyin: 'Wǒ huì kǎolǜ nǐ de jiànyì', meaning: 'Tôi sẽ xem xét đề nghị của bạn' },
{ hanzi: '北京烤鸭很好吃', pinyin: 'Běijīng kǎoyā hěn hǎochī', meaning: 'Vịt quay Bắc Kinh rất ngon' },
{ hanzi: '科学是非常重要的学科', pinyin: 'Kēxué shì fēicháng zhòngyào de xuékē', meaning: 'Khoa học là một môn học rất quan trọng' },
{ hanzi: '花园里有很多棵树', pinyin: 'Huāyuán lǐ yǒu hěn duō kē shù', meaning: 'Trong vườn có rất nhiều cây' },
{ hanzi: '我感冒了，咳嗽很厉害', pinyin: 'Wǒ gǎnmào le, késou hěn lìhài', meaning: 'Tôi bị cảm, ho rất nặng' },
{ hanzi: '他很可怜，需要帮助', pinyin: 'Tā hěn kělián, xūyào bāngzhù', meaning: 'Anh ấy rất đáng thương, cần sự giúp đỡ' },
{ hanzi: '我很想去，可是没有时间', pinyin: 'Wǒ hěn xiǎng qù, kěshì méiyǒu shíjiān', meaning: 'Tôi rất muốn đi, nhưng không có thời gian' },
{ hanzi: '太可惜了，我没看到', pinyin: 'Tài kěxī le, wǒ méi kàndào', meaning: 'Thật đáng tiếc, tôi đã không thấy' },
{ hanzi: '客厅里有很多家具', pinyin: 'Kètīng lǐ yǒu hěn duō jiājù', meaning: 'Trong phòng khách có rất nhiều đồ nội thất' },
{ hanzi: '这件事肯定是真的', pinyin: 'Zhè jiàn shì kěndìng shì zhēn de', meaning: 'Chuyện này chắc chắn là thật' },
{ hanzi: '房间里空无一人', pinyin: 'Fángjiān lǐ kōng wú yī rén', meaning: 'Phòng trống không một ai' },
{ hanzi: '山上的空气很新鲜', pinyin: 'Shānshàng de kōngqì hěn xīnxiān', meaning: 'Không khí trên núi rất trong lành' },
{ hanzi: '我恐怕他不会来了', pinyin: 'Wǒ kǒngpà tā bù huì lái le', meaning: 'Tôi sợ rằng anh ấy sẽ không đến' },
{ hanzi: '这个药很苦', pinyin: 'Zhè ge yào hěn kǔ', meaning: 'Thuốc này rất đắng' },
{ hanzi: '我喜欢喝矿泉水', pinyin: 'Wǒ xǐhuān hē kuàngquánshuǐ', meaning: 'Tôi thích uống nước khoáng' },
{ hanzi: '我昨晚没睡好，很困', pinyin: 'Wǒ zuówǎn méi shuì hǎo, hěn kùn', meaning: 'Tối qua tôi ngủ không ngon, rất buồn ngủ' },
{ hanzi: '学习汉语很困难', pinyin: 'Xuéxí Hànyǔ hěn kùnnán', meaning: 'Học tiếng Trung rất khó' },
{ hanzi: '请把垃圾扔进垃圾桶', pinyin: 'Qǐng bǎ lājī rēng jìn lājītǒng', meaning: 'Vui lòng bỏ rác vào thùng rác' },
{ hanzi: '他把箱子拉到房间里', pinyin: 'Tā bǎ xiāngzi lā dào fángjiān lǐ', meaning: 'Anh ấy kéo vali vào phòng' },
{ hanzi: '我不喜欢吃辣的东西', pinyin: 'Wǒ bù xǐhuān chī là de dōngxī', meaning: 'Tôi không thích ăn đồ cay' },
{ hanzi: '我们来不及赶飞机了', pinyin: 'Wǒmen láibují gǎn fēijī le', meaning: 'Chúng tôi không kịp chuyến bay rồi' },
{ hanzi: '你来得及去火车站', pinyin: 'Nǐ láidéjí qù huǒchē zhàn', meaning: 'Bạn kịp giờ đi đến ga tàu' },
{ hanzi: '他来自中国', pinyin: 'Tā láizì Zhōngguó', meaning: 'Anh ấy đến từ Trung Quốc' },
{ hanzi: '他很懒，不喜欢工作', pinyin: 'Tā hěn lǎn, bù xǐhuān gōngzuò', meaning: 'Anh ấy rất lười, không thích làm việc' },
{ hanzi: '我们应该避免浪费时间', pinyin: 'Wǒmen yīnggāi bìmiǎn làngfèi shíjiān', meaning: 'Chúng ta nên tránh lãng phí thời gian' },
{ hanzi: '他们的故事很浪漫', pinyin: 'Tāmen de gùshì hěn làngmàn', meaning: 'Câu chuyện của họ rất lãng mạn' },
{ hanzi: '动物园里有一只老虎', pinyin: 'Dòngwùyuán lǐ yǒu yī zhī lǎohǔ', meaning: 'Trong sở thú có một con hổ' },
{ hanzi: '请冷静下来，不要生气', pinyin: 'Qǐng lěngjìng xiàlái, bùyào shēngqì', meaning: 'Xin hãy bình tĩnh lại, đừng tức giận' },
{ hanzi: '我们星期天去公园', pinyin: 'Wǒmen xīngqītiān qù gōngyuán', meaning: 'Chủ nhật chúng ta đi công viên' },
{ hanzi: '他对人很有礼貌', pinyin: 'Tā duì rén hěn yǒu lǐmào', meaning: 'Anh ấy rất lịch sự với mọi người' },
{ hanzi: '今天我要去理发', pinyin: 'Jīntiān wǒ yào qù lǐfà', meaning: 'Hôm nay tôi sẽ đi cắt tóc' },
{ hanzi: '我不理解你的意思', pinyin: 'Wǒ bù lǐjiě nǐ de yìsi', meaning: 'Tôi không hiểu ý của bạn' },
{ hanzi: '他的理想是当医生', pinyin: 'Tā de lǐxiǎng shì dāng yīshēng', meaning: 'Lý tưởng của anh ấy là trở thành bác sĩ' },
{ hanzi: '我没有力气搬动这张桌子', pinyin: 'Wǒ méiyǒu lìqì bāndòng zhè zhāng zhuōzi', meaning: 'Tôi không có sức để di chuyển cái bàn này' },
{ hanzi: '他的汉语说得很厉害', pinyin: 'Tā de Hànyǔ shuō de hěn lìhài', meaning: 'Anh ấy nói tiếng Trung rất giỏi' },
{ hanzi: '例如，苹果和香蕉都是水果', pinyin: 'Lìrú, píngguǒ hé xiāngjiāo dōu shì shuǐguǒ', meaning: 'Ví dụ, táo và chuối đều là trái cây' },
{ hanzi: '我们俩是好朋友', pinyin: 'Wǒmen liǎ shì hǎo péngyǒu', meaning: 'Hai chúng tôi là bạn tốt' },
{ hanzi: '他连书都没带', pinyin: 'Tā lián shū dōu méi dài', meaning: 'Anh ấy thậm chí còn không mang sách' },
{ hanzi: '我会联系你', pinyin: 'Wǒ huì liánxì nǐ', meaning: 'Tôi sẽ liên lạc với bạn' },
{ hanzi: '今天很凉快', pinyin: 'Jīntiān hěn liángkuai', meaning: 'Hôm nay rất mát mẻ' },
{ hanzi: '我有一些零钱', pinyin: 'Wǒ yǒu yīxiē língqián', meaning: 'Tôi có một ít tiền lẻ' },
{ hanzi: '我们还有另外一个问题要解决', pinyin: 'Wǒmen hái yǒu lìngwài yī ge wèntí yào jiějué', meaning: 'Chúng ta còn một vấn đề khác cần giải quyết' },
{ hanzi: '请把文件留在桌上', pinyin: 'Qǐng bǎ wénjiàn liú zài zhuō shàng', meaning: 'Vui lòng để tài liệu trên bàn' },
{ hanzi: '他的汉语说得很流利', pinyin: 'Tā de Hànyǔ shuō de hěn liúlì', meaning: 'Anh ấy nói tiếng Trung rất lưu loát' },
{ hanzi: '这首歌很流行', pinyin: 'Zhè shǒu gē hěn liúxíng', meaning: 'Bài hát này rất thịnh hành' },
{ hanzi: '我们打算去旅行', pinyin: 'Wǒmen dǎsuàn qù lǚxíng', meaning: 'Chúng tôi dự định đi du lịch' },
{ hanzi: '他是一名律师', pinyin: 'Tā shì yī míng lǜshī', meaning: 'Anh ấy là một luật sư' },
{ hanzi: '房间里很乱', pinyin: 'Fángjiān lǐ hěn luàn', meaning: 'Phòng rất lộn xộn' },
{ hanzi: '麻烦你帮我拿一下', pinyin: 'Máfan nǐ bāng wǒ ná yīxià', meaning: 'Phiền bạn giúp tôi cầm cái này' },
{ hanzi: '他做事很马虎', pinyin: 'Tā zuòshì hěn mǎhǔ', meaning: 'Anh ấy làm việc rất cẩu thả' },
{ hanzi: '我的行李箱装满了', pinyin: 'Wǒ de xínglǐ xiāng zhuāng mǎnle', meaning: 'Vali của tôi đầy rồi' },
{ hanzi: '我不喜欢穿毛衣', pinyin: 'Wǒ bù xǐhuān chuān máoyī', meaning: 'Tôi không thích mặc áo lông' },
{ hanzi: '请给我一条毛巾', pinyin: 'Qǐng gěi wǒ yī tiáo máojīn', meaning: 'Xin hãy đưa cho tôi một cái khăn tắm' },
{ hanzi: '这个地方很美丽', pinyin: 'Zhè ge dìfāng hěn měilì', meaning: 'Nơi này rất đẹp' },
{ hanzi: '我昨晚做了一个好梦', pinyin: 'Wǒ zuówǎn zuò le yī ge hǎo mèng', meaning: 'Tối qua tôi đã có một giấc mơ đẹp' },
{ hanzi: '我迷路了，找不到回家的路', pinyin: 'Wǒ mílù le, zhǎo bù dào huí jiā de lù', meaning: 'Tôi bị lạc, không tìm thấy đường về nhà' },
{ hanzi: '请不要告诉别人我的密码', pinyin: 'Qǐng bùyào gàosù biérén wǒ de mìmǎ', meaning: 'Xin đừng nói mật khẩu của tôi cho người khác' },
{ hanzi: '这家博物馆是免费的', pinyin: 'Zhè jiā bówùguǎn shì miǎnfèi de', meaning: 'Bảo tàng này miễn phí' },
{ hanzi: '我们需要等几秒钟', pinyin: 'Wǒmen xūyào děng jǐ miǎo zhōng', meaning: 'Chúng ta cần đợi vài giây' },
{ hanzi: '中国是一个多民族的国家', pinyin: 'Zhōngguó shì yī ge duō mínzú de guójiā', meaning: 'Trung Quốc là một quốc gia đa dân tộc' },
{ hanzi: '我的母亲很善良', pinyin: 'Wǒ de mǔqīn hěn shànliáng', meaning: 'Mẹ của tôi rất hiền lành' },
{ hanzi: '我的目的是学好汉语', pinyin: 'Wǒ de mùdì shì xuéhǎo Hànyǔ', meaning: 'Mục đích của tôi là học giỏi tiếng Trung' },
{ hanzi: '请耐心一点', pinyin: 'Qǐng nàixīn yīdiǎn', meaning: 'Xin hãy kiên nhẫn một chút' },
{ hanzi: '难道你不想去吗？', pinyin: 'Nándào nǐ bù xiǎng qù ma?', meaning: 'Chẳng lẽ bạn không muốn đi à?' },
{ hanzi: '他觉得很难受', pinyin: 'Tā juéde hěn nánshòu', meaning: 'Anh ấy cảm thấy rất khó chịu' },
{ hanzi: '他住在城市内', pinyin: 'Tā zhù zài chéngshì nèi', meaning: 'Anh ấy sống trong thành phố' },
{ hanzi: '这本书的内容很有趣', pinyin: 'Zhè běn shū de nèiróng hěn yǒuqù', meaning: 'Nội dung của cuốn sách này rất thú vị' },
{ hanzi: '他有很强的工作能力', pinyin: 'Tā yǒu hěn qiáng de gōngzuò nénglì', meaning: 'Anh ấy có khả năng làm việc rất tốt' },
{ hanzi: '她的年龄是25岁', pinyin: 'Tā de niánlíng shì 25 suì', meaning: 'Cô ấy 25 tuổi' },
{ hanzi: '别弄坏了我的手机', pinyin: 'Bié nòng huài le wǒ de shǒujī', meaning: 'Đừng làm hỏng điện thoại của tôi' },
{ hanzi: '今天天气很暖和', pinyin: 'Jīntiān tiānqì hěn nuǎnhuo', meaning: 'Hôm nay thời tiết rất ấm áp' },
{ hanzi: '我偶尔会去图书馆', pinyin: 'Wǒ ǒu\'ěr huì qù túshūguǎn', meaning: 'Thỉnh thoảng tôi sẽ đi thư viện' },
{ hanzi: '请大家排队等候', pinyin: 'Qǐng dàjiā páiduì děnghòu', meaning: 'Xin mọi người xếp hàng chờ' },
{ hanzi: '书架上的书排列的非常整齐', pinyin: 'shūjià shàng de shū páiliè de fēicháng zhěngqí', meaning: 'Sách trên giá xếp rất ngay ngắn' },
{ hanzi: '我无法判断他是否说真话', pinyin: 'Wǒ wúfǎ pànduàn tā shìfǒu shuō zhēnhuà', meaning: 'Tôi không thể đánh giá anh ấy có nói thật hay không' },
{ hanzi: '她陪我去看医生', pinyin: 'Tā péi wǒ qù kàn yīshēng', meaning: 'Cô ấy đi cùng tôi đến gặp bác sĩ' },
{ hanzi: '他总是批评我的工作', pinyin: 'Tā zǒngshì pīpíng wǒ de gōngzuò', meaning: 'Anh ấy luôn chỉ trích công việc của tôi' },
{ hanzi: '她的皮肤很白', pinyin: 'Tā de pífū hěn bái', meaning: 'Da của cô ấy rất trắng' },
{ hanzi: '他的脾气很坏', pinyin: 'Tā de píqì hěn huài', meaning: 'Tính tình của anh ấy rất tệ' },
{ hanzi: '我读了一篇有趣的文章', pinyin: 'Wǒ dú le yī piān yǒuqù de wénzhāng', meaning: 'Tôi đã đọc một bài viết thú vị' },
{ hanzi: '别骗我', pinyin: 'Bié piàn wǒ', meaning: 'Đừng lừa tôi' },
{ hanzi: '我喜欢打乒乓球', pinyin: 'Wǒ xǐhuān dǎ pīngpāng qiú', meaning: 'Tôi thích chơi bóng bàn' },
{ hanzi: '平时他很少运动', pinyin: 'Píngshí tā hěn shǎo yùndòng', meaning: 'Thường thì anh ấy ít khi tập thể dục' },
{ hanzi: '我的鞋子破了', pinyin: 'Wǒ de xiézi pò le', meaning: 'Giày của tôi bị rách rồi' },
{ hanzi: '这些葡萄很好吃', pinyin: 'Zhèxiē pútao hěn hǎochī', meaning: 'Những trái nho này rất ngon' },
{ hanzi: '这种现象很普遍', pinyin: 'Zhè zhǒng xiànxiàng hěn pǔbiàn', meaning: 'Hiện tượng này rất phổ biến' },
{ hanzi: '他说普通话说得很好', pinyin: 'Tā shuō Pǔtōnghuà shuō de hěn hǎo', meaning: 'Anh ấy nói tiếng phổ thông rất tốt' },
{ hanzi: '首先要努力，其次要坚持', pinyin: 'Shǒuxiān yào nǔlì, qícì yào jiānchí', meaning: 'Trước tiên phải nỗ lực, sau đó phải kiên trì' },
{ hanzi: '在所有的人群中，其中有一个人是我认识的人', pinyin: 'Zài suǒyǒu de rénqún zhōng, qízhōng yǒuyī gèrén shì wǒ rènshí de rén', meaning: 'Trong số tất cả mọi người, có một người tôi biết' },
{ hanzi: '这个地方的气候很宜人', pinyin: 'Zhège dìfāng de qìhòu hěn yírén', meaning: 'Khí hậu nơi này rất dễ chịu' },
{ hanzi: '你千万不要忘记', pinyin: 'Nǐ qiānwàn bùyào wàngjì', meaning: 'Bạn nhất định đừng quên' },
{ hanzi: '我需要办理签证', pinyin: 'Wǒ xūyào bànlǐ qiānzhèng', meaning: 'Tôi cần làm thị thực' },
{ hanzi: '他敲门进来了', pinyin: 'Tā qiāo mén jìn lái le', meaning: 'Anh ấy gõ cửa rồi vào' },
{ hanzi: '他们在桥上拍照', pinyin: 'Tāmen zài qiáo shàng pāizhào', meaning: 'Họ chụp ảnh trên cầu' },
{ hanzi: '她给了我一块巧克力', pinyin: 'Tā gěi le wǒ yī kuài qiǎokèlì', meaning: 'Cô ấy đưa cho tôi một miếng sô-cô-la' },
{ hanzi: '我有很多亲戚住在国外', pinyin: 'Wǒ yǒu hěn duō qīnqi zhù zài guówài', meaning: 'Tôi có nhiều họ hàng sống ở nước ngoài' },
{ hanzi: '这本书很轻', pinyin: 'Zhè běn shū hěn qīng', meaning: 'Cuốn sách này rất nhẹ' },
{ hanzi: '他觉得工作很轻松', pinyin: 'Tā juéde gōngzuò hěn qīngsōng', meaning: 'Anh ấy cảm thấy công việc rất nhẹ nhàng' },
{ hanzi: '目前的情况很复杂', pinyin: 'Mùqián de qíngkuàng hěn fùzá', meaning: 'Tình hình hiện tại rất phức tạp' },
{ hanzi: '他家很穷', pinyin: 'Tā jiā hěn qióng', meaning: 'Gia đình anh ấy rất nghèo' },
{ hanzi: '这个问题有很多区别', pinyin: 'Zhège wèntí yǒu hěn duō qūbié', meaning: 'Vấn đề này có nhiều khác biệt' },
{ hanzi: '请把书取出来', pinyin: 'Qǐng bǎ shū qǔ chūlái', meaning: 'Vui lòng lấy sách ra' },
{ hanzi: '我们全部完成了任务', pinyin: 'Wǒmen quánbù wánchéng le rènwù', meaning: 'Chúng tôi hoàn thành toàn bộ nhiệm vụ' },
{ hanzi: '他有很多缺点', pinyin: 'Tā yǒu hěn duō quēdiǎn', meaning: 'Anh ấy có nhiều khuyết điểm' },
{ hanzi: '这里缺少水', pinyin: 'Zhèlǐ quēshǎo shuǐ', meaning: 'Ở đây thiếu nước' },
{ hanzi: '他很想去，却不能去', pinyin: 'Tā hěn xiǎng qù, què bùnéng qù', meaning: 'Anh ấy rất muốn đi, nhưng không thể đi' },
{ hanzi: '这次确实是我的错', pinyin: 'Zhè cì quèshí shì wǒ de cuò', meaning: 'Lần này thật sự là lỗi của tôi' },
{ hanzi: '然而，他并没有成功', pinyin: 'Rán\'ér, tā bìng méiyǒu chénggōng', meaning: 'Tuy nhiên, anh ấy không thành công' },
{ hanzi: '市场很热闹', pinyin: 'Shìchǎng hěn rènào', meaning: 'Chợ rất nhộn nhịp' },
{ hanzi: '任何人都可以参加', pinyin: 'Rènhé rén dōu kěyǐ cānjiā', meaning: 'Bất kỳ ai cũng có thể tham gia' },
{ hanzi: '我们的任务是保护环境', pinyin: 'Wǒmen de rènwù shì bǎohù huánjìng', meaning: 'Nhiệm vụ của chúng tôi là bảo vệ môi trường' },
{ hanzi: '请不要随便扔垃圾', pinyin: 'Qǐng bùyào suíbiàn rēng lājī', meaning: 'Xin đừng vứt rác bừa bãi' },
{ hanzi: '他仍然在等你', pinyin: 'Tā réngrán zài děng nǐ', meaning: 'Anh ấy vẫn đang chờ bạn' },
{ hanzi: '我每天都写日记', pinyin: 'Wǒ měitiān dōu xiě rìjì', meaning: 'Tôi viết nhật ký mỗi ngày' },
{ hanzi: '这是超市的入口', pinyin: 'Zhè shì chāoshì de rùkǒu', meaning: 'Đây là lối vào của siêu thị' },
{ hanzi: '我喜欢晚上散步', pinyin: 'Wǒ xǐhuān wǎnshàng sànbù', meaning: 'Tôi thích đi dạo buổi tối' },
{ hanzi: '森林里有很多动物', pinyin: 'Sēnlín lǐ yǒu hěn duō dòngwù', meaning: 'Trong rừng có rất nhiều động vật' },
{ hanzi: '我家有一张沙发', pinyin: 'Wǒ jiā yǒu yī zhāng shāfā', meaning: 'Nhà tôi có một chiếc ghế sofa' },
{ hanzi: '他听到这个消息很伤心', pinyin: 'Tā tīngdào zhège xiāoxi hěn shāngxīn', meaning: 'Anh ấy rất đau lòng khi nghe tin này' },
{ hanzi: '我们需要商量一下计划', pinyin: 'Wǒmen xūyào shāngliáng yīxià jìhuà', meaning: 'Chúng ta cần thảo luận kế hoạch một chút' },
{ hanzi: '你稍微等一下', pinyin: 'Nǐ shāowēi děng yīxià', meaning: 'Bạn đợi một chút' },
{ hanzi: '请给我一把勺子', pinyin: 'Qǐng gěi wǒ yī bǎ sháozi', meaning: 'Vui lòng đưa tôi một cái muỗng' },
{ hanzi: '这个社会变化很快', pinyin: 'Zhège shèhuì biànhuà hěn kuài', meaning: 'Xã hội này thay đổi rất nhanh' },
{ hanzi: '我申请了一个新工作', pinyin: 'Wǒ shēnqǐng le yī ge xīn gōngzuò', meaning: 'Tôi đã nộp đơn xin một công việc mới' },
{ hanzi: '湖水很深', pinyin: 'Húshuǐ hěn shēn', meaning: 'Nước hồ rất sâu' },
{ hanzi: '他甚至不知道我的名字', pinyin: 'Tā shènzhì bù zhīdào wǒ de míngzì', meaning: 'Anh ấy thậm chí không biết tên tôi' },
{ hanzi: '我们的生活很幸福', pinyin: 'Wǒmen de shēnghuó hěn xìngfú', meaning: 'Cuộc sống của chúng tôi rất hạnh phúc' },
{ hanzi: '生命很宝贵', pinyin: 'Shēngmìng hěn bǎoguì', meaning: 'Sinh mệnh rất quý giá' },
{ hanzi: '他的生意做得很好', pinyin: 'Tā de shēngyì zuò de hěn hǎo', meaning: 'Việc kinh doanh của anh ấy rất tốt' },
{ hanzi: '我们住在北江省', pinyin: 'Wǒmen zhù zài běijiāng shěng', meaning: 'Chúng tôi sống ở tỉnh Bắc Giang' },
{ hanzi: '剩下的路程只能靠我们自己了', pinyin: 'Shèng xià de lùchéng zhǐ néng kào wǒmen zìjǐ le', meaning: 'Phần còn lại của hành trình chỉ có thể dựa vào bản thân chúng ta' },
{ hanzi: '他没有失败过', pinyin: 'Tā méiyǒu shībài guò', meaning: 'Anh ấy chưa từng thất bại' },
{ hanzi: '结果让我很失望', pinyin: 'Jiéguǒ ràng wǒ hěn shīwàng', meaning: 'Kết quả làm tôi rất thất vọng' },
{ hanzi: '师傅，请教我开车', pinyin: 'Shīfù, qǐng jiāo wǒ kāichē', meaning: 'Thầy, xin dạy tôi lái xe' },
{ hanzi: '他十分聪明', pinyin: 'Tā shífēn cōngmíng', meaning: 'Anh ấy rất thông minh' },
{ hanzi: '他的建议很实际', pinyin: 'Tā de jiànyì hěn shíjì', meaning: 'Lời khuyên của anh ấy rất thực tế' },
{ hanzi: '这个故事实在太感人了', pinyin: 'Zhège gùshì shízài tài gǎnrén le', meaning: 'Câu chuyện này thật sự rất cảm động' },
{ hanzi: '她的表现使观众们非常兴奋', pinyin: 'Tā de biǎoxiàn shǐ guānzhòngmen fēicháng xīngfèn', meaning: 'Màn trình diễn của cô khiến khán giả vô cùng hưng phấn' },
{ hanzi: '请不要随便使用别人的东西', pinyin: 'Qǐng bùyào suíbiàn shǐyòng biérén de dōngxī', meaning: 'Xin đừng tùy tiện sử dụng đồ của người khác' },
{ hanzi: '这是二十一世纪的科技', pinyin: 'Zhè shì èrshíyī shìjì de kējì', meaning: 'Đây là công nghệ của thế kỷ 21' },
{ hanzi: '他是否同意还不确定', pinyin: 'Tā shìfǒu tóngyì hái bù quèdìng', meaning: 'Anh ấy có đồng ý hay không còn chưa chắc chắn' },
{ hanzi: '这件衣服适合你', pinyin: 'Zhè jiàn yīfú shìhé nǐ', meaning: 'Cái áo này hợp với bạn' },
{ hanzi: '他适应了新的环境', pinyin: 'Tā shìyìng le xīn de huánjìng', meaning: 'Anh ấy đã thích nghi với môi trường mới' },
{ hanzi: '请收这个包裹', pinyin: 'Qǐng shōu zhège bāoguǒ', meaning: 'Xin nhận cái gói hàng này' },
{ hanzi: '他的收入很高', pinyin: 'Tā de shōurù hěn gāo', meaning: 'Thu nhập của anh ấy rất cao' },
{ hanzi: '请把房间收拾干净', pinyin: 'Qǐng bǎ fángjiān shōushi gānjìng', meaning: 'Xin dọn phòng sạch sẽ' },
{ hanzi: '北京是中国的首都', pinyin: 'Běijīng shì Zhōngguó de shǒudū', meaning: 'Bắc Kinh là thủ đô của Trung Quốc' },
{ hanzi: '首先要学习，其次要实践', pinyin: 'Shǒuxiān yào xuéxí, qícì yào shíjiàn', meaning: 'Trước tiên phải học, sau đó phải thực hành' },
{ hanzi: '我受不了这么热的天气', pinyin: 'Wǒ shòubùliǎo zhème rè de tiānqì', meaning: 'Tôi không chịu nổi thời tiết nóng như thế này' },
{ hanzi: '我受到了一封信', pinyin: 'Wǒ shòudào le yī fēng xìn', meaning: 'Tôi nhận được một lá thư' },
{ hanzi: '售货员向我介绍了这款手机', pinyin: 'Shòuhuòyuán xiàng wǒ jièshào le zhè kuǎn shǒujī', meaning: 'Người bán hàng giới thiệu cho tôi mẫu điện thoại này' },
{ hanzi: '我们输了比赛', pinyin: 'Wǒmen shū le bǐsài', meaning: 'Chúng tôi thua trận đấu' },
{ hanzi: '我对这儿很熟悉', pinyin: 'Wǒ duì zhèr hěn shúxī', meaning: 'Tôi rất quen thuộc với nơi này' },
{ hanzi: '这里的学生数量很多', pinyin: 'Zhèlǐ de xuéshēng shùliàng hěn duō', meaning: 'Số lượng học sinh ở đây rất nhiều' },
{ hanzi: '这个数字很大', pinyin: 'Zhège shùzì hěn dà', meaning: 'Con số này rất lớn' },
{ hanzi: '他很帅', pinyin: 'Tā hěn shuài', meaning: 'Anh ấy rất đẹp trai' },
{ hanzi: '我顺便买了些水果', pinyin: 'Wǒ shùnbiàn mǎi le xiē shuǐguǒ', meaning: 'Tôi tiện thể mua một ít hoa quả' },
{ hanzi: '事情进行得很顺利', pinyin: 'Shìqíng jìnxíng de hěn shùnlì', meaning: 'Mọi việc tiến hành rất thuận lợi' },
{ hanzi: '请按顺序排队', pinyin: 'Qǐng àn shùnxù páiduì', meaning: 'Vui lòng xếp hàng theo thứ tự' },
{ hanzi: '请说明一下原因', pinyin: 'Qǐng shuōmíng yīxià yuányīn', meaning: 'Xin hãy giải thích lý do' },
{ hanzi: '他是硕士毕业', pinyin: 'Tā shì shuòshì bìyè', meaning: 'Anh ấy tốt nghiệp thạc sĩ' },
{ hanzi: '他突然死了', pinyin: 'Tā tūrán sǐ le', meaning: 'Anh ấy đột nhiên qua đời' },
{ hanzi: '请提高速度', pinyin: 'Qǐng tígāo sùdù', meaning: 'Xin hãy tăng tốc độ' },
{ hanzi: '请不要使用塑料袋', pinyin: 'Qǐng bùyào shǐyòng sùliào dài', meaning: 'Xin đừng sử dụng túi nhựa' },
{ hanzi: '这道菜有点酸', pinyin: 'Zhè dào cài yǒudiǎn suān', meaning: 'Món này hơi chua' },
{ hanzi: '请随便坐', pinyin: 'Qǐng suíbiàn zuò', meaning: 'Xin cứ ngồi tự nhiên' },
{ hanzi: '随着时间的流逝，他变得成熟了', pinyin: 'Suízhe shíjiān de liúshì, tā biàn dé chéngshú le', meaning: 'Theo thời gian trôi qua, anh ấy trở nên chín chắn' },
{ hanzi: '我有两个孙子', pinyin: 'Wǒ yǒu liǎng gè sūnzi', meaning: 'Tôi có hai cháu trai' },
{ hanzi: '所有的人都来了', pinyin: 'Suǒyǒu de rén dōu lái le', meaning: 'Mọi người đều đã đến' },
{ hanzi: '他站在台上', pinyin: 'Tā zhàn zài tái shàng', meaning: 'Anh ấy đứng trên sân khấu' },
{ hanzi: '请抬一下这个箱子', pinyin: 'Qǐng tái yīxià zhège xiāngzi', meaning: 'Xin hãy nâng cái hộp này lên một chút' },
{ hanzi: '他的态度很不好', pinyin: 'Tā de tàidù hěn bù hǎo', meaning: 'Thái độ của anh ấy rất tệ' },
{ hanzi: '我们谈了很多事情', pinyin: 'Wǒmen tán le hěn duō shìqíng', meaning: 'Chúng tôi đã nói về rất nhiều chuyện' },
{ hanzi: '她会弹钢琴', pinyin: 'Tā huì tán gāngqín', meaning: 'Cô ấy biết chơi piano' },
{ hanzi: '我喜欢喝鸡汤', pinyin: 'Wǒ xǐhuān hē jītāng', meaning: 'Tôi thích uống súp gà' },
{ hanzi: '我不喜欢吃太多糖', pinyin: 'Wǒ bù xǐhuān chī tài duō táng', meaning: 'Tôi không thích ăn quá nhiều đường' },
{ hanzi: '我喜欢躺在沙发上看书', pinyin: 'Wǒ xǐhuān tǎng zài shāfā shàng kàn shū', meaning: 'Tôi thích nằm trên ghế sofa đọc sách' },
{ hanzi: '我刚刚去了一趟商店', pinyin: 'Wǒ gānggāng qù le yī tàng shāngdiàn', meaning: 'Tôi vừa đi một chuyến đến cửa hàng' },
{ hanzi: '我们在会议上讨论了这个问题', pinyin: 'Wǒmen zài huìyì shàng tǎolùn le zhège wèntí', meaning: 'Chúng tôi đã thảo luận về vấn đề này trong cuộc họp' },
{ hanzi: '我讨厌吃苦瓜', pinyin: 'Wǒ tǎoyàn chī kǔguā', meaning: 'Tôi ghét ăn mướp đắng' },
{ hanzi: '这个产品的特点是什么？', pinyin: 'Zhège chǎnpǐn de tèdiǎn shì shénme?', meaning: 'Đặc điểm của sản phẩm này là gì?' },
{ hanzi: '请提一些建议', pinyin: 'Qǐng tí yīxiē jiànyì', meaning: 'Xin hãy đưa ra một vài gợi ý' },
{ hanzi: '我们提供免费早餐', pinyin: 'Wǒmen tígōng miǎnfèi zǎocān', meaning: 'Chúng tôi cung cấp bữa sáng miễn phí' },
{ hanzi: '请提前告诉我', pinyin: 'Qǐng tíqián gàosù wǒ', meaning: 'Xin hãy cho tôi biết trước' },
{ hanzi: '他提醒我明天开会', pinyin: 'Tā tíxǐng wǒ míngtiān kāihuì', meaning: 'Anh ấy nhắc tôi rằng ngày mai họp' },
{ hanzi: '请在填空处写上答案', pinyin: 'Qǐng zài tiánkòng chù xiě shàng dá\'àn', meaning: 'Xin hãy điền câu trả lời vào chỗ trống' },
{ hanzi: '这个工作条件很好', pinyin: 'Zhège gōngzuò tiáojiàn hěn hǎo', meaning: 'Điều kiện công việc này rất tốt' },
{ hanzi: '请停车', pinyin: 'Qǐng tíng chē', meaning: 'Xin dừng xe' },
{ hanzi: '他挺高的', pinyin: 'Tā tǐng gāo de', meaning: 'Anh ấy khá cao' },
{ hanzi: '我通过了考试', pinyin: 'Wǒ tōngguò le kǎoshì', meaning: 'Tôi đã qua kỳ thi' },
{ hanzi: '请通知大家明天的会议', pinyin: 'Qǐng tōngzhī dàjiā míngtiān de huìyì', meaning: 'Xin thông báo với mọi người về cuộc họp ngày mai' },
{ hanzi: '我们都很同情他', pinyin: 'Wǒmen dōu hěn tóngqíng tā', meaning: 'Chúng tôi đều rất đồng cảm với anh ấy' },
{ hanzi: '他同时做两份工作', pinyin: 'Tā tóngshí zuò liǎng fèn gōngzuò', meaning: 'Anh ấy làm hai công việc cùng một lúc' },
{ hanzi: '请帮我推一下门', pinyin: 'Qǐng bāng wǒ tuī yīxià mén', meaning: 'Xin hãy giúp tôi đẩy cửa' },
{ hanzi: '会议推迟到明天', pinyin: 'Huìyì tuīchí dào míngtiān', meaning: 'Cuộc họp bị hoãn đến ngày mai' },
{ hanzi: '请脱下你的外套', pinyin: 'Qǐng tuō xià nǐ de wàitào', meaning: 'Xin cởi áo khoác ra' },
{ hanzi: '我需要一双新的袜子', pinyin: 'Wǒ xūyào yī shuāng xīn de wàzi', meaning: 'Tôi cần một đôi tất mới' },
{ hanzi: '我完全同意你的看法', pinyin: 'Wǒ wánquán tóngyì nǐ de kànfǎ', meaning: 'Tôi hoàn toàn đồng ý với quan điểm của bạn' },
{ hanzi: '我喜欢打网球', pinyin: 'Wǒ xǐhuān dǎ wǎngqiú', meaning: 'Tôi thích chơi tennis' },
{ hanzi: '这个网站很好用', pinyin: 'Zhège wǎngzhàn hěn hǎo yòng', meaning: 'Trang web này rất hữu ích' },
{ hanzi: '他往往迟到', pinyin: 'Tā wǎngwǎng chídào', meaning: 'Anh ấy thường xuyên đến muộn' },
{ hanzi: '小心，这里很危险', pinyin: 'Xiǎoxīn, zhèlǐ hěn wēixiǎn', meaning: 'Cẩn thận, chỗ này rất nguy hiểm' },
{ hanzi: '卫生间在哪里？', pinyin: 'Wèishēngjiān zài nǎlǐ?', meaning: 'Nhà vệ sinh ở đâu?' },
{ hanzi: '这个菜的味道很好', pinyin: 'Zhège cài de wèidào hěn hǎo', meaning: 'Món này có hương vị rất ngon' },
{ hanzi: '今天的温度很高', pinyin: 'Jīntiān de wēndù hěn gāo', meaning: 'Nhiệt độ hôm nay rất cao' },
{ hanzi: '这篇文章写得很好', pinyin: 'Zhè piān wénzhāng xiě de hěn hǎo', meaning: 'Bài viết này được viết rất hay' },
{ hanzi: '这里的污染很严重', pinyin: 'Zhèlǐ de wūrǎn hěn yánzhòng', meaning: 'Ô nhiễm ở đây rất nghiêm trọng' },
{ hanzi: '他无话可说', pinyin: 'Tā wú huà kě shuō', meaning: 'Anh ấy không biết nói gì' },
{ hanzi: '这本书很无聊', pinyin: 'Zhè běn shū hěn wúliáo', meaning: 'Cuốn sách này rất nhàm chán' },
{ hanzi: '无论天气如何，我们都去', pinyin: 'Wúlùn tiānqì rúhé, wǒmen dōu qù', meaning: 'Bất kể thời tiết thế nào, chúng tôi đều đi' },
{ hanzi: '我误会了他的意思', pinyin: 'Wǒ wùhuì le tā de yìsi', meaning: 'Tôi đã hiểu lầm ý của anh ấy' },
{ hanzi: '我喜欢吃西红柿', pinyin: 'Wǒ xǐhuān chī xīhóngshì', meaning: 'Tôi thích ăn cà chua' },
{ hanzi: '他的表演吸引了很多人', pinyin: 'Tā de biǎoyǎn xīyǐn le hěn duō rén', meaning: 'Màn biểu diễn của anh ấy thu hút rất nhiều người' },
{ hanzi: '这个菜有点咸', pinyin: 'Zhège cài yǒudiǎn xián', meaning: 'Món này hơi mặn' },
{ hanzi: '请用现金付款', pinyin: 'Qǐng yòng xiànjīn fùkuǎn', meaning: 'Vui lòng thanh toán bằng tiền mặt' },
{ hanzi: '我羡慕他的生活', pinyin: 'Wǒ xiànmù tā de shēnghuó', meaning: 'Tôi ngưỡng mộ cuộc sống của anh ấy' },
{ hanzi: '他的意见和我的相反', pinyin: 'Tā de yìjiàn hé wǒ de xiāngfǎn', meaning: 'Ý kiến của anh ấy trái ngược với của tôi' },
{ hanzi: '他们有相同的爱好', pinyin: 'Tāmen yǒu xiāngtóng de àihào', meaning: 'Họ có cùng sở thích' },
{ hanzi: '这朵花很香', pinyin: 'Zhè duǒ huā hěn xiāng', meaning: 'Bông hoa này rất thơm' },
{ hanzi: '他给我详细地解释了这个问题', pinyin: 'Tā gěi wǒ xiángxì de jiěshì le zhège wèntí', meaning: 'Anh ấy giải thích chi tiết vấn đề này cho tôi' },
{ hanzi: '门铃响了', pinyin: 'Ménlíng xiǎng le', meaning: 'Chuông cửa reo' },
{ hanzi: '我需要一块橡皮', pinyin: 'Wǒ xūyào yī kuài xiàngpí', meaning: 'Tôi cần một cục tẩy' },
{ hanzi: '你听到了什么消息？', pinyin: 'Nǐ tīngdào le shénme xiāoxi?', meaning: 'Bạn nghe thấy tin tức gì?' },
{ hanzi: '北京的小吃很有名', pinyin: 'Běijīng de xiǎochī hěn yǒumíng', meaning: 'Đồ ăn vặt Bắc Kinh rất nổi tiếng' },
{ hanzi: '他是一个很勤快的小伙子', pinyin: 'Tā shì yīgè hěn qínkuài de xiǎohuǒzi', meaning: 'Anh ấy là một chàng trai rất chăm chỉ' },
{ hanzi: '这本小说很有意思', pinyin: 'Zhè běn xiǎoshuō hěn yǒu yìsi', meaning: 'Cuốn tiểu thuyết này rất thú vị' },
{ hanzi: '你的笑话很好笑', pinyin: 'Nǐ de xiàohuà hěn hǎo xiào', meaning: 'Truyện cười của bạn rất buồn cười' },
{ hanzi: '新政策的效果很好', pinyin: 'Xīn zhèngcè de xiàoguǒ hěn hǎo', meaning: 'Hiệu quả của chính sách mới rất tốt' },
{ hanzi: '我的心情很好', pinyin: 'Wǒ de xīnqíng hěn hǎo', meaning: 'Tâm trạng của tôi rất tốt' },
{ hanzi: '工作很辛苦，但很值得', pinyin: 'Gōngzuò hěn xīnkǔ, dàn hěn zhídé', meaning: 'Công việc rất vất vả nhưng rất đáng' },
{ hanzi: '我需要一个信封', pinyin: 'Wǒ xūyào yī gè xìnfēng', meaning: 'Tôi cần một cái phong bì' },
{ hanzi: '我们需要更多的信息', pinyin: 'Wǒmen xūyào gèng duō de xìnxī', meaning: 'Chúng tôi cần thêm thông tin' },
{ hanzi: '我对自己有信心', pinyin: 'Wǒ duì zìjǐ yǒu xìnxīn', meaning: 'Tôi có tự tin vào bản thân' },
{ hanzi: '见到你，我很兴奋', pinyin: 'jiàn dào nǐ, wǒ hěn xīngfèn', meaning: 'Tôi rất phấn khích khi gặp bạn' },
{ hanzi: '这条路,行吗？', pinyin: 'Zhè tiáo lù, xíng ma?', meaning: 'Con đường này được không?' },
{ hanzi: '他醒了', pinyin: 'Tā xǐng le', meaning: 'Anh ấy đã tỉnh dậy' },
{ hanzi: '我们过得很幸福', pinyin: 'Wǒmen guò de hěn xìngfú', meaning: 'Chúng tôi sống rất hạnh phúc' },
{ hanzi: '请填写你的性别', pinyin: 'Qǐng tiánxiě nǐ de xìngbié', meaning: 'Vui lòng điền giới tính của bạn' },
{ hanzi: '他的性格很开朗', pinyin: 'Tā de xìnggé hěn kāilǎng', meaning: 'Tính cách của anh ấy rất cởi mở' },
{ hanzi: '他在修理自行车', pinyin: 'Tā zài xiūlǐ zìxíngchē', meaning: 'Anh ấy đang sửa xe đạp' },
{ hanzi: '学校有许多学生', pinyin: 'Xuéxiào yǒu xǔduō xuéshēng', meaning: 'Trường có nhiều học sinh' },
{ hanzi: '这个学期很忙', pinyin: 'Zhège xuéqī hěn máng', meaning: 'Học kỳ này rất bận' },
{ hanzi: '我的压力很大', pinyin: 'Wǒ de yālì hěn dà', meaning: 'Tôi có nhiều áp lực' },
{ hanzi: '他呀，真是个好人', pinyin: 'Tā ya, zhēn shì gè hǎo rén', meaning: 'Anh ấy, thật sự là một người tốt' },
{ hanzi: '我需要买牙膏', pinyin: 'Wǒ xūyào mǎi yágāo', meaning: 'Tôi cần mua kem đánh răng' },
{ hanzi: '亚洲的文化很丰富', pinyin: 'Yàzhōu de wénhuà hěn fēngfù', meaning: 'Văn hóa châu Á rất phong phú' },
{ hanzi: '他对自己很严格', pinyin: 'Tā duì zìjǐ hěn yángé', meaning: 'Anh ấy rất nghiêm khắc với bản thân' },
{ hanzi: '这个问题很严重', pinyin: 'Zhège wèntí hěn yánzhòng', meaning: 'Vấn đề này rất nghiêm trọng' },
{ hanzi: '他在研究新技术', pinyin: 'Tā zài yánjiū xīn jìshù', meaning: 'Anh ấy đang nghiên cứu công nghệ mới' },
{ hanzi: '我们需要加点盐', pinyin: 'Wǒmen xūyào jiā diǎn yán', meaning: 'Chúng ta cần thêm một chút muối' },
{ hanzi: '我需要戴眼镜', pinyin: 'Wǒ xūyào dài yǎnjìng', meaning: 'Tôi cần đeo kính' },
{ hanzi: '他们正在准备演出', pinyin: 'Tāmen zhèngzài zhǔnbèi yǎnchū', meaning: 'Họ đang chuẩn bị biểu diễn' },
{ hanzi: '他是一名演员', pinyin: 'Tā shì yī míng yǎnyuán', meaning: 'Anh ấy là một diễn viên' },
{ hanzi: '今天阳光明媚', pinyin: 'Jīntiān yángguāng míngmèi', meaning: 'Hôm nay nắng đẹp' },
{ hanzi: '这种习惯需要时间养成', pinyin: 'Zhè zhǒng xíguàn xūyào shíjiān yǎngchéng', meaning: 'Thói quen này cần thời gian để hình thành' },
{ hanzi: '这件衣服的样子很好看', pinyin: 'Zhè jiàn yīfú de yàngzi hěn hǎokàn', meaning: 'kiểu dáng của quần áo này rất đẹp' },
{ hanzi: '我们邀请了很多朋友', pinyin: 'Wǒmen yāoqǐng le hěn duō péngyǒu', meaning: 'Chúng tôi mời rất nhiều bạn bè' },
{ hanzi: '要是你有时间，我们一起去吧', pinyin: 'Yàoshì nǐ yǒu shíjiān, wǒmen yīqǐ qù ba', meaning: 'Nếu bạn có thời gian, chúng ta cùng đi nhé' },
{ hanzi: '我找不到我的钥匙了', pinyin: 'Wǒ zhǎo bù dào wǒ de yàoshi le', meaning: 'Tôi không tìm thấy chìa khóa của mình' },
{ hanzi: '也许明天会下雨', pinyin: 'Yěxǔ míngtiān huì xià yǔ', meaning: 'Có lẽ ngày mai sẽ mưa' },
{ hanzi: '树上的叶子变黄了', pinyin: 'Shù shàng de yèzi biàn huáng le', meaning: 'Lá trên cây đã chuyển sang màu vàng' },
{ hanzi: '请翻到下一页', pinyin: 'Qǐng fān dào xià yī yè', meaning: 'Vui lòng lật sang trang tiếp theo' },
{ hanzi: '一切都会好的', pinyin: 'Yīqiè dōu huì hǎo de', meaning: 'Mọi thứ sẽ ổn thôi' },
{ hanzi: '以他的能力，他能做到', pinyin: 'Yǐ tā de nénglì, tā néng zuò dào', meaning: 'Với khả năng của anh ấy, anh ấy có thể làm được' },
{ hanzi: '我以为他已经走了', pinyin: 'Wǒ yǐwéi tā yǐjīng zǒu le', meaning: 'Tôi tưởng rằng anh ấy đã đi rồi' },
{ hanzi: '他对艺术很有兴趣', pinyin: 'Tā duì yìshù hěn yǒu xìngqù', meaning: 'Anh ấy rất hứng thú với nghệ thuật' },
{ hanzi: '我有一些不同的意见', pinyin: 'Wǒ yǒu yīxiē bùtóng de yìjiàn', meaning: 'Tôi có một vài ý kiến khác nhau' },
{ hanzi: '因此，我们需要改变计划', pinyin: 'Yīncǐ, wǒmen xūyào gǎibiàn jìhuà', meaning: 'Vì vậy, chúng ta cần thay đổi kế hoạch' },
{ hanzi: '他的演讲引起了大家的兴趣', pinyin: 'Tā de yǎnjiǎng yǐnqǐ le dàjiā de xìngqù', meaning: 'Bài diễn thuyết của anh ấy đã thu hút sự quan tâm của mọi người' },
{ hanzi: '我对他的印象很好', pinyin: 'Wǒ duì tā de yìnxiàng hěn hǎo', meaning: 'Ấn tượng của tôi về anh ấy rất tốt' },
{ hanzi: '我们赢了比赛', pinyin: 'Wǒmen yíng le bǐsài', meaning: 'Chúng tôi đã thắng trận đấu' },
{ hanzi: '我去公司应聘了', pinyin: 'Wǒ qù gōngsī yìngpìn le', meaning: 'Tôi đã đến công ty để ứng tuyển' },
{ hanzi: '我们的友谊永远不会改变', pinyin: 'Wǒmen de yǒuyì yǒngyuǎn bù huì gǎibiàn', meaning: 'Tình bạn của chúng ta sẽ không bao giờ thay đổi' },
{ hanzi: '他很勇敢地面对困难', pinyin: 'Tā hěn yǒnggǎn de miànduì kùnnán', meaning: 'Anh ấy rất dũng cảm đối mặt với khó khăn' },
{ hanzi: '他的优点是很认真', pinyin: 'Tā de yōudiǎn shì hěn rènzhēn', meaning: 'Ưu điểm của anh ấy là rất chăm chỉ' },
{ hanzi: '她是一个优秀的学生', pinyin: 'Tā shì yīgè yōuxiù de xuéshēng', meaning: 'Cô ấy là một học sinh xuất sắc' },
{ hanzi: '他讲笑话很幽默', pinyin: 'Tā jiǎng xiàohuà hěn yōumò', meaning: 'Anh ấy kể chuyện cười rất hài hước' },
{ hanzi: '我尤其喜欢吃水果', pinyin: 'Wǒ yóuqí xǐhuān chī shuǐguǒ', meaning: 'Tôi đặc biệt thích ăn trái cây' },
{ hanzi: '由他负责这项工作', pinyin: 'Yóu tā fùzé zhè xiàng gōngzuò', meaning: 'Công việc này do anh ấy phụ trách' },
{ hanzi: '由于下雨，我们取消了计划', pinyin: 'Yóuyú xiàyǔ, wǒmen qǔxiāo le jìhuà', meaning: 'Do trời mưa, chúng tôi đã hủy bỏ kế hoạch' },
{ hanzi: '我去邮局寄信', pinyin: 'Wǒ qù yóujú jì xìn', meaning: 'Tôi đi bưu điện gửi thư' },
{ hanzi: '他们对我们很友好', pinyin: 'Tāmen duì wǒmen hěn yǒuhǎo', meaning: 'Họ rất thân thiện với chúng tôi' },
{ hanzi: '友谊是非常珍贵的', pinyin: 'Yǒuyì shì fēicháng zhēnguì de', meaning: 'Tình bạn rất quý giá' },
{ hanzi: '这个故事很有趣', pinyin: 'Zhège gùshì hěn yǒuqù', meaning: 'Câu chuyện này rất thú vị' },
{ hanzi: '天黑了，于是我们回家了', pinyin: 'Tiān hēi le, yúshì wǒmen huí jiā le', meaning: 'Trời tối rồi, nên chúng tôi về nhà' },
{ hanzi: '希望你度过一个愉快的假期', pinyin: 'Xīwàng nǐ dùguò yīgè yúkuài de jiàqī', meaning: 'Hy vọng bạn có một kỳ nghỉ vui vẻ' },
{ hanzi: '他与我一起去旅游', pinyin: 'Tā yǔ wǒ yīqǐ qù lǚyóu', meaning: 'Anh ấy đi du lịch cùng tôi' },
{ hanzi: '我喜欢打羽毛球', pinyin: 'Wǒ xǐhuān dǎ yǔmáoqiú', meaning: 'Tôi thích chơi cầu lông' },
{ hanzi: '他的语法很好', pinyin: 'Tā de yǔfǎ hěn hǎo', meaning: 'Ngữ pháp của anh ấy rất tốt' },
{ hanzi: '他会说多种语言', pinyin: 'Tā huì shuō duō zhǒng yǔyán', meaning: 'Anh ấy có thể nói nhiều ngôn ngữ' },
{ hanzi: '请预习明天的课文', pinyin: 'Qǐng yùxí míngtiān de kèwén', meaning: 'Vui lòng chuẩn bị trước bài học ngày mai' },
{ hanzi: '我原来住在北京', pinyin: 'Wǒ yuánlái zhù zài Běijīng', meaning: 'Tôi vốn sống ở Bắc Kinh' },
{ hanzi: '请原谅我的错误', pinyin: 'Qǐng yuánliàng wǒ de cuòwù', meaning: 'Xin hãy tha thứ cho lỗi lầm của tôi' },
{ hanzi: '他解释了事情的原因', pinyin: 'Tā jiěshì le shìqíng de yuányīn', meaning: 'Anh ấy đã giải thích nguyên nhân của sự việc' },
{ hanzi: '明天的约会你来吗？', pinyin: 'Míngtiān de yuēhuì nǐ lái ma?', meaning: 'Cuộc hẹn ngày mai bạn đến không?' },
{ hanzi: '我每天阅读书籍', pinyin: 'Wǒ měitiān yuèdú shūjí', meaning: 'Tôi đọc sách hàng ngày' },
{ hanzi: '天空中有很多云', pinyin: 'Tiānkōng zhōng yǒu hěn duō yún', meaning: 'Trên bầu trời có rất nhiều mây' },
{ hanzi: '这里不允许吸烟', pinyin: 'Zhèlǐ bù yǔnxǔ xīyān', meaning: 'Ở đây không được phép hút thuốc' },
{ hanzi: '他正在看杂志', pinyin: 'Tā zhèngzài kàn zázhì', meaning: 'Anh ấy đang đọc tạp chí' },
{ hanzi: '咱们一起去吧', pinyin: 'Zánmen yīqǐ qù ba', meaning: 'Chúng ta cùng đi nhé' },
{ hanzi: '我暂时住在朋友家', pinyin: 'Wǒ zànshí zhù zài péngyǒu jiā', meaning: 'Tôi tạm thời sống ở nhà bạn' },
{ hanzi: '这件衣服很脏', pinyin: 'Zhè jiàn yīfú hěn zāng', meaning: 'Bộ quần áo này rất bẩn' },
{ hanzi: '你要负责任', pinyin: 'Nǐ yào fù zérèn', meaning: 'Bạn phải chịu trách nhiệm' },
{ hanzi: '我们需要增加预算', pinyin: 'Wǒmen xūyào zēngjiā yùsuàn', meaning: 'Chúng ta cần tăng ngân sách' },
{ hanzi: '电话一直占线', pinyin: 'Diànhuà yīzhí zhànxiàn', meaning: 'Điện thoại luôn bận' },
{ hanzi: '公司正在招聘员工', pinyin: 'Gōngsī zhèngzài zhāopìn yuángōng', meaning: 'Công ty đang tuyển dụng nhân viên' },
{ hanzi: '请照一下这张照片', pinyin: 'Qǐng zhào yīxià zhè zhāng zhàopiàn', meaning: 'Xin hãy chụp bức ảnh này' },
{ hanzi: '他是一个真正的朋友', pinyin: 'Tā shì yīgè zhēnzhèng de péngyǒu', meaning: 'Anh ấy là một người bạn thực sự' },
{ hanzi: '我需要整理房间', pinyin: 'Wǒ xūyào zhěnglǐ fángjiān', meaning: 'Tôi cần dọn dẹp phòng' },
{ hanzi: '一切都很正常', pinyin: 'Yīqiè dōu hěn zhèngcháng', meaning: 'Mọi thứ đều rất bình thường' },
{ hanzi: '你来得正好', pinyin: 'Nǐ lái de zhènghǎo', meaning: 'Bạn đến vừa đúng lúc' },
{ hanzi: '你的答案是正确的', pinyin: 'Nǐ de dá\'àn shì zhèngquè de', meaning: 'Câu trả lời của bạn là chính xác' },
{ hanzi: '这是一场正式的会议', pinyin: 'Zhè shì yī chǎng zhèngshì de huìyì', meaning: 'Đây là một cuộc họp chính thức' },
{ hanzi: '请你证明一下身份', pinyin: 'Qǐng nǐ zhèngmíng yīxià shēnfèn', meaning: 'Vui lòng xác minh danh tính của bạn' },
{ hanzi: '这本书之内容很丰富', pinyin: 'Zhè běn shū zhī nèiróng hěn fēngfù', meaning: 'Nội dung của cuốn sách này rất phong phú' },
{ hanzi: '我们支持你的决定', pinyin: 'Wǒmen zhīchí nǐ de juédìng', meaning: 'Chúng tôi ủng hộ quyết định của bạn' },
{ hanzi: '知识是无价之宝', pinyin: 'Zhīshì shì wújià zhī bǎo', meaning: 'Kiến thức là vô giá' },
{ hanzi: '请直接告诉我结果', pinyin: 'Qǐng zhíjiē gàosù wǒ jiéguǒ', meaning: 'Vui lòng nói trực tiếp với tôi kết quả' },
{ hanzi: '这部电影很值得看', pinyin: 'Zhè bù diànyǐng hěn zhídé kàn', meaning: 'Bộ phim này rất đáng xem' },
{ hanzi: '他的职业是医生', pinyin: 'Tā de zhíyè shì yīshēng', meaning: 'Nghề nghiệp của anh ấy là bác sĩ' },
{ hanzi: '我喜欢养植物', pinyin: 'Wǒ xǐhuān yǎng zhíwù', meaning: 'Tôi thích trồng cây' },
{ hanzi: '下雨了，我们只好回家', pinyin: 'Xiàyǔ le, wǒmen zhǐhǎo huí jiā', meaning: 'Trời mưa rồi, chúng ta đành phải về nhà' },
{ hanzi: '只要努力，就会成功', pinyin: 'Zhǐyào nǔlì, jiù huì chénggōng', meaning: 'Chỉ cần cố gắng, sẽ thành công' },
{ hanzi: '他指了指那棵树', pinyin: 'Tā zhǐle zhǐ nà kē shù', meaning: 'Anh ấy chỉ vào cái cây kia' },
{ hanzi: '我至少要休息一天', pinyin: 'Wǒ zhìshǎo yào xiūxí yī tiān', meaning: 'Tôi ít nhất cần nghỉ ngơi một ngày' },
{ hanzi: '这家店的产品质量很好', pinyin: 'Zhè jiā diàn de chǎnpǐn zhìliàng hěn hǎo', meaning: 'Sản phẩm của cửa hàng này có chất lượng rất tốt' },
{ hanzi: '这箱子很重', pinyin: 'Zhè xiāngzi hěn zhòng', meaning: 'Cái vali này rất nặng' },
{ hanzi: '这个问题是重点', pinyin: 'Zhège wèntí shì zhòngdiǎn', meaning: 'Vấn đề này là trọng điểm' },
{ hanzi: '他很重视健康', pinyin: 'Tā hěn zhòngshì jiànkāng', meaning: 'Anh ấy rất coi trọng sức khỏe' },
{ hanzi: '我住在学校的周围', pinyin: 'Wǒ zhù zài xuéxiào de zhōuwéi', meaning: 'Tôi sống xung quanh trường học' },
{ hanzi: '这是一个好主意', pinyin: 'Zhè shì yīgè hǎo zhǔyì', meaning: 'Đây là một ý tưởng hay' },
{ hanzi: '祝贺你通过考试', pinyin: 'Zhùhè nǐ tōngguò kǎoshì', meaning: 'Chúc mừng bạn đã vượt qua kỳ thi' },
{ hanzi: '他是一位著名的作家', pinyin: 'Tā shì yī wèi zhùmíng de zuòjiā', meaning: 'Anh ấy là một nhà văn nổi tiếng' },
{ hanzi: '他专门研究历史', pinyin: 'Tā zhuānmén yánjiū lìshǐ', meaning: 'Anh ấy chuyên nghiên cứu lịch sử' },
{ hanzi: '他的专业是数学', pinyin: 'Tā de zhuānyè shì shùxué', meaning: 'Chuyên ngành của anh ấy là toán học' },
{ hanzi: '请把椅子转过来', pinyin: 'Qǐng bǎ yǐzi zhuǎn guòlái', meaning: 'Vui lòng xoay ghế lại' },
{ hanzi: '他在公司赚了很多钱', pinyin: 'Tā zài gōngsī zhuàn le hěn duō qián', meaning: 'Anh ấy kiếm được rất nhiều tiền ở công ty' },
{ hanzi: '他的答案非常准确', pinyin: 'Tā de dá\'àn fēicháng zhǔnquè', meaning: 'Câu trả lời của anh ấy rất chính xác' },
{ hanzi: '请准时到达', pinyin: 'Qǐng zhǔnshí dàodá', meaning: 'Vui lòng đến đúng giờ' },
{ hanzi: '他做事很仔细', pinyin: 'Tā zuòshì hěn zǐxì', meaning: 'Anh ấy làm việc rất cẩn thận' },
{ hanzi: '自然景色很美', pinyin: 'Zìrán jǐngsè hěn měi', meaning: 'Cảnh thiên nhiên rất đẹp' },
{ hanzi: '我对自己很有自信', pinyin: 'Wǒ duì zìjǐ hěn yǒu zìxìn', meaning: 'Tôi rất tự tin vào bản thân' },
{ hanzi: '他总结了会议的要点', pinyin: 'Tā zǒngjié le huìyì de yàodiǎn', meaning: 'Anh ấy đã tổng kết các điểm chính của cuộc họp' },
{ hanzi: '我租了一辆车', pinyin: 'Wǒ zū le yī liàng chē', meaning: 'Tôi đã thuê một chiếc xe' },
{ hanzi: '这是最好的选择', pinyin: 'Zhè shì zuì hǎo de xuǎnzé', meaning: 'Đây là lựa chọn tốt nhất' },
{ hanzi: '我们应该尊重他人的意见', pinyin: 'Wǒmen yīnggāi zūnzhòng tārén de yìjiàn', meaning: 'Chúng ta nên tôn trọng ý kiến của người khác' },
{ hanzi: '他站在我左右', pinyin: 'Tā zhàn zài wǒ zuǒyòu', meaning: 'Anh ấy đứng bên cạnh tôi' },
{ hanzi: '他是一位著名的作家', pinyin: 'Tā shì yī wèi zhùmíng de zuòjiā', meaning: 'Anh ấy là một nhà văn nổi tiếng' },
{ hanzi: '这个药对治疗感冒很有作用', pinyin: 'Zhège yào duì zhìliáo gǎnmào hěn yǒu zuòyòng', meaning: 'Thuốc này rất hiệu quả trong việc điều trị cảm lạnh' },
{ hanzi: '这本书的作者是谁？', pinyin: 'Zhè běn shū de zuòzhě shì shéi?', meaning: 'Tác giả của cuốn sách này là ai?' },
{ hanzi: '这座城市很大', pinyin: 'Zhè zuò chéngshì hěn dà', meaning: 'Thành phố này rất lớn' },
{ hanzi: '请找你的座位', pinyin: 'Qǐng zhǎo nǐ de zuòwèi', meaning: 'Vui lòng tìm chỗ ngồi của bạn' },

];