vocab = [
  { hanzi: '请你帮我吧。', pinyin: 'Qǐng nǐ bāng wǒ ba.', meaning: 'Xin bạn giúp tôi nhé.' },
{ hanzi: '他的白色衬衫很漂亮。', pinyin: 'Tā de báisè chènshān hěn piàoliang.', meaning: 'Áo sơ mi trắng của anh ấy rất đẹp.' },
{ hanzi: '我们要买一百个苹果。', pinyin: 'Wǒmen yào mǎi yī bǎi gè píngguǒ.', meaning: 'Chúng tôi muốn mua một trăm quả táo.' },
{ hanzi: '请你帮忙翻译这篇文章。', pinyin: 'Qǐng nǐ bāngmáng fānyì zhè piān wénzhāng.', meaning: 'Xin bạn giúp dịch bài viết này.' },
{ hanzi: '我每天都看报纸。', pinyin: 'Wǒ měitiān dōu kàn bàozhǐ.', meaning: 'Tôi đọc báo mỗi ngày.' },
{ hanzi: '我的家比你的家大。', pinyin: 'Wǒ de jiā bǐ nǐ de jiā dà.', meaning: 'Nhà của tôi lớn hơn nhà của bạn.' },
{ hanzi: '别忘带钥匙。', pinyin: 'Bié wàng dài yàoshi.', meaning: 'Đừng quên mang theo chìa khóa.' },
{ hanzi: '她的头发很长。', pinyin: 'Tā de tóufǎ hěn cháng.', meaning: 'Tóc của cô ấy rất dài.' },
{ hanzi: '我喜欢唱歌。', pinyin: 'Wǒ xǐhuān chànggē.', meaning: 'Tôi thích hát.' },
{ hanzi: '我们出去玩吧。', pinyin: 'Wǒmen chūqù wán ba.', meaning: 'Chúng ta ra ngoài chơi đi.' },
{ hanzi: '你穿的衣服很漂亮。', pinyin: 'Nǐ chuān de yīfú hěn piàoliang.', meaning: 'Quần áo bạn mặc rất đẹp.' },
{ hanzi: '他坐在船上。', pinyin: 'Tā zuò zài chuán shàng.', meaning: 'Anh ấy ngồi trên thuyền.' },
{ hanzi: '这是我第一次来这里。', pinyin: 'Zhè shì wǒ dì yī cì lái zhèlǐ.', meaning: 'Đây là lần đầu tiên tôi đến đây.' },
{ hanzi: '他从早上工作到晚上。', pinyin: 'Tā cóng zǎoshang gōngzuò dào wǎnshang.', meaning: 'Anh ấy làm việc từ sáng đến tối.' },
{ hanzi: '他做错了一个题。', pinyin: 'Tā zuò cuòle yīgè tí.', meaning: 'Anh ấy đã làm sai một bài tập.' },
{ hanzi: '他打篮球打得很好。', pinyin: 'Tā dǎ lánqiú dǎ de hěn hǎo.', meaning: 'Anh ấy chơi bóng rổ rất giỏi.' },
{ hanzi: '大家都很高兴。', pinyin: 'Dàjiā dōu hěn gāoxìng.', meaning: 'Mọi người đều rất vui.' },
{ hanzi: '我想去，但是没有时间。', pinyin: 'Wǒ xiǎng qù, dànshì méiyǒu shíjiān.', meaning: 'Tôi muốn đi, nhưng không có thời gian.' },
{ hanzi: '我们今天到学校了。', pinyin: 'Wǒmen jīntiān dào xuéxiào le.', meaning: 'Hôm nay chúng tôi đã đến trường.' },
{ hanzi: '你得努力学习。', pinyin: 'Nǐ děi nǔlì xuéxí.', meaning: 'Bạn phải cố gắng học.' },
{ hanzi: '我们等你来。', pinyin: 'Wǒmen děng nǐ lái.', meaning: 'Chúng tôi đợi bạn đến.' },
{ hanzi: '弟弟在玩玩具。', pinyin: 'Dìdì zài wán wánjù.', meaning: 'Em trai đang chơi đồ chơi.' },
{ hanzi: '他是第一名。', pinyin: 'Tā shì dì yī míng.', meaning: 'Anh ấy là người đứng đầu.' },
{ hanzi: '我不懂这个问题。', pinyin: 'Wǒ bù dǒng zhège wèntí.', meaning: 'Tôi không hiểu vấn đề này.' },
{ hanzi: '你对我很好。', pinyin: 'Nǐ duì wǒ hěn hǎo.', meaning: 'Bạn đối xử tốt với tôi.' },
{ hanzi: '房间里很安静。', pinyin: 'Fángjiān lǐ hěn ānjìng.', meaning: 'Trong phòng rất yên tĩnh.' },
{ hanzi: '这道菜非常好吃。', pinyin: 'Zhè dào cài fēicháng hǎochī.', meaning: 'Món ăn này rất ngon.' },
{ hanzi: '服务员请帮忙。', pinyin: 'Fúwùyuán qǐng bāngmáng.', meaning: 'Nhân viên phục vụ, xin giúp đỡ.' },
{ hanzi: '他很高。', pinyin: 'Tā hěn gāo.', meaning: 'Anh ấy rất cao.' },
{ hanzi: '请告诉我答案。', pinyin: 'Qǐng gàosù wǒ dá\'àn.', meaning: 'Xin cho tôi biết đáp án.' },
{ hanzi: '哥哥在家里。', pinyin: 'Gēge zài jiālǐ.', meaning: 'Anh trai đang ở nhà.' },
{ hanzi: '请给我一本书。', pinyin: 'Qǐng gěi wǒ yī běn shū.', meaning: 'Xin hãy đưa cho tôi một cuốn sách.' },
{ hanzi: '公共汽车很方便。', pinyin: 'Gōnggòng qìchē hěn fāngbiàn.', meaning: 'Xe buýt rất tiện lợi.' },
{ hanzi: '这个包十公斤。', pinyin: 'Zhège bāo shí gōngjīn.', meaning: 'Cái túi này mười kilogram.' },
{ hanzi: '我在公司工作。', pinyin: 'Wǒ zài gōngsī gōngzuò.', meaning: 'Tôi làm việc ở công ty.' },
{ hanzi: '这件衣服很贵。', pinyin: 'Zhè jiàn yīfú hěn guì.', meaning: 'Cái áo này rất đắt.' },
{ hanzi: '请过安检门。', pinyin: 'Qǐng guò ānjiǎn mén.', meaning: 'Mời đi qua cửa an ninh.' },
{ hanzi: '我还想要一杯水。', pinyin: 'Wǒ hái xiǎng yào yī bēi shuǐ.', meaning: 'Tôi còn muốn một cốc nước.' },
{ hanzi: '孩子们都在玩。', pinyin: 'Háizimen dōu zài wán.', meaning: 'Những đứa trẻ đang chơi.' },
{ hanzi: '这道菜很好吃。', pinyin: 'Zhè dào cài hěn hǎo chī.', meaning: 'Món ăn này rất ngon.' },
{ hanzi: '你的手机号是多少？', pinyin: 'Nǐ de shǒujī hào shì duōshǎo?', meaning: 'Số điện thoại của bạn là bao nhiêu?' },
{ hanzi: '我的车是黑色的。', pinyin: 'Wǒ de chē shì hēisè de.', meaning: 'Xe của tôi màu đen.' },
{ hanzi: '她喜欢红色的衣服。', pinyin: 'Tā xǐhuān hóngsè de yīfú.', meaning: 'Cô ấy thích quần áo màu đỏ.' },
{ hanzi: '欢迎你来我家。', pinyin: 'Huānyíng nǐ lái wǒ jiā.', meaning: 'Chào mừng bạn đến nhà tôi.' },
{ hanzi: '请回答我的问题。', pinyin: 'Qǐng huídá wǒ de wèntí.', meaning: 'Xin trả lời câu hỏi của tôi.' },
{ hanzi: '机场离这里很近。', pinyin: 'Jīchǎng lí zhèlǐ hěn jìn.', meaning: 'Sân bay gần đây.' },
{ hanzi: '我喜欢吃鸡蛋。', pinyin: 'Wǒ xǐhuān chī jīdàn.', meaning: 'Tôi thích ăn trứng.' },
{ hanzi: '这件衣服很好看。', pinyin: 'Zhè jiàn yīfú hěn hǎokàn.', meaning: 'Cái áo này rất đẹp.' },
{ hanzi: '学生们在教室里学习。', pinyin: 'Xuéshēngmen zài jiàoshì lǐ xuéxí.', meaning: 'Học sinh đang học trong lớp học.' },
{ hanzi: '姐姐比我大三岁。', pinyin: 'Jiějiě bǐ wǒ dà sān suì.', meaning: 'Chị gái lớn hơn tôi ba tuổi.' },
{ hanzi: '请介绍一下你自己。', pinyin: 'Qǐng jièshào yīxià nǐ zìjǐ.', meaning: 'Xin hãy giới thiệu về bản thân.' },
{ hanzi: '请进，别客气。', pinyin: 'Qǐng jìn, bié kèqì.', meaning: 'Mời vào, đừng khách sáo.' },
{ hanzi: '学校离我家很近。', pinyin: 'Xuéxiào lí wǒ jiā hěn jìn.', meaning: 'Trường học gần nhà tôi.' },
{ hanzi: '他就住在我家旁边。', pinyin: 'Tā jiù zhù zài wǒ jiā pángbiān.', meaning: 'Anh ấy sống ngay cạnh nhà tôi.' },
{ hanzi: '我觉得今天很热。', pinyin: 'Wǒ juéde jīntiān hěn rè.', meaning: 'Tôi cảm thấy hôm nay rất nóng.' },
{ hanzi: '我每天早上喝咖啡。', pinyin: 'Wǒ měitiān zǎoshang hē kāfēi.', meaning: 'Tôi uống cà phê mỗi sáng.' },
{ hanzi: '我们现在开始上课。', pinyin: 'Wǒmen xiànzài kāishǐ shàngkè.', meaning: 'Bây giờ chúng ta bắt đầu học.' },
{ hanzi: '我准备好考试了。', pinyin: 'Wǒ zhǔnbèi hǎo kǎoshì le.', meaning: 'Tôi đã chuẩn bị sẵn sàng cho kỳ thi.' },
{ hanzi: '可能会下雨。', pinyin: 'Kěnéng huì xiàyǔ.', meaning: 'Có thể sẽ mưa.' },
{ hanzi: '你可以坐在这里。', pinyin: 'Nǐ kěyǐ zuò zài zhèlǐ.', meaning: 'Bạn có thể ngồi ở đây.' },
{ hanzi: '我们今天有三节课。', pinyin: 'Wǒmen jīntiān yǒu sān jié kè.', meaning: 'Hôm nay chúng ta có ba tiết học.' },
{ hanzi: '他跑得很快。', pinyin: 'Tā pǎo de hěn kuài.', meaning: 'Anh ấy chạy rất nhanh.' },
{ hanzi: '祝你生日快乐。', pinyin: 'Zhù nǐ shēngrì kuàilè.', meaning: 'Chúc bạn sinh nhật vui vẻ.' },
{ hanzi: '我累了，想休息一下。', pinyin: 'Wǒ lèile, xiǎng xiūxí yīxià.', meaning: 'Tôi mệt rồi, muốn nghỉ ngơi một chút.' },
{ hanzi: '学校离我家不远。', pinyin: 'Xuéxiào lí wǒ jiā bù yuǎn.', meaning: 'Trường học không xa nhà tôi.' },
{ hanzi: '我有两个弟弟。', pinyin: 'Wǒ yǒu liǎng gè dìdì.', meaning: 'Tôi có hai em trai.' },
{ hanzi: '这条路很长。', pinyin: 'Zhè tiáo lù hěn cháng.', meaning: 'Con đường này rất dài.' },
{ hanzi: '我喜欢旅游。', pinyin: 'Wǒ xǐhuān lǚyóu.', meaning: 'Tôi thích du lịch.' },
{ hanzi: '他在商店里卖东西。', pinyin: 'Tā zài shāngdiàn lǐ mài dōngxī.', meaning: 'Anh ấy bán hàng trong cửa hàng.' },
{ hanzi: '他走得很慢。', pinyin: 'Tā zǒu de hěn màn.', meaning: 'Anh ấy đi rất chậm.' },
{ hanzi: '我今天很忙。', pinyin: 'Wǒ jīntiān hěn máng.', meaning: 'Hôm nay tôi rất bận.' },
{ hanzi: '每个人都有机会。', pinyin: 'Měi gèrén dōu yǒu jīhuì.', meaning: 'Mỗi người đều có cơ hội.' },
{ hanzi: '妹妹在唱歌。', pinyin: 'Mèimei zài chànggē.', meaning: 'Em gái đang hát.' },
{ hanzi: '他站在门口。', pinyin: 'Tā zhàn zài ménkǒu.', meaning: 'Anh ấy đứng ở cửa.' },
{ hanzi: '那个男人很高。', pinyin: 'Nàgè nánrén hěn gāo.', meaning: 'Người đàn ông đó rất cao.' },
{ hanzi: '您好，请进。', pinyin: 'Nín hǎo, qǐng jìn.', meaning: 'Xin chào, mời vào.' },
{ hanzi: '我每天早上喝牛奶。', pinyin: 'Wǒ měitiān zǎoshang hē niúnǎi.', meaning: 'Tôi uống sữa mỗi sáng.' },
{ hanzi: '那个女人是我妈妈。', pinyin: 'Nàgè nǚrén shì wǒ māma.', meaning: 'Người phụ nữ đó là mẹ tôi.' },
{ hanzi: '学校在我家旁边。', pinyin: 'Xuéxiào zài wǒ jiā pángbiān.', meaning: 'Trường học ở cạnh nhà tôi.' },
{ hanzi: '我每天早上跑步。', pinyin: 'Wǒ měitiān zǎoshang pǎobù.', meaning: 'Tôi chạy bộ mỗi sáng.' },
{ hanzi: '这件衣服很便宜。', pinyin: 'Zhè jiàn yīfú hěn piányí.', meaning: 'Cái áo này rất rẻ.' },
{ hanzi: '我买了两张电影票。', pinyin: 'Wǒ mǎile liǎng zhāng diànyǐng piào.', meaning: 'Tôi đã mua hai vé xem phim.' },
{ hanzi: '这是我的妻子。', pinyin: 'Zhè shì wǒ de qīzi.', meaning: 'Đây là vợ tôi.' },
{ hanzi: '我每天六点起床。', pinyin: 'Wǒ měitiān liù diǎn qǐchuáng.', meaning: 'Tôi thức dậy lúc sáu giờ mỗi ngày.' },
{ hanzi: '我有一千块钱。', pinyin: 'Wǒ yǒu yīqiān kuài qián.', meaning: 'Tôi có một ngàn đồng.' },
{ hanzi: '今天是晴天。', pinyin: 'Jīntiān shì qíngtiān.', meaning: 'Hôm nay trời nắng.' },
{ hanzi: '我去年去了中国。', pinyin: 'Wǒ qùnián qùle zhōngguó.', meaning: 'Năm ngoái tôi đã đi Trung Quốc.' },
{ hanzi: '请让他进来。', pinyin: 'Qǐng ràng tā jìnlái.', meaning: 'Xin hãy để anh ấy vào.' },
{ hanzi: '我每天八点上班。', pinyin: 'Wǒ měitiān bā diǎn shàngbān.', meaning: 'Tôi đi làm lúc tám giờ mỗi ngày.' },
{ hanzi: '你的身体怎么样？', pinyin: 'Nǐ de shēntǐ zěnme yàng?', meaning: 'Sức khỏe của bạn thế nào?' },
{ hanzi: '他生病了，不能来上课。', pinyin: 'Tā shēngbìng le, bùnéng lái shàngkè.', meaning: 'Anh ấy bị ốm, không thể đến lớp.' },
{ hanzi: '今天是我的生日。', pinyin: 'Jīntiān shì wǒ de shēngrì.', meaning: 'Hôm nay là sinh nhật của tôi.' },
{ hanzi: '现在我没有时间。', pinyin: 'Xiànzài wǒ méiyǒu shíjiān.', meaning: 'Bây giờ tôi không có thời gian.' },
{ hanzi: '你在做什么事情？', pinyin: 'Nǐ zài zuò shénme shìqíng?', meaning: 'Bạn đang làm việc gì vậy?' },
{ hanzi: '这块手表很贵。', pinyin: 'Zhè kuài shǒubiǎo hěn guì.', meaning: 'Chiếc đồng hồ này rất đắt.' },
{ hanzi: '我的手机没电了。', pinyin: 'Wǒ de shǒujī méi diàn le.', meaning: 'Điện thoại của tôi hết pin rồi.' },
{ hanzi: '我送你一本书。', pinyin: 'Wǒ sòng nǐ yī běn shū.', meaning: 'Tôi tặng bạn một quyển sách.' },
{ hanzi: '他很累，所以休息了。', pinyin: 'Tā hěn lèi, suǒyǐ xiūxí le.', meaning: 'Anh ấy rất mệt, nên đã nghỉ ngơi rồi.' },
{ hanzi: '它是一只可爱的小猫。', pinyin: 'Tā shì yī zhī kě\'ài de xiǎo māo.', meaning: 'Nó là một chú mèo đáng yêu.' },
{ hanzi: '我们一起踢足球吧。', pinyin: 'Wǒmen yīqǐ tī zúqiú ba.', meaning: 'Chúng ta cùng chơi đá bóng nhé.' },
{ hanzi: '这道题很难。', pinyin: 'Zhè dào tí hěn nán.', meaning: 'Câu hỏi này rất khó.' },
{ hanzi: '我喜欢跳舞。', pinyin: 'Wǒ xǐhuān tiàowǔ.', meaning: 'Tôi thích nhảy múa.' },
{ hanzi: '他在外面等你。', pinyin: 'Tā zài wàimiàn děng nǐ.', meaning: 'Anh ấy đang đợi bạn ở bên ngoài.' },
{ hanzi: '小孩子们在玩游戏。', pinyin: 'Xiǎo háizimen zài wán yóuxì.', meaning: 'Các em nhỏ đang chơi trò chơi.' },
{ hanzi: '我已经做完了作业。', pinyin: 'Wǒ yǐjīng zuò wán le zuòyè.', meaning: 'Tôi đã làm xong bài tập.' },
{ hanzi: '我晚上九点睡觉。', pinyin: 'Wǒ wǎnshàng jiǔ diǎn shuìjiào.', meaning: 'Tôi đi ngủ lúc chín giờ tối.' },
{ hanzi: '你为什么不来？', pinyin: 'Nǐ wèishéme bù lái?', meaning: 'Tại sao bạn không đến?' },
{ hanzi: '请问你叫什么名字？', pinyin: 'Qǐng wèn nǐ jiào shénme míngzì?', meaning: 'Xin hỏi bạn tên là gì?' },
{ hanzi: '这个问题很重要。', pinyin: 'Zhège wèntí hěn zhòngyào.', meaning: 'Vấn đề này rất quan trọng.' },
{ hanzi: '我喜欢吃西瓜。', pinyin: 'Wǒ xǐhuān chī xīguā.', meaning: 'Tôi thích ăn dưa hấu.' },
{ hanzi: '我希望你能来。', pinyin: 'Wǒ xīwàng nǐ néng lái.', meaning: 'Tôi hy vọng bạn có thể đến.' },
{ hanzi: '请洗手。', pinyin: 'Qǐng xǐ shǒu.', meaning: 'Xin rửa tay.' },
{ hanzi: '向左走。', pinyin: 'Xiàng zuǒ zǒu.', meaning: 'Đi về phía bên trái.' },
{ hanzi: '我每天学习一个小时。', pinyin: 'Wǒ měitiān xuéxí yī gè xiǎoshí.', meaning: 'Tôi học một tiếng mỗi ngày.' },
{ hanzi: '他在笑什么？', pinyin: 'Tā zài xiào shénme?', meaning: 'Anh ấy đang cười gì vậy?' },
{ hanzi: '我有一个新手机。', pinyin: 'Wǒ yǒu yī gè xīn shǒujī.', meaning: 'Tôi có một chiếc điện thoại mới.' },
{ hanzi: '你姓什么？', pinyin: 'Nǐ xìng shénme?', meaning: 'Họ của bạn là gì?' },
{ hanzi: '我累了，需要休息。', pinyin: 'Wǒ lèile, xūyào xiūxí.', meaning: 'Tôi mệt rồi, cần nghỉ ngơi.' },
{ hanzi: '明天会下雪。', pinyin: 'Míngtiān huì xià xuě.', meaning: 'Ngày mai sẽ có tuyết rơi.' },
{ hanzi: '你喜欢什么颜色？', pinyin: 'Nǐ xǐhuān shénme yánsè?', meaning: 'Bạn thích màu gì?' },
{ hanzi: '他的眼睛很大。', pinyin: 'Tā de yǎnjīng hěn dà.', meaning: 'Mắt của anh ấy rất to.' },
{ hanzi: '我喜欢吃羊肉。', pinyin: 'Wǒ xǐhuān chī yángròu.', meaning: 'Tôi thích ăn thịt cừu.' },
{ hanzi: '我要一杯水。', pinyin: 'Wǒ yào yī bēi shuǐ.', meaning: 'Tôi muốn một cốc nước.' },
{ hanzi: '我生病了，要吃药。', pinyin: 'Wǒ shēngbìng le, yào chī yào.', meaning: 'Tôi bị ốm, cần uống thuốc.' },
{ hanzi: '他也喜欢游泳。', pinyin: 'Tā yě xǐhuān yóuyǒng.', meaning: 'Anh ấy cũng thích bơi lội.' },
{ hanzi: '我已经吃过饭了。', pinyin: 'Wǒ yǐjīng chī guò fàn le.', meaning: 'Tôi đã ăn cơm rồi.' },
{ hanzi: '我们一起去看电影吧。', pinyin: 'Wǒmen yīqǐ qù kàn diànyǐng ba.', meaning: 'Chúng ta cùng đi xem phim nhé.' },
{ hanzi: '这是什么意思？', pinyin: 'Zhè shì shénme yìsi?', meaning: 'Điều này có nghĩa là gì?' },
{ hanzi: '今天是阴天。', pinyin: 'Jīntiān shì yīntiān.', meaning: 'Hôm nay là ngày trời âm u.' },
{ hanzi: '因为下雨，我不去跑步。', pinyin: 'Yīnwèi xiàyǔ, wǒ bú qù pǎobù.', meaning: 'Vì trời mưa, tôi không đi chạy bộ.' },
{ hanzi: '我喜欢游泳。', pinyin: 'Wǒ xǐhuān yóuyǒng.', meaning: 'Tôi thích bơi lội.' },
{ hanzi: '他坐在我右边。', pinyin: 'Tā zuò zài wǒ yòubiān.', meaning: 'Anh ấy ngồi bên phải tôi.' },
{ hanzi: '我们晚饭吃鱼。', pinyin: 'Wǒmen wǎnfàn chī yú.', meaning: 'Chúng tôi ăn cá vào bữa tối.' },
{ hanzi: '这本书要十元。', pinyin: 'Zhè běn shū yào shí yuán.', meaning: 'Quyển sách này giá mười đồng.' },
{ hanzi: '他家离学校很远。', pinyin: 'Tā jiā lí xuéxiào hěn yuǎn.', meaning: 'Nhà anh ấy cách xa trường học.' },
{ hanzi: '我每天都运动。', pinyin: 'Wǒ měitiān dōu yùndòng.', meaning: 'Tôi tập thể dục mỗi ngày.' },
{ hanzi: '请再说一遍。', pinyin: 'Qǐng zài shuō yī biàn.', meaning: 'Xin hãy nói lại một lần nữa.' },
{ hanzi: '我每天早上六点起床。', pinyin: 'Wǒ měitiān zǎoshang liù diǎn qǐchuáng.', meaning: 'Tôi dậy lúc sáu giờ sáng mỗi ngày.' },
{ hanzi: '这是一张照片。', pinyin: 'Zhè shì yī zhāng zhàopiàn.', meaning: 'Đây là một tấm ảnh.' },
{ hanzi: '这是我的丈夫。', pinyin: 'Zhè shì wǒ de zhàngfu.', meaning: 'Đây là chồng tôi.' },
{ hanzi: '我在找我的钥匙。', pinyin: 'Wǒ zài zhǎo wǒ de yàoshi.', meaning: 'Tôi đang tìm chìa khóa của mình.' },
{ hanzi: '他在吃着饭呢。', pinyin: 'Tā zài chī zhe fàn ne.', meaning: 'Anh ấy đang ăn cơm.' },
{ hanzi: '这个苹果真好吃。', pinyin: 'Zhège píngguǒ zhēn hào chī.', meaning: 'Quả táo này thật ngon.' },
{ hanzi: '妈妈正在打电话。', pinyin: 'Māma zhèngzài dǎ diànhuà.', meaning: 'Mẹ đang gọi điện thoại.' },
{ hanzi: '我知道他是谁。', pinyin: 'Wǒ zhīdào tā shì shéi.', meaning: 'Tôi biết anh ấy là ai.' },
{ hanzi: '我正在准备考试。', pinyin: 'Wǒ zhèngzài zhǔnbèi kǎoshì.', meaning: 'Tôi đang chuẩn bị cho kỳ thi.' },
{ hanzi: '他骑自行车去上班。', pinyin: 'Tā qí zìxíngchē qù shàngbān.', meaning: 'Anh ấy đi làm bằng xe đạp.' },
{ hanzi: '我们一起走吧。', pinyin: 'Wǒmen yīqǐ zǒu ba.', meaning: 'Chúng ta cùng đi nhé.' },
{ hanzi: '这是我最喜欢的书。', pinyin: 'Zhè shì wǒ zuì xǐhuān de shū.', meaning: 'Đây là cuốn sách tôi thích nhất.' },
{ hanzi: '他坐在我左边。', pinyin: 'Tā zuò zài wǒ zuǒbiān.', meaning: 'Anh ấy ngồi bên trái tôi.' },

];