vocab = [
  { hanzi: '阿姨非常喜欢我们', pinyin: 'Āyí fēicháng xǐhuān wǒmen', meaning: 'Dì rất thích chúng tôi' },
{ hanzi: '啊，我忘记了！', pinyin: 'A, wǒ wàngjì le!', meaning: 'À, tôi quên rồi!' },
{ hanzi: '他比我矮', pinyin: 'Tā bǐ wǒ ǎi', meaning: 'Anh ấy thấp hơn tôi' },
{ hanzi: '我的爱好是画画儿', pinyin: 'Wǒ de àihào shì huà huàr', meaning: 'Sở thích của tôi là vẽ tranh' },
{ hanzi: '请保持安静', pinyin: 'Qǐng bǎochí ānjìng', meaning: 'Xin hãy giữ yên lặng' },
{ hanzi: '把书给我', pinyin: 'Bǎ shū gěi wǒ', meaning: 'Đưa cuốn sách cho tôi' },
{ hanzi: '我们班有二十个学生', pinyin: 'Wǒmen bān yǒu èrshí gè xuéshēng', meaning: 'Lớp chúng tôi có hai mươi học sinh' },
{ hanzi: '他搬家到北京了', pinyin: 'Tā bānjiā dào Běijīng le', meaning: 'Anh ấy đã chuyển nhà đến Bắc Kinh' },
{ hanzi: '我们半个小时后见', pinyin: 'Wǒmen bàn gè xiǎoshí hòu jiàn', meaning: 'Chúng ta gặp nhau sau nửa giờ' },
{ hanzi: '我有一个好办法', pinyin: 'Wǒ yǒu yīgè hǎo bànfǎ', meaning: 'Tôi có một cách hay' },
{ hanzi: '他在办公室工作', pinyin: 'Tā zài bàngōngshì gōngzuò', meaning: 'Anh ấy làm việc ở văn phòng' },
{ hanzi: '有你帮忙我就放心了', pinyin: 'Yǒu nǐ bāngmáng wǒ jiù fàngxīn le', meaning: 'Có bạn giúp thì tôi yên tâm rồi' },
{ hanzi: '我的包丢了', pinyin: 'Wǒ de bāo diū le', meaning: 'Cái túi của tôi bị mất rồi' },
{ hanzi: '我吃饱了', pinyin: 'Wǒ chī bǎo le', meaning: 'Tôi ăn no rồi' },
{ hanzi: '北方的冬天很冷', pinyin: 'Běifāng de dōngtiān hěn lěng', meaning: 'Mùa đông ở phía Bắc rất lạnh' },
{ hanzi: '他被老师表扬了', pinyin: 'Tā bèi lǎoshī biǎoyáng le', meaning: 'Anh ấy được thầy giáo khen ngợi' },
{ hanzi: '她比较高', pinyin: 'Tā bǐjiào gāo', meaning: 'Cô ấy khá cao' },
{ hanzi: '他们在参加比赛', pinyin: 'Tāmen zài cānjiā bǐsài', meaning: 'Họ đang tham gia thi đấu' },
{ hanzi: '你必须按时到', pinyin: 'Nǐ bìxū ànshí dào', meaning: 'Bạn phải đến đúng giờ' },
{ hanzi: '这里的天气变化很大', pinyin: 'Zhèlǐ de tiānqì biànhuà hěn dà', meaning: 'Thời tiết ở đây thay đổi rất nhiều' },
{ hanzi: '他表示同意这个计划', pinyin: 'Tā biǎoshì tóngyì zhège jìhuà', meaning: 'Anh ấy thể hiện đồng ý với kế hoạch này' },
{ hanzi: '她在表演节目', pinyin: 'Tā zài biǎoyǎn jiémù', meaning: 'Cô ấy đang biểu diễn chương trình' },
{ hanzi: '别人的意见很重要', pinyin: 'Biérén de yìjiàn hěn zhòngyào', meaning: 'Ý kiến của người khác rất quan trọng' },
{ hanzi: '宾馆的房间很干净', pinyin: 'Bīnguǎn de fángjiān hěn gānjìng', meaning: 'Phòng của khách sạn rất sạch sẽ' },
{ hanzi: '冰箱里有很多食物', pinyin: 'Bīngxiāng lǐ yǒu hěn duō shíwù', meaning: 'Trong tủ lạnh có rất nhiều thức ăn' },
{ hanzi: '为什么你现在才来', pinyin: 'Wèi shénme nǐ xiànzài cái lái?', meaning: 'Tại sao bây giờ bạn mới tới?' },
{ hanzi: '菜单上有很多菜', pinyin: 'Càidān shàng yǒu hěn duō cài', meaning: 'Trên thực đơn có nhiều món ăn' },
{ hanzi: '我参加了这个活动', pinyin: 'Wǒ cānjiā le zhège huódòng', meaning: 'Tôi đã tham gia hoạt động này' },
{ hanzi: '草地上有很多花', pinyin: 'Cǎodì shàng yǒu hěn duō huā', meaning: 'Trên bãi cỏ có nhiều hoa' },
{ hanzi: '我住在三层', pinyin: 'Wǒ zhù zài sān céng', meaning: 'Tôi sống ở tầng ba' },
{ hanzi: '今天的天气很差', pinyin: 'Jīntiān de tiānqì hěn chà', meaning: 'Thời tiết hôm nay rất tệ' },
{ hanzi: '我去超市买东西', pinyin: 'Wǒ qù chāoshì mǎi dōngxi', meaning: 'Tôi đi siêu thị mua đồ' },
{ hanzi: '他穿了一件白衬衫', pinyin: 'Tā chuān le yī jiàn bái chènshān', meaning: 'Anh ấy mặc một chiếc áo sơ mi trắng' },
{ hanzi: '他的成绩很好', pinyin: 'Tā de chéngjī hěn hǎo', meaning: 'Thành tích của anh ấy rất tốt' },
{ hanzi: '这座城市很大', pinyin: 'Zhè zuò chéngshì hěn dà', meaning: 'Thành phố này rất lớn' },
{ hanzi: '他今天迟到了', pinyin: 'Tā jīntiān chídào le', meaning: 'Hôm nay anh ấy đến muộn' },
{ hanzi: '我们出现了问题', pinyin: 'Wǒmen chūxiàn le wèntí', meaning: 'Chúng tôi gặp vấn đề rồi' },
{ hanzi: '厨房很干净', pinyin: 'Chúfáng hěn gānjìng', meaning: 'Nhà bếp rất sạch' },
{ hanzi: '除了他，大家都来了', pinyin: 'Chúle tā, dàjiā dōu lái le', meaning: 'Ngoài anh ấy, mọi người đều đến' },
{ hanzi: '春天来了，花开了', pinyin: 'Chūntiān lái le, huā kāi le', meaning: 'Mùa xuân đến rồi, hoa nở rồi' },
{ hanzi: '我喜欢学习新词语', pinyin: 'Wǒ xǐhuān xuéxí xīn cíyǔ', meaning: 'Tôi thích học từ mới' },
{ hanzi: '她很聪明，总是知道答案', pinyin: 'Tā hěn cōngmíng, zǒng shì zhīdào dá\'àn', meaning: 'Cô ấy rất thông minh, luôn biết đáp án' },
{ hanzi: '我们一起打扫房间吧', pinyin: 'Wǒmen yīqǐ dǎsǎo fángjiān ba', meaning: 'Chúng ta cùng dọn phòng nhé' },
{ hanzi: '我打算去旅游', pinyin: 'Wǒ dǎsuàn qù lǚyóu', meaning: 'Tôi dự định đi du lịch' },
{ hanzi: '别忘了带雨伞', pinyin: 'Bié wàngle dài yǔsǎn', meaning: 'Đừng quên mang theo ô' },
{ hanzi: '我担心他的健康', pinyin: 'Wǒ dānxīn tā de jiànkāng', meaning: 'Tôi lo lắng cho sức khỏe của anh ấy' },
{ hanzi: '生日快乐，给你蛋糕', pinyin: 'Shēngrì kuàilè, gěi nǐ dàngāo', meaning: 'Sinh nhật vui vẻ, tặng bạn bánh ngọt' },
{ hanzi: '你当然可以去', pinyin: 'Nǐ dāngrán kěyǐ qù', meaning: 'Đương nhiên bạn có thể đi' },
{ hanzi: '请慢慢地说', pinyin: 'Qǐng mànmàn de shuō', meaning: 'Xin hãy nói chậm lại' },
{ hanzi: '请开灯', pinyin: 'Qǐng kāi dēng', meaning: 'Vui lòng bật đèn' },
{ hanzi: '他的声音很低', pinyin: 'Tā de shēngyīn hěn dī', meaning: 'Giọng anh ấy rất nhỏ' },
{ hanzi: '这个地方很好玩', pinyin: 'Zhège dìfāng hěn hǎowán', meaning: 'Nơi này rất vui' },
{ hanzi: '我坐地铁去上班', pinyin: 'Wǒ zuò dìtiě qù shàngbān', meaning: 'Tôi đi làm bằng tàu điện ngầm' },
{ hanzi: '你有这座城市的地图吗？', pinyin: 'Nǐ yǒu zhè zuò chéngshì de dìtú ma?', meaning: 'Bạn có bản đồ của thành phố này không?' },
{ hanzi: '我们坐电梯上楼', pinyin: 'Wǒmen zuò diàntī shàng lóu', meaning: 'Chúng tôi đi thang máy lên lầu' },
{ hanzi: '请发电子邮件给我', pinyin: 'Qǐng fā diànzǐ yóujiàn gěi wǒ', meaning: 'Xin gửi email cho tôi' },
{ hanzi: '东边有一座山', pinyin: 'Dōngbiān yǒu yī zuò shān', meaning: 'Phía đông có một ngọn núi' },
{ hanzi: '冬天很冷', pinyin: 'Dōngtiān hěn lěng', meaning: 'Mùa đông rất lạnh' },
{ hanzi: '我喜欢动物', pinyin: 'Wǒ xǐhuān dòngwù', meaning: 'Tôi thích động vật' },
{ hanzi: '这条裙子太短了', pinyin: 'Zhè tiáo qúnzi tài duǎn le', meaning: 'Chiếc váy này quá ngắn' },
{ hanzi: '他讲了一段故事', pinyin: 'Tā jiǎng le yī duàn gùshì', meaning: 'Anh ấy đã kể một đoạn câu chuyện' },
{ hanzi: '我每天锻炼身体', pinyin: 'Wǒ měitiān duànliàn shēntǐ', meaning: 'Tôi tập thể dục mỗi ngày' },
{ hanzi: '这里的景色多么美丽', pinyin: 'Zhèlǐ de jǐngsè duōme měilì', meaning: 'Cảnh ở đây đẹp làm sao' },
{ hanzi: '我饿了，想吃饭', pinyin: 'Wǒ è le, xiǎng chī fàn', meaning: 'Tôi đói rồi, muốn ăn cơm' },
{ hanzi: '他聪明而且很努力', pinyin: 'Tā cōngmíng érqiě hěn nǔlì', meaning: 'Anh ấy thông minh hơn nữa rất chăm chỉ' },
{ hanzi: '我的耳朵很敏感', pinyin: 'Wǒ de ěrduo hěn mǐngǎn', meaning: 'Tai tôi rất nhạy cảm' },
{ hanzi: '他发烧了，要休息', pinyin: 'Tā fāshāo le, yào xiūxí', meaning: 'Anh ấy bị sốt, cần nghỉ ngơi' },
{ hanzi: '我发现了一个秘密', pinyin: 'Wǒ fāxiàn le yīgè mìmì', meaning: 'Tôi đã phát hiện ra một bí mật' },
{ hanzi: '这里很方便', pinyin: 'Zhèlǐ hěn fāngbiàn', meaning: 'Ở đây rất tiện lợi' },
{ hanzi: '请把书放在桌子上', pinyin: 'Qǐng bǎ shū fàng zài zhuōzi shàng', meaning: 'Vui lòng để sách lên bàn' },
{ hanzi: '请你放心', pinyin: 'Qǐng nǐ fàngxīn', meaning: 'Xin bạn yên tâm' },
{ hanzi: '我们八点十分出发', pinyin: 'Wǒmen bā diǎn shí fēn chūfā', meaning: 'Chúng ta khởi hành lúc tám giờ mười phút' },
{ hanzi: '我家附近有公园', pinyin: 'Wǒ jiā fùjìn yǒu gōngyuán', meaning: 'Gần nhà tôi có công viên' },
{ hanzi: '我需要复习功课', pinyin: 'Wǒ xūyào fùxí gōngkè', meaning: 'Tôi cần ôn bài' },
{ hanzi: '房间很干净', pinyin: 'Fángjiān hěn gānjìng', meaning: 'Phòng rất sạch sẽ' },
{ hanzi: '我敢说你是对的', pinyin: 'Wǒ gǎn shuō nǐ shì duì de', meaning: 'Tôi dám nói bạn đúng' },
{ hanzi: '他感冒了，不能来', pinyin: 'Tā gǎnmào le, bùnéng lái', meaning: 'Anh ấy bị cảm, không thể đến' },
{ hanzi: '刚才我看见他了', pinyin: 'Gāngcái wǒ kànjiàn tā le', meaning: 'Vừa rồi tôi đã nhìn thấy anh ấy' },
{ hanzi: '我跟他一起去', pinyin: 'Wǒ gēn tā yīqǐ qù', meaning: 'Tôi đi cùng anh ấy' },
{ hanzi: '根据天气预报，今天会下雨', pinyin: 'Gēnjù tiānqì yùbào, jīntiān huì xiàyǔ', meaning: 'Theo dự báo thời tiết, hôm nay sẽ mưa' },
{ hanzi: '她比我更高', pinyin: 'Tā bǐ wǒ gèng gāo', meaning: 'Cô ấy cao hơn tôi' },
{ hanzi: '我喜欢去公园散步', pinyin: 'Wǒ xǐhuān qù gōngyuán sànbù', meaning: 'Tôi thích đi dạo trong công viên' },
{ hanzi: '这个故事很有趣', pinyin: 'Zhège gùshì hěn yǒuqù', meaning: 'Câu chuyện này rất thú vị' },
{ hanzi: '今天刮风了', pinyin: 'Jīntiān guāfēng le', meaning: 'Hôm nay gió thổi mạnh' },
{ hanzi: '请关门', pinyin: 'Qǐng guān mén', meaning: 'Vui lòng đóng cửa' },
{ hanzi: '我们是好朋友，关系很好', pinyin: 'Wǒmen shì hǎo péngyǒu, guānxì hěn hǎo', meaning: 'Chúng tôi là bạn tốt, quan hệ rất tốt' },
{ hanzi: '她很关心我', pinyin: 'Tā hěn guānxīn wǒ', meaning: 'Cô ấy rất quan tâm đến tôi' },
{ hanzi: '这是关于旅行的书', pinyin: 'Zhè shì guānyú lǚxíng de shū', meaning: 'Đây là cuốn sách về du lịch' },
{ hanzi: '我爱我的国家', pinyin: 'Wǒ ài wǒ de guójiā', meaning: 'Tôi yêu đất nước của tôi' },
{ hanzi: '请给我一杯果汁', pinyin: 'Qǐng gěi wǒ yī bēi guǒzhī', meaning: 'Vui lòng cho tôi một ly nước ép' },
{ hanzi: '我们过去是同学', pinyin: 'Wǒmen guòqù shì tóngxué', meaning: 'Chúng tôi từng là bạn học' },
{ hanzi: '你还是学生吗？', pinyin: 'Nǐ háishì xuéshēng ma?', meaning: 'Bạn vẫn là học sinh à?' },
{ hanzi: '我害怕黑暗', pinyin: 'Wǒ hàipà hēi\'àn', meaning: 'Tôi sợ bóng tối' },
{ hanzi: '河边有很多花', pinyin: 'Hé biān yǒu hěn duō huā', meaning: 'Bên bờ sông có nhiều hoa' },
{ hanzi: '请在黑板上写字', pinyin: 'Qǐng zài hēibǎn shàng xiězì', meaning: 'Vui lòng viết lên bảng' },
{ hanzi: '我需要护照去旅行', pinyin: 'Wǒ xūyào hùzhào qù lǚxíng', meaning: 'Tôi cần hộ chiếu để đi du lịch' },
{ hanzi: '这里的花开得很美', pinyin: 'Zhèlǐ de huā kāi de hěn měi', meaning: 'Hoa ở đây nở rất đẹp' },
{ hanzi: '我们在花园里玩', pinyin: 'Wǒmen zài huāyuán lǐ wán', meaning: 'Chúng tôi chơi trong vườn hoa' },
{ hanzi: '他喜欢画画儿', pinyin: 'Tā xǐhuān huà huàr', meaning: 'Anh ấy thích vẽ tranh' },
{ hanzi: '我的手机坏了', pinyin: 'Wǒ de shǒujī huài le', meaning: 'Điện thoại của tôi bị hỏng rồi' },
{ hanzi: '你什么时候把钱还给我?', pinyin: 'Nǐ shénme shíhòu bǎ qián huán gěi wǒ?', meaning: 'Khi nào bạn trả tiền cho tôi?' },
{ hanzi: '我喜欢安静的环境', pinyin: 'Wǒ xǐhuān ānjìng de huánjìng', meaning: 'Tôi thích môi trường yên tĩnh' },
{ hanzi: '我想换工作', pinyin: 'Wǒ xiǎng huàn gōngzuò', meaning: 'Tôi muốn đổi công việc' },
{ hanzi: '这条裙子是黄色的', pinyin: 'Zhè tiáo qúnzi shì huángsè de', meaning: 'Chiếc váy này màu vàng' },
{ hanzi: '会议将在下午三点开始', pinyin: 'Huìyì jiāng zài xiàwǔ sān diǎn kāishǐ', meaning: 'Cuộc họp sẽ bắt đầu lúc ba giờ chiều' },
{ hanzi: '你可以选择苹果或者香蕉', pinyin: 'Nǐ kěyǐ xuǎnzé píngguǒ huòzhě xiāngjiāo', meaning: 'Bạn có thể chọn táo hoặc chuối' },
{ hanzi: '这是一个好机会', pinyin: 'Zhè shì yīgè hǎo jīhuì', meaning: 'Đây là một cơ hội tốt' },
{ hanzi: '他几乎每天都锻炼', pinyin: 'Tā jīhū měitiān dōu duànliàn', meaning: 'Anh ấy hầu như tập thể dục mỗi ngày' },
{ hanzi: '这个菜的味道好极了', pinyin: 'Zhège cài de wèidào hǎo jí le', meaning: 'Mùi vị của món ăn này cực kỳ ngon' },
{ hanzi: '请记得带钥匙', pinyin: 'Qǐng jìdé dài yàoshi', meaning: 'Hãy nhớ mang theo chìa khóa' },
{ hanzi: '我最喜欢的季节是春天', pinyin: 'Wǒ zuì xǐhuān de jìjié shì chūntiān', meaning: 'Mùa yêu thích của tôi là mùa xuân' },
{ hanzi: '老师检查了我们的作业', pinyin: 'Lǎoshī jiǎnchá le wǒmen de zuòyè', meaning: 'Thầy giáo đã kiểm tra bài tập của chúng tôi' },
{ hanzi: '这个问题很简单', pinyin: 'Zhège wèntí hěn jiǎndān', meaning: 'Câu hỏi này rất đơn giản' },
{ hanzi: '健康比什么都重要', pinyin: 'Jiànkāng bǐ shénme dōu zhòngyào', meaning: 'Sức khỏe quan trọng hơn mọi thứ' },
{ hanzi: '我们明天见面吧', pinyin: 'Wǒmen míngtiān jiànmiàn ba', meaning: 'Chúng ta gặp nhau vào ngày mai nhé' },
{ hanzi: '他喜欢讲故事', pinyin: 'Tā xǐhuān jiǎng gùshì', meaning: 'Anh ấy thích kể chuyện' },
{ hanzi: '他教我们汉语', pinyin: 'Tā jiāo wǒmen Hànyǔ', meaning: 'Anh ấy dạy chúng tôi tiếng Trung' },
{ hanzi: '猫在桌子的角落里', pinyin: 'Māo zài zhuōzi de jiǎoluò lǐ', meaning: 'Con mèo ở góc bàn' },
{ hanzi: '我的脚很疼', pinyin: 'Wǒ de jiǎo hěn téng', meaning: 'Chân tôi rất đau' },
{ hanzi: '请接电话', pinyin: 'Qǐng jiē diànhuà', meaning: 'Vui lòng nghe điện thoại' },
{ hanzi: '这条街道很宽', pinyin: 'Zhè tiáo jiēdào hěn kuān', meaning: 'Con đường này rất rộng' },
{ hanzi: '他们结婚了', pinyin: 'Tāmen jiéhūn le', meaning: 'Họ đã kết hôn' },
{ hanzi: '会议结束了', pinyin: 'Huìyì jiéshù le', meaning: 'Cuộc họp đã kết thúc' },
{ hanzi: '我喜欢这个节目', pinyin: 'Wǒ xǐhuān zhège jiémù', meaning: 'Tôi thích chương trình này' },
{ hanzi: '春节是中国的传统节日', pinyin: 'Chūnjié shì Zhōngguó de chuántǒng jiérì', meaning: 'Tết Nguyên Đán là ngày lễ truyền thống của Trung Quốc' },
{ hanzi: '我们需要解决这个问题', pinyin: 'Wǒmen xūyào jiějué zhège wèntí', meaning: 'Chúng ta cần giải quyết vấn đề này' },
{ hanzi: '我可以借你的书吗？', pinyin: 'Wǒ kěyǐ jiè nǐ de shū ma?', meaning: 'Tôi có thể mượn sách của bạn không?' },
{ hanzi: '我经常去图书馆', pinyin: 'Wǒ jīngcháng qù túshūguǎn', meaning: 'Tôi thường xuyên đến thư viện' },
{ hanzi: '他经过我家门口', pinyin: 'Tā jīngguò wǒ jiā ménkǒu', meaning: 'Anh ấy đi qua cửa nhà tôi' },
{ hanzi: '这是一段难忘的经历', pinyin: 'Zhè shì yī duàn nánwàng de jīnglì', meaning: 'Đây là một trải nghiệm khó quên' },
{ hanzi: '我等了很久', pinyin: 'Wǒ děng le hěn jiǔ', meaning: 'Tôi đã đợi rất lâu' },
{ hanzi: '这本书很旧', pinyin: 'Zhè běn shū hěn jiù', meaning: 'Cuốn sách này rất cũ' },
{ hanzi: '学校将举行运动会', pinyin: 'Xuéxiào jiāng jǔxíng yùndònghuì', meaning: 'Trường sẽ tổ chức đại hội thể thao' },
{ hanzi: '请你用这个词语造句子', pinyin: 'Qǐng nǐ yòng zhège cíyǔ zào jùzi', meaning: 'Vui lòng dùng từ này để tạo câu' },
{ hanzi: '我决定明天去旅行', pinyin: 'Wǒ juédìng míngtiān qù lǚxíng', meaning: 'Tôi quyết định đi du lịch vào ngày mai' },
{ hanzi: '这只猫很可爱', pinyin: 'Zhè zhǐ māo hěn kě\'ài', meaning: 'Con mèo này rất dễ thương' },
{ hanzi: '八点一刻我来', pinyin: 'Bā diǎn yí kè wǒ lái', meaning: '8 giờ 15 phút tôi tới' },
{ hanzi: '客人已经来了', pinyin: 'Kèrén yǐjīng lái le', meaning: 'Khách đã đến rồi' },
{ hanzi: '房间里有空调', pinyin: 'Fángjiān lǐ yǒu kòngtiáo', meaning: 'Trong phòng có điều hòa' },
{ hanzi: '瓶子口上贴着一张纸', pinyin: 'Píngzi kǒu shàng tiē zhe yì zhāng zhǐ', meaning: 'Trên miệng chai có dán 1 tờ giấy' },
{ hanzi: '孩子们在哭', pinyin: 'Háizimen zài kū', meaning: 'Bọn trẻ đang khóc' },
{ hanzi: '他穿了一条新裤子', pinyin: 'Tā chuān le yī tiáo xīn kùzi', meaning: 'Anh ấy mặc một chiếc quần mới' },
{ hanzi: '我用筷子吃饭', pinyin: 'Wǒ yòng kuàizi chīfàn', meaning: 'Tôi dùng đũa để ăn cơm' },
{ hanzi: '天空是蓝色的', pinyin: 'Tiānkōng shì lánsè de', meaning: 'Bầu trời màu xanh' },
{ hanzi: '他是个老朋友', pinyin: 'Tā shì gè lǎo péngyǒu', meaning: 'Anh ấy là bạn cũ' },
{ hanzi: '他已经离开了', pinyin: 'Tā yǐjīng líkāi le', meaning: 'Anh ấy đã rời đi rồi' },
{ hanzi: '这是我的生日礼物', pinyin: 'Zhè shì wǒ de shēngrì lǐwù', meaning: 'Đây là quà sinh nhật của tôi' },
{ hanzi: '他喜欢学习历史', pinyin: 'Tā xǐhuān xuéxí lìshǐ', meaning: 'Anh ấy thích học lịch sử' },
{ hanzi: '她的脸很漂亮', pinyin: 'Tā de liǎn hěn piàoliang', meaning: 'Khuôn mặt cô ấy rất đẹp' },
{ hanzi: '我每天练习中文', pinyin: 'Wǒ měitiān liànxí Zhōngwén', meaning: 'Tôi luyện tập tiếng Trung mỗi ngày' },
{ hanzi: '他有一辆新车', pinyin: 'Tā yǒu yī liàng xīn chē', meaning: 'Anh ấy có một chiếc xe mới' },
{ hanzi: '我了解你的意思', pinyin: 'Wǒ liǎojiě nǐ de yìsi', meaning: 'Tôi hiểu ý của bạn' },
{ hanzi: '我的邻居很友好', pinyin: 'Wǒ de línjū hěn yǒuhǎo', meaning: 'Hàng xóm của tôi rất thân thiện' },
{ hanzi: '我们住在三楼', pinyin: 'Wǒmen zhù zài sān lóu', meaning: 'Chúng tôi sống ở tầng ba' },
{ hanzi: '马跑得很快', pinyin: 'Mǎ pǎo de hěn kuài', meaning: 'Con ngựa chạy rất nhanh' },
{ hanzi: '我马上就来', pinyin: 'Wǒ mǎshàng jiù lái', meaning: 'Tôi sẽ đến ngay' },
{ hanzi: '我对结果很满意', pinyin: 'Wǒ duì jiéguǒ hěn mǎnyì', meaning: 'Tôi rất hài lòng với kết quả' },
{ hanzi: '这顶帽子很漂亮', pinyin: 'Zhè dǐng màozi hěn piàoliang', meaning: 'Chiếc mũ này rất đẹp' },
{ hanzi: '我吃了一碗米饭', pinyin: 'Wǒ chī le yī wǎn mǐfàn', meaning: 'Tôi đã ăn một bát cơm' },
{ hanzi: '我每天早餐都吃面包', pinyin: 'Wǒ měitiān zǎocān dōu chī miànbāo', meaning: 'Tôi ăn bánh mì vào bữa sáng mỗi ngày' },
{ hanzi: '他喜欢吃面条', pinyin: 'Tā xǐhuān chī miàntiáo', meaning: 'Anh ấy thích ăn mì' },
{ hanzi: '我明白你的意思', pinyin: 'Wǒ míngbái nǐ de yìsi', meaning: 'Tôi hiểu ý của bạn' },
{ hanzi: '请你帮我拿一下书', pinyin: 'Qǐng nǐ bāng wǒ ná yīxià shū', meaning: 'Vui lòng giúp tôi cầm sách một chút' },
{ hanzi: '我奶奶住在乡下', pinyin: 'Wǒ nǎinai zhù zài xiāngxià', meaning: 'Bà nội của tôi sống ở quê' },
{ hanzi: '我们往南走', pinyin: 'Wǒmen wǎng nán zǒu', meaning: 'Chúng ta đi về hướng nam' },
{ hanzi: '这个问题很难', pinyin: 'Zhège wèntí hěn nán', meaning: 'Vấn đề này rất khó' },
{ hanzi: '他听到这个消息很难过', pinyin: 'Tā tīngdào zhège xiāoxi hěn nánguò', meaning: 'Anh ấy rất buồn khi nghe tin này' },
{ hanzi: '我今年上三年级', pinyin: 'Wǒ jīnnián shàng sān niánjí', meaning: 'Năm nay tôi học lớp ba' },
{ hanzi: '她很年轻', pinyin: 'Tā hěn niánqīng', meaning: 'Cô ấy rất trẻ' },
{ hanzi: '树上有很多鸟', pinyin: 'Shù shàng yǒu hěn duō niǎo', meaning: 'Trên cây có nhiều chim' },
{ hanzi: '他学习很努力', pinyin: 'Tā xuéxí hěn nǔlì', meaning: 'Anh ấy học rất chăm chỉ' },
{ hanzi: '周末我们去爬山吧', pinyin: 'Zhōumò wǒmen qù páshān ba', meaning: 'Cuối tuần chúng ta đi leo núi nhé' },
{ hanzi: '请把盘子放在桌子上', pinyin: 'Qǐng bǎ pánzi fàng zài zhuōzi shàng', meaning: 'Vui lòng đặt đĩa lên bàn' },
{ hanzi: '这个小孩有点儿胖', pinyin: 'Zhège xiǎohái yǒudiǎnr pàng', meaning: 'Đứa trẻ này hơi mập' },
{ hanzi: '我不喝啤酒', pinyin: 'Wǒ bù hē píjiǔ', meaning: 'Tôi không uống bia' },
{ hanzi: '我喜欢吃葡萄', pinyin: 'Wǒ xǐhuān chī pútáo', meaning: 'Tôi thích ăn nho' },
{ hanzi: '他说普通话说得很流利', pinyin: 'Tā shuō Pǔtōnghuà shuō de hěn liúlì', meaning: 'Anh ấy nói tiếng Phổ thông rất lưu loát' },
{ hanzi: '我喜欢骑自行车', pinyin: 'Wǒ xǐhuān qí zìxíngchē', meaning: 'Tôi thích đi xe đạp' },
{ hanzi: '其实我不太喜欢吃辣', pinyin: 'Qíshí wǒ bù tài xǐhuān chī là', meaning: 'Thật ra tôi không thích ăn cay lắm' },
{ hanzi: '其他人都已经走了', pinyin: 'Qítā rén dōu yǐjīng zǒu le', meaning: 'Những người khác đều đã đi rồi' },
{ hanzi: '这个事情很奇怪', pinyin: 'Zhège shìqíng hěn qíguài', meaning: 'Chuyện này rất kỳ lạ' },
{ hanzi: '我需要一支铅笔', pinyin: 'Wǒ xūyào yī zhī qiānbǐ', meaning: 'Tôi cần một cây bút chì' },
{ hanzi: '我不太清楚他的名字', pinyin: 'Wǒ bù tài qīngchǔ tā de míngzi', meaning: 'Tôi không rõ tên của anh ấy lắm' },
{ hanzi: '秋天是我最喜欢的季节', pinyin: 'Qiūtiān shì wǒ zuì xǐhuān de jìjié', meaning: 'Mùa thu là mùa tôi thích nhất' },
{ hanzi: '她穿了一条红色的裙子', pinyin: 'Tā chuān le yī tiáo hóngsè de qúnzi', meaning: 'Cô ấy mặc một chiếc váy đỏ' },
{ hanzi: '我们吃完饭然后去看电影', pinyin: 'Wǒmen chī wán fàn ránhòu qù kàn diànyǐng', meaning: 'Chúng tôi ăn xong rồi đi xem phim' },
{ hanzi: '他对人很热情', pinyin: 'Tā duì rén hěn rèqíng', meaning: 'Anh ấy rất nhiệt tình với mọi người' },
{ hanzi: '我认为他是对的', pinyin: 'Wǒ rènwéi tā shì duì de', meaning: 'Tôi cho rằng anh ấy đúng' },
{ hanzi: '她学习很认真', pinyin: 'Tā xuéxí hěn rènzhēn', meaning: 'Cô ấy học rất chăm chỉ' },
{ hanzi: '这个问题很容易解决', pinyin: 'Zhège wèntí hěn róngyì jiějué', meaning: 'Vấn đề này rất dễ giải quyết' },
{ hanzi: '如果你有时间，请来我家', pinyin: 'Rúguǒ nǐ yǒu shíjiān, qǐng lái wǒ jiā', meaning: 'Nếu bạn có thời gian, xin hãy đến nhà tôi' },
{ hanzi: '下雨了，带上伞吧', pinyin: 'Xiàyǔ le, dài shàng sǎn ba', meaning: 'Trời mưa rồi, mang ô đi nhé' },
{ hanzi: '我喜欢上网看新闻', pinyin: 'Wǒ xǐhuān shàngwǎng kàn xīnwén', meaning: 'Tôi thích lên mạng đọc tin tức' },
{ hanzi: '她生气了，因为你迟到了', pinyin: 'Tā shēngqì le, yīnwèi nǐ chídào le', meaning: 'Cô ấy tức giận vì bạn đến muộn' },
{ hanzi: '我听不到他的声音', pinyin: 'Wǒ tīng bú dào tā de shēngyīn', meaning: 'Tôi không nghe thấy giọng của anh ấy' },
{ hanzi: '他使我非常生气', pinyin: 'Tā shǐ wǒ fēicháng shēngqì', meaning: 'Anh ất làm tôi cực kỳ tức giận' },
{ hanzi: '世界很大', pinyin: 'Shìjiè hěn dà', meaning: 'Thế giới rất rộng lớn' },
{ hanzi: '我觉得他越来越瘦了', pinyin: 'Wǒ juéde tā yuè lái yuè shòu le', meaning: 'Tôi cảm thấy anh ấy ngày càng gầy' },
{ hanzi: '这张椅子很舒服', pinyin: 'Zhè zhāng yǐzi hěn shūfu', meaning: 'Cái ghế này rất thoải mái' },
{ hanzi: '我的叔叔很高', pinyin: 'Wǒ de shūshu hěn gāo', meaning: 'Chú của tôi rất cao' },
{ hanzi: '树上的鸟在唱歌', pinyin: 'Shù shàng de niǎo zài chànggē', meaning: 'Con chim trên cây đang hót' },
{ hanzi: '他数学很好', pinyin: 'Tā shùxué hěn hǎo', meaning: 'Anh ấy giỏi toán' },
{ hanzi: '我每天刷两次牙', pinyin: 'Wǒ měitiān shuā liǎng cì yá ', meaning: 'Tôi đánh răng hai lần mỗi ngày' },
{ hanzi: '我买了一双鞋', pinyin: 'Wǒ mǎi le yī shuāng xié', meaning: 'Tôi đã mua một đôi giày' },
{ hanzi: '他的游泳水平很高', pinyin: 'Tā de yóuyǒng shuǐpíng hěn gāo', meaning: 'Trình độ bơi của anh ấy rất cao' },
{ hanzi: '他是我们的司机', pinyin: 'Tā shì wǒmen de sījī', meaning: 'Anh ấy là tài xế của chúng tôi' },
{ hanzi: '虽然他很忙，但他还是来了', pinyin: 'Suīrán tā hěn máng, dàn tā háishì lái le', meaning: 'Mặc dù anh ấy rất bận, nhưng anh ấy vẫn đến' },
{ hanzi: '太阳出来了', pinyin: 'Tàiyáng chū lái le', meaning: 'Mặt trời đã mọc' },
{ hanzi: '我不喜欢吃糖', pinyin: 'Wǒ bù xǐhuān chī táng', meaning: 'Tôi không thích ăn kẹo' },
{ hanzi: '他特别喜欢跑步', pinyin: 'Tā tèbié xǐhuān pǎobù', meaning: 'Anh ấy đặc biệt thích chạy bộ' },
{ hanzi: '我的头很疼', pinyin: 'Wǒ de tóu hěn téng', meaning: 'Đầu tôi rất đau' },
{ hanzi: '我们要提高汉语水平', pinyin: 'Wǒmen yào tígāo hànyǔ shuǐpíng', meaning: 'Chúng ta cần nâng cao trình độ tiếng Trung' },
{ hanzi: '我喜欢体育运动', pinyin: 'Wǒ xǐhuān tǐyù yùndòng', meaning: 'Tôi thích các hoạt động thể thao' },
{ hanzi: '这个蛋糕很甜', pinyin: 'Zhège dàngāo hěn tián', meaning: 'Cái bánh này rất ngọt' },
{ hanzi: '他买了一条裤子', pinyin: 'Tā mǎi le yī tiáo kùzi', meaning: 'Anh ấy đã mua một chiếc quần' },
{ hanzi: '他是我的同事', pinyin: 'Tā shì wǒ de tóngshì', meaning: 'Anh ấy là đồng nghiệp của tôi' },
{ hanzi: '我同意你的看法', pinyin: 'Wǒ tóngyì nǐ de kànfǎ', meaning: 'Tôi đồng ý với quan điểm của bạn' },
{ hanzi: '她的头发很长', pinyin: 'Tā de tóufa hěn cháng', meaning: 'Tóc của cô ấy rất dài' },
{ hanzi: '他突然离开了', pinyin: 'Tā tūrán líkāi le', meaning: 'Anh ấy đột nhiên rời đi' },
{ hanzi: '我们去图书馆看书吧', pinyin: 'Wǒmen qù túshūguǎn kànshū ba', meaning: 'Chúng ta đến thư viện đọc sách nhé' },
{ hanzi: '他的腿很长', pinyin: 'Tā de tuǐ hěn cháng', meaning: 'Chân của anh ấy rất dài' },
{ hanzi: '我完成了作业', pinyin: 'Wǒ wánchéng le zuòyè', meaning: 'Tôi đã hoàn thành bài tập' },
{ hanzi: '他吃了三碗饭', pinyin: 'Tā chī le sān wǎn fàn', meaning: 'Anh ấy đã ăn ba bát cơm' },
{ hanzi: '一万个人参加了比赛', pinyin: 'Yī wàn gè rén cānjiā le bǐsài', meaning: 'Mười nghìn người đã tham gia cuộc thi' },
{ hanzi: '请不要忘记带书', pinyin: 'Qǐng bùyào wàngjì dài shū', meaning: 'Vui lòng đừng quên mang sách' },
{ hanzi: '请坐在这位先生旁边', pinyin: 'Qǐng zuò zài zhè wèi xiānshēng pángbiān', meaning: 'Xin ngồi bên cạnh ông này' },
{ hanzi: '我为你感到骄傲', pinyin: 'Wǒ wèi nǐ gǎndào jiāo\'ào', meaning: 'Tôi tự hào về bạn' },
{ hanzi: '我来中国是为了学习汉语', pinyin: 'Wǒ lái Zhōngguó shì wèile xuéxí hànyǔ ', meaning: 'Tôi đến Trung Quốc để học tiếng Trung' },
{ hanzi: '他对中国文化很感兴趣', pinyin: 'Tā duì Zhōngguó wénhuà hěn gǎn xìngqù', meaning: 'Anh ấy rất quan tâm đến văn hóa Trung Quốc' },
{ hanzi: '我住在西边', pinyin: 'Wǒ zhù zài xībiān', meaning: 'Tôi sống ở phía tây' },
{ hanzi: '他习惯早起', pinyin: 'Tā xíguàn zǎoqǐ', meaning: 'Anh ấy quen dậy sớm' },
{ hanzi: '洗手间在那边', pinyin: 'Xǐshǒujiān zài nà biān', meaning: 'Nhà vệ sinh ở đằng kia' },
{ hanzi: '我每天早上都洗澡', pinyin: 'Wǒ měitiān zǎoshang dōu xǐzǎo', meaning: 'Tôi đều tắm vào mỗi buổi sáng' },
{ hanzi: '我喜欢这个颜色', pinyin: 'Wǒ xǐhuān zhège yánsè', meaning: 'Tôi thích màu này' },
{ hanzi: '现在是八点', pinyin: 'Xiànzài shì bā diǎn', meaning: 'Bây giờ là tám giờ' },
{ hanzi: '香蕉是黄色的', pinyin: 'Xiāngjiāo shì huángsè de', meaning: 'Chuối có màu vàng' },
{ hanzi: '我们的看法相同', pinyin: 'Wǒmen de kànfǎ xiāngtóng', meaning: 'Quan điểm của chúng tôi giống nhau' },
{ hanzi: '我相信他的话', pinyin: 'Wǒ xiāngxìn tā de huà', meaning: 'Tôi tin lời anh ấy' },
{ hanzi: '他像他爸爸一样高', pinyin: 'Tā xiàng tā bàba yīyàng gāo', meaning: 'Anh ấy cao giống như bố của mình' },
{ hanzi: '请小心地走路', pinyin: 'Qǐng xiǎoxīn de zǒulù', meaning: 'Vui lòng đi bộ cẩn thận' },
{ hanzi: '校长在办公室工作', pinyin: 'Xiàozhǎng zài bàngōngshì gōngzuò', meaning: 'Hiệu trưởng làm việc trong văn phòng' },
{ hanzi: '我买了一双新鞋', pinyin: 'Wǒ mǎi le yī shuāng xīn xié', meaning: 'Tôi đã mua một đôi giày mới' },
{ hanzi: '我每天都看新闻', pinyin: 'Wǒ měitiān dōu kàn xīnwén', meaning: 'Tôi xem tin tức mỗi ngày' },
{ hanzi: '这些水果很新鲜', pinyin: 'Zhèxiē shuǐguǒ hěn xīnxiān', meaning: 'Những loại trái cây này rất tươi' },
{ hanzi: '我给你写了一封信', pinyin: 'Wǒ gěi nǐ xiě le yī fēng xìn', meaning: 'Tôi đã viết cho bạn một bức thư' },
{ hanzi: '我的行李箱很重', pinyin: 'Wǒ de xínglǐxiāng hěn zhòng', meaning: 'Vali của tôi rất nặng' },
{ hanzi: '我对中国文化有兴趣', pinyin: 'Wǒ duì Zhōngguó wénhuà yǒu xìngqù', meaning: 'Tôi có hứng thú với văn hóa Trung Quốc' },
{ hanzi: '熊猫是中国的国宝', pinyin: 'Xióngmāo shì Zhōngguó de guóbǎo', meaning: 'Gấu trúc là báu vật quốc gia của Trung Quốc' },
{ hanzi: '我需要一杯水', pinyin: 'Wǒ xūyào yī bēi shuǐ', meaning: 'Tôi cần một cốc nước' },
{ hanzi: '你可以选择一个礼物', pinyin: 'Nǐ kěyǐ xuǎnzé yī gè lǐwù', meaning: 'Bạn có thể chọn một món quà' },
{ hanzi: '他戴着一副眼镜', pinyin: 'Tā dài zhe yī fù yǎnjìng', meaning: 'Anh ấy đang đeo một chiếc kính' },
{ hanzi: '老师对学生有很高的要求', pinyin: 'Lǎoshī duì xuéshēng yǒu hěn gāo de yāoqiú', meaning: 'Giáo viên có yêu cầu rất cao đối với học sinh' },
{ hanzi: '我爷爷很喜欢看书', pinyin: 'Wǒ yéye hěn xǐhuān kàn shū', meaning: 'Ông của tôi rất thích đọc sách' },
{ hanzi: '我一定会努力学习', pinyin: 'Wǒ yídìng huì nǔlì xuéxí', meaning: 'Tôi chắc chắn sẽ học chăm chỉ' },
{ hanzi: '我们一共有五个人', pinyin: 'Wǒmen yígòng yǒu wǔ gè rén', meaning: 'Chúng tôi có tổng cộng năm người' },
{ hanzi: '请等我一会儿', pinyin: 'Qǐng děng wǒ yíhuìr', meaning: 'Xin hãy đợi tôi một lát' },
{ hanzi: '他们和我们一样高', pinyin: 'Tāmen hé wǒmen yīyàng gāo', meaning: 'Họ cao bằng chúng tôi' },
{ hanzi: '我以后再来', pinyin: 'Wǒ yǐhòu zài lái', meaning: 'Tôi sẽ đến sau' },
{ hanzi: '我以前住在北京', pinyin: 'Wǒ yǐqián zhù zài Běijīng', meaning: 'Tôi đã từng sống ở Bắc Kinh' },
{ hanzi: '我以为你不来了', pinyin: 'Wǒ yǐwéi nǐ bù lái le', meaning: 'Tôi tưởng rằng bạn không đến' },
{ hanzi: '这个饭馆很一般', pinyin: 'Zhège fànguǎn hěn yībān', meaning: 'Nhà hàng này rất bình thường' },
{ hanzi: '他一边吃饭一边看电视', pinyin: 'Tā yìbiān chīfàn yìbiān kàn diànshì', meaning: 'Anh ấy vừa ăn vừa xem TV' },
{ hanzi: '他一直在学习', pinyin: 'Tā yìzhí zài xuéxí', meaning: 'Anh ấy luôn luôn học tập' },
{ hanzi: '我喜欢听音乐', pinyin: 'Wǒ xǐhuān tīng yīnyuè', meaning: 'Tôi thích nghe nhạc' },
{ hanzi: '我去银行取钱', pinyin: 'Wǒ qù yínháng qǔ qián', meaning: 'Tôi đến ngân hàng rút tiền' },
{ hanzi: '你应该多休息', pinyin: 'Nǐ yīnggāi duō xiūxí', meaning: 'Bạn nên nghỉ ngơi nhiều hơn' },
{ hanzi: '这个电影对我影响很大', pinyin: 'Zhège diànyǐng duì wǒ yǐngxiǎng hěn dà', meaning: 'Bộ phim này có ảnh hưởng lớn đối với tôi' },
{ hanzi: '请不要用手机', pinyin: 'Qǐng bùyào yòng shǒujī', meaning: 'Vui lòng không sử dụng điện thoại' },
{ hanzi: '我喜欢玩游戏', pinyin: 'Wǒ xǐhuān wán yóuxì', meaning: 'Tôi thích chơi trò chơi' },
{ hanzi: '他又来了', pinyin: 'Tā yòu lái le', meaning: 'Anh ấy lại đến' },
{ hanzi: '他是一个有名的歌手', pinyin: 'Tā shì yī gè yǒumíng de gēshǒu', meaning: 'Anh ấy là một ca sĩ nổi tiếng' },
{ hanzi: '我在路上遇到他了', pinyin: 'Wǒ zài lùshàng yùdào tā le', meaning: 'Tôi đã gặp anh ấy trên đường' },
{ hanzi: '今天晚上的月亮很圆', pinyin: 'Jīntiān wǎnshang de yuèliàng hěn yuán', meaning: 'Trăng tối nay rất tròn' },
{ hanzi: '天上的云很美', pinyin: 'Tiānshàng de yún hěn měi', meaning: 'Mây trên trời rất đẹp' },
{ hanzi: '请站在这儿', pinyin: 'Qǐng zhàn zài zhèr', meaning: 'Xin hãy đứng ở đây' },
{ hanzi: '他长得很高', pinyin: 'Tā zhǎng de hěn gāo', meaning: 'Anh ấy cao' },
{ hanzi: '他很着急', pinyin: 'Tā hěn zhāojí', meaning: 'Anh ấy rất lo lắng' },
{ hanzi: '我会照顾你', pinyin: 'Wǒ huì zhàogù nǐ', meaning: 'Tôi sẽ chăm sóc bạn' },
{ hanzi: '这张照片很好看', pinyin: 'Zhè zhāng zhàopiàn hěn hǎokàn', meaning: 'Bức ảnh này rất đẹp' },
{ hanzi: '我有一台新的照相机', pinyin: 'Wǒ yǒu yī tái xīn de zhàoxiàngjī', meaning: 'Tôi có một chiếc máy ảnh mới' },
{ hanzi: '我只吃了一点儿', pinyin: 'Wǒ zhǐ chī le yīdiǎnr', meaning: 'Tôi chỉ ăn một chút' },
{ hanzi: '他站在房间的中间', pinyin: 'Tā zhàn zài fángjiān de zhōngjiān', meaning: 'Anh ấy đứng ở giữa phòng' },
{ hanzi: '我终于完成了作业', pinyin: 'Wǒ zhōngyú wánchéng le zuòyè', meaning: 'Cuối cùng tôi đã hoàn thành bài tập' },
{ hanzi: '他喜欢这种花', pinyin: 'Tā xǐhuān zhè zhǒng huā', meaning: 'Anh ấy thích loại hoa này' },
{ hanzi: '这件事很重要', pinyin: 'Zhè jiàn shì hěn zhòngyào', meaning: 'Việc này rất quan trọng' },
{ hanzi: '主要问题是时间不够', pinyin: 'Zhǔyào wèntí shì shíjiān bù gòu', meaning: 'Vấn đề chính là không đủ thời gian' },
{ hanzi: '周末我去公园玩', pinyin: 'Zhōumò wǒ qù gōngyuán wán', meaning: 'Cuối tuần tôi đi công viên chơi' },
{ hanzi: '祝你生日快乐', pinyin: 'Zhù nǐ shēngrì kuàilè', meaning: 'Chúc bạn sinh nhật vui vẻ' },
{ hanzi: '请注意安全', pinyin: 'Qǐng zhùyì ānquán', meaning: 'Vui lòng chú ý an toàn' },
{ hanzi: '我需要一本字典', pinyin: 'Wǒ xūyào yī běn zìdiǎn', meaning: 'Tôi cần một quyển từ điển' },
{ hanzi: '这是我自己的问题', pinyin: 'Zhè shì wǒ zìjǐ de wèntí', meaning: 'Đây là vấn đề của chính tôi' },
{ hanzi: '他总是很忙', pinyin: 'Tā zǒngshì hěn máng', meaning: 'Anh ấy luôn luôn bận rộn' },
{ hanzi: '最近我很忙', pinyin: 'Zuìjìn wǒ hěn máng', meaning: 'Gần đây tôi rất bận' },
{ hanzi: '我已经做完作业了', pinyin: 'Wǒ yǐjīng zuò wán zuòyè le', meaning: 'Tôi đã làm xong bài tập' },
{ hanzi: '这个词的作用是什么？', pinyin: 'Zhège cí de zuòyòng shì shénme?', meaning: 'Tác dụng của từ này là gì?' },

];