vocab = [
{ hanzi: '我爱你', pinyin: 'Wǒ ài nǐ', meaning: 'Tôi yêu bạn' },
{ hanzi: '他有八个苹果', pinyin: 'Tā yǒu bā ge píngguǒ', meaning: 'Anh ấy có tám quả táo' },
{ hanzi: '我的爸爸很高', pinyin: 'Wǒ de bàba hěn gāo', meaning: 'Bố của tôi rất cao' },
{ hanzi: '这是我的杯子', pinyin: 'Zhè shì wǒ de bēizi', meaning: 'Đây là cốc của tôi' },
{ hanzi: '北京很大', pinyin: 'Běijīng hěn dà', meaning: 'Bắc Kinh thì lớn' },
{ hanzi: '这本书很有趣', pinyin: 'Zhè běn shū hěn yǒuqù', meaning: 'Quyển sách này rất thú vị' },
{ hanzi: '不客气', pinyin: 'bú kèqì', meaning: 'Không có gì' },
{ hanzi: '他不喜欢吃鱼', pinyin: 'Tā bù xǐhuān chī yú', meaning: 'Anh ấy không thích ăn cá' },
{ hanzi: '我喜欢吃菜', pinyin: 'Wǒ xǐhuān chī cài', meaning: 'Tôi thích ăn rau' },
{ hanzi: '我喝茶', pinyin: 'Wǒ hē chá', meaning: 'Tôi uống trà' },
{ hanzi: '我吃苹果', pinyin: 'Wǒ chī píngguǒ', meaning: 'Tôi ăn táo' },
{ hanzi: '我坐出租车', pinyin: 'Wǒ zuò chūzūchē', meaning: 'Tôi đi taxi' },
{ hanzi: '她给我打电话', pinyin: 'Tā gěi wǒ dǎ diànhuà', meaning: 'Cô ấy gọi điện cho tôi' },
{ hanzi: '这件衣服很大', pinyin: 'Zhè jiàn yīfú hěn dà', meaning: 'Cái áo này rất to' },
{ hanzi: '这是我的书', pinyin: 'Zhè shì wǒ de shū', meaning: 'Đây là sách của tôi' },
{ hanzi: '现在是三点', pinyin: 'Xiànzài shì sān diǎn?', meaning: 'Bây giờ là mấy giờ?' },
{ hanzi: '我用电脑', pinyin: 'Wǒ yòng diànnǎo', meaning: 'Tôi dùng máy tính' },
{ hanzi: '电视很大', pinyin: 'Diànshì hěn dà', meaning: 'Tivi thì lớn' },
{ hanzi: '我喜欢看电影', pinyin: 'Wǒ xǐhuān kàn diànyǐng', meaning: 'Tôi thích xem phim' },
{ hanzi: '这是什么东西？', pinyin: 'Zhè shì shénme dōngxī?', meaning: 'Đây là cái gì?' },
{ hanzi: '我们都去学校', pinyin: 'Wǒmen dōu qù xuéxiào', meaning: 'Chúng tôi đều đi đến trường' },
{ hanzi: '她读书很快', pinyin: 'Tā dúshū hěn kuài', meaning: 'Cô ấy đọc sách rất nhanh' },
{ hanzi: '对不起，我迟到了', pinyin: 'Duìbuqǐ, wǒ chídào le', meaning: 'Xin lỗi, tôi đến muộn' },
{ hanzi: '我有很多书', pinyin: 'Wǒ yǒu hěn duō shū', meaning: 'Tôi có nhiều sách' },
{ hanzi: '这本书多少钱？', pinyin: 'Zhè běn shū duōshǎo qián?', meaning: 'Quyển sách này bao nhiêu tiền?' },
{ hanzi: '我的儿子很聪明', pinyin: 'Wǒ de érzi hěn cōngmíng', meaning: 'Con trai của tôi rất thông minh' },
{ hanzi: '我喜欢“二”数字', pinyin: 'Wǒ xǐhuān "èr" shùzi', meaning: 'Tôi thích số 2' },
{ hanzi: '我们去饭馆吃饭', pinyin: 'Wǒmen qù fànguǎn chīfàn', meaning: 'Chúng tôi đi nhà hàng ăn cơm' },
{ hanzi: '飞机很快', pinyin: 'Fēijī hěn kuài', meaning: 'Máy bay thì nhanh' },
{ hanzi: '他等了五分钟', pinyin: 'Tā děngle wǔ fēnzhōng', meaning: 'Anh ấy đợi năm phút' },
{ hanzi: '我很高兴', pinyin: 'Wǒ hěn gāoxìng', meaning: 'Tôi rất vui' },
{ hanzi: '我有一个钱包', pinyin: 'Wǒ yǒu yī ge qiánbāo', meaning: 'Tôi có một cái ví tiền' },
{ hanzi: '我的工作很忙', pinyin: 'Wǒ de gōngzuò hěn máng', meaning: 'Công việc của tôi rất bận' },
{ hanzi: '这只狗很可爱', pinyin: 'Zhè zhī gǒu hěn kě\'ài', meaning: 'Con chó này rất dễ thương' },
{ hanzi: '我在学汉语', pinyin: 'Wǒ zài xué Hànyǔ', meaning: 'Tôi đang học tiếng Trung' },
{ hanzi: '他很好', pinyin: 'Tā hěn hǎo', meaning: 'Anh ấy rất tốt' },
{ hanzi: '我喝水', pinyin: 'Wǒ hē shuǐ', meaning: 'Tôi uống nước' },
{ hanzi: '我和你一起去', pinyin: 'Wǒ hé nǐ yīqǐ qù', meaning: 'Tôi và bạn cùng đi' },
{ hanzi: '这个苹果很甜', pinyin: 'Zhège píngguǒ hěn tián', meaning: 'Cái táo này rất ngọt' },
{ hanzi: '我家在后面', pinyin: 'Wǒ jiā zài hòumiàn', meaning: 'Nhà tôi ở phía sau' },
{ hanzi: '我回家了', pinyin: 'Wǒ huí jiā le', meaning: 'Tôi đã về nhà' },
{ hanzi: '我会说汉语', pinyin: 'Wǒ huì shuō Hànyǔ', meaning: 'Tôi biết nói tiếng Trung' },
{ hanzi: '火车站在前面', pinyin: 'Huǒchēzhàn zài qiánmiàn', meaning: 'Ga tàu ở phía trước' },
{ hanzi: '你有几个苹果？', pinyin: 'Nǐ yǒu jǐ ge píngguǒ?', meaning: 'Bạn có mấy quả táo?' },
{ hanzi: '我家有四口人', pinyin: 'Wǒ jiā yǒu sì kǒu rén', meaning: 'Nhà tôi có bốn người' },
{ hanzi: '她叫李娜', pinyin: 'Tā jiào Lǐ Nà', meaning: 'Cô ấy tên là Lý Na' },
{ hanzi: '今天是星期一', pinyin: 'Jīntiān shì xīngqī yī', meaning: 'Hôm nay là thứ Hai' },
{ hanzi: '我有九本书', pinyin: 'Wǒ yǒu jiǔ běn shū', meaning: 'Tôi có chín quyển sách' },
{ hanzi: '我们开车去', pinyin: 'Wǒmen kāichē qù', meaning: 'Chúng tôi đi bằng ô tô' },
{ hanzi: '我喜欢看电影', pinyin: 'Wǒ xǐhuān kàn diànyǐng', meaning: 'Tôi thích xem phim' },
{ hanzi: '我看见你了', pinyin: 'Wǒ kànjiàn nǐ le', meaning: 'Tôi đã thấy bạn' },
{ hanzi: '这个苹果两块钱', pinyin: 'Zhège píngguǒ liǎng kuài qián', meaning: 'Cái táo này hai tệ' },
{ hanzi: '明天我来', pinyin: 'Míngtiān wǒ lái', meaning: 'Ngày mai tôi đến' },
{ hanzi: '我的老师很友好', pinyin: 'Wǒ de lǎoshī hěn yǒuhǎo', meaning: 'Giáo viên của tôi rất thân thiện' },
{ hanzi: '她去了学校', pinyin: 'Tā qùle xuéxiào', meaning: 'Cô ấy đã đi đến trường' },
{ hanzi: '外面很冷', pinyin: 'Wàimiàn hěn lěng', meaning: 'Bên ngoài rất lạnh' },
{ hanzi: '我的书在里面', pinyin: 'Wǒ de shū zài lǐmiàn', meaning: 'Sách của tôi ở bên trong' },
{ hanzi: '今天零度', pinyin: 'Jīntiān líng dù', meaning: 'Hôm nay không độ' },
{ hanzi: '我有六个苹果', pinyin: 'Wǒ yǒu liù ge píngguǒ', meaning: 'Tôi có sáu quả táo' },
{ hanzi: '我的妈妈很漂亮', pinyin: 'Wǒ de māmā hěn piàoliang', meaning: 'Mẹ của tôi rất xinh đẹp' },
{ hanzi: '你好吗？', pinyin: 'Nǐ hǎo ma?', meaning: 'Bạn khỏe không?' },
{ hanzi: '我买了水果', pinyin: 'Wǒ mǎile shuǐguǒ', meaning: 'Tôi đã mua trái cây' },
{ hanzi: '这只猫很可爱', pinyin: 'Zhè zhī māo hěn kě\'ài', meaning: 'Con mèo này rất dễ thương' },
{ hanzi: '我没看见他', pinyin: 'Wǒ méi kànjiàn tā', meaning: 'Tôi không nhìn thấy anh ấy' },
{ hanzi: '下雨了，没关系，我们有伞', pinyin: 'Xiàyǔ le, méi guānxì, wǒmen yǒu sǎn', meaning: 'Trời mưa rồi, không sao đâu, chúng ta có ô' },
{ hanzi: '我们吃米饭', pinyin: 'Wǒmen chī mǐfàn', meaning: 'Chúng tôi ăn cơm' },
{ hanzi: '明天见', pinyin: 'Míngtiān jiàn', meaning: 'Ngày mai gặp' },
{ hanzi: '你叫什么名字？', pinyin: 'Nǐ jiào shénme míngzì?', meaning: 'Bạn tên là gì?' },
{ hanzi: '你要去哪儿？', pinyin: 'Nǐ yào qù nǎr？', meaning: 'Bạn muốn đi đâu?' },
{ hanzi: '那个书包很漂亮', pinyin: 'Nàge shūbāo hěn piàoliang', meaning: 'Cái cặp sách đó rất đẹp' },
{ hanzi: '你呢？', pinyin: 'Nǐ ne?', meaning: 'Còn bạn thì sao?' },
{ hanzi: '他能说三种语言', pinyin: 'Tā néng shuō sān zhǒng yǔyán', meaning: 'Anh ấy có thể nói ba ngôn ngữ' },
{ hanzi: '你叫什么名字？', pinyin: 'Nǐ jiào shénme míngzi?', meaning: 'Bạn tên là gì?' },
{ hanzi: '我结婚三年了', pinyin: 'Wǒ jiéhūn sān nián le', meaning: 'Tôi kết hôn 3 năm rồi' },
{ hanzi: '她是我的女儿', pinyin: 'Tā shì wǒ de nǚ\'ér', meaning: 'Con bé là con gái của tôi' },
{ hanzi: '她的朋友很聪明', pinyin: 'Tā de péngyou hěn cōngmíng', meaning: 'Bạn của cô ấy rất thông minh' },
{ hanzi: '她很漂亮', pinyin: 'Tā hěn piàoliang', meaning: 'Cô ấy rất xinh đẹp' },
{ hanzi: '这个苹果很好吃', pinyin: 'Zhège píngguǒ hěn hǎochī', meaning: 'Táo này rất ngon' },
{ hanzi: '我有七个朋友', pinyin: 'Wǒ yǒu qī ge péngyou', meaning: 'Tôi có bảy người bạn' },
{ hanzi: '这本书多少钱？', pinyin: 'Zhè běn shū duōshǎo qián?', meaning: 'Cuốn sách này giá bao nhiêu?' },
{ hanzi: '火车站在前面', pinyin: 'Huǒchēzhàn zài qiánmiàn', meaning: 'Ga tàu ở phía trước' },
{ hanzi: '请给我菜单', pinyin: 'Qǐng gěi wǒ càidān', meaning: 'Xin vui lòng đưa cho tôi thực đơn' },
{ hanzi: '我们要去商店', pinyin: 'Wǒmen yào qù shāngdiàn', meaning: 'Chúng tôi phải đến cửa hàng' },
{ hanzi: '天气很热', pinyin: 'Tiānqì hěn rè', meaning: 'Thời tiết rất nóng' },
{ hanzi: '这个人很友好', pinyin: 'Zhè ge rén hěn yǒuhǎo', meaning: 'Người này rất thân thiện' },
{ hanzi: '我认识他', pinyin: 'Wǒ rènshi tā', meaning: 'Tôi quen anh ấy' },
{ hanzi: '今天是几月几日？', pinyin: 'Jīntiān shì jǐ yuè jǐ rì?', meaning: 'Hôm nay là ngày mấy tháng mấy?' },
{ hanzi: '我有三本书', pinyin: 'Wǒ yǒu sān běn shū', meaning: 'Tôi có ba cuốn sách' },
{ hanzi: '这个商店很大', pinyin: 'Zhège shāngdiàn hěn dà', meaning: 'Cửa hàng này rất lớn' },
{ hanzi: '他在上楼', pinyin: 'Tā zài shàng lóu', meaning: 'Anh ấy đang lên tầng' },
{ hanzi: '上午我们去学校', pinyin: 'Shàngwǔ wǒmen qù xuéxiào', meaning: 'Vào buổi sáng chúng tôi đi học' },
{ hanzi: '我们还少一个人', pinyin: 'Wǒmen hái shǎo yīgè rén', meaning: 'Chúng tôi vẫn thiếu một người' },
{ hanzi: '谁是你的老师？', pinyin: 'Shéi shì nǐ de lǎoshī?', meaning: 'Ai là giáo viên của bạn?' },
{ hanzi: '你想吃什么？', pinyin: 'Nǐ xiǎng chī shénme?', meaning: 'Bạn muốn ăn gì?' },
{ hanzi: '我有十块钱', pinyin: 'Wǒ yǒu shí kuài qián', meaning: 'Tôi có mười tệ' },
{ hanzi: '你什么时候来？', pinyin: 'Nǐ shénme shíhòu lái?', meaning: 'Bạn đến lúc nào ?' },
{ hanzi: '这是一本好书', pinyin: 'Zhè shì yī běn hǎo shū', meaning: 'Đây là một cuốn sách hay' },
{ hanzi: '这本书很有意思', pinyin: 'Zhè běn shū hěn yǒuyìsi', meaning: 'Cuốn sách này rất thú vị' },
{ hanzi: '我喝水', pinyin: 'Wǒ hē shuǐ', meaning: 'Tôi uống nước' },
{ hanzi: '她喜欢吃水果', pinyin: 'Tā xǐhuān chī shuǐguǒ', meaning: 'Cô ấy thích ăn trái cây' },
{ hanzi: '他每天晚上十点睡觉', pinyin: 'Tā měitiān wǎnshàng shí diǎn shuìjiào', meaning: 'Anh ấy đi ngủ lúc mười giờ tối mỗi ngày' },
{ hanzi: '你怎么不说话？', pinyin: 'Nǐ zěnme bù shuōhuà?', meaning: 'Sao bạn không nói chuyện thế?' },
{ hanzi: '他们四个人去旅行', pinyin: 'Tāmen sì gè rén qù lǚxíng', meaning: 'Bốn người họ đi du lịch' },
{ hanzi: '我今年二十五岁', pinyin: 'Wǒ jīnnián èrshíwǔ suì', meaning: 'Tôi năm nay hai mươi lăm tuổi' },
{ hanzi: '他是我的朋友', pinyin: 'Tā shì wǒ de péngyou', meaning: 'Anh ấy là bạn của tôi' },
{ hanzi: '她在家里', pinyin: 'Tā zài jiālǐ', meaning: 'Cô ấy ở nhà' },
{ hanzi: '今天太热了', pinyin: 'Jīntiān tài rè le', meaning: 'Hôm nay nóng quá' },
{ hanzi: '今天天气很好', pinyin: 'Jīntiān tiānqì hěn hǎo', meaning: 'Thời tiết hôm nay rất tốt' },
{ hanzi: '我喜欢听音乐', pinyin: 'Wǒ xǐhuān tīng yīnyuè', meaning: 'Tôi thích nghe nhạc' },
{ hanzi: '我们是同学', pinyin: 'Wǒmen shì tóngxué', meaning: 'Chúng tôi là bạn học' },
{ hanzi: '喂，你好吗？', pinyin: 'Wèi, nǐ hǎo ma?', meaning: 'Alo, bạn khỏe không?' },
{ hanzi: '我想喝水', pinyin: 'Wǒ xiǎng hē shuǐ', meaning: 'Tôi muốn uống nước' },
{ hanzi: '我们一起去吧', pinyin: 'Wǒmen yīqǐ qù ba', meaning: 'Chúng ta cùng đi nhé' },
{ hanzi: '他有五本书', pinyin: 'Tā yǒu wǔ běn shū', meaning: 'Anh ấy có năm cuốn sách' },
{ hanzi: '我喜欢喝咖啡', pinyin: 'Wǒ xǐhuān hē kāfēi', meaning: 'Tôi thích uống cà phê' },
{ hanzi: '我在下楼', pinyin: 'Wǒ zài xià lóu', meaning: 'Tôi đang xuống lầu' },
{ hanzi: '下午我们去逛街', pinyin: 'Xiàwǔ wǒmen qù guàngjiē', meaning: 'uổi chiều, chúng tôi đi dạo phố' },
{ hanzi: '外面下雨了，记得带伞', pinyin: 'Wàimiàn xià yǔ le, jìdé dài sǎn', meaning: 'Ngoài trời mưa, nhớ mang theo ô' },
{ hanzi: '先生，这边请', pinyin: 'Xiānshēng, zhè biān qǐng', meaning: 'Mời anh qua bên này' },
{ hanzi: '我现在很累', pinyin: 'Wǒ xiànzài hěn lèi', meaning: 'Tôi hiện tại rất mệt' },
{ hanzi: '我想去看电影', pinyin: 'Wǒ xiǎng qù kàn diànyǐng', meaning: 'Tôi muốn đi xem phim' },
{ hanzi: '这是一只小狗', pinyin: 'Zhè shì yī zhī xiǎo gǒu', meaning: 'Đây là một chú chó con' },
{ hanzi: '小姐，请问这里有洗手间吗？', pinyin: 'Xiǎojiě, qǐngwèn zhèlǐ yǒu xǐshǒujiān ma?', meaning: 'Cô ơi, xin hỏi ở đây có nhà vệ sinh không?' },
{ hanzi: '我们买了一些水果', pinyin: 'Wǒmen mǎile yīxiē shuǐguǒ', meaning: 'Chúng tôi đã mua một ít trái cây' },
{ hanzi: '我正在写信', pinyin: 'Wǒ zhèngzài xiě xìn', meaning: 'Tôi đang viết thư' },
{ hanzi: '谢谢你的帮助', pinyin: 'Xièxiè nǐ de bāngzhù', meaning: 'Cảm ơn sự giúp đỡ của bạn' },
{ hanzi: '一个星期就好', pinyin: 'Yí gè xīngqī jiǔ hǎo', meaning: 'Một tuần là được' },
{ hanzi: '他是一个好学生', pinyin: 'Tā shì yīgè hǎo xuéshēng', meaning: 'Anh ấy là một học sinh giỏi' },
{ hanzi: '学习中文很有趣', pinyin: 'Xuéxí zhōngwén hěn yǒuqù', meaning: 'Học tiếng Trung rất thú vị' },
{ hanzi: '我在学校学习中文', pinyin: 'Wǒ zài xuéxiào xuéxí zhōngwén', meaning: 'Tôi học tiếng Trung ở trường' },
{ hanzi: '一个人在公园散步', pinyin: 'Yī gè rén zài gōngyuán sànbù', meaning: 'Một người đang đi dạo trong công viên' },
{ hanzi: '这件衣服很漂亮', pinyin: 'Zhè jiàn yīfu hěn piàoliang', meaning: 'Bộ quần áo này rất đẹp' },
{ hanzi: '他是一位医生', pinyin: 'Tā shì yī wèi yīshēng', meaning: 'Anh ấy là một bác sĩ' },
{ hanzi: '我们去医院看病', pinyin: 'Wǒmen qù yīyuàn kàn bìng', meaning: 'Chúng tôi đến bệnh viện để khám bệnh' },
{ hanzi: '请坐在椅子上', pinyin: 'Qǐng zuò zài yǐzi shàng', meaning: 'Xin ngồi lên ghế' },
{ hanzi: '这个月我很忙', pinyin: 'Zhège yuè wǒ hěn máng', meaning: 'Tháng này tôi rất bận' },
{ hanzi: '他在学校学习', pinyin: 'Tā zài xuéxiào xuéxí', meaning: 'Anh ấy học ở trường' },
{ hanzi: '我们明天再见', pinyin: 'Wǒmen míngtiān zàijiàn', meaning: 'Chúng ta gặp lại vào ngày mai' },
{ hanzi: '你怎么了？', pinyin: 'Nǐ zěnme le?', meaning: 'Bạn sao vậy?' },
{ hanzi: '你的工作怎么样？', pinyin: 'Nǐ de gōngzuò zěnmeyàng?', meaning: 'Công việc của bạn thế nào?' },
{ hanzi: '这件事怎么样？', pinyin: 'Zhè jiàn shì zěnme yàng?', meaning: 'Việc này như thế nào?' },
{ hanzi: '中国有很多美丽的风景', pinyin: 'Zhōngguó yǒu hěn duō měilì de fēngjǐng', meaning: 'Trung Quốc có nhiều cảnh đẹp' },
{ hanzi: '中午我们去吃饭吧', pinyin: 'Zhōngwǔ wǒmen qù chīfàn ba', meaning: 'Buổi trưa chúng ta đi ăn cơm nhé' },
{ hanzi: '我住在一个很安静的地方', pinyin: 'Wǒ zhù zài yīgè hěn ānjìng de dìfāng', meaning: 'Tôi sống ở một nơi rất yên tĩnh' },
{ hanzi: '桌子上放着一本书', pinyin: 'Zhuōzi shàng fàngzhe yī běn shū', meaning: 'Trên bàn có một cuốn sách' },
{ hanzi: '我们要学会写字', pinyin: 'Wǒmen yào xuéhuì xiě zì', meaning: 'Chúng ta phải học viết chữ' },
{ hanzi: '昨天我去看了一部电影', pinyin: 'Zuótiān wǒ qù kànle yī bù diànyǐng', meaning: 'Hôm qua tôi đã đi xem một bộ phim' },
{ hanzi: '我们在公园里坐了一会儿', pinyin: 'Wǒmen zài gōngyuán lǐ zuòle yīhuìr', meaning: 'Chúng tôi đã ngồi một lúc trong công viên' },
{ hanzi: '他正在做作业', pinyin: 'Tā zhèngzài zuò zuòyè', meaning: 'Anh ấy đang làm bài tập về nhà' },

];