vocab = [
{ hanzi: '吧', pinyin: 'ba', meaning: 'đi, nhé, nhỉ (đứng cuối câu)' },
{ hanzi: '白', pinyin: 'bái', meaning: 'trắng' },
{ hanzi: '百', pinyin: 'bǎi', meaning: 'trăm' },
{ hanzi: '帮助', pinyin: 'bāngzhù', meaning: 'giúp đỡ' },
{ hanzi: '报纸', pinyin: 'bàozhǐ', meaning: 'báo' },
{ hanzi: '比', pinyin: 'bǐ', meaning: 'so sánh' },
{ hanzi: '别', pinyin: 'bié', meaning: 'đừng, khác biệt' },
{ hanzi: '长', pinyin: 'cháng', meaning: 'dài' },
{ hanzi: '唱歌', pinyin: 'chànggē', meaning: 'hát' },
{ hanzi: '出', pinyin: 'chū', meaning: 'ra ngoài' },
{ hanzi: '穿', pinyin: 'chuān', meaning: 'mặc' },
{ hanzi: '船', pinyin: 'chuán', meaning: 'thuyền' },
{ hanzi: '次', pinyin: 'cì', meaning: 'lần' },
{ hanzi: '从', pinyin: 'cóng', meaning: 'từ, theo' },
{ hanzi: '错', pinyin: 'cuò', meaning: 'sai' },
{ hanzi: '打篮球', pinyin: 'dǎ lánqiú', meaning: 'chơi bóng rổ' },
{ hanzi: '大家', pinyin: 'dàjiā', meaning: 'mọi người' },
{ hanzi: '但是', pinyin: 'dànshì', meaning: 'nhưng' },
{ hanzi: '到', pinyin: 'dào', meaning: 'đến' },
{ hanzi: '得', pinyin: 'děi', meaning: 'phải, đạt được' },
{ hanzi: '等', pinyin: 'děng', meaning: 'đợi' },
{ hanzi: '弟弟', pinyin: 'dìdì', meaning: 'em trai' },
{ hanzi: '第一', pinyin: 'dì yī', meaning: 'đầu tiên' },
{ hanzi: '懂', pinyin: 'dǒng', meaning: 'hiểu' },
{ hanzi: '对', pinyin: 'duì', meaning: 'đúng, đối với' },
{ hanzi: '房间', pinyin: 'fángjiān', meaning: 'phòng' },
{ hanzi: '非常', pinyin: 'fēicháng', meaning: 'rất, cực kỳ' },
{ hanzi: '服务员', pinyin: 'fúwùyuán', meaning: 'nhân viên phục vụ' },
{ hanzi: '高', pinyin: 'gāo', meaning: 'cao' },
{ hanzi: '告诉', pinyin: 'gàosù', meaning: 'nói cho, thông báo' },
{ hanzi: '哥哥', pinyin: 'gēge', meaning: 'anh trai' },
{ hanzi: '给', pinyin: 'gěi', meaning: 'đưa cho, cho' },
{ hanzi: '公共汽车', pinyin: 'gōnggòng qìchē', meaning: 'xe buýt' },
{ hanzi: '公斤', pinyin: 'gōngjīn', meaning: 'kilogram (kg)' },
{ hanzi: '公司', pinyin: 'gōngsī', meaning: 'công ty' },
{ hanzi: '贵', pinyin: 'guì', meaning: 'đắt, quý' },
{ hanzi: '过', pinyin: 'guò', meaning: 'qua, đi qua' },
{ hanzi: '还', pinyin: 'hái', meaning: 'vẫn, còn' },
{ hanzi: '孩子', pinyin: 'háizi', meaning: 'trẻ con' },
{ hanzi: '好吃', pinyin: 'hǎochī', meaning: 'ngon' },
{ hanzi: '号', pinyin: 'hào', meaning: 'số (như số điện thoại, số nhà)' },
{ hanzi: '黑', pinyin: 'hēi', meaning: 'đen' },
{ hanzi: '红', pinyin: 'hóng', meaning: 'đỏ' },
{ hanzi: '欢迎', pinyin: 'huānyíng', meaning: 'hoan nghênh, chào mừng' },
{ hanzi: '回答', pinyin: 'huídá', meaning: 'trả lời' },
{ hanzi: '机场', pinyin: 'jīchǎng', meaning: 'sân bay' },
{ hanzi: '鸡蛋', pinyin: 'jīdàn', meaning: 'trứng gà' },
{ hanzi: '件', pinyin: 'jiàn', meaning: 'cái (dùng cho sự việc, quần áo)' },
{ hanzi: '教室', pinyin: 'jiàoshì', meaning: 'lớp học' },
{ hanzi: '姐姐', pinyin: 'jiějie', meaning: 'chị gái' },
{ hanzi: '介绍', pinyin: 'jièshào', meaning: 'giới thiệu' },
{ hanzi: '进', pinyin: 'jìn', meaning: 'vào' },
{ hanzi: '近', pinyin: 'jìn', meaning: 'gần' },
{ hanzi: '就', pinyin: 'jiù', meaning: 'thì, ngay' },
{ hanzi: '觉得', pinyin: 'juéde', meaning: 'cảm thấy' },
{ hanzi: '咖啡', pinyin: 'kāfēi', meaning: 'cà phê' },
{ hanzi: '开始', pinyin: 'kāishǐ', meaning: 'bắt đầu' },
{ hanzi: '考试', pinyin: 'kǎoshì', meaning: 'thi' },
{ hanzi: '可能', pinyin: 'kěnéng', meaning: 'có thể' },
{ hanzi: '可以', pinyin: 'kěyǐ', meaning: 'có thể' },
{ hanzi: '课', pinyin: 'kè', meaning: 'bài học' },
{ hanzi: '快', pinyin: 'kuài', meaning: 'nhanh' },
{ hanzi: '快乐', pinyin: 'kuàilè', meaning: 'vui vẻ' },
{ hanzi: '累', pinyin: 'lèi', meaning: 'mệt' },
{ hanzi: '离', pinyin: 'lí', meaning: 'cách (khoảng cách), rời' },
{ hanzi: '两', pinyin: 'liǎng', meaning: 'hai (khi đếm số lượng)' },
{ hanzi: '路', pinyin: 'lù', meaning: 'đường' },
{ hanzi: '旅游', pinyin: 'lǚyóu', meaning: 'du lịch' },
{ hanzi: '卖', pinyin: 'mài', meaning: 'bán' },
{ hanzi: '慢', pinyin: 'màn', meaning: 'chậm' },
{ hanzi: '忙', pinyin: 'máng', meaning: 'bận' },
{ hanzi: '每', pinyin: 'měi', meaning: 'mỗi' },
{ hanzi: '妹妹', pinyin: 'mèimei', meaning: 'em gái' },
{ hanzi: '门', pinyin: 'mén', meaning: 'cửa' },
{ hanzi: '男人', pinyin: 'nánrén', meaning: 'đàn ông' },
{ hanzi: '您', pinyin: 'nín', meaning: 'bạn (dùng lịch sự)' },
{ hanzi: '牛奶', pinyin: 'niúnǎi', meaning: 'sữa bò' },
{ hanzi: '女人', pinyin: 'nǚrén', meaning: 'phụ nữ' },
{ hanzi: '旁边', pinyin: 'pángbiān', meaning: 'bên cạnh' },
{ hanzi: '跑步', pinyin: 'pǎobù', meaning: 'chạy bộ' },
{ hanzi: '便宜', pinyin: 'piányí', meaning: 'rẻ' },
{ hanzi: '票', pinyin: 'piào', meaning: 'vé' },
{ hanzi: '妻子', pinyin: 'qīzi', meaning: 'vợ' },
{ hanzi: '起床', pinyin: 'qǐchuáng', meaning: 'dậy (rời khỏi giường)' },
{ hanzi: '千', pinyin: 'qiān', meaning: 'nghìn' },
{ hanzi: '晴', pinyin: 'qíng', meaning: 'nắng, quang đãng' },
{ hanzi: '去年', pinyin: 'qùnián', meaning: 'năm ngoái' },
{ hanzi: '让', pinyin: 'ràng', meaning: 'để, làm cho, nhường' },
{ hanzi: '上班', pinyin: 'shàngbān', meaning: 'đi làm' },
{ hanzi: '身体', pinyin: 'shēntǐ', meaning: 'cơ thể' },
{ hanzi: '生病', pinyin: 'shēngbìng', meaning: 'bị bệnh' },
{ hanzi: '生日', pinyin: 'shēngrì', meaning: 'sinh nhật' },
{ hanzi: '时间', pinyin: 'shíjiān', meaning: 'thời gian' },
{ hanzi: '事情', pinyin: 'shìqíng', meaning: 'việc' },
{ hanzi: '手表', pinyin: 'shǒubiǎo', meaning: 'đồng hồ' },
{ hanzi: '手机', pinyin: 'shǒujī', meaning: 'điện thoại di động' },
{ hanzi: '送', pinyin: 'sòng', meaning: 'tặng' },
{ hanzi: '所以', pinyin: 'suǒyǐ', meaning: 'vì vậy' },
{ hanzi: '它', pinyin: 'tā', meaning: 'nó (cho vật, động vật)' },
{ hanzi: '踢足球', pinyin: 'tī zúqiú', meaning: 'đá bóng' },
{ hanzi: '题', pinyin: 'tí', meaning: 'câu hỏi, đề bài' },
{ hanzi: '跳舞', pinyin: 'tiàowǔ', meaning: 'nhảy múa' },
{ hanzi: '外', pinyin: 'wài', meaning: 'ngoài' },
{ hanzi: '玩', pinyin: 'wán', meaning: 'chơi' },
{ hanzi: '完', pinyin: 'wán', meaning: 'xong, hoàn thành' },
{ hanzi: '晚上', pinyin: 'wǎnshàng', meaning: 'buổi tối' },
{ hanzi: '为什么', pinyin: 'wèishénme', meaning: 'tại sao' },
{ hanzi: '问', pinyin: 'wèn', meaning: 'hỏi' },
{ hanzi: '问题', pinyin: 'wèntí', meaning: 'vấn đề' },
{ hanzi: '西瓜', pinyin: 'xīguā', meaning: 'dưa hấu' },
{ hanzi: '希望', pinyin: 'xīwàng', meaning: 'hy vọng' },
{ hanzi: '洗', pinyin: 'xǐ', meaning: 'rửa' },
{ hanzi: '向', pinyin: 'xiàng', meaning: 'hướng về, đối với' },
{ hanzi: '小时', pinyin: 'xiǎoshí', meaning: 'tiếng đồng hồ' },
{ hanzi: '笑', pinyin: 'xiào', meaning: 'cười' },
{ hanzi: '新', pinyin: 'xīn', meaning: 'mới' },
{ hanzi: '姓', pinyin: 'xìng', meaning: 'họ' },
{ hanzi: '休息', pinyin: 'xiūxi', meaning: 'nghỉ ngơi' },
{ hanzi: '雪', pinyin: 'xuě', meaning: 'tuyết' },
{ hanzi: '颜色', pinyin: 'yánsè', meaning: 'màu sắc' },
{ hanzi: '眼睛', pinyin: 'yǎnjing', meaning: 'mắt' },
{ hanzi: '羊肉', pinyin: 'yángròu', meaning: 'thịt cừu' },
{ hanzi: '要', pinyin: 'yào', meaning: 'muốn, cần' },
{ hanzi: '药', pinyin: 'yào', meaning: 'thuốc' },
{ hanzi: '也', pinyin: 'yě', meaning: 'cũng' },
{ hanzi: '已经', pinyin: 'yǐjīng', meaning: 'đã' },
{ hanzi: '一起', pinyin: 'yìqǐ', meaning: 'cùng nhau' },
{ hanzi: '意思', pinyin: 'yìsi', meaning: 'ý nghĩa' },
{ hanzi: '阴', pinyin: 'yīn', meaning: 'âm u, trời nhiều mây' },
{ hanzi: '因为', pinyin: 'yīnwèi', meaning: 'vì' },
{ hanzi: '游泳', pinyin: 'yóuyǒng', meaning: 'bơi' },
{ hanzi: '右边', pinyin: 'yòubiān', meaning: 'bên phải' },
{ hanzi: '鱼', pinyin: 'yú', meaning: 'cá' },
{ hanzi: '元', pinyin: 'yuán', meaning: 'Đồng (đơn vị tiền tệ)' },
{ hanzi: '远', pinyin: 'yuǎn', meaning: 'xa' },
{ hanzi: '运动', pinyin: 'yùndòng', meaning: 'vận' },
{ hanzi: '再', pinyin: 'zài', meaning: 'lại' },
{ hanzi: '早上', pinyin: 'zǎoshàng', meaning: 'buổi sáng' },
{ hanzi: '张', pinyin: 'zhāng', meaning: 'tờ, bức (dùng cho vật phẳng, giấy, tranh, bàn)' },
{ hanzi: '丈夫', pinyin: 'zhàngfu', meaning: 'chồng' },
{ hanzi: '找', pinyin: 'zhǎo', meaning: 'tìm' },
{ hanzi: '着', pinyin: 'zhe', meaning: 'đang (dùng để chỉ trạng thái hiện tại)' },
{ hanzi: '真', pinyin: 'zhēn', meaning: 'thật' },
{ hanzi: '正在', pinyin: 'zhèngzài', meaning: 'đang' },
{ hanzi: '知道', pinyin: 'zhīdào', meaning: 'biết' },
{ hanzi: '准备', pinyin: 'zhǔnbèi', meaning: 'chuẩn bị' },
{ hanzi: '自行车', pinyin: 'zìxíngchē', meaning: 'xe đạp' },
{ hanzi: '走', pinyin: 'zǒu', meaning: 'đi' },
{ hanzi: '最', pinyin: 'zuì', meaning: 'nhất (so sánh nhất)' },
{ hanzi: '左边', pinyin: 'zuǒbiān', meaning: 'bên trái' },
];