vocab = [
    { hanzi: '阿姨', pinyin: 'āyí', meaning: 'dì, cô' },
{ hanzi: '啊', pinyin: 'a', meaning: 'a, à, ơ (trợ từ ngữ khí)' },
{ hanzi: '矮', pinyin: 'ǎi', meaning: 'thấp, lùn' },
{ hanzi: '爱好', pinyin: 'àihào', meaning: 'sở thích' },
{ hanzi: '安静', pinyin: 'ānjìng', meaning: 'yên tĩnh' },
{ hanzi: '把', pinyin: 'bǎ', meaning: 'đem, lấy (giới từ)' },
{ hanzi: '班', pinyin: 'bān', meaning: 'lớp, ca (làm việc)' },
{ hanzi: '搬', pinyin: 'bān', meaning: 'chuyển, dời' },
{ hanzi: '半', pinyin: 'bàn', meaning: 'một nửa' },
{ hanzi: '办法', pinyin: 'bànfǎ', meaning: 'biện pháp' },
{ hanzi: '办公室', pinyin: 'bàngōngshì', meaning: 'văn phòng' },
{ hanzi: '帮忙', pinyin: 'bāngmáng', meaning: 'giúp đỡ (động từ li hợp)' },
{ hanzi: '包', pinyin: 'bāo', meaning: 'túi, bao' },
{ hanzi: '饱', pinyin: 'bǎo', meaning: 'no' },
{ hanzi: '北方', pinyin: 'běifāng', meaning: 'miền Bắc' },
{ hanzi: '被', pinyin: 'bèi', meaning: 'bị, được (giới từ bị động)' },
{ hanzi: '比较', pinyin: 'bǐjiào', meaning: 'khá, tương đối' },
{ hanzi: '比赛', pinyin: 'bǐsài', meaning: 'cuộc thi, thi đấu' },
{ hanzi: '必须', pinyin: 'bìxū', meaning: 'phải, cần phải' },
{ hanzi: '变化', pinyin: 'biànhuà', meaning: 'thay đổi' },
{ hanzi: '表示', pinyin: 'biǎoshì', meaning: 'biểu thị, thể hiện' },
{ hanzi: '表演', pinyin: 'biǎoyǎn', meaning: 'biểu diễn' },
{ hanzi: '别人', pinyin: 'biérén', meaning: 'người khác' },
{ hanzi: '宾馆', pinyin: 'bīnguǎn', meaning: 'khách sạn' },
{ hanzi: '冰箱', pinyin: 'bīngxiāng', meaning: 'tủ lạnh' },
{ hanzi: '才', pinyin: 'cái', meaning: 'mới (nhấn mạnh thời gian muộn, trễ)' },
{ hanzi: '菜单', pinyin: 'càidān', meaning: 'thực đơn' },
{ hanzi: '参加', pinyin: 'cānjiā', meaning: 'tham gia' },
{ hanzi: '草', pinyin: 'cǎo', meaning: 'cỏ' },
{ hanzi: '层', pinyin: 'céng', meaning: 'tầng' },
{ hanzi: '差', pinyin: 'chà', meaning: 'kém, thiếu, tệ' },
{ hanzi: '超市', pinyin: 'chāoshì', meaning: 'siêu thị' },
{ hanzi: '衬衫', pinyin: 'chènshān', meaning: 'áo sơ mi' },
{ hanzi: '成绩', pinyin: 'chéngjì', meaning: 'thành tích' },
{ hanzi: '城市', pinyin: 'chéngshì', meaning: 'thành phố' },
{ hanzi: '迟到', pinyin: 'chídào', meaning: 'đến trễ' },
{ hanzi: '出现', pinyin: 'chūxiàn', meaning: 'xuất hiện' },
{ hanzi: '厨房', pinyin: 'chúfáng', meaning: 'nhà bếp' },
{ hanzi: '除了', pinyin: 'chúle', meaning: 'ngoài ra, trừ ra' },
{ hanzi: '春', pinyin: 'chūn', meaning: 'mùa xuân' },
{ hanzi: '词语', pinyin: 'cíyǔ', meaning: 'từ ngữ' },
{ hanzi: '聪明', pinyin: 'cōngmíng', meaning: 'thông minh' },
{ hanzi: '打扫', pinyin: 'dǎsǎo', meaning: 'quét dọn' },
{ hanzi: '打算', pinyin: 'dǎsuàn', meaning: 'dự định' },
{ hanzi: '带', pinyin: 'dài', meaning: 'mang theo, dẫn theo' },
{ hanzi: '担心', pinyin: 'dānxīn', meaning: 'lo lắng' },
{ hanzi: '蛋糕', pinyin: 'dàngāo', meaning: 'bánh ngọt' },
{ hanzi: '当然', pinyin: 'dāngrán', meaning: 'đương nhiên' },
{ hanzi: '地', pinyin: 'de', meaning: 'trợ từ của động từ' },
{ hanzi: '灯', pinyin: 'dēng', meaning: 'đèn' },
{ hanzi: '低', pinyin: 'dī', meaning: 'thấp' },
{ hanzi: '地方', pinyin: 'dìfāng', meaning: 'nơi, chỗ' },
{ hanzi: '地铁', pinyin: 'dìtiě', meaning: 'tàu điện ngầm' },
{ hanzi: '地图', pinyin: 'dìtú', meaning: 'bản đồ' },
{ hanzi: '电梯', pinyin: 'diàntī', meaning: 'thang máy' },
{ hanzi: '电子邮箱', pinyin: 'diànzǐ yóuxiāng', meaning: 'hộp thư điện tử (email)' },
{ hanzi: '东', pinyin: 'dōng', meaning: 'đông (hướng đông)' },
{ hanzi: '冬', pinyin: 'dōng', meaning: 'mùa đông' },
{ hanzi: '动物', pinyin: 'dòngwù', meaning: 'động vật' },
{ hanzi: '短', pinyin: 'duǎn', meaning: 'ngắn' },
{ hanzi: '段', pinyin: 'duàn', meaning: 'đoạn, quãng' },
{ hanzi: '锻炼', pinyin: 'duànliàn', meaning: 'luyện tập, rèn luyện' },
{ hanzi: '多么', pinyin: 'duōme', meaning: 'bao nhiêu, biết bao' },
{ hanzi: '饿', pinyin: 'è', meaning: 'đói' },
{ hanzi: '而且', pinyin: 'érqiě', meaning: 'mà còn, hơn nữa' },
{ hanzi: '耳朵', pinyin: 'ěrduo', meaning: 'tai' },
{ hanzi: '发烧', pinyin: 'fāshāo', meaning: 'sốt' },
{ hanzi: '发现', pinyin: 'fāxiàn', meaning: 'phát hiện' },
{ hanzi: '方便', pinyin: 'fāngbiàn', meaning: 'thuận tiện' },
{ hanzi: '放', pinyin: 'fàng', meaning: 'đặt, để' },
{ hanzi: '放心', pinyin: 'fàngxīn', meaning: 'yên tâm' },
{ hanzi: '分', pinyin: 'fēn', meaning: 'phút, phân' },
{ hanzi: '附近', pinyin: 'fùjìn', meaning: 'gần đây, vùng lân cận' },
{ hanzi: '复习', pinyin: 'fùxí', meaning: 'ôn tập' },
{ hanzi: '干净', pinyin: 'gānjìng', meaning: 'sạch sẽ' },
{ hanzi: '敢', pinyin: 'gǎn', meaning: 'dám' },
{ hanzi: '感冒', pinyin: 'gǎnmào', meaning: 'cảm mạo, cảm lạnh' },
{ hanzi: '刚才', pinyin: 'gāngcái', meaning: 'vừa mới' },
{ hanzi: '跟', pinyin: 'gēn', meaning: 'cùng với' },
{ hanzi: '根据', pinyin: 'gēnjù', meaning: 'căn cứ vào' },
{ hanzi: '更', pinyin: 'gèng', meaning: 'hơn, càng' },
{ hanzi: '公园', pinyin: 'gōngyuán', meaning: 'công viên' },
{ hanzi: '故事', pinyin: 'gùshì', meaning: 'câu chuyện' },
{ hanzi: '刮风', pinyin: 'guā fēng', meaning: 'gió thổi' },
{ hanzi: '关', pinyin: 'guān', meaning: 'đóng, tắt' },
{ hanzi: '关系', pinyin: 'guānxì', meaning: 'quan hệ' },
{ hanzi: '关心', pinyin: 'guānxīn', meaning: 'quan tâm' },
{ hanzi: '关于', pinyin: 'guānyú', meaning: 'về (liên quan đến)' },
{ hanzi: '国家', pinyin: 'guójiā', meaning: 'quốc gia' },
{ hanzi: '果汁', pinyin: 'guǒzhī', meaning: 'nước ép trái cây' },
{ hanzi: '过去', pinyin: 'guòqù', meaning: 'quá khứ' },
{ hanzi: '还是', pinyin: 'háishì', meaning: 'vẫn còn, hay là' },
{ hanzi: '害怕', pinyin: 'hàipà', meaning: 'sợ' },
{ hanzi: '河', pinyin: 'hé', meaning: 'sông' },
{ hanzi: '黑板', pinyin: 'hēibǎn', meaning: 'bảng' },
{ hanzi: '护照', pinyin: 'hùzhào', meaning: 'hộ chiếu' },
{ hanzi: '花', pinyin: 'huā', meaning: 'hoa, tiêu (tiền, thời gian)' },
{ hanzi: '花园', pinyin: 'huāyuán', meaning: 'vườn hoa' },
{ hanzi: '画', pinyin: 'huà', meaning: 'vẽ, tranh' },
{ hanzi: '坏', pinyin: 'huài', meaning: 'hỏng, xấu' },
{ hanzi: '还', pinyin: 'huán', meaning: 'trả lại, hoàn' },
{ hanzi: '环境', pinyin: 'huánjìng', meaning: 'môi trường' },
{ hanzi: '换', pinyin: 'huàn', meaning: 'đổi' },
{ hanzi: '黄', pinyin: 'huáng', meaning: 'màu vàng' },
{ hanzi: '会议', pinyin: 'huìyì', meaning: 'hội nghị, cuộc họp' },
{ hanzi: '或者', pinyin: 'huòzhě', meaning: 'hoặc là' },
{ hanzi: '机会', pinyin: 'jīhuì', meaning: 'cơ hội' },
{ hanzi: '几乎', pinyin: 'jīhū', meaning: 'hầu như, gần như' },
{ hanzi: '极', pinyin: 'jí', meaning: 'cực kỳ' },
{ hanzi: '记得', pinyin: 'jìdé', meaning: 'nhớ, nhớ đến' },
{ hanzi: '季节', pinyin: 'jìjié', meaning: 'mùa' },
{ hanzi: '检查', pinyin: 'jiǎnchá', meaning: 'kiểm tra' },
{ hanzi: '简单', pinyin: 'jiǎndān', meaning: 'đơn giản' },
{ hanzi: '健康', pinyin: 'jiànkāng', meaning: 'khỏe mạnh' },
{ hanzi: '见面', pinyin: 'jiànmiàn', meaning: 'gặp mặt' },
{ hanzi: '讲', pinyin: 'jiǎng', meaning: 'nói, giảng' },
{ hanzi: '教', pinyin: 'jiāo', meaning: 'dạy' },
{ hanzi: '角', pinyin: 'jiǎo', meaning: 'góc' },
{ hanzi: '脚', pinyin: 'jiǎo', meaning: 'chân' },
{ hanzi: '接', pinyin: 'jiē', meaning: 'nhận, tiếp' },
{ hanzi: '街道', pinyin: 'jiēdào', meaning: 'đường phố' },
{ hanzi: '结婚', pinyin: 'jiéhūn', meaning: 'kết hôn' },
{ hanzi: '结束', pinyin: 'jiéshù', meaning: 'kết thúc' },
{ hanzi: '节目', pinyin: 'jiémù', meaning: 'chương trình' },
{ hanzi: '节日', pinyin: 'jiérì', meaning: 'ngày lễ' },
{ hanzi: '解决', pinyin: 'jiějué', meaning: 'giải quyết' },
{ hanzi: '借', pinyin: 'jiè', meaning: 'mượn' },
{ hanzi: '经常', pinyin: 'jīngcháng', meaning: 'thường xuyên' },
{ hanzi: '经过', pinyin: 'jīngguò', meaning: 'trải qua' },
{ hanzi: '经历', pinyin: 'jīnglì', meaning: 'kinh nghiệm' },
{ hanzi: '久', pinyin: 'jiǔ', meaning: 'lâu' },
{ hanzi: '旧', pinyin: 'jiù', meaning: 'cũ' },
{ hanzi: '举行', pinyin: 'jǔxíng', meaning: 'tổ chức' },
{ hanzi: '句子', pinyin: 'jùzi', meaning: 'câu' },
{ hanzi: '决定', pinyin: 'juédìng', meaning: 'quyết định' },
{ hanzi: '可爱', pinyin: 'kě\'ài', meaning: 'đáng yêu' },
{ hanzi: '刻', pinyin: 'kè', meaning: 'khắc (15 phút)' },
{ hanzi: '客人', pinyin: 'kèrén', meaning: 'khách' },
{ hanzi: '空调', pinyin: 'kòngtiáo', meaning: 'máy điều hòa' },
{ hanzi: '口', pinyin: 'kǒu', meaning: 'miệng, khẩu' },
{ hanzi: '哭', pinyin: 'kū', meaning: 'khóc' },
{ hanzi: '裤子', pinyin: 'kùzi', meaning: 'quần' },
{ hanzi: '筷子', pinyin: 'kuàizi', meaning: 'đũa' },
{ hanzi: '蓝', pinyin: 'lán', meaning: 'màu xanh' },
{ hanzi: '老', pinyin: 'lǎo', meaning: 'già, cũ' },
{ hanzi: '离开', pinyin: 'líkāi', meaning: 'rời khỏi' },
{ hanzi: '礼物', pinyin: 'lǐwù', meaning: 'quà' },
{ hanzi: '历史', pinyin: 'lìshǐ', meaning: 'lịch sử' },
{ hanzi: '脸', pinyin: 'liǎn', meaning: 'mặt' },
{ hanzi: '练习', pinyin: 'liànxí', meaning: 'luyện tập' },
{ hanzi: '辆', pinyin: 'liàng', meaning: 'chiếc (xe)' },
{ hanzi: '了解', pinyin: 'liǎojiě', meaning: 'hiểu rõ' },
{ hanzi: '邻居', pinyin: 'línjū', meaning: 'hàng xóm' },
{ hanzi: '楼', pinyin: 'lóu', meaning: 'tòa nhà' },
{ hanzi: '马', pinyin: 'mǎ', meaning: 'con ngựa' },
{ hanzi: '马上', pinyin: 'mǎshàng', meaning: 'ngay lập tức' },
{ hanzi: '满意', pinyin: 'mǎnyì', meaning: 'hài lòng' },
{ hanzi: '帽子', pinyin: 'màozi', meaning: 'mũ' },
{ hanzi: '米', pinyin: 'mǐ', meaning: 'gạo, mét' },
{ hanzi: '面包', pinyin: 'miànbāo', meaning: 'bánh mì' },
{ hanzi: '面条', pinyin: 'miàntiáo', meaning: 'mì sợi' },
{ hanzi: '明白', pinyin: 'míngbái', meaning: 'hiểu rõ' },
{ hanzi: '拿', pinyin: 'ná', meaning: 'cầm, lấy' },
{ hanzi: '奶奶', pinyin: 'nǎinai', meaning: 'bà nội' },
{ hanzi: '南', pinyin: 'nán', meaning: 'phía nam' },
{ hanzi: '难', pinyin: 'nán', meaning: 'khó' },
{ hanzi: '难过', pinyin: 'nánguò', meaning: 'buồn' },
{ hanzi: '年级', pinyin: 'niánjí', meaning: 'lớp, năm học' },
{ hanzi: '年轻', pinyin: 'niánqīng', meaning: 'trẻ' },
{ hanzi: '鸟', pinyin: 'niǎo', meaning: 'chim' },
{ hanzi: '努力', pinyin: 'nǔlì', meaning: 'nỗ lực, chăm chỉ' },
{ hanzi: '爬山', pinyin: 'páshān', meaning: 'leo núi' },
{ hanzi: '盘子', pinyin: 'pánzi', meaning: 'đĩa' },
{ hanzi: '胖', pinyin: 'pàng', meaning: 'béo' },
{ hanzi: '啤酒', pinyin: 'píjiǔ', meaning: 'bia' },
{ hanzi: '葡萄', pinyin: 'pútao', meaning: 'nho' },
{ hanzi: '普通话', pinyin: 'pǔtōnghuà', meaning: 'tiếng Phổ thông (tiếng Trung chuẩn)' },
{ hanzi: '骑', pinyin: 'qí', meaning: 'cưỡi, đi (xe đạp, xe máy)' },
{ hanzi: '其实', pinyin: 'qíshí', meaning: 'thực ra' },
{ hanzi: '其他', pinyin: 'qítā', meaning: 'khác' },
{ hanzi: '奇怪', pinyin: 'qíguài', meaning: 'kỳ lạ' },
{ hanzi: '铅笔', pinyin: 'qiānbǐ', meaning: 'bút chì' },
{ hanzi: '清楚', pinyin: 'qīngchǔ', meaning: 'rõ ràng' },
{ hanzi: '秋', pinyin: 'qiū', meaning: 'mùa thu' },
{ hanzi: '裙子', pinyin: 'qúnzi', meaning: 'váy' },
{ hanzi: '然后', pinyin: 'ránhòu', meaning: 'sau đó' },
{ hanzi: '热情', pinyin: 'rèqíng', meaning: 'nhiệt tình' },
{ hanzi: '认为', pinyin: 'rènwéi', meaning: 'cho rằng' },
{ hanzi: '认真', pinyin: 'rènzhēn', meaning: 'nghiêm túc' },
{ hanzi: '容易', pinyin: 'róngyì', meaning: 'dễ dàng' },
{ hanzi: '如果', pinyin: 'rúguǒ', meaning: 'nếu như' },
{ hanzi: '伞', pinyin: 'sǎn', meaning: 'ô, dù' },
{ hanzi: '上网', pinyin: 'shàngwǎng', meaning: 'lên mạng' },
{ hanzi: '生气', pinyin: 'shēngqì', meaning: 'giận dữ' },
{ hanzi: '声音', pinyin: 'shēngyīn', meaning: 'âm thanh' },
{ hanzi: '使', pinyin: 'shǐ', meaning: 'khiến, làm cho' },
{ hanzi: '世界', pinyin: 'shìjiè', meaning: 'thế giới' },
{ hanzi: '瘦', pinyin: 'shòu', meaning: 'gầy' },
{ hanzi: '舒服', pinyin: 'shūfu', meaning: 'thoải mái' },
{ hanzi: '叔叔', pinyin: 'shūshu', meaning: 'chú' },
{ hanzi: '树', pinyin: 'shù', meaning: 'cây' },
{ hanzi: '数学', pinyin: 'shùxué', meaning: 'toán học' },
{ hanzi: '刷牙', pinyin: 'shuāyá', meaning: 'đánh răng' },
{ hanzi: '双', pinyin: 'shuāng', meaning: 'đôi' },
{ hanzi: '水平', pinyin: 'shuǐpíng', meaning: 'trình độ' },
{ hanzi: '司机', pinyin: 'sījī', meaning: 'lái xe, tài xế' },
{ hanzi: '虽然', pinyin: 'suīrán', meaning: 'tuy rằng' },
{ hanzi: '太阳', pinyin: 'tàiyáng', meaning: 'mặt trời' },
{ hanzi: '糖', pinyin: 'táng', meaning: 'kẹo, đường' },
{ hanzi: '特别', pinyin: 'tèbié', meaning: 'đặc biệt' },
{ hanzi: '疼', pinyin: 'téng', meaning: 'đau' },
{ hanzi: '提高', pinyin: 'tígāo', meaning: 'nâng cao' },
{ hanzi: '体育', pinyin: 'tǐyù', meaning: 'thể dục, thể thao' },
{ hanzi: '甜', pinyin: 'tián', meaning: 'ngọt' },
{ hanzi: '条', pinyin: 'tiáo', meaning: 'sợi, cái' },
{ hanzi: '同事', pinyin: 'tóngshì', meaning: 'đồng nghiệp' },
{ hanzi: '同意', pinyin: 'tóngyì', meaning: 'đồng ý' },
{ hanzi: '头发', pinyin: 'tóufa', meaning: 'tóc' },
{ hanzi: '突然', pinyin: 'tūrán', meaning: 'đột nhiên' },
{ hanzi: '图书馆', pinyin: 'túshūguǎn', meaning: 'thư viện' },
{ hanzi: '腿', pinyin: 'tuǐ', meaning: 'chân' },
{ hanzi: '完成', pinyin: 'wánchéng', meaning: 'hoàn thành' },
{ hanzi: '碗', pinyin: 'wǎn', meaning: 'bát' },
{ hanzi: '万', pinyin: 'wàn', meaning: 'vạn, mười nghìn' },
{ hanzi: '忘记', pinyin: 'wàngjì', meaning: 'quên' },
{ hanzi: '位', pinyin: 'wèi', meaning: 'vị, ngài' },
{ hanzi: '为', pinyin: 'wèi', meaning: 'vì' },
{ hanzi: '为了', pinyin: 'wèile', meaning: 'để, vì' },
{ hanzi: '文化', pinyin: 'wénhuà', meaning: 'văn hóa' },
{ hanzi: '西', pinyin: 'xī', meaning: 'phía tây' },
{ hanzi: '习惯', pinyin: 'xíguàn', meaning: 'thói quen' },
{ hanzi: '洗手间', pinyin: 'xǐshǒujiān', meaning: 'nhà vệ sinh' },
{ hanzi: '洗澡', pinyin: 'xǐzǎo', meaning: 'tắm' },
{ hanzi: '喜欢', pinyin: 'xǐhuān', meaning: 'thích' },
{ hanzi: '现在', pinyin: 'xiànzài', meaning: 'hiện' },
{ hanzi: '香蕉', pinyin: 'xiāngjiāo', meaning: 'chuối' },
{ hanzi: '相同', pinyin: 'xiāngtóng', meaning: 'giống nhau' },
{ hanzi: '相信', pinyin: 'xiāngxìn', meaning: 'tin tưởng' },
{ hanzi: '像', pinyin: 'xiàng', meaning: 'giống' },
{ hanzi: '小心', pinyin: 'xiǎoxīn', meaning: 'cẩn thận' },
{ hanzi: '校长', pinyin: 'xiàozhǎng', meaning: 'hiệu trưởng' },
{ hanzi: '鞋', pinyin: 'xié', meaning: 'giày' },
{ hanzi: '新闻', pinyin: 'xīnwén', meaning: 'tin tức' },
{ hanzi: '新鲜', pinyin: 'xīnxiān', meaning: 'tươi mới' },
{ hanzi: '信', pinyin: 'xìn', meaning: 'thư, tin tưởng' },
{ hanzi: '行李箱', pinyin: 'xínglǐxiāng', meaning: 'vali' },
{ hanzi: '兴趣', pinyin: 'xìngqù', meaning: 'hứng thú' },
{ hanzi: '熊猫', pinyin: 'xióngmāo', meaning: 'gấu trúc' },
{ hanzi: '需要', pinyin: 'xūyào', meaning: 'cần' },
{ hanzi: '选择', pinyin: 'xuǎnzé', meaning: 'lựa chọn' },
{ hanzi: '眼镜', pinyin: 'yǎnjìng', meaning: 'kính' },
{ hanzi: '要求', pinyin: 'yāoqiú', meaning: 'yêu cầu' },
{ hanzi: '爷爷', pinyin: 'yéye', meaning: 'ông nội' },
{ hanzi: '一定', pinyin: 'yīdìng', meaning: 'nhất định' },
{ hanzi: '一共', pinyin: 'yīgòng', meaning: 'tổng cộng' },
{ hanzi: '一会儿', pinyin: 'yīhuìr', meaning: 'một lát' },
{ hanzi: '一样', pinyin: 'yīyàng', meaning: 'giống nhau' },
{ hanzi: '以后', pinyin: 'yǐhòu', meaning: 'sau này' },
{ hanzi: '以前', pinyin: 'yǐqián', meaning: 'trước đây' },
{ hanzi: '以为', pinyin: 'yǐwéi', meaning: 'cho rằng' },
{ hanzi: '一般', pinyin: 'yībān', meaning: 'thông thường' },
{ hanzi: '一边', pinyin: 'yībiān', meaning: 'vừa ... vừa ...' },
{ hanzi: '一直', pinyin: 'yīzhí', meaning: 'luôn luôn' },
{ hanzi: '音乐', pinyin: 'yīnyuè', meaning: 'âm nhạc' },
{ hanzi: '银行', pinyin: 'yínháng', meaning: 'ngân hàng' },
{ hanzi: '应该', pinyin: 'yīnggāi', meaning: 'nên' },
{ hanzi: '影响', pinyin: 'yǐngxiǎng', meaning: 'ảnh hưởng' },
{ hanzi: '用', pinyin: 'yòng', meaning: 'dùng' },
{ hanzi: '游戏', pinyin: 'yóuxì', meaning: 'trò chơi' },
{ hanzi: '又', pinyin: 'yòu', meaning: 'lại, vừa' },
{ hanzi: '有名', pinyin: 'yǒumíng', meaning: 'nổi tiếng' },
{ hanzi: '遇到', pinyin: 'yùdào', meaning: 'gặp phải' },
{ hanzi: '月亮', pinyin: 'yuèliàng', meaning: 'mặt trăng' },
{ hanzi: '云', pinyin: 'yún', meaning: 'mây' },
{ hanzi: '站', pinyin: 'zhàn', meaning: 'đứng, trạm' },
{ hanzi: '长', pinyin: 'zhǎng', meaning: 'dài' },
{ hanzi: '着急', pinyin: 'zhāojí', meaning: 'lo lắng' },
{ hanzi: '照顾', pinyin: 'zhàogu', meaning: 'chăm sóc' },
{ hanzi: '照片', pinyin: 'zhàopiàn', meaning: 'bức ảnh' },
{ hanzi: '照相机', pinyin: 'zhàoxiàngjī', meaning: 'máy ảnh' },
{ hanzi: '只', pinyin: 'zhǐ', meaning: 'chỉ' },
{ hanzi: '中间', pinyin: 'zhōngjiān', meaning: 'ở giữa' },
{ hanzi: '终于', pinyin: 'zhōngyú', meaning: 'cuối cùng' },
{ hanzi: '种', pinyin: 'zhǒng', meaning: 'loại, hạt giống' },
{ hanzi: '重要', pinyin: 'zhòngyào', meaning: 'quan trọng' },
{ hanzi: '主要', pinyin: 'zhǔyào', meaning: 'chủ yếu' },
{ hanzi: '周末', pinyin: 'zhōumò', meaning: 'cuối tuần' },
{ hanzi: '祝', pinyin: 'zhù', meaning: 'chúc' },
{ hanzi: '注意', pinyin: 'zhùyì', meaning: 'chú ý' },
{ hanzi: '字典', pinyin: 'zìdiǎn', meaning: 'từ điển' },
{ hanzi: '自己', pinyin: 'zìjǐ', meaning: 'bản thân' },
{ hanzi: '总是', pinyin: 'zǒngshì', meaning: 'luôn luôn' },
{ hanzi: '最近', pinyin: 'zuìjìn', meaning: 'gần đây' },
{ hanzi: '作业', pinyin: 'zuòyè', meaning: 'bài tập về nhà' },
{ hanzi: '作用', pinyin: 'zuòyòng', meaning: 'tác dụng' },

];