vocab = [
    { hanzi: '爱情', pinyin: 'ài qíng [ái tình]', meaning: 'tình yêu' },
{ hanzi: '安排', pinyin: 'ān pái [an bài]', meaning: 'sắp xếp' },
{ hanzi: '安全', pinyin: 'ān quán [an toàn]', meaning: 'an toàn' },
{ hanzi: '按时', pinyin: 'àn shí', meaning: 'đúng hạn' },
{ hanzi: '按照', pinyin: 'àn zhào', meaning: 'dựa vào, theo' },
{ hanzi: '百分之', pinyin: 'bǎi fēn zhī', meaning: '%' },
{ hanzi: '棒', pinyin: 'bàng', meaning: 'cây gậy/ giỏi, tốt' },
{ hanzi: '包子', pinyin: 'bāo zi', meaning: 'bánh bao' },
{ hanzi: '保护', pinyin: 'bǎo hù', meaning: 'che chở, bảo vệ' },
{ hanzi: '保证', pinyin: 'bǎo zhèng', meaning: 'đảm bảo, cam đoan' },
{ hanzi: '报名', pinyin: 'bào míng', meaning: 'đăng kí' },
{ hanzi: '抱', pinyin: 'bào', meaning: 'ôm' },
{ hanzi: '抱歉', pinyin: 'bào qiàn', meaning: 'xin lỗi' },
{ hanzi: '倍', pinyin: 'bèi', meaning: 'lần' },
{ hanzi: '本来', pinyin: 'běn lái', meaning: 'vốn có' },
{ hanzi: '笨', pinyin: 'bèn', meaning: 'ngốc nghếch' },
{ hanzi: '比如', pinyin: 'bǐ rú', meaning: 'ví dụ như' },
{ hanzi: '毕业', pinyin: 'bì yè', meaning: 'tốt nghiệp' },
{ hanzi: '遍', pinyin: 'biàn', meaning: 'lần, lượt' },
{ hanzi: '标准', pinyin: 'biāo zhǔn', meaning: 'tiêu chuẩn' },
{ hanzi: '表格', pinyin: 'biǎo gé', meaning: 'bảng biểu' },
{ hanzi: '表示', pinyin: 'biǎo shì', meaning: 'biểu thị, cho thấy' },
{ hanzi: '表演', pinyin: 'biǎo yǎn', meaning: 'biểu diễn' },
{ hanzi: '表扬', pinyin: 'biǎo yáng', meaning: 'tuyên dương' },
{ hanzi: '饼干', pinyin: 'bǐng gān', meaning: 'bánh' },
{ hanzi: '并且', pinyin: 'bìng qiě', meaning: 'đồng thời' },
{ hanzi: '博士', pinyin: 'bó shì', meaning: 'tiến sĩ' },
{ hanzi: '不得不', pinyin: 'bù dé bù', meaning: 'đành' },
{ hanzi: '不管', pinyin: 'bù guǎn', meaning: 'bất kể' },
{ hanzi: '不过', pinyin: 'bù guò', meaning: 'nhưng, có điều' },
{ hanzi: '不仅', pinyin: 'bù jǐn', meaning: 'không những' },
{ hanzi: '部分', pinyin: 'bù fèn', meaning: 'bộ phận, phần' },
{ hanzi: '擦', pinyin: 'cā', meaning: 'lau' },
{ hanzi: '猜', pinyin: 'cāi', meaning: 'đoán' },
{ hanzi: '材料', pinyin: 'cái liào', meaning: 'tài liệu' },
{ hanzi: '参观', pinyin: 'cān guān', meaning: 'tham quan' },
{ hanzi: '餐厅', pinyin: 'cān tīng', meaning: 'căng tin, nhà ăn' },
{ hanzi: '厕所', pinyin: 'cè suǒ', meaning: 'phòng vệ sinh' },
{ hanzi: '差不多', pinyin: 'chà bù duō', meaning: 'gần như' },
{ hanzi: '长城', pinyin: 'cháng chéng', meaning: 'Trường Thành' },
{ hanzi: '长江', pinyin: 'cháng jiāng', meaning: 'Trường Giang' },
{ hanzi: '尝', pinyin: 'cháng', meaning: 'nếm thử' },
{ hanzi: '场', pinyin: 'chǎng', meaning: 'trận, suất' },
{ hanzi: '超过', pinyin: 'chāo guò', meaning: 'vượt trên' },
{ hanzi: '成功', pinyin: 'chéng gōng', meaning: 'thành công' },
{ hanzi: '成为', pinyin: 'chéng wéi', meaning: 'trở thành' },
{ hanzi: '诚实', pinyin: 'chéng shí', meaning: 'trung thực' },
{ hanzi: '乘坐', pinyin: 'chéng zuò', meaning: 'ngồi xe' },
{ hanzi: '吃惊', pinyin: 'chī jīng', meaning: 'ngạc nhiên' },
{ hanzi: '重新', pinyin: 'chóng xīn', meaning: 'làm lại' },
{ hanzi: '抽烟', pinyin: 'chōu yān', meaning: 'hút thuốc' },
{ hanzi: '出差', pinyin: 'chū chāi', meaning: 'đi công tác' },
{ hanzi: '出发', pinyin: 'chū fā', meaning: 'xuất phát' },
{ hanzi: '出生', pinyin: 'chū shēng', meaning: 'ra đời' },
{ hanzi: '出现', pinyin: 'chū xiàn', meaning: 'xuất hiện' },
{ hanzi: '厨房', pinyin: 'chú fáng', meaning: 'phòng bếp' },
{ hanzi: '传真', pinyin: 'chuán zhēn', meaning: 'fax, bản fax' },
{ hanzi: '窗户', pinyin: 'chuāng hù', meaning: 'cửa sổ' },
{ hanzi: '词语', pinyin: 'cí yǔ', meaning: 'từ ngữ' },
{ hanzi: '从来', pinyin: 'cóng lái', meaning: 'từ trước đến nay' },
{ hanzi: '粗心', pinyin: 'cū xīn', meaning: 'thô lỗ, cẩu thả' },
{ hanzi: '存', pinyin: 'cún', meaning: 'giữ, tiết kiệm, tồn' },
{ hanzi: '错误', pinyin: 'cuò wù', meaning: 'sai lầm' },
{ hanzi: '答案', pinyin: 'dá àn', meaning: 'đáp án' },
{ hanzi: '打扮', pinyin: 'dǎ bàn', meaning: 'trau chuốt, trang điểm' },
{ hanzi: '打扰', pinyin: 'dǎ rǎo', meaning: 'làm phiền' },
{ hanzi: '打印', pinyin: 'dǎ yìn', meaning: 'in ấn' },
{ hanzi: '打招呼', pinyin: 'dǎ zhāo hū', meaning: 'chào hỏi' },
{ hanzi: '打折', pinyin: 'dǎ zhé', meaning: 'giảm giá' },
{ hanzi: '打针', pinyin: 'dǎ zhēn', meaning: 'tiêm' },
{ hanzi: '大概', pinyin: 'dà gài', meaning: 'khoảng' },
{ hanzi: '大使馆', pinyin: 'dà shǐ guǎn', meaning: 'đại sứ quán' },
{ hanzi: '大约', pinyin: 'dà yuē', meaning: 'khoảng' },
{ hanzi: '大夫', pinyin: 'dài fū', meaning: 'bác sĩ, đại phu' },
{ hanzi: '戴', pinyin: 'dài', meaning: 'đeo' },
{ hanzi: '当', pinyin: 'dāng', meaning: 'làm' },
{ hanzi: '当时', pinyin: 'dāng shí', meaning: 'lúc đó' },
{ hanzi: '刀', pinyin: 'dāo', meaning: 'cái dao' },
{ hanzi: '导游', pinyin: 'dǎo yóu', meaning: 'hướng dẫn viên du lịch' },
{ hanzi: '到处', pinyin: 'dào chù', meaning: 'khắp nơi' },
{ hanzi: '到底', pinyin: 'dào dǐ', meaning: 'cuối cùng' },
{ hanzi: '倒', pinyin: 'dǎo', meaning: 'đổ, ngã' },
{ hanzi: '道歉', pinyin: 'dào qiàn', meaning: 'xin lỗi' },
{ hanzi: '得意', pinyin: 'dé yì', meaning: 'đắc ý' },
{ hanzi: '得（助动词）', pinyin: 'de （ zhù dòng cí ）', meaning: 'trợ từ' },
{ hanzi: '登机牌', pinyin: 'dēng jī pái', meaning: 'thẻ lên tàu' },
{ hanzi: '等（助词）', pinyin: 'děng （ zhù cí ）', meaning: 'vân vân' },
{ hanzi: '低', pinyin: 'dī', meaning: 'thấp' },
{ hanzi: '底', pinyin: 'dǐ', meaning: 'đáy' },
{ hanzi: '地点', pinyin: 'dì diǎn', meaning: 'địa điểm' },
{ hanzi: '地球', pinyin: 'dì qiú', meaning: 'địa cầu' },
{ hanzi: '地址', pinyin: 'dì zhǐ', meaning: 'địa chỉ' },
{ hanzi: '调查', pinyin: 'diào chá', meaning: 'điều tra' },
{ hanzi: '掉', pinyin: 'diào', meaning: 'rơi' },
{ hanzi: '丢', pinyin: 'diū', meaning: 'mất' },
{ hanzi: '动作', pinyin: 'dòng zuò', meaning: 'động tác' },
{ hanzi: '堵车', pinyin: 'dǔ chē', meaning: 'tắc đường' },
{ hanzi: '肚子', pinyin: 'dù zi', meaning: 'bụng' },
{ hanzi: '短信', pinyin: 'duǎn xìn', meaning: 'tin nhắn' },
{ hanzi: '对话', pinyin: 'duì huà', meaning: 'hội thoại, đối thoại' },
{ hanzi: '对面', pinyin: 'duì miàn', meaning: 'đối diện' },
{ hanzi: '对于', pinyin: 'duì yú', meaning: 'về (vấn đề gì đó)' },
{ hanzi: '儿童', pinyin: 'ér tóng', meaning: 'trẻ con' },
{ hanzi: '而', pinyin: 'ér', meaning: 'còn' },
{ hanzi: '发生', pinyin: 'fā shēng', meaning: 'xảy ra' },
{ hanzi: '发展', pinyin: 'fā zhǎn', meaning: 'phát triển' },
{ hanzi: '法律', pinyin: 'fǎ lǜ', meaning: 'pháp luật' },
{ hanzi: '翻译', pinyin: 'fān yì', meaning: 'phiên dịch' },
{ hanzi: '烦恼', pinyin: 'fán nǎo', meaning: 'phiền não' },
{ hanzi: '反对', pinyin: 'fǎn duì', meaning: 'phản đối' },
{ hanzi: '方法', pinyin: 'fāng fǎ', meaning: 'phương pháp' },
{ hanzi: '方面', pinyin: 'fāng miàn', meaning: 'phương diện' },
{ hanzi: '方向', pinyin: 'fāng xiàng', meaning: 'phương hướng' },
{ hanzi: '房东', pinyin: 'fáng dōng', meaning: 'chủ nhà' },
{ hanzi: '放弃', pinyin: 'fàng qì', meaning: 'vứt bỏ, từ bỏ' },
{ hanzi: '放暑假', pinyin: 'fàng shǔ jià', meaning: 'nghỉ hè' },
{ hanzi: '放松', pinyin: 'fàng sōng', meaning: 'thư giãn' },
{ hanzi: '份', pinyin: 'fèn', meaning: 'phần' },
{ hanzi: '丰富', pinyin: 'fēng fù', meaning: 'phong phú' },
{ hanzi: '否则', pinyin: 'fǒu zé', meaning: 'nếu không thì' },
{ hanzi: '符合', pinyin: 'fú hé', meaning: 'phù hợp' },
{ hanzi: '父亲', pinyin: 'fù qīn', meaning: 'bố' },
{ hanzi: '付款', pinyin: 'fù kuǎn', meaning: 'thanh toán' },
{ hanzi: '负责', pinyin: 'fù zé', meaning: 'phụ trách' },
{ hanzi: '复印', pinyin: 'fù yìn', meaning: 'phô tô' },
{ hanzi: '复杂', pinyin: 'fù zá', meaning: 'phức tạp' },
{ hanzi: '富', pinyin: 'fù', meaning: 'giàu' },
{ hanzi: '改变', pinyin: 'gǎi biàn', meaning: 'thay đổi' },
{ hanzi: '干杯', pinyin: 'gān bēi', meaning: 'cạn ly' },
{ hanzi: '赶', pinyin: 'gǎn', meaning: 'đuổi theo' },
{ hanzi: '敢', pinyin: 'gǎn', meaning: 'dám' },
{ hanzi: '感动', pinyin: 'gǎn dòng', meaning: 'cảm động' },
{ hanzi: '感觉', pinyin: 'gǎn jué', meaning: 'cảm giác' },
{ hanzi: '感情', pinyin: 'gǎn qíng', meaning: 'tình cảm' },
{ hanzi: '感谢', pinyin: 'gǎn xiè', meaning: 'cảm ơn' },
{ hanzi: '干', pinyin: 'gān', meaning: 'khô' },
{ hanzi: '刚', pinyin: 'gāng', meaning: 'vừa mới' },
{ hanzi: '高速公路', pinyin: 'gāo sù gōng lù', meaning: 'đường cao tốc' },
{ hanzi: '胳膊', pinyin: 'gē bo', meaning: 'cánh tay' },
{ hanzi: '各', pinyin: 'gè', meaning: 'các' },
{ hanzi: '工资', pinyin: 'gōng zī', meaning: 'lương' },
{ hanzi: '公里', pinyin: 'gōng lǐ', meaning: 'km' },
{ hanzi: '功夫', pinyin: 'gōng fū', meaning: 'công phu' },
{ hanzi: '共同', pinyin: 'gòng tóng', meaning: 'giống nhau' },
{ hanzi: '购物', pinyin: 'gòu wù', meaning: 'mua sắm' },
{ hanzi: '够', pinyin: 'gòu', meaning: 'đủ' },
{ hanzi: '估计', pinyin: 'gū jì', meaning: 'ước lượng' },
{ hanzi: '鼓励', pinyin: 'gǔ lì', meaning: 'cổ vũ' },
{ hanzi: '故意', pinyin: 'gù yì', meaning: 'cố ý' },
{ hanzi: '顾客', pinyin: 'gù kè', meaning: 'khách hàng' },
{ hanzi: '挂', pinyin: 'guà', meaning: 'treo, ngắt điện thoại' },
{ hanzi: '关键', pinyin: 'guān jiàn', meaning: 'mấu chốt' },
{ hanzi: '观众', pinyin: 'guān zhòng', meaning: 'khán giả' },
{ hanzi: '管理', pinyin: 'guǎn lǐ', meaning: 'quản lý' },
{ hanzi: '光', pinyin: 'guāng', meaning: 'chỉ, hết' },
{ hanzi: '广播', pinyin: 'guǎng bō', meaning: 'phát thanh' },
{ hanzi: '广告', pinyin: 'guǎng gào', meaning: 'quảng cáo' },
{ hanzi: '逛', pinyin: 'guàng', meaning: 'đi dạo' },
{ hanzi: '规定', pinyin: 'guī dìng', meaning: 'qui định' },
{ hanzi: '国籍', pinyin: 'guó jí', meaning: 'quốc tịch' },
{ hanzi: '国际', pinyin: 'guó jì', meaning: 'quốc tế' },
{ hanzi: '果汁', pinyin: 'guǒ zhī', meaning: 'nước hoa quả' },
{ hanzi: '过程', pinyin: 'guò chéng', meaning: 'quá trình' },
{ hanzi: '海洋', pinyin: 'hǎi yáng', meaning: 'đại dương' },
{ hanzi: '害羞', pinyin: 'hài xiū', meaning: 'xấu hổ' },
{ hanzi: '寒假', pinyin: 'hán jià', meaning: 'kì nghỉ đông' },
{ hanzi: '汗', pinyin: 'hàn', meaning: 'mồ hôi' },
{ hanzi: '航班', pinyin: 'háng bān', meaning: 'chuyến bay' },
{ hanzi: '好处', pinyin: 'hǎo chù', meaning: 'cái tốt' },
{ hanzi: '好像', pinyin: 'hǎo xiàng', meaning: 'dường như' },
{ hanzi: '号码', pinyin: 'hào mǎ', meaning: 'số' },
{ hanzi: '合格', pinyin: 'hé gé', meaning: 'đạt yêu cầu' },
{ hanzi: '合适', pinyin: 'hé shì', meaning: 'thích hợp' },
{ hanzi: '盒子', pinyin: 'hé zi', meaning: 'cái hộp' },
{ hanzi: '后悔', pinyin: 'hòu huǐ', meaning: 'hối hận' },
{ hanzi: '厚', pinyin: 'hòu', meaning: 'dày' },
{ hanzi: '互联网', pinyin: 'hù lián wǎng', meaning: 'mạng internet' },
{ hanzi: '互相', pinyin: 'hù xiāng', meaning: 'lẫn nhau' },
{ hanzi: '护士', pinyin: 'hù shì', meaning: 'y tá' },
{ hanzi: '怀疑', pinyin: 'huái yí', meaning: 'nghi ngờ' },
{ hanzi: '回忆', pinyin: 'huí yì', meaning: 'hồi ức, nhớ lại' },
{ hanzi: '活动', pinyin: 'huó dòng', meaning: 'hoạt động' },
{ hanzi: '活泼', pinyin: 'huó pō', meaning: 'hoạt bát' },
{ hanzi: '火', pinyin: 'huǒ', meaning: 'lửa' },
{ hanzi: '获得', pinyin: 'huò dé', meaning: 'giành được' },
{ hanzi: '积极', pinyin: 'jī jí', meaning: 'tích cực' },
{ hanzi: '积累', pinyin: 'jī lěi', meaning: 'tích lũy' },
{ hanzi: '基础', pinyin: 'jī chǔ', meaning: 'cơ sở, căn bản' },
{ hanzi: '激动', pinyin: 'jī dòng', meaning: 'xúc động' },
{ hanzi: '及时', pinyin: 'jí shí', meaning: 'kịp thời' },
{ hanzi: '即使', pinyin: 'jí shǐ', meaning: 'cho dù' },
{ hanzi: '计划', pinyin: 'jì huà', meaning: 'kế hoạch' },
{ hanzi: '记者', pinyin: 'jì zhě', meaning: 'phóng viên' },
{ hanzi: '技术', pinyin: 'jì shù', meaning: 'kỹ thuật' },
{ hanzi: '既然', pinyin: 'jì rán', meaning: 'đã….' },
{ hanzi: '继续', pinyin: 'jì xù', meaning: 'tiếp tục' },
{ hanzi: '寄', pinyin: 'jì', meaning: 'gửi' },
{ hanzi: '加班', pinyin: 'jiā bān', meaning: 'tăng ca' },
{ hanzi: '加油站', pinyin: 'jiā yóu zhàn', meaning: 'cây xăng' },
{ hanzi: '家具', pinyin: 'jiā jù', meaning: 'đồ gia dụng' },
{ hanzi: '假', pinyin: 'jiǎ', meaning: 'giả' },
{ hanzi: '价格', pinyin: 'jià gé', meaning: 'giá cả' },
{ hanzi: '坚持', pinyin: 'jiān chí', meaning: 'kiên trì' },
{ hanzi: '减肥', pinyin: 'jiǎn féi', meaning: 'giảm béo' },
{ hanzi: '减少', pinyin: 'jiǎn shǎo', meaning: 'cắt giảm' },
{ hanzi: '建议', pinyin: 'jiàn yì', meaning: 'kiến nghị' },
{ hanzi: '将来', pinyin: 'jiāng lái', meaning: 'tương lai' },
{ hanzi: '奖金', pinyin: 'jiǎng jīn', meaning: 'học bổng' },
{ hanzi: '降低', pinyin: 'jiàng dī', meaning: 'hạ thấp' },
{ hanzi: '降落', pinyin: 'jiàng luò', meaning: 'hạ cánh' },
{ hanzi: '交', pinyin: 'jiāo', meaning: 'giao' },
{ hanzi: '交流', pinyin: 'jiāo liú', meaning: 'giao lưu' },
{ hanzi: '交通', pinyin: 'jiāo tōng', meaning: 'giao thông' },
{ hanzi: '郊区', pinyin: 'jiāo qū', meaning: 'ngoại ô' },
{ hanzi: '骄傲', pinyin: 'jiāo ào', meaning: 'tự hào, kiêu ngạo' },
{ hanzi: '饺子', pinyin: 'jiǎo zi', meaning: 'sủi cảo' },
{ hanzi: '教授', pinyin: 'jiào shòu', meaning: 'giáo sư' },
{ hanzi: '教育', pinyin: 'jiào yù', meaning: 'giáo dục' },
{ hanzi: '接受', pinyin: 'jiē shòu', meaning: 'tiếp nhận' },
{ hanzi: '接着', pinyin: 'jiē zhe', meaning: 'tiếp theo' },
{ hanzi: '节', pinyin: 'jié', meaning: 'tiết' },
{ hanzi: '节约', pinyin: 'jié yuē', meaning: 'tiết kiệm' },
{ hanzi: '结果', pinyin: 'jié guǒ', meaning: 'kết quả' },
{ hanzi: '解释', pinyin: 'jiě shì', meaning: 'giải thích' },
{ hanzi: '尽管', pinyin: 'jǐn guǎn', meaning: 'tuy rằng' },
{ hanzi: '紧张', pinyin: 'jǐn zhāng', meaning: 'căng thẳng' },
{ hanzi: '进行', pinyin: 'jìn xíng', meaning: 'tiến hành' },
{ hanzi: '禁止', pinyin: 'jìn zhǐ', meaning: 'cấm' },
{ hanzi: '京剧', pinyin: 'jīng jù', meaning: 'kinh kịch' },
{ hanzi: '经济', pinyin: 'jīng jì', meaning: 'kinh tế' },
{ hanzi: '经历', pinyin: 'jīng lì', meaning: 'trải qua, kinh qua' },
{ hanzi: '经验', pinyin: 'jīng yàn', meaning: 'kinh nghiệm' },
{ hanzi: '精彩', pinyin: 'jīng cǎi', meaning: 'hấp dẫn' },
{ hanzi: '景色', pinyin: 'jǐng sè', meaning: 'cảnh sắc' },
{ hanzi: '警察', pinyin: 'jǐng chá', meaning: 'cảnh sát' },
{ hanzi: '竞争', pinyin: 'jìng zhēng', meaning: 'cạnh tranh' },
{ hanzi: '竟然', pinyin: 'jìng rán', meaning: 'vậy mà lại' },
{ hanzi: '镜子', pinyin: 'jìng zi', meaning: 'kính, gương' },
{ hanzi: '究竟', pinyin: 'jiū jìng', meaning: 'rốt cuộc' },
{ hanzi: '举', pinyin: 'jǔ', meaning: 'giơ, nâng' },
{ hanzi: '举办', pinyin: 'jǔ bàn', meaning: 'tổ chức' },
{ hanzi: '举行', pinyin: 'jǔ xíng', meaning: 'tổ chức' },
{ hanzi: '拒绝', pinyin: 'jù jué', meaning: 'từ chối' },
{ hanzi: '距离', pinyin: 'jù lí', meaning: 'khoảng cách' },
{ hanzi: '聚会', pinyin: 'jù huì', meaning: 'tụ tập' },
{ hanzi: '开玩笑', pinyin: 'kāi wán xiào', meaning: 'đùa' },
{ hanzi: '开心', pinyin: 'kāi xīn', meaning: 'vui vẻ' },
{ hanzi: '看法', pinyin: 'kàn fǎ', meaning: 'quan điểm' },
{ hanzi: '考虑', pinyin: 'kǎo lǜ', meaning: 'suy nghĩ' },
{ hanzi: '烤鸭', pinyin: 'kǎo yā', meaning: 'vịt quay' },
{ hanzi: '科学', pinyin: 'kē xué', meaning: 'khoa học' },
{ hanzi: '棵', pinyin: 'kē', meaning: 'lượng từ cho cây' },
{ hanzi: '咳嗽', pinyin: 'ké sou', meaning: 'ho' },
{ hanzi: '可怜', pinyin: 'kě lián', meaning: 'đáng thương' },
{ hanzi: '可是', pinyin: 'kě shì', meaning: 'nhưng' },
{ hanzi: '可惜', pinyin: 'kě xī', meaning: 'đáng tiếc' },
{ hanzi: '客厅', pinyin: 'kè tīng', meaning: 'phòng khách' },
{ hanzi: '肯定', pinyin: 'kěn dìng', meaning: 'khẳng định' },
{ hanzi: '空', pinyin: 'kōng', meaning: 'trống rỗng' },
{ hanzi: '空气', pinyin: 'kōng qì', meaning: 'không khí' },
{ hanzi: '恐怕', pinyin: 'kǒng pà', meaning: 'e rằng' },
{ hanzi: '苦', pinyin: 'kǔ', meaning: 'khổ, đắng' },
{ hanzi: '矿泉水', pinyin: 'kuàng quán shuǐ', meaning: 'nước khoáng' },
{ hanzi: '困', pinyin: 'kùn', meaning: 'buồn ngủ' },
{ hanzi: '困难', pinyin: 'kùn nán', meaning: 'khó khăn' },
{ hanzi: '垃圾桶', pinyin: 'lā jī tǒng', meaning: 'thùng rác' },
{ hanzi: '拉', pinyin: 'lā', meaning: 'kéo' },
{ hanzi: '辣', pinyin: 'là', meaning: 'cay' },
{ hanzi: '来不及', pinyin: 'lái bù jí', meaning: 'không kịp' },
{ hanzi: '来得及', pinyin: 'lái de jí', meaning: 'kịp' },
{ hanzi: '来自', pinyin: 'lái zì', meaning: 'đến từ' },
{ hanzi: '懒', pinyin: 'lǎn', meaning: 'lười biếng' },
{ hanzi: '浪费', pinyin: 'làng fèi', meaning: 'lãng phí' },
{ hanzi: '浪漫', pinyin: 'làng màn', meaning: 'lãng mạn' },
{ hanzi: '老虎', pinyin: 'lǎo hǔ', meaning: 'hổ' },
{ hanzi: '冷静', pinyin: 'lěng jìng', meaning: 'bình tĩnh' },
{ hanzi: '礼拜天', pinyin: 'lǐ bài tiān', meaning: 'chủ nhật' },
{ hanzi: '礼貌', pinyin: 'lǐ mào', meaning: 'lễ phép, lịch sự' },
{ hanzi: '理发', pinyin: 'lǐ fà', meaning: 'cắt tóc' },
{ hanzi: '理解', pinyin: 'lǐ jiě', meaning: 'lý giải, hiểu' },
{ hanzi: '理想', pinyin: 'lǐ xiǎng', meaning: 'lý tưởng' },
{ hanzi: '力气', pinyin: 'lì qì', meaning: 'sức lực' },
{ hanzi: '厉害', pinyin: 'lì hài', meaning: 'lợi hại' },
{ hanzi: '例如', pinyin: 'lì rú', meaning: 'ví dụ' },
{ hanzi: '俩', pinyin: 'liǎ', meaning: 'hai người' },
{ hanzi: '连', pinyin: 'lián', meaning: 'liên kết, nối' },
{ hanzi: '联系', pinyin: 'lián xì', meaning: 'liên hệ' },
{ hanzi: '凉快', pinyin: 'liáng kuài', meaning: 'mát mẻ' },
{ hanzi: '零钱', pinyin: 'líng qián', meaning: 'tiền lẻ' },
{ hanzi: '另外', pinyin: 'lìng wài', meaning: 'ngoài ra, còn lại' },
{ hanzi: '留', pinyin: 'liú', meaning: 'lưu lại, ở lại' },
{ hanzi: '流利', pinyin: 'liú lì', meaning: 'lưu loát' },
{ hanzi: '流行', pinyin: 'liú xíng', meaning: 'thịnh hành' },
{ hanzi: '旅行', pinyin: 'lǚ xíng', meaning: 'du lịch' },
{ hanzi: '律师', pinyin: 'lǜ shī', meaning: 'luật sư' },
{ hanzi: '乱', pinyin: 'luàn', meaning: 'loạn' },
{ hanzi: '麻烦', pinyin: 'má fan', meaning: 'phiền phức, làm phiền' },
{ hanzi: '马虎', pinyin: 'mǎ hu', meaning: 'qua loa' },
{ hanzi: '满', pinyin: 'mǎn', meaning: 'đầy' },
{ hanzi: '毛', pinyin: 'máo', meaning: 'lông' },
{ hanzi: '毛巾', pinyin: 'máo jīn', meaning: 'khăn bông' },
{ hanzi: '美丽', pinyin: 'měi lì', meaning: 'đẹp' },
{ hanzi: '梦', pinyin: 'mèng', meaning: 'giấc mơ, mơ' },
{ hanzi: '迷路', pinyin: 'mí lù', meaning: 'lạc đường' },
{ hanzi: '密码', pinyin: 'mì mǎ', meaning: 'mật khẩu' },
{ hanzi: '免费', pinyin: 'miǎn fèi', meaning: 'miễn phí' },
{ hanzi: '秒', pinyin: 'miǎo', meaning: 'giây' },
{ hanzi: '民族', pinyin: 'mín zú', meaning: 'dân tộc' },
{ hanzi: '母亲', pinyin: 'mǔ qin', meaning: 'mẹ' },
{ hanzi: '目的', pinyin: 'mù dì', meaning: 'mục đích' },
{ hanzi: '耐心', pinyin: 'nài xīn', meaning: 'nhẫn nại' },
{ hanzi: '难道', pinyin: 'nán dào', meaning: 'lẽ nào' },
{ hanzi: '难受', pinyin: 'nán shòu', meaning: 'buồn' },
{ hanzi: '内', pinyin: 'nèi', meaning: 'bên trong' },
{ hanzi: '内容', pinyin: 'nèi róng', meaning: 'nội dung' },
{ hanzi: '能力', pinyin: 'néng lì', meaning: 'năng lực' },
{ hanzi: '年龄', pinyin: 'nián líng', meaning: 'tuổi tác' },
{ hanzi: '弄', pinyin: 'nòng', meaning: 'làm' },
{ hanzi: '暖和', pinyin: 'nuǎn huo', meaning: 'ấm áp' },
{ hanzi: '偶尔', pinyin: 'ǒu ěr', meaning: 'đôi khi' },
{ hanzi: '排队', pinyin: 'pái duì', meaning: 'xếp hàng' },
{ hanzi: '排列', pinyin: 'pái liè', meaning: 'sắp xếp, xếp' },
{ hanzi: '判断', pinyin: 'pàn duàn', meaning: 'phán đoán' },
{ hanzi: '陪', pinyin: 'péi', meaning: 'cùng' },
{ hanzi: '批评', pinyin: 'pī píng', meaning: 'phê bình' },
{ hanzi: '皮肤', pinyin: 'pí fū', meaning: 'da' },
{ hanzi: '脾气', pinyin: 'pí qì', meaning: 'tính khí' },
{ hanzi: '篇', pinyin: 'piān', meaning: 'lượng từ cho bài viết' },
{ hanzi: '骗', pinyin: 'piàn', meaning: 'lừa' },
{ hanzi: '乒乓球', pinyin: 'pīng pāng qiú', meaning: 'bóng bàn' },
{ hanzi: '平时', pinyin: 'píng shí', meaning: 'bình thường' },
{ hanzi: '破', pinyin: 'pò', meaning: 'rách, nổ' },
{ hanzi: '葡萄', pinyin: 'pú táo', meaning: 'nho' },
{ hanzi: '普遍', pinyin: 'pǔ biàn', meaning: 'phổ biến' },
{ hanzi: '普通话', pinyin: 'pǔ tōng huà', meaning: 'tiếng phổ thông' },
{ hanzi: '其次', pinyin: 'qí cì', meaning: 'tiếp theo' },
{ hanzi: '其中', pinyin: 'qí zhōng', meaning: 'trong đó' },
{ hanzi: '气候', pinyin: 'qì hòu', meaning: 'khí hậu' },
{ hanzi: '千万', pinyin: 'qiān wàn', meaning: 'nhất thiết' },
{ hanzi: '签证', pinyin: 'qiān zhèng', meaning: 'visa' },
{ hanzi: '敲', pinyin: 'qiāo', meaning: 'gõ' },
{ hanzi: '桥', pinyin: 'qiáo', meaning: 'cầu' },
{ hanzi: '巧克力', pinyin: 'qiǎo kè lì', meaning: 'sô cô la' },
{ hanzi: '亲戚', pinyin: 'qīn qi', meaning: 'họ hàng' },
{ hanzi: '轻', pinyin: 'qīng', meaning: 'nhẹ' },
{ hanzi: '轻松', pinyin: 'qīng sōng', meaning: 'thoải mái' },
{ hanzi: '情况', pinyin: 'qíng kuàng', meaning: 'tình hình' },
{ hanzi: '穷', pinyin: 'qióng', meaning: 'nghèo' },
{ hanzi: '区别', pinyin: 'qū bié', meaning: 'khác biệt' },
{ hanzi: '取', pinyin: 'qǔ', meaning: 'lấy' },
{ hanzi: '全部', pinyin: 'quán bù', meaning: 'toàn bộ' },
{ hanzi: '缺点', pinyin: 'quē diǎn', meaning: 'khuyết điểm' },
{ hanzi: '缺少', pinyin: 'quē shǎo', meaning: 'thiếu' },
{ hanzi: '却', pinyin: 'què', meaning: 'lại, nhưng' },
{ hanzi: '确实', pinyin: 'què shí', meaning: 'thật sự' },
{ hanzi: '然而', pinyin: 'rán ér', meaning: 'vậy mà' },
{ hanzi: '热闹', pinyin: 'rè nào', meaning: 'náo nhiệt' },
{ hanzi: '任何', pinyin: 'rèn hé', meaning: 'bất kì' },
{ hanzi: '任务', pinyin: 'rèn wù', meaning: 'nhiệm vụ' },
{ hanzi: '扔', pinyin: 'rēng', meaning: 'ném' },
{ hanzi: '仍然', pinyin: 'réng rán', meaning: 'vẫn' },
{ hanzi: '日记', pinyin: 'rì jì', meaning: 'nhật kí' },
{ hanzi: '入口', pinyin: 'rù kǒu', meaning: 'cửa vào' },
{ hanzi: '散步', pinyin: 'sàn bù', meaning: 'tản bộ' },
{ hanzi: '森林', pinyin: 'sēn lín', meaning: 'rừng sâu' },
{ hanzi: '沙发', pinyin: 'shā fā', meaning: 'ghế sô pha' },
{ hanzi: '伤心', pinyin: 'shāng xīn', meaning: 'tổn thương' },
{ hanzi: '商量', pinyin: 'shāng liáng', meaning: 'thương lượng, bàn bạc' },
{ hanzi: '稍微', pinyin: 'shāo wēi', meaning: 'một chút' },
{ hanzi: '勺子', pinyin: 'sháo zi', meaning: 'cái thìa' },
{ hanzi: '社会', pinyin: 'shè huì', meaning: 'xã hội' },
{ hanzi: '申请', pinyin: 'shēn qǐng', meaning: 'xin' },
{ hanzi: '深', pinyin: 'shēn', meaning: 'sâu' },
{ hanzi: '甚至', pinyin: 'shèn zhì', meaning: 'thậm chí' },
{ hanzi: '生活', pinyin: 'shēng huó', meaning: 'cuộc sống' },
{ hanzi: '生命', pinyin: 'shēng mìng', meaning: 'tính mạng' },
{ hanzi: '生意', pinyin: 'shēng yì', meaning: 'kinh doanh' },
{ hanzi: '省', pinyin: 'shěng', meaning: 'tỉnh thành' },
{ hanzi: '剩', pinyin: 'shèng', meaning: 'thừa' },
{ hanzi: '失败', pinyin: 'shī bài', meaning: 'thất bại' },
{ hanzi: '失望', pinyin: 'shī wàng', meaning: 'thất vọng' },
{ hanzi: '师傅', pinyin: 'shī fù', meaning: 'sư phụ' },
{ hanzi: '十分', pinyin: 'shí fēn', meaning: 'vô cùng' },
{ hanzi: '实际', pinyin: 'shí jì', meaning: 'thực tế' },
{ hanzi: '实在', pinyin: 'shí zài', meaning: 'thật sự' },
{ hanzi: '使', pinyin: 'shǐ', meaning: 'khiến cho' },
{ hanzi: '使用', pinyin: 'shǐ yòng', meaning: 'sử dụng' },
{ hanzi: '世纪', pinyin: 'shì jì', meaning: 'thế kỉ' },
{ hanzi: '是否', pinyin: 'shì fǒu', meaning: 'liệu có phải' },
{ hanzi: '适合', pinyin: 'shì hé', meaning: 'thích hợp' },
{ hanzi: '适应', pinyin: 'shì yìng', meaning: 'thích nghi' },
{ hanzi: '收', pinyin: 'shōu', meaning: 'nhận' },
{ hanzi: '收入', pinyin: 'shōu rù', meaning: 'thu nhập' },
{ hanzi: '收拾', pinyin: 'shōu shí', meaning: 'dọn dẹp' },
{ hanzi: '首都', pinyin: 'shǒu dū', meaning: 'thủ đô' },
{ hanzi: '首先', pinyin: 'shǒu xiān', meaning: 'đầu tiên' },
{ hanzi: '受不了', pinyin: 'shòu bù liǎo', meaning: 'không chịu nổi' },
{ hanzi: '受到', pinyin: 'shòu dào', meaning: 'nhận được' },
{ hanzi: '售货员', pinyin: 'shòu huò yuán', meaning: 'nhân viên bán vé' },
{ hanzi: '输', pinyin: 'shū', meaning: 'thua' },
{ hanzi: '熟悉', pinyin: 'shú xī', meaning: 'quen thuộc' },
{ hanzi: '数量', pinyin: 'shù liàng', meaning: 'số lượng' },
{ hanzi: '数字', pinyin: 'shù zi', meaning: 'con cố' },
{ hanzi: '帅', pinyin: 'shuài', meaning: 'đẹp trai' },
{ hanzi: '顺便', pinyin: 'shùn biàn', meaning: 'nhân tiện' },
{ hanzi: '顺利', pinyin: 'shùn lì', meaning: 'thuận lợi' },
{ hanzi: '顺序', pinyin: 'shùn xù', meaning: 'thứ tự' },
{ hanzi: '说明', pinyin: 'shuō míng', meaning: 'nói rõ' },
{ hanzi: '硕士', pinyin: 'shuò shì', meaning: 'thạc sĩ' },
{ hanzi: '死', pinyin: 'sǐ', meaning: 'chết' },
{ hanzi: '速度', pinyin: 'sù dù', meaning: 'tốc độ' },
{ hanzi: '塑料袋', pinyin: 'sù liào dài', meaning: 'túi ni lông' },
{ hanzi: '酸', pinyin: 'suān', meaning: 'chua' },
{ hanzi: '随便', pinyin: 'suí biàn', meaning: 'tùy tiện, tự nhiên' },
{ hanzi: '随着', pinyin: 'suí zhe', meaning: 'cùng với' },
{ hanzi: '孙子', pinyin: 'sūn zi', meaning: 'cháu trai' },
{ hanzi: '所有', pinyin: 'suǒ yǒu', meaning: 'tất cả' },
{ hanzi: '台', pinyin: 'tái', meaning: 'cái, chiếc' },
{ hanzi: '抬', pinyin: 'tái', meaning: 'ngẩng' },
{ hanzi: '态度', pinyin: 'tài dù', meaning: 'thái độ' },
{ hanzi: '谈', pinyin: 'tán', meaning: 'nói chuyện' },
{ hanzi: '弹钢琴', pinyin: 'tán gāng qín', meaning: 'chơi piano' },
{ hanzi: '汤', pinyin: 'tāng', meaning: 'canh' },
{ hanzi: '糖', pinyin: 'táng', meaning: 'đường' },
{ hanzi: '躺', pinyin: 'tǎng', meaning: 'nằm' },
{ hanzi: '趟', pinyin: 'tàng', meaning: 'chuyến' },
{ hanzi: '讨论', pinyin: 'tǎo lùn', meaning: 'thảo luận' },
{ hanzi: '讨厌', pinyin: 'tǎo yàn', meaning: 'ghét' },
{ hanzi: '特点', pinyin: 'tè diǎn', meaning: 'đặc điểm' },
{ hanzi: '提', pinyin: 'tí', meaning: 'đề ra' },
{ hanzi: '提供', pinyin: 'tí gōng', meaning: 'cung cấp' },
{ hanzi: '提前', pinyin: 'tí qián', meaning: 'trước thời hạn' },
{ hanzi: '提醒', pinyin: 'tí xǐng', meaning: 'nhắc nhở' },
{ hanzi: '填空', pinyin: 'tián kòng', meaning: 'điền trống' },
{ hanzi: '条件', pinyin: 'tiáo jiàn', meaning: 'điều kiện' },
{ hanzi: '停', pinyin: 'tíng', meaning: 'dừng' },
{ hanzi: '挺', pinyin: 'tǐng', meaning: 'rất' },
{ hanzi: '通过', pinyin: 'tōng guò', meaning: 'thông qua' },
{ hanzi: '通知', pinyin: 'tōng zhī', meaning: 'thông báo' },
{ hanzi: '同情', pinyin: 'tóng qíng', meaning: 'đồng tình' },
{ hanzi: '同时', pinyin: 'tóng shí', meaning: 'đồng thời' },
{ hanzi: '推', pinyin: 'tuī', meaning: 'đẩy' },
{ hanzi: '推迟', pinyin: 'tuī chí', meaning: 'kéo dài thời gian' },
{ hanzi: '脱', pinyin: 'tuō', meaning: 'cởi' },
{ hanzi: '袜子', pinyin: 'wà zi', meaning: 'tất chân' },
{ hanzi: '完全', pinyin: 'wán quán', meaning: 'hoàn toàn' },
{ hanzi: '网球', pinyin: 'wǎng qiú', meaning: 'tennis' },
{ hanzi: '网站', pinyin: 'wǎng zhàn', meaning: 'trang mạng' },
{ hanzi: '往往', pinyin: 'wǎng wǎng', meaning: 'thường (quá khứ)' },
{ hanzi: '危险', pinyin: 'wēi xiǎn', meaning: 'nguy hiểm' },
{ hanzi: '卫生间', pinyin: 'wèi shēng jiān', meaning: 'phòng vệ sinh' },
{ hanzi: '味道', pinyin: 'wèi dào', meaning: 'mùi vị' },
{ hanzi: '温度', pinyin: 'wēn dù', meaning: 'nhiệt độ' },
{ hanzi: '文章', pinyin: 'wén zhāng', meaning: 'bài văn' },
{ hanzi: '污染', pinyin: 'wū rǎn', meaning: 'ô nhiễm' },
{ hanzi: '无', pinyin: 'wú', meaning: 'không' },
{ hanzi: '无聊', pinyin: 'wú liáo', meaning: 'nhàm chán' },
{ hanzi: '无论', pinyin: 'wú lùn', meaning: 'bất luận' },
{ hanzi: '误会', pinyin: 'wù huì', meaning: 'hiểu lầm' },
{ hanzi: '西红柿', pinyin: 'xī hóng shì', meaning: 'cà chua' },
{ hanzi: '吸引', pinyin: 'xī yǐn', meaning: 'thu hút' },
{ hanzi: '咸', pinyin: 'xián', meaning: 'mặn' },
{ hanzi: '现金', pinyin: 'xiàn jīn', meaning: 'tiền mặt' },
{ hanzi: '羡慕', pinyin: 'xiàn mù', meaning: 'ngưỡng mộ' },
{ hanzi: '相反', pinyin: 'xiāng fǎn', meaning: 'ngược lại' },
{ hanzi: '相同', pinyin: 'xiāng tóng', meaning: 'giống nhau' },
{ hanzi: '香', pinyin: 'xiāng', meaning: 'thơm' },
{ hanzi: '详细', pinyin: 'xiáng xì', meaning: 'tỉ mỉ' },
{ hanzi: '响', pinyin: 'xiǎng', meaning: 'kêu' },
{ hanzi: '橡皮', pinyin: 'xiàng pí', meaning: 'cục tẩy' },
{ hanzi: '消息', pinyin: 'xiāo xi', meaning: 'thông tin, tin' },
{ hanzi: '小吃', pinyin: 'xiǎo chī', meaning: 'đồ ăn vặt' },
{ hanzi: '小伙子', pinyin: 'xiǎo huǒ zi', meaning: 'anh chàng' },
{ hanzi: '小说', pinyin: 'xiǎo shuō', meaning: 'tiểu thuyết' },
{ hanzi: '笑话', pinyin: 'xiào huà', meaning: 'truyện cười' },
{ hanzi: '效果', pinyin: 'xiào guǒ', meaning: 'hiệu quả' },
{ hanzi: '心情', pinyin: 'xīn qíng', meaning: 'tâm trạng' },
{ hanzi: '辛苦', pinyin: 'xīn kǔ', meaning: 'vất vả' },
{ hanzi: '信封', pinyin: 'xìn fēng', meaning: 'bức thư' },
{ hanzi: '信息', pinyin: 'xìn xī', meaning: 'thông tin' },
{ hanzi: '信心', pinyin: 'xìn xīn', meaning: 'niềm tin' },
{ hanzi: '兴奋', pinyin: 'xīng fèn', meaning: 'hưng phấn, hứng khởi' },
{ hanzi: '行', pinyin: 'xíng', meaning: 'được' },
{ hanzi: '醒', pinyin: 'xǐng', meaning: 'tỉnh' },
{ hanzi: '幸福', pinyin: 'xìng fú', meaning: 'hạnh phúc' },
{ hanzi: '性别', pinyin: 'xìng bié', meaning: 'giới tính' },
{ hanzi: '性格', pinyin: 'xìng gé', meaning: 'tính cách' },
{ hanzi: '修理', pinyin: 'xiū lǐ', meaning: 'sửa chữa' },
{ hanzi: '许多', pinyin: 'xǔ duō', meaning: 'rất nhiều' },
{ hanzi: '学期', pinyin: 'xué qī', meaning: 'học kì' },
{ hanzi: '压力', pinyin: 'yā lì', meaning: 'áp lực' },
{ hanzi: '呀', pinyin: 'yā', meaning: 'a' },
{ hanzi: '牙膏', pinyin: 'yá gāo', meaning: 'kem đánh răng' },
{ hanzi: '亚洲', pinyin: 'yà zhōu', meaning: 'châu Á' },
{ hanzi: '严格', pinyin: 'yán gé', meaning: 'nghiêm khắc' },
{ hanzi: '严重', pinyin: 'yán zhòng', meaning: 'nghiêm trọng' },
{ hanzi: '研究', pinyin: 'yán jiū', meaning: 'nghiên cứu' },
{ hanzi: '盐', pinyin: 'yán', meaning: 'muối' },
{ hanzi: '眼镜', pinyin: 'yǎn jìng', meaning: 'kính mắt' },
{ hanzi: '演出', pinyin: 'yǎn chū', meaning: 'buổi diễn' },
{ hanzi: '演员', pinyin: 'yǎn yuán', meaning: 'diễn viên' },
{ hanzi: '阳光', pinyin: 'yáng guāng', meaning: 'ánh nắng' },
{ hanzi: '养成', pinyin: 'yǎng chéng', meaning: 'nuôi dưỡng, hình thành' },
{ hanzi: '样子', pinyin: 'yàng zi', meaning: 'kiểu dáng, dáng vẻ' },
{ hanzi: '邀请', pinyin: 'yāo qǐng', meaning: 'mời' },
{ hanzi: '要是', pinyin: 'yào shì', meaning: 'nếu' },
{ hanzi: '钥匙', pinyin: 'yào shi', meaning: 'chìa khóa' },
{ hanzi: '也许', pinyin: 'yě xǔ', meaning: 'có lẽ' },
{ hanzi: '叶子', pinyin: 'yè zi', meaning: 'chiếc lá' },
{ hanzi: '页', pinyin: 'yè', meaning: 'trang mạng' },
{ hanzi: '一切', pinyin: 'yī qiè', meaning: 'tất cả' },
{ hanzi: '以', pinyin: 'yǐ', meaning: 'lấy, với' },
{ hanzi: '以为', pinyin: 'yǐ wéi', meaning: 'tưởng rằng' },
{ hanzi: '艺术', pinyin: 'yì shù', meaning: 'nghệ thuật' },
{ hanzi: '意见', pinyin: 'yì jiàn', meaning: 'ý kiến' },
{ hanzi: '因此', pinyin: 'yīn cǐ', meaning: 'cho nên' },
{ hanzi: '引起', pinyin: 'yǐn qǐ', meaning: 'dẫn đến, gây ra' },
{ hanzi: '印象', pinyin: 'yìn xiàng', meaning: 'ấn tượng' },
{ hanzi: '赢', pinyin: 'yíng', meaning: 'thắng' },
{ hanzi: '应聘', pinyin: 'yìng pìn', meaning: 'ứng tuyển' },
{ hanzi: '永远', pinyin: 'yǒng yuǎn', meaning: 'mãi mãi' },
{ hanzi: '勇敢', pinyin: 'yǒng gǎn', meaning: 'dũng cảm' },
{ hanzi: '优点', pinyin: 'yōu diǎn', meaning: 'ưu điểm' },
{ hanzi: '优秀', pinyin: 'yōu xiù', meaning: 'ưu tú' },
{ hanzi: '幽默', pinyin: 'yōu mò', meaning: 'hài hước' },
{ hanzi: '尤其', pinyin: 'yóu qí', meaning: 'đặc biệt là' },
{ hanzi: '由', pinyin: 'yóu', meaning: 'do' },
{ hanzi: '由于', pinyin: 'yóu yú', meaning: 'do' },
{ hanzi: '邮局', pinyin: 'yóu jú', meaning: 'bưu điện' },
{ hanzi: '友好', pinyin: 'yǒu hǎo', meaning: 'hữu hảo' },
{ hanzi: '友谊', pinyin: 'yǒu yì', meaning: 'hữu nghị' },
{ hanzi: '有趣', pinyin: 'yǒu qù', meaning: 'hứng thú' },
{ hanzi: '于是', pinyin: 'yú shì', meaning: 'thế là' },
{ hanzi: '愉快', pinyin: 'yú kuài', meaning: 'vui vẻ' },
{ hanzi: '与', pinyin: 'yǔ', meaning: 'và' },
{ hanzi: '羽毛球', pinyin: 'yǔ máo qiú', meaning: 'cầu lông' },
{ hanzi: '语法', pinyin: 'yǔ fǎ', meaning: 'ngữ pháp' },
{ hanzi: '语言', pinyin: 'yǔ yán', meaning: 'ngôn ngữ' },
{ hanzi: '预习', pinyin: 'yù xí', meaning: 'chuẩn bị trước' },
{ hanzi: '原来', pinyin: 'yuán lái', meaning: 'hóa ra, vốn, cũ' },
{ hanzi: '原谅', pinyin: 'yuán liàng', meaning: 'tha thứ' },
{ hanzi: '原因', pinyin: 'yuán yīn', meaning: 'nguyên nhân' },
{ hanzi: '约会', pinyin: 'yuē huì', meaning: 'hẹn, cuộc hẹn' },
{ hanzi: '阅读', pinyin: 'yuè dú', meaning: 'đọc hiểu' },
{ hanzi: '云', pinyin: 'yún', meaning: 'mây' },
{ hanzi: '允许', pinyin: 'yǔn xǔ', meaning: 'cho phép' },
{ hanzi: '杂志', pinyin: 'zá zhì', meaning: 'tạp chí' },
{ hanzi: '咱们', pinyin: 'zán men', meaning: 'chúng ta' },
{ hanzi: '暂时', pinyin: 'zàn shí', meaning: 'tạm thời' },
{ hanzi: '脏', pinyin: 'zāng', meaning: 'bẩn' },
{ hanzi: '责任', pinyin: 'zé rèn', meaning: 'trách nhiệm' },
{ hanzi: '增加', pinyin: 'zēng jiā', meaning: 'tăng thêm' },
{ hanzi: '占线', pinyin: 'zhàn xiàn', meaning: 'máy bận' },
{ hanzi: '招聘', pinyin: 'zhāo pìn', meaning: 'tuyển dụng' },
{ hanzi: '照', pinyin: 'zhào', meaning: 'chiếu, chụp' },
{ hanzi: '真正', pinyin: 'zhēn zhèng', meaning: 'thật' },
{ hanzi: '整理', pinyin: 'zhěng lǐ', meaning: 'chỉnh sửa' },
{ hanzi: '正常', pinyin: 'zhèng cháng', meaning: 'bình thường' },
{ hanzi: '正好', pinyin: 'zhèng hǎo', meaning: 'vừa hay' },
{ hanzi: '正确', pinyin: 'zhèng què', meaning: 'chính xác' },
{ hanzi: '正式', pinyin: 'zhèng shì', meaning: 'chính thức' },
{ hanzi: '证明', pinyin: 'zhèng míng', meaning: 'chứng minh' },
{ hanzi: '之', pinyin: 'zhī', meaning: 'của' },
{ hanzi: '支持', pinyin: 'zhī chí', meaning: 'ủng hộ' },
{ hanzi: '知识', pinyin: 'zhī shí', meaning: 'tri thức, kiến thức' },
{ hanzi: '直接', pinyin: 'zhí jiē', meaning: 'trực tiếp' },
{ hanzi: '值得', pinyin: 'zhí dé', meaning: 'đáng' },
{ hanzi: '职业', pinyin: 'zhí yè', meaning: 'nghề nghiệp' },
{ hanzi: '植物', pinyin: 'zhí wù', meaning: 'thực vật' },
{ hanzi: '只好', pinyin: 'zhǐ hǎo', meaning: 'đành' },
{ hanzi: '只要', pinyin: 'zhǐ yào', meaning: 'chỉ cần' },
{ hanzi: '指', pinyin: 'zhǐ', meaning: 'chỉ' },
{ hanzi: '至少', pinyin: 'zhì shǎo', meaning: 'chí ít' },
{ hanzi: '质量', pinyin: 'zhì liàng', meaning: 'chất lượng' },
{ hanzi: '重', pinyin: 'zhòng', meaning: 'nặng' },
{ hanzi: '重点', pinyin: 'zhòng diǎn', meaning: 'trọng điểm' },
{ hanzi: '重视', pinyin: 'zhòng shì', meaning: 'coi trọng' },
{ hanzi: '周围', pinyin: 'zhōu wéi', meaning: 'xung quanh' },
{ hanzi: '主意', pinyin: 'zhǔ yì', meaning: 'chủ ý' },
{ hanzi: '祝贺', pinyin: 'zhù hè', meaning: 'chúc mừng' },
{ hanzi: '著名', pinyin: 'zhù míng', meaning: 'nổi tiếng' },
{ hanzi: '专门', pinyin: 'zhuān mén', meaning: 'chuyên môn' },
{ hanzi: '专业', pinyin: 'zhuān yè', meaning: 'chuyên ngành' },
{ hanzi: '转', pinyin: 'zhuǎn', meaning: 'chuyển' },
{ hanzi: '赚', pinyin: 'zhuàn', meaning: 'kiếm' },
{ hanzi: '准确', pinyin: 'zhǔn què', meaning: 'chính xác' },
{ hanzi: '准时', pinyin: 'zhǔn shí', meaning: 'đúng giờ' },
{ hanzi: '仔细', pinyin: 'zǐ xì', meaning: 'cẩn thận' },
{ hanzi: '自然', pinyin: 'zì rán', meaning: 'tự nhiên' },
{ hanzi: '自信', pinyin: 'zì xìn', meaning: 'tự tin' },
{ hanzi: '总结', pinyin: 'zǒng jié', meaning: 'tổng kết' },
{ hanzi: '租', pinyin: 'zū', meaning: 'thuê' },
{ hanzi: '最好', pinyin: 'zuì hǎo', meaning: 'tốt nhất' },
{ hanzi: '尊重', pinyin: 'zūn zhòng', meaning: 'tôn trọng' },
{ hanzi: '左右', pinyin: 'zuǒ yòu', meaning: 'khoảng' },
{ hanzi: '作家', pinyin: 'zuò jiā', meaning: 'tác gia' },
{ hanzi: '作用', pinyin: 'zuò yòng', meaning: 'tác dụng' },
{ hanzi: '作者', pinyin: 'zuò zhě', meaning: 'tác giả' },
{ hanzi: '座', pinyin: 'zuò', meaning: 'tòa' },
{ hanzi: '座位', pinyin: 'zuò wèi', meaning: 'chỗ ngồi' },

];