vocab = [
    { hanzi: '哎', pinyin: 'āi', meaning: 'thán từ' },
{ hanzi: '唉', pinyin: 'āi', meaning: 'thán từ' },
{ hanzi: '爱护', pinyin: 'ài hù', meaning: 'yêu thương, giữ gìn' },
{ hanzi: '爱惜', pinyin: 'ài xī', meaning: 'quý trọng' },
{ hanzi: '爱心', pinyin: 'ài xīn', meaning: 'lòng tốt' },
{ hanzi: '安装', pinyin: 'ān zhuāng', meaning: 'lắp đặt' },
{ hanzi: '岸', pinyin: 'àn', meaning: 'bờ' },
{ hanzi: '暗', pinyin: 'àn', meaning: 'tối' },
{ hanzi: '熬夜', pinyin: 'áo yè', meaning: 'thức đêm' },
{ hanzi: '把握', pinyin: 'bǎ wò', meaning: 'nắm chắc' },
{ hanzi: '摆', pinyin: 'bǎi', meaning: 'bày' },
{ hanzi: '办理', pinyin: 'bàn lǐ', meaning: 'làm (thủ tục)' },
{ hanzi: '傍晚', pinyin: 'bàng wǎn', meaning: 'chiều muộn' },
{ hanzi: '包裹', pinyin: 'bāo guǒ', meaning: 'bưu kiện' },
{ hanzi: '包含', pinyin: 'bāo hán', meaning: 'bao hàm' },
{ hanzi: '包括', pinyin: 'bāo kuò', meaning: 'bao gồm' },
{ hanzi: '薄', pinyin: 'báo', meaning: 'mỏng' },
{ hanzi: '宝贝', pinyin: 'bǎo bèi', meaning: 'bảo bối' },
{ hanzi: '宝贵', pinyin: 'bǎo guì', meaning: 'quí báu' },
{ hanzi: '保持', pinyin: 'bǎo chí', meaning: 'duy trì' },
{ hanzi: '保留', pinyin: 'bǎo liú', meaning: 'bảo lưu' },
{ hanzi: '保险', pinyin: 'bǎo xiǎn', meaning: 'bảo hiểm' },
{ hanzi: '报到', pinyin: 'bào dào', meaning: 'điểm danh' },
{ hanzi: '报道', pinyin: 'bào dào', meaning: 'đưa tin, bản tin' },
{ hanzi: '报告', pinyin: 'bào gào', meaning: 'báo cáo' },
{ hanzi: '报社', pinyin: 'bào shè', meaning: 'tòa soạn báo' },
{ hanzi: '抱怨', pinyin: 'bào yuàn', meaning: 'trách móc' },
{ hanzi: '背', pinyin: 'bèi', meaning: 'học thuộc, cõng' },
{ hanzi: '悲观', pinyin: 'bēi guān', meaning: 'bi quan' },
{ hanzi: '背景', pinyin: 'bèi jǐng', meaning: 'bối cảnh' },
{ hanzi: '被子', pinyin: 'bèi zi', meaning: 'chăn' },
{ hanzi: '本科', pinyin: 'běn kē', meaning: 'trình độ đại học' },
{ hanzi: '本领', pinyin: 'běn lǐng', meaning: 'bản lĩnh' },
{ hanzi: '本质', pinyin: 'běn zhì', meaning: 'bản chất' },
{ hanzi: '比例', pinyin: 'bǐ lì', meaning: 'tỉ lệ' },
{ hanzi: '彼此', pinyin: 'bǐ cǐ', meaning: 'lẫn nhau, với nhau' },
{ hanzi: '必然', pinyin: 'bì rán', meaning: 'tất yếu' },
{ hanzi: '必要', pinyin: 'bì yào', meaning: 'cần thiết, cần' },
{ hanzi: '避免', pinyin: 'bì miǎn', meaning: 'tránh' },
{ hanzi: '编辑', pinyin: 'biān jí', meaning: 'biên tập' },
{ hanzi: '鞭炮', pinyin: 'biān pào', meaning: 'pháo' },
{ hanzi: '便', pinyin: 'biàn', meaning: 'liền' },
{ hanzi: '辩论', pinyin: 'biàn lùn', meaning: 'biện luận' },
{ hanzi: '标点', pinyin: 'biāo diǎn', meaning: 'dấu' },
{ hanzi: '标志', pinyin: 'biāo zhì', meaning: 'đánh dấu, ký hiệu' },
{ hanzi: '表达', pinyin: 'biǎo dá', meaning: 'diễn đạt' },
{ hanzi: '表面', pinyin: 'biǎo miàn', meaning: 'bề mặt, bề ngoài' },
{ hanzi: '表明', pinyin: 'biǎo míng', meaning: 'cho thấy' },
{ hanzi: '表情', pinyin: 'biǎo qíng', meaning: 'biểu cảm' },
{ hanzi: '表现', pinyin: 'biǎo xiàn', meaning: 'biểu hiện' },
{ hanzi: '冰淇淋', pinyin: 'bīng qí lín', meaning: 'kem' },
{ hanzi: '病毒', pinyin: 'bìng dú', meaning: 'vi rút' },
{ hanzi: '玻璃', pinyin: 'bō lí', meaning: 'thủy tinh' },
{ hanzi: '播放', pinyin: 'bō fàng', meaning: 'phát sóng' },
{ hanzi: '脖子', pinyin: 'bó zi', meaning: 'cổ' },
{ hanzi: '博物馆', pinyin: 'bó wù guǎn', meaning: 'bảo tàng' },
{ hanzi: '补充', pinyin: 'bǔ chōng', meaning: 'bổ sung' },
{ hanzi: '不安', pinyin: 'bú ān', meaning: 'bất an' },
{ hanzi: '不断', pinyin: 'bú duàn', meaning: 'không ngừng' },
{ hanzi: '不见得', pinyin: 'bú jiàn dé', meaning: 'chưa chắc' },
{ hanzi: '不耐烦', pinyin: 'bú nài fán', meaning: 'chán nản, không kiên nhẫn' },
{ hanzi: '不然', pinyin: 'bú rán', meaning: 'nếu không thì' },
{ hanzi: '不如', pinyin: 'bú rú', meaning: 'không bằng' },
{ hanzi: '不要紧', pinyin: 'bú yào jǐn', meaning: 'không quan trọng' },
{ hanzi: '不足', pinyin: 'bú zú', meaning: 'không đủ' },
{ hanzi: '布', pinyin: 'bù', meaning: 'vải' },
{ hanzi: '步骤', pinyin: 'bù zhòu', meaning: 'bước' },
{ hanzi: '部门', pinyin: 'bù mén', meaning: 'ban ngành, bộ phận' },
{ hanzi: '财产', pinyin: 'cái chǎn', meaning: 'tài sản' },
{ hanzi: '采访', pinyin: 'cǎi fǎng', meaning: 'phỏng vấn' },
{ hanzi: '采取', pinyin: 'cǎi qǔ', meaning: 'chọn, dùng' },
{ hanzi: '彩虹', pinyin: 'cǎi hóng', meaning: 'cầu vồng' },
{ hanzi: '踩', pinyin: 'cǎi', meaning: 'giẫm' },
{ hanzi: '参考', pinyin: 'cān kǎo', meaning: 'tham khảo' },
{ hanzi: '参与', pinyin: 'cān yù', meaning: 'tham gia' },
{ hanzi: '惭愧', pinyin: 'cán kuì', meaning: 'hổ thẹn' },
{ hanzi: '操场', pinyin: 'cāo chǎng', meaning: 'sân vận động' },
{ hanzi: '操心', pinyin: 'cāo xīn', meaning: 'lo lắng' },
{ hanzi: '册', pinyin: 'cè', meaning: 'quyển, sổ' },
{ hanzi: '测验', pinyin: 'cè yàn', meaning: 'thí nghiệm' },
{ hanzi: '曾经', pinyin: 'céng jīng', meaning: 'đã từng' },
{ hanzi: '叉子', pinyin: 'chā zi', meaning: 'cái dĩa, cái xiên, cái nĩa' },
{ hanzi: '差距', pinyin: 'chā jù', meaning: 'sự khác biệt' },
{ hanzi: '插', pinyin: 'chā', meaning: 'cắm, chèn' },
{ hanzi: '拆', pinyin: 'chāi', meaning: 'gỡ, dỡ' },
{ hanzi: '产品', pinyin: 'chǎn pǐn', meaning: 'sản phẩm' },
{ hanzi: '产生', pinyin: 'chǎn shēng', meaning: 'sản sinh, nảy sinh' },
{ hanzi: '长途', pinyin: 'cháng tú', meaning: 'đường dài' },
{ hanzi: '常识', pinyin: 'cháng shí', meaning: 'kiến thức cơ bản' },
{ hanzi: '抄', pinyin: 'chāo', meaning: 'chép' },
{ hanzi: '超级', pinyin: 'chāo jí', meaning: 'siêu cấp, cực kỳ' },
{ hanzi: '朝', pinyin: 'cháo', meaning: 'về hướng' },
{ hanzi: '潮湿', pinyin: 'cháo shī', meaning: 'ẩm ướt' },
{ hanzi: '吵', pinyin: 'chǎo', meaning: 'ồn ào' },
{ hanzi: '吵架', pinyin: 'chǎo jià', meaning: 'cãi vã' },
{ hanzi: '炒', pinyin: 'chǎo', meaning: 'xào' },
{ hanzi: '车库', pinyin: 'chē kù', meaning: 'nhà xe' },
{ hanzi: '车厢', pinyin: 'chē xiāng', meaning: 'toa tàu' },
{ hanzi: '彻底', pinyin: 'chè dǐ', meaning: 'triệt để' },
{ hanzi: '沉默', pinyin: 'chén mò', meaning: 'im lặng' },
{ hanzi: '趁', pinyin: 'chèn', meaning: 'nhân' },
{ hanzi: '称', pinyin: 'chēng', meaning: 'gọi là' },
{ hanzi: '称呼', pinyin: 'chēng hū', meaning: 'xưng hô' },
{ hanzi: '称赞', pinyin: 'chēng zàn', meaning: 'tán thưởng' },
{ hanzi: '成分', pinyin: 'chéng fèn', meaning: 'thành phần' },
{ hanzi: '成果', pinyin: 'chéng guǒ', meaning: 'thành quả' },
{ hanzi: '成就', pinyin: 'chéng jiù', meaning: 'thành tựu' },
{ hanzi: '成立', pinyin: 'chéng lì', meaning: 'thành lập' },
{ hanzi: '成人', pinyin: 'chéng rén', meaning: 'người lớn' },
{ hanzi: '成熟', pinyin: 'chéng shú', meaning: 'thành thục' },
{ hanzi: '成语', pinyin: 'chéng yǔ', meaning: 'thành ngữ' },
{ hanzi: '成长', pinyin: 'chéng zhǎng', meaning: 'trưởng thành' },
{ hanzi: '诚恳', pinyin: 'chéng kěn', meaning: 'thành khẩn' },
{ hanzi: '承担', pinyin: 'chéng dān', meaning: 'chịu trách nhiệm' },
{ hanzi: '承认', pinyin: 'chéng rèn', meaning: 'thừa nhận' },
{ hanzi: '承受', pinyin: 'chéng shòu', meaning: 'chịu đựng' },
{ hanzi: '程度', pinyin: 'chéng dù', meaning: 'trình độ' },
{ hanzi: '程序', pinyin: 'chéng xù', meaning: 'trình tự' },
{ hanzi: '吃亏', pinyin: 'chī kuī', meaning: 'thiệt thòi' },
{ hanzi: '池塘', pinyin: 'chí táng', meaning: 'ao hồ' },
{ hanzi: '迟早', pinyin: 'chí zǎo', meaning: 'sớm muộn' },
{ hanzi: '持续', pinyin: 'chí xù', meaning: 'kéo dài, tiêp tục' },
{ hanzi: '尺子', pinyin: 'chǐ zi', meaning: 'thước đo' },
{ hanzi: '翅膀', pinyin: 'chì bǎng', meaning: 'cánh' },
{ hanzi: '冲', pinyin: 'chōng', meaning: 'xông, xô đẩy' },
{ hanzi: '充分', pinyin: 'chōng fèn', meaning: 'đầy đủ' },
{ hanzi: '充满', pinyin: 'chōng mǎn', meaning: 'tràn đầy' },
{ hanzi: '重复', pinyin: 'chóng fù', meaning: 'lặp lại' },
{ hanzi: '宠物', pinyin: 'chǒng wù', meaning: 'thú cưng' },
{ hanzi: '抽屉', pinyin: 'chōu tì', meaning: 'ngăn kéo' },
{ hanzi: '抽象', pinyin: 'chōu xiàng', meaning: 'trừu tượng' },
{ hanzi: '丑', pinyin: 'chǒu', meaning: 'xấu' },
{ hanzi: '臭', pinyin: 'chòu', meaning: 'thối' },
{ hanzi: '出版', pinyin: 'chū bǎn', meaning: 'xuất bản' },
{ hanzi: '出口', pinyin: 'chū kǒu', meaning: 'lối ra, cửa ra' },
{ hanzi: '出色', pinyin: 'chū sè', meaning: 'xuất sắc' },
{ hanzi: '出示', pinyin: 'chū shì', meaning: 'xuất trình' },
{ hanzi: '出席', pinyin: 'chū xí', meaning: 'tham dự' },
{ hanzi: '初级', pinyin: 'chū jí', meaning: 'sơ cấp' },
{ hanzi: '除非', pinyin: 'chú fēi', meaning: 'trừ phi' },
{ hanzi: '除夕', pinyin: 'chú xī', meaning: 'giao thừa' },
{ hanzi: '处理', pinyin: 'chǔ lǐ', meaning: 'xử lý' },
{ hanzi: '传播', pinyin: 'chuán bō', meaning: 'lan truyền, lây lan' },
{ hanzi: '传染', pinyin: 'chuán rǎn', meaning: 'nhiễm' },
{ hanzi: '传说', pinyin: 'chuán shuō', meaning: 'truyền thuyết' },
{ hanzi: '传统', pinyin: 'chuán tǒng', meaning: 'truyền thống' },
{ hanzi: '窗帘', pinyin: 'chuāng lián', meaning: 'rèm cửa' },
{ hanzi: '闯', pinyin: 'chuǎng', meaning: 'xông vào, xông lên' },
{ hanzi: '创造', pinyin: 'chuàng zào', meaning: 'sáng tạo' },
{ hanzi: '吹', pinyin: 'chuī', meaning: 'thổi' },
{ hanzi: '词汇', pinyin: 'cí huì', meaning: 'từ vựng' },
{ hanzi: '辞职', pinyin: 'cí zhí', meaning: 'từ chức, bỏ việc' },
{ hanzi: '此外', pinyin: 'cǐ wài', meaning: 'ngoài ra' },
{ hanzi: '次要', pinyin: 'cì yào', meaning: 'thứ yếu' },
{ hanzi: '刺激', pinyin: 'cì jī', meaning: 'kích thích' },
{ hanzi: '匆忙', pinyin: 'cōng máng', meaning: 'vội vàng' },
{ hanzi: '从此', pinyin: 'cóng cǐ', meaning: 'từ đó' },
{ hanzi: '从而', pinyin: 'cóng ér', meaning: 'cho nên' },
{ hanzi: '从前', pinyin: 'cóng qián', meaning: 'từ trước' },
{ hanzi: '从事', pinyin: 'cóng shì', meaning: 'theo đuổi' },
{ hanzi: '粗糙', pinyin: 'cū cāo', meaning: 'thô ráp' },
{ hanzi: '促进', pinyin: 'cù jìn', meaning: 'xúc tiến' },
{ hanzi: '促使', pinyin: 'cù shǐ', meaning: 'thúc đẩy' },
{ hanzi: '醋', pinyin: 'cù', meaning: 'giấm' },
{ hanzi: '催', pinyin: 'cuī', meaning: 'giục' },
{ hanzi: '存在', pinyin: 'cún zài', meaning: 'tồn tại' },
{ hanzi: '措施', pinyin: 'cuò shī', meaning: 'sách lược, chính sách' },
{ hanzi: '答应', pinyin: 'dā yìng', meaning: 'hứa, đồng ý' },
{ hanzi: '达到', pinyin: 'dá dào', meaning: 'đạt đến' },
{ hanzi: '打工', pinyin: 'dǎ gōng', meaning: 'làm thêm' },
{ hanzi: '打交道', pinyin: 'dǎ jiāo dào', meaning: 'kết bạn' },
{ hanzi: '打喷嚏', pinyin: 'dǎ pēn tì', meaning: 'hắt xì' },
{ hanzi: '打听', pinyin: 'dǎ tīng', meaning: 'hỏi thăm' },
{ hanzi: '大方', pinyin: 'dà fāng', meaning: 'phóng khoáng' },
{ hanzi: '大厦', pinyin: 'dà shà', meaning: 'tòa nhà' },
{ hanzi: '大象', pinyin: 'dà xiàng', meaning: 'voi' },
{ hanzi: '大型', pinyin: 'dà xíng', meaning: 'lớn (qui mô)' },
{ hanzi: '呆', pinyin: 'dāi', meaning: 'ở lì, ở' },
{ hanzi: '代表', pinyin: 'dài biǎo', meaning: 'đại diện' },
{ hanzi: '代替', pinyin: 'dài tì', meaning: 'thay thế' },
{ hanzi: '贷款', pinyin: 'dài kuǎn', meaning: 'vay tiền' },
{ hanzi: '待遇', pinyin: 'dài yù', meaning: 'đãi ngộ' },
{ hanzi: '担任', pinyin: 'dān rèn', meaning: 'đảm nhiệm' },
{ hanzi: '单纯', pinyin: 'dān chún', meaning: 'đơn thuần,ngây thơ' },
{ hanzi: '单调', pinyin: 'dān diào', meaning: 'đơn điệu' },
{ hanzi: '单独', pinyin: 'dān dú', meaning: 'đơn độc' },
{ hanzi: '单位', pinyin: 'dān wèi', meaning: 'đơn vị' },
{ hanzi: '单元', pinyin: 'dān yuán', meaning: 'đơn nguyên, cụm' },
{ hanzi: '耽误', pinyin: 'dān wù', meaning: 'bỏ lỡ' },
{ hanzi: '胆小鬼', pinyin: 'dǎn xiǎo guǐ', meaning: 'kẻ nhát gan' },
{ hanzi: '淡', pinyin: 'dàn', meaning: 'nhạt' },
{ hanzi: '当地', pinyin: 'dāng dì', meaning: 'địa phương' },
{ hanzi: '当心', pinyin: 'dāng xīn', meaning: 'để tâm, lưu tâm' },
{ hanzi: '挡', pinyin: 'dǎng', meaning: 'chắn' },
{ hanzi: '导演', pinyin: 'dǎo yǎn', meaning: 'đạo diễn' },
{ hanzi: '导致', pinyin: 'dǎo zhì', meaning: 'gây ra' },
{ hanzi: '岛屿', pinyin: 'dǎo yǔ', meaning: 'đảo' },
{ hanzi: '倒霉', pinyin: 'dǎo méi', meaning: 'xui xẻo' },
{ hanzi: '到达', pinyin: 'dào dá', meaning: 'đến' },
{ hanzi: '道德', pinyin: 'dào dé', meaning: 'đạo đức' },
{ hanzi: '道理', pinyin: 'dào lǐ', meaning: 'đạo lí, bài học' },
{ hanzi: '登记', pinyin: 'dēng jì', meaning: 'đăng kí' },
{ hanzi: '等待', pinyin: 'děng dài', meaning: 'đợi, chờ đợi' },
{ hanzi: '等于', pinyin: 'děng yú', meaning: 'bằng' },
{ hanzi: '滴', pinyin: 'dī', meaning: 'giọt' },
{ hanzi: '的确', pinyin: 'dí què', meaning: 'đúng, thật (phó từ)' },
{ hanzi: '敌人', pinyin: 'dí rén', meaning: 'kẻ địch' },
{ hanzi: '地道', pinyin: 'dì dào', meaning: 'chuẩn bản địa (ngôn ngữ, món ăn)' },
{ hanzi: '地理', pinyin: 'dì lǐ', meaning: 'địa lý' },
{ hanzi: '地区', pinyin: 'dì qū', meaning: 'khu vực' },
{ hanzi: '地毯', pinyin: 'dì tǎn', meaning: 'thảm' },
{ hanzi: '地位', pinyin: 'dì wèi', meaning: 'địa vị' },
{ hanzi: '地震', pinyin: 'dì zhèn', meaning: 'động đất' },
{ hanzi: '递', pinyin: 'dì', meaning: 'truyền' },
{ hanzi: '点心', pinyin: 'diǎn xīn', meaning: 'điểm tâm' },
{ hanzi: '电池', pinyin: 'diàn chí', meaning: 'pin' },
{ hanzi: '电台', pinyin: 'diàn tái', meaning: 'đài truyền hình' },
{ hanzi: '钓', pinyin: 'diào', meaning: 'câu (cá)' },
{ hanzi: '顶', pinyin: 'dǐng', meaning: 'đội, cái (lượng từ cho mũ)' },
{ hanzi: '动画片', pinyin: 'dòng huà piàn', meaning: 'phim hoạt hình' },
{ hanzi: '冻', pinyin: 'dòng', meaning: 'đông cứng' },
{ hanzi: '洞', pinyin: 'dòng', meaning: 'hang động' },
{ hanzi: '豆腐', pinyin: 'dòu fǔ', meaning: 'đậu phụ' },
{ hanzi: '逗', pinyin: 'dòu', meaning: 'trêu' },
{ hanzi: '独立', pinyin: 'dú lì', meaning: 'độc lập' },
{ hanzi: '独特', pinyin: 'dú tè', meaning: 'độc đáo' },
{ hanzi: '度过', pinyin: 'dù guò', meaning: 'trải qua (thời kì, thời gian)' },
{ hanzi: '断', pinyin: 'duàn', meaning: 'đoạn, đứt' },
{ hanzi: '堆', pinyin: 'duī', meaning: 'đống' },
{ hanzi: '对比', pinyin: 'duì bǐ', meaning: 'đối chiếu' },
{ hanzi: '对待', pinyin: 'duì dài', meaning: 'đối đãi' },
{ hanzi: '对方', pinyin: 'duì fāng', meaning: 'đối phương' },
{ hanzi: '对手', pinyin: 'duì shǒu', meaning: 'đối thủ' },
{ hanzi: '对象', pinyin: 'duì xiàng', meaning: 'đối tượng' },
{ hanzi: '兑换', pinyin: 'duì huàn', meaning: 'đổi' },
{ hanzi: '吨', pinyin: 'dūn', meaning: 'tấn' },
{ hanzi: '蹲', pinyin: 'dūn', meaning: 'ngồi xổm' },
{ hanzi: '顿', pinyin: 'dùn', meaning: 'bữa' },
{ hanzi: '多亏', pinyin: 'duō kuī', meaning: 'may mà' },
{ hanzi: '多余', pinyin: 'duō yú', meaning: 'thừa thãi' },
{ hanzi: '朵', pinyin: 'duǒ', meaning: 'bông' },
{ hanzi: '躲藏', pinyin: 'duǒ cáng', meaning: 'trốn' },
{ hanzi: '恶劣', pinyin: 'è liè', meaning: 'khắc nghiệt, hà khắc' },
{ hanzi: '耳环', pinyin: 'ěr huán', meaning: 'khuyên tai' },
{ hanzi: '发表', pinyin: 'fā biǎo', meaning: 'phát biểu, đăng, ra mắt (tác phẩm)' },
{ hanzi: '发愁', pinyin: 'fā chóu', meaning: 'phát buồn, chán' },
{ hanzi: '发达', pinyin: 'fā dá', meaning: 'phát đạt, phát triển' },
{ hanzi: '发抖', pinyin: 'fā dǒu', meaning: 'run rẩy' },
{ hanzi: '发挥', pinyin: 'fā huī', meaning: 'phát huy' },
{ hanzi: '发明', pinyin: 'fā míng', meaning: 'phát minh' },
{ hanzi: '发票', pinyin: 'fā piào', meaning: 'hóa đơn giá trị gia tăng' },
{ hanzi: '发言', pinyin: 'fā yán', meaning: 'phát biểu (ý kiến)' },
{ hanzi: '罚款', pinyin: 'fá kuǎn', meaning: 'phạt tiền' },
{ hanzi: '法院', pinyin: 'fǎ yuàn', meaning: 'tòa án' },
{ hanzi: '翻', pinyin: 'fān', meaning: 'lật, giở' },
{ hanzi: '繁荣', pinyin: 'fán róng', meaning: 'phồn vinh' },
{ hanzi: '反而', pinyin: 'fǎn ér', meaning: 'ngược lại' },
{ hanzi: '反复', pinyin: 'fǎn fù', meaning: 'lặp đi lặp lại' },
{ hanzi: '反应', pinyin: 'fǎn yìng', meaning: 'phản ứng' },
{ hanzi: '反映', pinyin: 'fǎn yìng', meaning: 'phản ánh' },
{ hanzi: '反正', pinyin: 'fǎn zhèng', meaning: 'dù sao thì' },
{ hanzi: '范围', pinyin: 'fàn wéi', meaning: 'phạm vi' },
{ hanzi: '方', pinyin: 'fāng', meaning: 'phương' },
{ hanzi: '方案', pinyin: 'fāng àn', meaning: 'phương án' },
{ hanzi: '方式', pinyin: 'fāng shì', meaning: 'phương thức' },
{ hanzi: '妨碍', pinyin: 'fáng ài', meaning: 'trở ngại, cản trở' },
{ hanzi: '仿佛', pinyin: 'fǎng fú', meaning: 'dường như' },
{ hanzi: '非', pinyin: 'fēi', meaning: 'phi, không' },
{ hanzi: '肥皂', pinyin: 'féi zào', meaning: 'bánh xà phòng' },
{ hanzi: '废话', pinyin: 'fèi huà', meaning: 'lời nói thừa thãi' },
{ hanzi: '分别', pinyin: 'fēn bié', meaning: 'phân biệt, lần lượt, xa nhau' },
{ hanzi: '分布', pinyin: 'fēn bù', meaning: 'phân bố' },
{ hanzi: '分配', pinyin: 'fēn pèi', meaning: 'chia sẻ, phân chia, phân công' },
{ hanzi: '分手', pinyin: 'fēn shǒu', meaning: 'chia tay' },
{ hanzi: '分析', pinyin: 'fēn xī', meaning: 'phân tích' },
{ hanzi: '纷纷', pinyin: 'fēn fēn', meaning: 'lũ lượt' },
{ hanzi: '奋斗', pinyin: 'fèn dòu', meaning: 'phấn đấu' },
{ hanzi: '风格', pinyin: 'fēng gé', meaning: 'phong cách' },
{ hanzi: '风景', pinyin: 'fēng jǐng', meaning: 'phong cảnh' },
{ hanzi: '风俗', pinyin: 'fēng sú', meaning: 'phong tục' },
{ hanzi: '风险', pinyin: 'fēng xiǎn', meaning: 'mạo hiểm, hiểm nguy' },
{ hanzi: '疯狂', pinyin: 'fēng kuáng', meaning: 'điên rồ' },
{ hanzi: '讽刺', pinyin: 'fěng cì', meaning: 'châm biếm' },
{ hanzi: '否定', pinyin: 'fǒu dìng', meaning: 'phủ định' },
{ hanzi: '否认', pinyin: 'fǒu rèn', meaning: 'phủ nhận' },
{ hanzi: '扶', pinyin: 'fú', meaning: 'vịn' },
{ hanzi: '服装', pinyin: 'fú zhuāng', meaning: 'phục trang, quần áo' },
{ hanzi: '幅', pinyin: 'fú', meaning: 'bức (lượng từ cho tranh)' },
{ hanzi: '辅导', pinyin: 'fǔ dǎo', meaning: 'phụ đạo, bổ trợ' },
{ hanzi: '妇女', pinyin: 'fù nǚ', meaning: 'phụ nữ' },
{ hanzi: '复制', pinyin: 'fù zhì', meaning: 'copy' },
{ hanzi: '改革', pinyin: 'gǎi gé', meaning: 'cải cách' },
{ hanzi: '改进', pinyin: 'gǎi jìn', meaning: 'cải tiến' },
{ hanzi: '改善', pinyin: 'gǎi shàn', meaning: 'cải thiện' },
{ hanzi: '改正', pinyin: 'gǎi zhèng', meaning: 'đính chính' },
{ hanzi: '盖', pinyin: 'gài', meaning: 'đậy, bao phủ' },
{ hanzi: '概括', pinyin: 'gài kuò', meaning: 'khái quát' },
{ hanzi: '概念', pinyin: 'gài niàn', meaning: 'khái niệm' },
{ hanzi: '干脆', pinyin: 'gān cuì', meaning: 'dứt khoát' },
{ hanzi: '干燥', pinyin: 'gān zào', meaning: 'khô ráo, khô hanh' },
{ hanzi: '赶紧', pinyin: 'gǎn jǐn', meaning: 'mau chóng' },
{ hanzi: '赶快', pinyin: 'gǎn kuài', meaning: 'mau chóng' },
{ hanzi: '感激', pinyin: 'gǎn jī', meaning: 'cảm kích, biết ơn' },
{ hanzi: '感受', pinyin: 'gǎn shòu', meaning: 'cảm nhận' },
{ hanzi: '感想', pinyin: 'gǎn xiǎng', meaning: 'cảm tưởng, suy nghĩ' },
{ hanzi: '干活儿', pinyin: 'gàn huó ér', meaning: 'lao động' },
{ hanzi: '钢铁', pinyin: 'gāng tiě', meaning: 'sắt thép' },
{ hanzi: '高档', pinyin: 'gāo dàng', meaning: 'cao cấp, đẳng cấp' },
{ hanzi: '高级', pinyin: 'gāo jí', meaning: 'cao cấp' },
{ hanzi: '搞', pinyin: 'gǎo', meaning: 'làm' },
{ hanzi: '告别', pinyin: 'gào bié', meaning: 'từ biệt' },
{ hanzi: '格外', pinyin: 'gé wài', meaning: 'đặc biệt' },
{ hanzi: '隔壁', pinyin: 'gé bì', meaning: 'sát vách, ngay cạnh' },
{ hanzi: '个别', pinyin: 'gè bié', meaning: 'cá biệt' },
{ hanzi: '个人', pinyin: 'gè rén', meaning: 'cá nhân' },
{ hanzi: '个性', pinyin: 'gè xìng', meaning: 'cá tính' },
{ hanzi: '各自', pinyin: 'gè zì', meaning: 'tự, mỗi' },
{ hanzi: '根', pinyin: 'gēn', meaning: 'lượng từ: sợi, cành, khúc, ngón' },
{ hanzi: '根本', pinyin: 'gēn běn', meaning: 'vốn' },
{ hanzi: '工厂', pinyin: 'gōng chǎng', meaning: 'xưởng, xí nghiệp' },
{ hanzi: '工程师', pinyin: 'gōng chéng shī', meaning: 'kỹ sư' },
{ hanzi: '工具', pinyin: 'gōng jù', meaning: 'công cụ' },
{ hanzi: '工人', pinyin: 'gōng rén', meaning: 'công nhân' },
{ hanzi: '工业', pinyin: 'gōng yè', meaning: 'công nghiệp' },
{ hanzi: '公布', pinyin: 'gōng bù', meaning: 'công bố' },
{ hanzi: '公开', pinyin: 'gōng kāi', meaning: 'công khai' },
{ hanzi: '公平', pinyin: 'gōng píng', meaning: 'công bằng' },
{ hanzi: '公寓', pinyin: 'gōng yù', meaning: 'chung cư' },
{ hanzi: '公元', pinyin: 'gōng yuán', meaning: 'công nguyên' },
{ hanzi: '公主', pinyin: 'gōng zhǔ', meaning: 'công chúa' },
{ hanzi: '功能', pinyin: 'gōng néng', meaning: 'công năng' },
{ hanzi: '恭喜', pinyin: 'gōng xǐ', meaning: 'chúc mừng' },
{ hanzi: '贡献', pinyin: 'gòng xiàn', meaning: 'cống hiến' },
{ hanzi: '沟通', pinyin: 'gōu tōng', meaning: 'trao đổi, thấu hiểu' },
{ hanzi: '构成', pinyin: 'gòu chéng', meaning: 'tạo thành, cấu thành' },
{ hanzi: '姑姑', pinyin: 'gū gu', meaning: 'cô' },
{ hanzi: '姑娘', pinyin: 'gū niang', meaning: 'cô gái' },
{ hanzi: '古代', pinyin: 'gǔ dài', meaning: 'cổ đại' },
{ hanzi: '古典', pinyin: 'gǔ diǎn', meaning: 'cổ điển' },
{ hanzi: '股票', pinyin: 'gǔ piào', meaning: 'cổ phiếu' },
{ hanzi: '骨头', pinyin: 'gǔ tou', meaning: 'xương' },
{ hanzi: '鼓舞', pinyin: 'gǔ wǔ', meaning: 'cổ vũ' },
{ hanzi: '鼓掌', pinyin: 'gǔ zhǎng', meaning: 'vỗ tay' },
{ hanzi: '固定', pinyin: 'gù dìng', meaning: 'cố định' },
{ hanzi: '挂号', pinyin: 'guà hào', meaning: 'xếp số' },
{ hanzi: '乖', pinyin: 'guāi', meaning: 'ngoan' },
{ hanzi: '拐弯', pinyin: 'guǎi wān', meaning: 'rẽ' },
{ hanzi: '怪不得', pinyin: 'guài bù dé', meaning: 'chẳng trách' },
{ hanzi: '关闭', pinyin: 'guān bì', meaning: 'đóng' },
{ hanzi: '观察', pinyin: 'guān chá', meaning: 'quan sát' },
{ hanzi: '观点', pinyin: 'guān diǎn', meaning: 'quan điểm' },
{ hanzi: '观念', pinyin: 'guān niàn', meaning: 'quan niệm' },
{ hanzi: '官', pinyin: 'guān', meaning: 'quan' },
{ hanzi: '管子', pinyin: 'guǎn zi', meaning: 'cái ống' },
{ hanzi: '冠军', pinyin: 'guàn jūn', meaning: 'quán quân' },
{ hanzi: '光滑', pinyin: 'guāng huá', meaning: 'bóng mượt' },
{ hanzi: '光临', pinyin: 'guāng lín', meaning: 'đến, có mặt' },
{ hanzi: '光明', pinyin: 'guāng míng', meaning: 'quang minh, sáng sủa' },
{ hanzi: '光盘', pinyin: 'guāng pán', meaning: 'đĩa CD, VCD,DVD' },
{ hanzi: '广场', pinyin: 'guǎng chǎng', meaning: 'quảng trường' },
{ hanzi: '广大', pinyin: 'guǎng dà', meaning: 'quảng đại, rộng lớn' },
{ hanzi: '广泛', pinyin: 'guǎng fàn', meaning: 'rộng khắp' },
{ hanzi: '归纳', pinyin: 'guī nà', meaning: 'tóm tắt' },
{ hanzi: '规矩', pinyin: 'guī ju', meaning: 'qui tắc' },
{ hanzi: '规律', pinyin: 'guī lǜ', meaning: 'qui luật' },
{ hanzi: '规模', pinyin: 'guī mó', meaning: 'qui mô' },
{ hanzi: '规则', pinyin: 'guī zé', meaning: 'nội qui' },
{ hanzi: '柜台', pinyin: 'guì tái', meaning: 'quầy ba, quầy' },
{ hanzi: '滚', pinyin: 'gǔn', meaning: 'cút, cuộn, lăn' },
{ hanzi: '锅', pinyin: 'guō', meaning: 'nồi' },
{ hanzi: '国庆节', pinyin: 'guó qìng jié', meaning: 'quốc khánh' },
{ hanzi: '国王', pinyin: 'guó wáng', meaning: 'quốc vương' },
{ hanzi: '果然', pinyin: 'guǒ rán', meaning: 'quả nhiên' },
{ hanzi: '果实', pinyin: 'guǒ shí', meaning: 'quả thật' },
{ hanzi: '过分', pinyin: 'guò fèn', meaning: 'quá đáng' },
{ hanzi: '过敏', pinyin: 'guò mǐn', meaning: 'mẫn cảm, dị ứng' },
{ hanzi: '过期', pinyin: 'guò qī', meaning: 'quá hạn' },
{ hanzi: '哈', pinyin: 'hā', meaning: 'ha ha' },
{ hanzi: '海关', pinyin: 'hǎi guān', meaning: 'hải quan' },
{ hanzi: '海鲜', pinyin: 'hǎi xiān', meaning: 'hải sản' },
{ hanzi: '喊', pinyin: 'hǎn', meaning: 'hét' },
{ hanzi: '行业', pinyin: 'háng yè', meaning: 'ngành nghề' },
{ hanzi: '豪华', pinyin: 'háo huá', meaning: 'sang trọng' },
{ hanzi: '好客', pinyin: 'hào kè', meaning: 'hiếu khách' },
{ hanzi: '好奇', pinyin: 'hào qí', meaning: 'hiếu kì' },
{ hanzi: '合法', pinyin: 'hé fǎ', meaning: 'hợp pháp' },
{ hanzi: '合理', pinyin: 'hé lǐ', meaning: 'hợp lý' },
{ hanzi: '合同', pinyin: 'hé tóng', meaning: 'hợp đồng' },
{ hanzi: '合影', pinyin: 'hé yǐng', meaning: 'chụp ảnh chung, chụp ảnh tập thể' },
{ hanzi: '合作', pinyin: 'hé zuò', meaning: 'hợp tác' },
{ hanzi: '何必', pinyin: 'hé bì', meaning: 'hà tất' },
{ hanzi: '何况', pinyin: 'hé kuàng', meaning: 'huống hồ, hơn nữa' },
{ hanzi: '和平', pinyin: 'hé píng', meaning: 'hòa bình' },
{ hanzi: '核心', pinyin: 'hé xīn', meaning: 'trọng tâm' },
{ hanzi: '恨', pinyin: 'hèn', meaning: 'hận' },
{ hanzi: '猴子', pinyin: 'hóu zi', meaning: 'khỉ' },
{ hanzi: '后背', pinyin: 'hòu bèi', meaning: 'phía sau' },
{ hanzi: '后果', pinyin: 'hòu guǒ', meaning: 'hậu quả' },
{ hanzi: '呼吸', pinyin: 'hū xī', meaning: 'hít thở' },
{ hanzi: '忽然', pinyin: 'hū rán', meaning: 'bỗng nhiên' },
{ hanzi: '忽视', pinyin: 'hū shì', meaning: 'không coi trọng (kinh tế, ngành nghề, vấn đề nhỏ, nghiên cứu)' },
{ hanzi: '胡说', pinyin: 'hú shuō', meaning: 'nói nhăng quậy' },
{ hanzi: '胡同', pinyin: 'hú tòng', meaning: 'ngõ, hẻm' },
{ hanzi: '壶', pinyin: 'hú', meaning: 'bình, ấm' },
{ hanzi: '蝴蝶', pinyin: 'hú dié', meaning: 'con bướm' },
{ hanzi: '糊涂', pinyin: 'hú tú', meaning: 'hồ đồ' },
{ hanzi: '花生', pinyin: 'huā shēng', meaning: 'lạc, đậu phộng' },
{ hanzi: '划', pinyin: 'huá', meaning: 'chèo (thuyền)' },
{ hanzi: '华裔', pinyin: 'huá yì', meaning: 'hoa kiều' },
{ hanzi: '滑', pinyin: 'huá', meaning: 'trượt, trơn' },
{ hanzi: '化学', pinyin: 'huà xué', meaning: 'hóa học' },
{ hanzi: '话题', pinyin: 'huà tí', meaning: 'chủ đề' },
{ hanzi: '怀念', pinyin: 'huái niàn', meaning: 'hoài niệm' },
{ hanzi: '怀孕', pinyin: 'huái yùn', meaning: 'mang bầu' },
{ hanzi: '缓解', pinyin: 'huǎn jiě', meaning: 'thả lỏng, giảm' },
{ hanzi: '幻想', pinyin: 'huàn xiǎng', meaning: 'ảo tưởng, giả tưởng' },
{ hanzi: '慌张', pinyin: 'huāng zhāng', meaning: 'hoảng sợ, rối rắm, rối' },
{ hanzi: '黄金', pinyin: 'huáng jīn', meaning: 'vàng' },
{ hanzi: '灰', pinyin: 'huī', meaning: 'màu xám' },
{ hanzi: '灰尘', pinyin: 'huī chén', meaning: 'tro bụi' },
{ hanzi: '灰心', pinyin: 'huī xīn', meaning: 'nản lòng' },
{ hanzi: '挥', pinyin: 'huī', meaning: 'vẫy' },
{ hanzi: '恢复', pinyin: 'huī fù', meaning: 'hồi phục, khôi phục' },
{ hanzi: '汇率', pinyin: 'huì lǜ', meaning: 'tỷ giá' },
{ hanzi: '婚礼', pinyin: 'hūn lǐ', meaning: 'hôn lễ' },
{ hanzi: '婚姻', pinyin: 'hūn yīn', meaning: 'hôn nhân' },
{ hanzi: '活跃', pinyin: 'huó yuè', meaning: 'sôi nổi' },
{ hanzi: '火柴', pinyin: 'huǒ chái', meaning: 'diêm' },
{ hanzi: '伙伴', pinyin: 'huǒ bàn', meaning: 'bạn đồng hành' },
{ hanzi: '或许', pinyin: 'huò xǔ', meaning: 'có lẽ' },
{ hanzi: '机器', pinyin: 'jī qì', meaning: 'máy móc' },
{ hanzi: '肌肉', pinyin: 'jī ròu', meaning: 'cơ bắp' },
{ hanzi: '基本', pinyin: 'jī běn', meaning: 'cơ bản, căn bản' },
{ hanzi: '激烈', pinyin: 'jī liè', meaning: 'khốc liệt, kịch liệt' },
{ hanzi: '及格', pinyin: 'jí gé', meaning: 'đạt điểm qua' },
{ hanzi: '极其', pinyin: 'jí qí', meaning: 'cực kì' },
{ hanzi: '急忙', pinyin: 'jí máng', meaning: 'vội vàng' },
{ hanzi: '急诊', pinyin: 'jí zhěn', meaning: 'cấp cứu' },
{ hanzi: '集合', pinyin: 'jí hé', meaning: 'tập hợp' },
{ hanzi: '集体', pinyin: 'jí tǐ', meaning: 'tập thể' },
{ hanzi: '集中', pinyin: 'jí zhōng', meaning: 'tập trung' },
{ hanzi: '计算', pinyin: 'jì suàn', meaning: 'tính toán' },
{ hanzi: '记录', pinyin: 'jì lù', meaning: 'ghi chép' },
{ hanzi: '记忆', pinyin: 'jì yì', meaning: 'ký ức' },
{ hanzi: '纪录', pinyin: 'jì lù', meaning: 'kỷ lục' },
{ hanzi: '纪律', pinyin: 'jì lǜ', meaning: 'kỷ luật' },
{ hanzi: '纪念', pinyin: 'jì niàn', meaning: 'kỉ niệm' },
{ hanzi: '系领带', pinyin: 'jì lǐng dài', meaning: 'thắt cà vạt' },
{ hanzi: '寂寞', pinyin: 'jì mò', meaning: 'cô đơn' },
{ hanzi: '夹子', pinyin: 'jiā zi', meaning: 'cái kẹp' },
{ hanzi: '家庭', pinyin: 'jiā tíng', meaning: 'gia đình' },
{ hanzi: '家务', pinyin: 'jiā wù', meaning: 'việc nhà' },
{ hanzi: '家乡', pinyin: 'jiā xiāng', meaning: 'quê hương' },
{ hanzi: '嘉宾', pinyin: 'jiā bīn', meaning: 'khách mời' },
{ hanzi: '甲', pinyin: 'jiǎ', meaning: 'giáp' },
{ hanzi: '假如', pinyin: 'jiǎ rú', meaning: 'giả dụ' },
{ hanzi: '假设', pinyin: 'jiǎ shè', meaning: 'giả thuyết' },
{ hanzi: '假装', pinyin: 'jiǎ zhuāng', meaning: 'giả vờ' },
{ hanzi: '价值', pinyin: 'jià zhí', meaning: 'giá trị' },
{ hanzi: '驾驶', pinyin: 'jià shǐ', meaning: 'lái xe' },
{ hanzi: '嫁', pinyin: 'jià', meaning: 'gả chồng' },
{ hanzi: '坚决', pinyin: 'jiān jué', meaning: 'kiên quyết' },
{ hanzi: '坚强', pinyin: 'jiān qiáng', meaning: 'kiên cường' },
{ hanzi: '肩膀', pinyin: 'jiān bǎng', meaning: 'bờ vai' },
{ hanzi: '艰巨', pinyin: 'jiān jù', meaning: 'khó khăn (công việc, nhiệm vụ)' },
{ hanzi: '艰苦', pinyin: 'jiān kǔ', meaning: 'gian khổ, gian khóa' },
{ hanzi: '兼职', pinyin: 'jiān zhí', meaning: 'kiêm nhiệm' },
{ hanzi: '捡', pinyin: 'jiǎn', meaning: 'nhặt' },
{ hanzi: '剪刀', pinyin: 'jiǎn dāo', meaning: 'cái kéo' },
{ hanzi: '简历', pinyin: 'jiǎn lì', meaning: 'sơ yếu lý lịch' },
{ hanzi: '简直', pinyin: 'jiǎn zhí', meaning: 'gần như' },
{ hanzi: '建立', pinyin: 'jiàn lì', meaning: 'thành lập (tổ chức, trường học), thiết lập (quan hệ)' },
{ hanzi: '建设', pinyin: 'jiàn shè', meaning: 'dựng xây, xây dựng' },
{ hanzi: '建筑', pinyin: 'jiàn zhù', meaning: 'công trình xây dưng, (công ty) xây dựng, (ngành) xây dựng' },
{ hanzi: '健身', pinyin: 'jiàn shēn', meaning: 'tập thể dục' },
{ hanzi: '键盘', pinyin: 'jiàn pán', meaning: 'bàn phím' },
{ hanzi: '讲究', pinyin: 'jiǎng jiū', meaning: 'coi trọng' },
{ hanzi: '讲座', pinyin: 'jiǎng zuò', meaning: 'buổi diễn thuyết' },
{ hanzi: '酱油', pinyin: 'jiàng yóu', meaning: 'xì dầu' },
{ hanzi: '交换', pinyin: 'jiāo huàn', meaning: 'trao đổi' },
{ hanzi: '交际', pinyin: 'jiāo jì', meaning: 'giao tiếp' },
{ hanzi: '交往', pinyin: 'jiāo wǎng', meaning: 'đi lại, giao thiệp' },
{ hanzi: '浇', pinyin: 'jiāo', meaning: 'tưới nước' },
{ hanzi: '胶水', pinyin: 'jiāo shuǐ', meaning: 'keo dán' },
{ hanzi: '角度', pinyin: 'jiǎo dù', meaning: 'góc độ' },
{ hanzi: '狡猾', pinyin: 'jiǎo huá', meaning: 'giảo hoạt' },
{ hanzi: '教材', pinyin: 'jiào cái', meaning: 'giao trình' },
{ hanzi: '教练', pinyin: 'jiào liàn', meaning: 'huấn luyện viên' },
{ hanzi: '教训', pinyin: 'jiào xùn', meaning: 'giáo huấn, bài học' },
{ hanzi: '阶段', pinyin: 'jiē duàn', meaning: 'giai đoạn' },
{ hanzi: '结实', pinyin: 'jiē shi', meaning: 'chắc chắn' },
{ hanzi: '接触', pinyin: 'jiē chù', meaning: 'tiếp xúc' },
{ hanzi: '接待', pinyin: 'jiē dài', meaning: 'tiếp đãi' },
{ hanzi: '接近', pinyin: 'jiē jìn', meaning: 'tiếp cận' },
{ hanzi: '节省', pinyin: 'jié shěng', meaning: 'tiết kiệm' },
{ hanzi: '结构', pinyin: 'jié gòu', meaning: 'kết cấu' },
{ hanzi: '结合', pinyin: 'jié hé', meaning: 'kết hợp' },
{ hanzi: '结论', pinyin: 'jié lùn', meaning: 'kết luận' },
{ hanzi: '结账', pinyin: 'jié zhàng', meaning: 'thanh toán' },
{ hanzi: '戒', pinyin: 'jiè', meaning: 'cai (thuốc, rượu, nghiện)' },
{ hanzi: '戒指', pinyin: 'jiè zhǐ', meaning: 'nhẫn' },
{ hanzi: '届', pinyin: 'jiè', meaning: 'khóa' },
{ hanzi: '借口', pinyin: 'jiè kǒu', meaning: 'cớ, lí do' },
{ hanzi: '金属', pinyin: 'jīn shǔ', meaning: 'kim loại' },
{ hanzi: '尽快', pinyin: 'jǐn kuài', meaning: 'mau chóng' },
{ hanzi: '尽量', pinyin: 'jǐn liàng', meaning: 'cố gắng' },
{ hanzi: '紧急', pinyin: 'jǐn jí', meaning: 'cấp bách' },
{ hanzi: '谨慎', pinyin: 'jǐn shèn', meaning: 'cẩn thận, thận trọng' },
{ hanzi: '尽力', pinyin: 'jìn lì', meaning: 'dốc hết sức' },
{ hanzi: '进步', pinyin: 'jìn bù', meaning: 'tiến bộ' },
{ hanzi: '进口', pinyin: 'jìn kǒu', meaning: 'nhập khẩu' },
{ hanzi: '近代', pinyin: 'jìn dài', meaning: 'cận đại' },
{ hanzi: '经典', pinyin: 'jīng diǎn', meaning: 'kinh điển' },
{ hanzi: '经商', pinyin: 'jīng shāng', meaning: 'kinh doanh' },
{ hanzi: '经营', pinyin: 'jīng yíng', meaning: 'kinh doanh (cửa hàng), vận hành (công ty)' },
{ hanzi: '精力', pinyin: 'jīng lì', meaning: 'tinh lực' },
{ hanzi: '精神', pinyin: 'jīng shén', meaning: 'tinh thần' },
{ hanzi: '酒吧', pinyin: 'jiǔ bā', meaning: 'quán ba' },
{ hanzi: '救', pinyin: 'jiù', meaning: 'cứu' },
{ hanzi: '救护车', pinyin: 'jiù hù chē', meaning: 'xe cứu thương' },
{ hanzi: '舅舅', pinyin: 'jiù jiù', meaning: 'cậu (em mẹ)' },
{ hanzi: '居然', pinyin: 'jū rán', meaning: 'không ngờ lại' },
{ hanzi: '桔子', pinyin: 'jú zi', meaning: 'quýt' },
{ hanzi: '巨大', pinyin: 'jù dà', meaning: 'lớn (thành tựu, thay đổi, ảnh hưởng, tác hại)' },
{ hanzi: '具备', pinyin: 'jù bèi', meaning: 'chuẩn bị đủ, có đủ (tư cách, điều kiện, tinh lực)' },
{ hanzi: '具体', pinyin: 'jù tǐ', meaning: 'cụ thể' },
{ hanzi: '俱乐部', pinyin: 'jù lè bù', meaning: 'câu lạc bộ' },
{ hanzi: '据说', pinyin: 'jù shuō', meaning: 'nghe nói, nghe đồn' },
{ hanzi: '捐', pinyin: 'juān', meaning: 'quyên góp' },
{ hanzi: '决赛', pinyin: 'jué sài', meaning: 'trận chung kết' },
{ hanzi: '决心', pinyin: 'jué xīn', meaning: 'quyết tâm' },
{ hanzi: '角色', pinyin: 'jué sè', meaning: 'nhân vật' },
{ hanzi: '绝对', pinyin: 'jué duì', meaning: 'tuyệt đối' },
{ hanzi: '军事', pinyin: 'jūn shì', meaning: 'quân sự' },
{ hanzi: '均匀', pinyin: 'jūn yún', meaning: 'bình quân, trung bình' },
{ hanzi: '卡车', pinyin: 'kǎ chē', meaning: 'xe tải' },
{ hanzi: '开发', pinyin: 'kāi fā', meaning: 'phát triển (hệ thống, ngành nghề, kĩ thuật, sản phẩm)' },
{ hanzi: '开放', pinyin: 'kāi fàng', meaning: 'mở cửa' },
{ hanzi: '开幕式', pinyin: 'kāi mù shì', meaning: 'lễ khai mạc' },
{ hanzi: '开水', pinyin: 'kāi shuǐ', meaning: 'nước sôi' },
{ hanzi: '砍', pinyin: 'kǎn', meaning: 'chặt, chém' },
{ hanzi: '看不起', pinyin: 'kàn bù qǐ', meaning: 'coi khinh' },
{ hanzi: '看望', pinyin: 'kàn wàng', meaning: 'đi thăm' },
{ hanzi: '靠', pinyin: 'kào', meaning: 'dựa dẫm, dựa vào' },
{ hanzi: '颗', pinyin: 'kē', meaning: 'quả (lượng từ)' },
{ hanzi: '可见', pinyin: 'kě jiàn', meaning: 'cho thấy (đứng đầu vế câu thứ hai)' },
{ hanzi: '可靠', pinyin: 'kě kào', meaning: 'đáng tin cậy' },
{ hanzi: '可怕', pinyin: 'kě pà', meaning: 'đáng sợ' },
{ hanzi: '克', pinyin: 'kè', meaning: 'gram' },
{ hanzi: '克服', pinyin: 'kè fú', meaning: 'khắc phục' },
{ hanzi: '刻苦', pinyin: 'kè kǔ', meaning: 'khắc khổ, chịu khó' },
{ hanzi: '客观', pinyin: 'kè guān', meaning: 'khách quan' },
{ hanzi: '课程', pinyin: 'kè chéng', meaning: 'môn học' },
{ hanzi: '空间', pinyin: 'kōng jiān', meaning: 'không gian' },
{ hanzi: '空闲', pinyin: 'kòng xián', meaning: 'rảnh rỗi (thời gian)' },
{ hanzi: '控制', pinyin: 'kòng zhì', meaning: 'kiềm chế (cảm xúc, tình cảm), kiểm soát' },
{ hanzi: '口味', pinyin: 'kǒu wèi', meaning: 'khẩu vị' },
{ hanzi: '夸', pinyin: 'kuā', meaning: 'khen' },
{ hanzi: '夸张', pinyin: 'kuā zhāng', meaning: 'phóng đại' },
{ hanzi: '会计', pinyin: 'kuàì jì', meaning: 'kế toán' },
{ hanzi: '宽', pinyin: 'kuān', meaning: 'rộng' },
{ hanzi: '昆虫', pinyin: 'kūn chóng', meaning: 'côn trùng' },
{ hanzi: '扩大', pinyin: 'kuò dà', meaning: 'mở rộng (phạm vi, khoảng cách, thị trường)' },
{ hanzi: '辣椒', pinyin: 'là jiāo', meaning: 'ớt' },
{ hanzi: '拦', pinyin: 'lán', meaning: 'ngăn, chặn' },
{ hanzi: '烂', pinyin: 'làn', meaning: 'nát, loét, rách, thối rữa' },
{ hanzi: '朗读', pinyin: 'lǎng dú', meaning: 'đọc to' },
{ hanzi: '劳动', pinyin: 'láo dòng', meaning: 'lao động' },
{ hanzi: '劳驾', pinyin: 'láo jià', meaning: 'làm ơn, xin phiền' },
{ hanzi: '老百姓', pinyin: 'lǎo bǎi xìng', meaning: 'lão bách tính' },
{ hanzi: '老板', pinyin: 'lǎo bǎn', meaning: 'ông chủ' },
{ hanzi: '老婆', pinyin: 'lǎo pó', meaning: 'bà xã' },
{ hanzi: '老实', pinyin: 'lǎo shí', meaning: 'thật thà' },
{ hanzi: '老鼠', pinyin: 'lǎo shǔ', meaning: 'con chuột' },
{ hanzi: '姥姥', pinyin: 'lǎo lǎo', meaning: 'bà ngoại' },
{ hanzi: '乐观', pinyin: 'lè guān', meaning: 'lạc quan' },
{ hanzi: '雷', pinyin: 'léi', meaning: 'sấm' },
{ hanzi: '类型', pinyin: 'lèi xíng', meaning: 'loại hình' },
{ hanzi: '冷淡', pinyin: 'lěng dàn', meaning: 'lãnh đạm, lạnh nhạt, lạnh lùng' },
{ hanzi: '厘米', pinyin: 'lí mǐ', meaning: 'cm' },
{ hanzi: '离婚', pinyin: 'lí hūn', meaning: 'li hôn' },
{ hanzi: '梨', pinyin: 'lí', meaning: 'quả lê' },
{ hanzi: '理论', pinyin: 'lǐ lùn', meaning: 'lý luận' },
{ hanzi: '理由', pinyin: 'lǐ yóu', meaning: 'lí do' },
{ hanzi: '力量', pinyin: 'lì liàng', meaning: 'sức mạnh' },
{ hanzi: '立即', pinyin: 'lì jí', meaning: 'lập tức' },
{ hanzi: '立刻', pinyin: 'lì kè', meaning: 'lập tức' },
{ hanzi: '利润', pinyin: 'lì rùn', meaning: 'lợi nhuận' },
{ hanzi: '利息', pinyin: 'lì xī', meaning: 'lợi tức' },
{ hanzi: '利益', pinyin: 'lì yì', meaning: 'lợi ích' },
{ hanzi: '利用', pinyin: 'lì yòng', meaning: 'tận dụng, lợi dụng' },
{ hanzi: '连忙', pinyin: 'lián máng', meaning: 'vội vã' },
{ hanzi: '连续', pinyin: 'lián xù', meaning: 'liên tục' },
{ hanzi: '联合', pinyin: 'lián hé', meaning: 'liên hiệp' },
{ hanzi: '恋爱', pinyin: 'liàn ài', meaning: 'yêu đương' },
{ hanzi: '良好', pinyin: 'liáng hǎo', meaning: 'tốt đẹp' },
{ hanzi: '粮食', pinyin: 'liáng shí', meaning: 'lương thực' },
{ hanzi: '亮', pinyin: 'liàng', meaning: 'sáng' },
{ hanzi: '了不起', pinyin: 'liǎo bù qǐ', meaning: 'giỏi giang' },
{ hanzi: '列车', pinyin: 'liè chē', meaning: 'tàu hỏa' },
{ hanzi: '临时', pinyin: 'lín shí', meaning: 'lâm thời, thời vụ, tạm thời' },
{ hanzi: '灵活', pinyin: 'líng huó', meaning: 'linh hoạt' },
{ hanzi: '铃', pinyin: 'líng', meaning: 'chuông' },
{ hanzi: '零件', pinyin: 'líng jiàn', meaning: 'linh kiện' },
{ hanzi: '零食', pinyin: 'líng shí', meaning: 'đồ ăn vặt' },
{ hanzi: '领导', pinyin: 'lǐng dǎo', meaning: 'lãnh đạo' },
{ hanzi: '领域', pinyin: 'lǐng yù', meaning: 'lĩnh vực' },
{ hanzi: '浏览', pinyin: 'liú lǎn', meaning: 'đọc lướt' },
{ hanzi: '流传', pinyin: 'liú chuán', meaning: 'lưu truyền, lan truyền' },
{ hanzi: '流泪', pinyin: 'liú lèi', meaning: 'rơi lệ' },
{ hanzi: '龙', pinyin: 'lóng', meaning: 'rồng' },
{ hanzi: '漏', pinyin: 'lòu', meaning: 'dột' },
{ hanzi: '陆地', pinyin: 'lù dì', meaning: 'lục địa, đất liền' },
{ hanzi: '陆续', pinyin: 'lù xù', meaning: 'lục tục, liên tiếp' },
{ hanzi: '录取', pinyin: 'lù qǔ', meaning: 'tuyển chọn' },
{ hanzi: '录音', pinyin: 'lù yīn', meaning: 'ghi âm' },
{ hanzi: '轮流', pinyin: 'lún liú', meaning: 'luân lưu, thay phiên' },
{ hanzi: '论文', pinyin: 'lùn wén', meaning: 'luận văn' },
{ hanzi: '逻辑', pinyin: 'luó jí', meaning: 'logic' },
{ hanzi: '落后', pinyin: 'luò hòu', meaning: 'lạc hậu' },
{ hanzi: '骂', pinyin: 'mà', meaning: 'mắng mỏ' },
{ hanzi: '麦克风', pinyin: 'mài kè fēng', meaning: 'microphone' },
{ hanzi: '馒头', pinyin: 'mán tóu', meaning: 'bánh bao không nhân, màn thầu' },
{ hanzi: '满足', pinyin: 'mǎn zú', meaning: 'đáp ứng (yêu cầu, điều kiện, tính tò mò, lòng tham)' },
{ hanzi: '毛病', pinyin: 'máo bìng', meaning: 'tật xấu, lỗi' },
{ hanzi: '矛盾', pinyin: 'máo dùn', meaning: 'mâu thuẫn' },
{ hanzi: '冒险', pinyin: 'mào xiǎn', meaning: 'mạo hiểm' },
{ hanzi: '贸易', pinyin: 'mào yì', meaning: 'thương mại' },
{ hanzi: '眉毛', pinyin: 'méi máo', meaning: 'lông mày' },
{ hanzi: '媒体', pinyin: 'méi tǐ', meaning: 'truyền thông, báo chí' },
{ hanzi: '煤炭', pinyin: 'méi tàn', meaning: 'than' },
{ hanzi: '美术', pinyin: 'měi shù', meaning: 'mỹ thuật' },
{ hanzi: '魅力', pinyin: 'mèi lì', meaning: 'sức hút' },
{ hanzi: '梦想', pinyin: 'mèng xiǎng', meaning: 'ước mơ' },
{ hanzi: '秘密', pinyin: 'mì mì', meaning: 'bí mật' },
{ hanzi: '秘书', pinyin: 'mì shū', meaning: 'thư ký' },
{ hanzi: '密切', pinyin: 'mì qiè', meaning: 'mật thiết' },
{ hanzi: '蜜蜂', pinyin: 'mì fēng', meaning: 'con ong' },
{ hanzi: '面对', pinyin: 'miàn duì', meaning: 'đối mặt (chứng cứ, tương lai, khủng hoảng, thách thức), đối diện' },
{ hanzi: '面积', pinyin: 'miàn jī', meaning: 'diện tích' },
{ hanzi: '面临', pinyin: 'miàn lín', meaning: 'đứng trước (khó khăn, nguy hiểm, thách thức)' },
{ hanzi: '苗条', pinyin: 'miáo tiáo', meaning: 'thon thả' },
{ hanzi: '描写', pinyin: 'miáo xiě', meaning: 'miêu tả' },
{ hanzi: '敏感', pinyin: 'mǐn gǎn', meaning: 'nhạy cảm' },
{ hanzi: '名牌', pinyin: 'míng pái', meaning: 'thương hiệu nổi tiếng' },
{ hanzi: '名片', pinyin: 'míng piàn', meaning: 'danh thiếp' },
{ hanzi: '名胜古迹', pinyin: 'míng shèng gǔ jì', meaning: 'danh lam thắng cảnh' },
{ hanzi: '明确', pinyin: 'míng què', meaning: 'rõ ràng, rành mạch' },
{ hanzi: '明显', pinyin: 'míng xiǎn', meaning: 'rõ ràng' },
{ hanzi: '明星', pinyin: 'míng xīng', meaning: 'minh tinh' },
{ hanzi: '命令', pinyin: 'mìng lìng', meaning: 'mệnh lệnh' },
{ hanzi: '命运', pinyin: 'mìng yùn', meaning: 'vận mệnh' },
{ hanzi: '摸', pinyin: 'mō', meaning: 'sờ' },
{ hanzi: '模仿', pinyin: 'mó fǎng', meaning: 'bắt chước' },
{ hanzi: '模糊', pinyin: 'mó hu', meaning: 'mơ hồ' },
{ hanzi: '模特', pinyin: 'mó tè', meaning: 'người mẫu' },
{ hanzi: '摩托车', pinyin: 'mó tuō chē', meaning: 'xe máy' },
{ hanzi: '陌生', pinyin: 'mò shēng', meaning: 'lạ lẫm' },
{ hanzi: '某', pinyin: 'mǒu', meaning: 'nào đó' },
{ hanzi: '木头', pinyin: 'mù tóu', meaning: 'khúc gỗ' },
{ hanzi: '目标', pinyin: 'mù biāo', meaning: 'mục tiêu' },
{ hanzi: '目录', pinyin: 'mù lù', meaning: 'mục lục' },
{ hanzi: '目前', pinyin: 'mù qián', meaning: 'trước mắt, hiện nay' },
{ hanzi: '哪怕', pinyin: 'nǎ pà', meaning: 'cho dù' },
{ hanzi: '难怪', pinyin: 'nán guài', meaning: 'chẳng trách' },
{ hanzi: '难免', pinyin: 'nán miǎn', meaning: 'khó tránh' },
{ hanzi: '脑袋', pinyin: 'nǎo dài', meaning: 'não' },
{ hanzi: '内部', pinyin: 'nèi bù', meaning: 'nội bộ' },
{ hanzi: '内科', pinyin: 'nèi kē', meaning: 'khoa nội' },
{ hanzi: '嫩', pinyin: 'nèn', meaning: 'mềm, non' },
{ hanzi: '能干', pinyin: 'néng gàn', meaning: 'được việc' },
{ hanzi: '能源', pinyin: 'néng yuán', meaning: 'tài nguyên' },
{ hanzi: '嗯', pinyin: 'ēn', meaning: 'ừ, ừm' },
{ hanzi: '年代', pinyin: 'nián dài', meaning: 'thời đại' },
{ hanzi: '年纪', pinyin: 'nián jì', meaning: 'tuổi tác' },
{ hanzi: '念', pinyin: 'niàn', meaning: 'đọc' },
{ hanzi: '宁可', pinyin: 'nìng kě', meaning: 'thà' },
{ hanzi: '牛仔裤', pinyin: 'niú zǎi kù', meaning: 'quần bò' },
{ hanzi: '农村', pinyin: 'nóng cūn', meaning: 'nông thôn' },
{ hanzi: '农民', pinyin: 'nóng mín', meaning: 'nông dân' },
{ hanzi: '农业', pinyin: 'nóng yè', meaning: 'nông nghiệp' },
{ hanzi: '浓', pinyin: 'nóng', meaning: 'nồng, đậm' },
{ hanzi: '女士', pinyin: 'nǚ shì', meaning: 'quý cô, quý bà' },
{ hanzi: '欧洲', pinyin: 'ōu zhōu', meaning: 'châu Âu' },
{ hanzi: '偶然', pinyin: 'ǒu rán', meaning: 'ngẫu nhiên' },
{ hanzi: '拍', pinyin: 'pāi', meaning: 'vỗ' },
{ hanzi: '派', pinyin: 'pài', meaning: 'cử, phái' },
{ hanzi: '盼望', pinyin: 'pàn wàng', meaning: 'mong chờ' },
{ hanzi: '培训', pinyin: 'péi xùn', meaning: 'bồi dưỡng, tập huấn' },
{ hanzi: '培养', pinyin: 'péi yǎng', meaning: 'nuôi dưỡng, hình thành' },
{ hanzi: '赔偿', pinyin: 'péi cháng', meaning: 'bồi thường' },
{ hanzi: '佩服', pinyin: 'pèi fú', meaning: 'khâm phục' },
{ hanzi: '配合', pinyin: 'pèi hé', meaning: 'phối hợp' },
{ hanzi: '盆', pinyin: 'pén', meaning: 'chậu' },
{ hanzi: '碰', pinyin: 'pèng', meaning: 'gặp phải, đụng phải' },
{ hanzi: '批', pinyin: 'pī', meaning: 'loạt, lô (lượng từ)' },
{ hanzi: '批准', pinyin: 'pī zhǔn', meaning: 'phê chuẩn, đồng ý' },
{ hanzi: '披', pinyin: 'pī', meaning: 'khoác' },
{ hanzi: '疲劳', pinyin: 'pí láo', meaning: 'mệt mỏi' },
{ hanzi: '匹', pinyin: 'pǐ', meaning: 'con (lượng từ cho ngựa)' },
{ hanzi: '片', pinyin: 'piàn', meaning: 'chiếc, lát, mảnh (lượng từ cho lá, bánh mì, đất đai )' },
{ hanzi: '片面', pinyin: 'piàn miàn', meaning: 'phiến diện' },
{ hanzi: '飘', pinyin: 'piāo', meaning: 'bay' },
{ hanzi: '拼音', pinyin: 'pīn yīn', meaning: 'phiên âm' },
{ hanzi: '频道', pinyin: 'pín dào', meaning: 'kênh' },
{ hanzi: '平', pinyin: 'píng', meaning: 'bằng, đều' },
{ hanzi: '平安', pinyin: 'píng ān', meaning: 'bình an' },
{ hanzi: '平常', pinyin: 'píng cháng', meaning: 'bình thường' },
{ hanzi: '平等', pinyin: 'píng děng', meaning: 'bình đẳng' },
{ hanzi: '平方', pinyin: 'píng fāng', meaning: 'bình phương' },
{ hanzi: '平衡', pinyin: 'píng héng', meaning: 'cân bằng' },
{ hanzi: '平静', pinyin: 'píng jìng', meaning: 'bình tĩnh, tĩnh lặng, yên tĩnh' },
{ hanzi: '平均', pinyin: 'píng jūn', meaning: 'trung bình, bình quân' },
{ hanzi: '评价', pinyin: 'píng jià', meaning: 'đánh giá' },
{ hanzi: '凭', pinyin: 'píng', meaning: 'dựa vào' },
{ hanzi: '迫切', pinyin: 'pò qiè', meaning: 'cấp bách' },
{ hanzi: '破产', pinyin: 'pò chǎn', meaning: 'phá sản' },
{ hanzi: '破坏', pinyin: 'pò huài', meaning: 'phá hoại' },
{ hanzi: '期待', pinyin: 'qī dài', meaning: 'kỳ vọng' },
{ hanzi: '期间', pinyin: 'qī jiān', meaning: 'khoảng thời gian' },
{ hanzi: '其余', pinyin: 'qí yú', meaning: 'còn lại' },
{ hanzi: '奇迹', pinyin: 'qí jì', meaning: 'kỳ tích' },
{ hanzi: '企业', pinyin: 'qǐ yè', meaning: 'nhà máy, xí nghiệp' },
{ hanzi: '启发', pinyin: 'qǐ fā', meaning: 'gợi mở, gợi ý' },
{ hanzi: '气氛', pinyin: 'qì fēn', meaning: 'không khí (cuộc họp, buổi tiệc)' },
{ hanzi: '汽油', pinyin: 'qì yóu', meaning: 'xăng' },
{ hanzi: '谦虚', pinyin: 'qiān xū', meaning: 'khiêm tốn' },
{ hanzi: '签', pinyin: 'qiān', meaning: 'ký (tên)' },
{ hanzi: '前途', pinyin: 'qián tú', meaning: 'tiền đồ' },
{ hanzi: '浅', pinyin: 'qiǎn', meaning: 'nông' },
{ hanzi: '欠', pinyin: 'qiàn', meaning: 'nợ' },
{ hanzi: '枪', pinyin: 'qiāng', meaning: 'súng' },
{ hanzi: '强调', pinyin: 'qiáng diào', meaning: 'nhấn mạnh' },
{ hanzi: '强烈', pinyin: 'qiáng liè', meaning: 'mãnh liệt, mạnh mẽ' },
{ hanzi: '墙', pinyin: 'qiáng', meaning: 'tường' },
{ hanzi: '抢', pinyin: 'qiǎng', meaning: 'cướp' },
{ hanzi: '悄悄', pinyin: 'qiāo qiāo', meaning: 'lặng lẽ' },
{ hanzi: '瞧', pinyin: 'qiáo', meaning: 'liếc nhìn' },
{ hanzi: '巧妙', pinyin: 'qiǎo miào', meaning: 'khéo léo' },
{ hanzi: '切', pinyin: 'qiè', meaning: 'cắt' },
{ hanzi: '亲爱', pinyin: 'qīn ài', meaning: 'thân yêu' },
{ hanzi: '亲切', pinyin: 'qīn qiè', meaning: 'thân thiết' },
{ hanzi: '亲自', pinyin: 'qīn zì', meaning: 'tự thân' },
{ hanzi: '勤奋', pinyin: 'qín fèn', meaning: 'cần cù' },
{ hanzi: '青', pinyin: 'qīng', meaning: 'màu xanh non' },
{ hanzi: '青春', pinyin: 'qīng chūn', meaning: 'thanh xuân' },
{ hanzi: '青少年', pinyin: 'qīng shào nián', meaning: 'thanh thiếu niên' },
{ hanzi: '轻视', pinyin: 'qīng shì', meaning: 'coi khinh, khinh thường' },
{ hanzi: '轻易', pinyin: 'qīng yì', meaning: 'dễ dàng (làm trạng ngữ), khinh suất' },
{ hanzi: '清淡', pinyin: 'qīng dàn', meaning: 'thanh đạm' },
{ hanzi: '情景', pinyin: 'qíng jǐng', meaning: 'cảnh tượng' },
{ hanzi: '情绪', pinyin: 'qíng xù', meaning: 'tâm trạng' },
{ hanzi: '请求', pinyin: 'qǐng qiú', meaning: 'thỉnh cầu' },
{ hanzi: '庆祝', pinyin: 'qìng zhù', meaning: 'chúc mừng' },
{ hanzi: '球迷', pinyin: 'qiú mí', meaning: 'người hâm mộ bóng' },
{ hanzi: '趋势', pinyin: 'qū shì', meaning: 'xu thế' },
{ hanzi: '取消', pinyin: 'qǔ xiāo', meaning: 'hủy bỏ' },
{ hanzi: '娶', pinyin: 'qǔ', meaning: 'lấy (vợ)' },
{ hanzi: '去世', pinyin: 'qù shì', meaning: 'tạ thế' },
{ hanzi: '圈', pinyin: 'quān', meaning: 'vòng' },
{ hanzi: '权力', pinyin: 'quán lì', meaning: 'quyền lực' },
{ hanzi: '权利', pinyin: 'quán lì', meaning: 'quyền lợi' },
{ hanzi: '全面', pinyin: 'quán miàn', meaning: 'toàn diện' },
{ hanzi: '劝', pinyin: 'quàn', meaning: 'khuyên' },
{ hanzi: '缺乏', pinyin: 'quē fá', meaning: 'thiếu' },
{ hanzi: '确定', pinyin: 'què dìng', meaning: 'xác định' },
{ hanzi: '确认', pinyin: 'què rèn', meaning: 'xác nhận' },
{ hanzi: '群', pinyin: 'qún', meaning: 'đám, nhóm' },
{ hanzi: '燃烧', pinyin: 'rán shāo', meaning: 'đốt cháy' },
{ hanzi: '绕', pinyin: 'rào', meaning: 'vòng vèo' },
{ hanzi: '热爱', pinyin: 'rè ài', meaning: 'yêu (cuộc sống, học sinh, thiên nhiên, âm nhạc, bạn bè, người thân)' },
{ hanzi: '热烈', pinyin: 'rè liè', meaning: 'nhiệt liệt' },
{ hanzi: '热心', pinyin: 'rè xīn', meaning: 'nhiệt tình (người, người bạn), nhiệt huyết' },
{ hanzi: '人才', pinyin: 'rén cái', meaning: 'nhân tài' },
{ hanzi: '人口', pinyin: 'rén kǒu', meaning: 'dân số' },
{ hanzi: '人类', pinyin: 'rén lèi', meaning: 'loài người' },
{ hanzi: '人民币', pinyin: 'rén mín bì', meaning: 'nhân dân tệ' },
{ hanzi: '人生', pinyin: 'rén shēng', meaning: 'đời người' },
{ hanzi: '人事', pinyin: 'rén shì', meaning: 'nhân sự' },
{ hanzi: '人物', pinyin: 'rén wù', meaning: 'nhân vật' },
{ hanzi: '人员', pinyin: 'rén yuán', meaning: 'nhân viên' },
{ hanzi: '忍不住', pinyin: 'rěn bù zhù', meaning: 'không nhịn được' },
{ hanzi: '日常', pinyin: 'rì cháng', meaning: 'thường ngày' },
{ hanzi: '日程', pinyin: 'rì chéng', meaning: 'lịch trình' },
{ hanzi: '日历', pinyin: 'rì lì', meaning: 'quyển lịch' },
{ hanzi: '日期', pinyin: 'rì qī', meaning: 'ngày tháng' },
{ hanzi: '日用品', pinyin: 'rì yòng pǐn', meaning: 'đồ dùng' },
{ hanzi: '日子', pinyin: 'rì zi', meaning: 'ngày' },
{ hanzi: '如何', pinyin: 'rú hé', meaning: 'như thế nào' },
{ hanzi: '如今', pinyin: 'rú jīn', meaning: 'hiện nay' },
{ hanzi: '软', pinyin: 'ruǎn', meaning: 'mềm' },
{ hanzi: '软件', pinyin: 'ruǎn jiàn', meaning: 'phần mềm' },
{ hanzi: '弱', pinyin: 'ruò', meaning: 'yếu ớt' },
{ hanzi: '洒', pinyin: 'sǎ', meaning: 'vãi, vung' },
{ hanzi: '嗓子', pinyin: 'sǎng zi', meaning: 'cổ họng' },
{ hanzi: '色彩', pinyin: 'sè cǎi', meaning: 'màu sắc' },
{ hanzi: '杀', pinyin: 'shā', meaning: 'giết' },
{ hanzi: '沙漠', pinyin: 'shā mò', meaning: 'sa mạc' },
{ hanzi: '沙滩', pinyin: 'shā tān', meaning: 'bãi cát' },
{ hanzi: '傻', pinyin: 'shǎ', meaning: 'ngốc nghếch' },
{ hanzi: '晒', pinyin: 'shài', meaning: 'phơi, tắm nắng' },
{ hanzi: '删除', pinyin: 'shān chú', meaning: 'xóa bỏ' },
{ hanzi: '闪电', pinyin: 'shǎn diàn', meaning: 'chớp' },
{ hanzi: '扇子', pinyin: 'shàn zi', meaning: 'cái quạt' },
{ hanzi: '善良', pinyin: 'shàn liáng', meaning: 'lương thiện, hiền lành' },
{ hanzi: '善于', pinyin: 'shàn yú', meaning: 'giỏi về việc gì đó' },
{ hanzi: '伤害', pinyin: 'shāng hài', meaning: 'làm hại' },
{ hanzi: '商品', pinyin: 'shāng pǐn', meaning: 'sản phẩm' },
{ hanzi: '商务', pinyin: 'shāng wù', meaning: 'thương gia (hạng, khoang),' },
{ hanzi: '商业', pinyin: 'shāng yè', meaning: 'thương mại' },
{ hanzi: '上当', pinyin: 'shàng dàng', meaning: 'mắc lừa' },
{ hanzi: '蛇', pinyin: 'shé', meaning: 'rắn' },
{ hanzi: '舍不得', pinyin: 'shě bù dé', meaning: 'không nỡ lòng' },
{ hanzi: '设备', pinyin: 'shè bèi', meaning: 'thiết bị' },
{ hanzi: '设计', pinyin: 'shè jì', meaning: 'thiết kế' },
{ hanzi: '设施', pinyin: 'shè shī', meaning: 'cơ sở vật chất' },
{ hanzi: '射击', pinyin: 'shè jī', meaning: 'bắn' },
{ hanzi: '摄影', pinyin: 'shè yǐng', meaning: 'quay phim, chụp ảnh' },
{ hanzi: '伸', pinyin: 'shēn', meaning: 'vươn, duỗi, kéo dài' },
{ hanzi: '身材', pinyin: 'shēn cái', meaning: 'cơ thể, dáng' },
{ hanzi: '身份', pinyin: 'shēn fèn', meaning: 'thân phận' },
{ hanzi: '深刻', pinyin: 'shēn kè', meaning: 'sâu sắc' },
{ hanzi: '神话', pinyin: 'shén huà', meaning: 'thần thoại' },
{ hanzi: '神秘', pinyin: 'shén mì', meaning: 'thần bí' },
{ hanzi: '升', pinyin: 'shēng', meaning: 'thăng, lên, lít (đơn vị đo thể tích)' },
{ hanzi: '生产', pinyin: 'shēng chǎn', meaning: 'sản xuất' },
{ hanzi: '生动', pinyin: 'shēng dòng', meaning: 'sinh động' },
{ hanzi: '生长', pinyin: 'shēng zhǎng', meaning: 'sinh trưởng, lớn' },
{ hanzi: '声调', pinyin: 'shēng diào', meaning: 'thanh điệu' },
{ hanzi: '绳子', pinyin: 'shéng zi', meaning: 'dây thừng' },
{ hanzi: '省略', pinyin: 'shěng lüè', meaning: 'tỉnh lược' },
{ hanzi: '胜利', pinyin: 'shèng lì', meaning: 'thắng lợi' },
{ hanzi: '失眠', pinyin: 'shī mián', meaning: 'mất ngủ' },
{ hanzi: '失去', pinyin: 'shī qù', meaning: 'mất đi' },
{ hanzi: '失业', pinyin: 'shī yè', meaning: 'thất nghiệp' },
{ hanzi: '诗', pinyin: 'shī', meaning: 'thơ' },
{ hanzi: '狮子', pinyin: 'shī zi', meaning: 'sư tử' },
{ hanzi: '湿润', pinyin: 'shī rùn', meaning: 'ẩm ướt' },
{ hanzi: '石头', pinyin: 'shí tou', meaning: 'hòn đá' },
{ hanzi: '时差', pinyin: 'shí chā', meaning: 'lệch múi giờ' },
{ hanzi: '时代', pinyin: 'shí dài', meaning: 'thời đại' },
{ hanzi: '时刻', pinyin: 'shí kè', meaning: 'khoảnh khắc' },
{ hanzi: '时髦', pinyin: 'shí máo', meaning: 'mốt' },
{ hanzi: '时期', pinyin: 'shí qī', meaning: 'thời kì' },
{ hanzi: '时尚', pinyin: 'shí shàng', meaning: 'thời thượng' },
{ hanzi: '实话', pinyin: 'shí huà', meaning: 'lời nói thật' },
{ hanzi: '实践', pinyin: 'shí jiàn', meaning: 'thực tiễn' },
{ hanzi: '实习', pinyin: 'shí xí', meaning: 'thực tập' },
{ hanzi: '实现', pinyin: 'shí xiàn', meaning: 'thực hiện (kế hoạch, nguyện vọng, ước mơ)' },
{ hanzi: '实验', pinyin: 'shí yàn', meaning: 'thí nghiệm' },
{ hanzi: '实用', pinyin: 'shí yòng', meaning: 'hữu ích' },
{ hanzi: '食物', pinyin: 'shí wù', meaning: 'đồ ăn' },
{ hanzi: '使劲儿', pinyin: 'shǐ jìn ér', meaning: 'ra sức, lấy sức' },
{ hanzi: '始终', pinyin: 'shǐ zhōng', meaning: 'từ đầu đến cuối' },
{ hanzi: '士兵', pinyin: 'shì bīng', meaning: 'binh sĩ' },
{ hanzi: '市场', pinyin: 'shì chǎng', meaning: 'chợ' },
{ hanzi: '似的', pinyin: 'shì de', meaning: 'giống như….' },
{ hanzi: '事实', pinyin: 'shì shí', meaning: 'sự thật' },
{ hanzi: '事物', pinyin: 'shì wù', meaning: 'sự vật' },
{ hanzi: '事先', pinyin: 'shì xiān', meaning: 'trước khi việc xảy ra' },
{ hanzi: '试卷', pinyin: 'shì juàn', meaning: 'bài thi' },
{ hanzi: '收获', pinyin: 'shōu huò', meaning: 'thu hoạch' },
{ hanzi: '收据', pinyin: 'shōu jù', meaning: 'giấy biên nhận' },
{ hanzi: '手工', pinyin: 'shǒu gōng', meaning: 'thủ công' },
{ hanzi: '手术', pinyin: 'shǒu shù', meaning: 'phẫu thuật' },
{ hanzi: '手套', pinyin: 'shǒu tào', meaning: 'găng tay' },
{ hanzi: '手续', pinyin: 'shǒu xù', meaning: 'thủ tục' },
{ hanzi: '手指', pinyin: 'shǒu zhǐ', meaning: 'ngón tay' },
{ hanzi: '首', pinyin: 'shǒu', meaning: 'đầu' },
{ hanzi: '寿命', pinyin: 'shòu mìng', meaning: 'tuổi thọ' },
{ hanzi: '受伤', pinyin: 'shòu shāng', meaning: 'bị thương' },
{ hanzi: '书架', pinyin: 'shū jià', meaning: 'giá sách' },
{ hanzi: '梳子', pinyin: 'shū zi', meaning: 'cái lược' },
{ hanzi: '舒适', pinyin: 'shū shì', meaning: 'thoải mái' },
{ hanzi: '输入', pinyin: 'shū rù', meaning: 'nhập' },
{ hanzi: '蔬菜', pinyin: 'shū cài', meaning: 'rau xanh' },
{ hanzi: '熟练', pinyin: 'shú liàn', meaning: 'thành thục' },
{ hanzi: '属于', pinyin: 'shǔ yú', meaning: 'thuộc về' },
{ hanzi: '鼠标', pinyin: 'shǔ biāo', meaning: 'chuột máy tính' },
{ hanzi: '数', pinyin: 'shǔ', meaning: 'đếm' },
{ hanzi: '数据', pinyin: 'shù jù', meaning: 'số liệu' },
{ hanzi: '数码', pinyin: 'shù mǎ', meaning: 'kỹ thuật số' },
{ hanzi: '摔倒', pinyin: 'shuāi dǎo', meaning: 'ngã nhào' },
{ hanzi: '甩', pinyin: 'shuǎi', meaning: 'vung, hất, bỏ lại' },
{ hanzi: '双方', pinyin: 'shuāng fāng', meaning: 'hai bên, song phương' },
{ hanzi: '税', pinyin: 'shuì', meaning: 'thuế' },
{ hanzi: '说不定', pinyin: 'shuō bù dìng', meaning: 'chưa biết chừng' },
{ hanzi: '说服', pinyin: 'shuō fú', meaning: 'thuyết phục' },
{ hanzi: '丝绸', pinyin: 'sī chóu', meaning: 'tơ lụa' },
{ hanzi: '丝毫', pinyin: 'sī háo', meaning: 'một chút (dùng dạng phủ định)' },
{ hanzi: '私人', pinyin: 'sī rén', meaning: 'tư nhân' },
{ hanzi: '思考', pinyin: 'sī kǎo', meaning: 'suy nghĩ' },
{ hanzi: '思想', pinyin: 'sī xiǎng', meaning: 'tư tưởng' },
{ hanzi: '撕', pinyin: 'sī', meaning: 'xé' },
{ hanzi: '似乎', pinyin: 'sì hū', meaning: 'dường như' },
{ hanzi: '搜索', pinyin: 'sōu suǒ', meaning: 'tìm kiếm' },
{ hanzi: '宿舍', pinyin: 'sù shè', meaning: 'ký túc xá' },
{ hanzi: '随身', pinyin: 'suí shēn', meaning: 'mang theo người' },
{ hanzi: '随时', pinyin: 'suí shí', meaning: 'bất cứ lúc nào' },
{ hanzi: '随手', pinyin: 'suí shǒu', meaning: 'tiện tay' },
{ hanzi: '碎', pinyin: 'suì', meaning: 'vỡ vụn' },
{ hanzi: '损失', pinyin: 'sǔn shī', meaning: 'tổn thất' },
{ hanzi: '缩短', pinyin: 'suō duǎn', meaning: 'thu hẹp (khoảng cách), rút ngắn (thời gian), cắt ngắn (câu chuyện)' },
{ hanzi: '所', pinyin: 'suǒ', meaning: 'trợ từ' },
{ hanzi: '锁', pinyin: 'suǒ', meaning: 'khóa' },
{ hanzi: '台阶', pinyin: 'tái jiē', meaning: 'bậc thềm, bậc' },
{ hanzi: '太极拳', pinyin: 'tài jí quán', meaning: 'thái cực quyền' },
{ hanzi: '太太', pinyin: 'tài tai', meaning: 'vợ' },
{ hanzi: '谈判', pinyin: 'tán pàn', meaning: 'đàm phán' },
{ hanzi: '坦率', pinyin: 'tǎn shuài', meaning: 'thẳng thắn' },
{ hanzi: '烫', pinyin: 'tàng', meaning: 'bỏng, là, ủi' },
{ hanzi: '逃', pinyin: 'táo', meaning: 'chạy trốn' },
{ hanzi: '逃避', pinyin: 'táo bì', meaning: 'trốn tránh' },
{ hanzi: '桃', pinyin: 'táo', meaning: 'đào' },
{ hanzi: '淘气', pinyin: 'táo qì', meaning: 'tinh nghịch' },
{ hanzi: '讨价还价', pinyin: 'tǎo jià huán jià', meaning: 'mặc cả' },
{ hanzi: '套', pinyin: 'tào', meaning: 'bộ (quần áo), căn (nhà)' },
{ hanzi: '特色', pinyin: 'tè sè', meaning: 'đặc sắc, đặc điểm đặc sắc' },
{ hanzi: '特殊', pinyin: 'tè shū', meaning: 'đặc biệt, đặc thù (quan hệ, nghi lễ, yêu cầu, đãi ngộ)' },
{ hanzi: '特征', pinyin: 'tè zhēng', meaning: 'đặc trưng' },
{ hanzi: '疼爱', pinyin: 'téng ài', meaning: 'chiều chuộng, yêu chiều' },
{ hanzi: '提倡', pinyin: 'tí chàng', meaning: 'đề xướng' },
{ hanzi: '提纲', pinyin: 'tí gāng', meaning: 'đề cương' },
{ hanzi: '提问', pinyin: 'tí wèn', meaning: 'hỏi' },
{ hanzi: '题目', pinyin: 'tí mù', meaning: 'đề mục' },
{ hanzi: '体会', pinyin: 'tǐ huì', meaning: 'cảm nhận' },
{ hanzi: '体贴', pinyin: 'tǐ tiē', meaning: 'sống tình cảm, chu đáo' },
{ hanzi: '体现', pinyin: 'tǐ xiàn', meaning: 'thể hiện' },
{ hanzi: '体验', pinyin: 'tǐ yàn', meaning: 'trải nghiệm' },
{ hanzi: '天空', pinyin: 'tiān kōng', meaning: 'bầu trời' },
{ hanzi: '天真', pinyin: 'tiān zhēn', meaning: 'hồn nhiên' },
{ hanzi: '调皮', pinyin: 'tiáo pí', meaning: 'nghịch ngợm' },
{ hanzi: '调整', pinyin: 'tiáo zhěng', meaning: 'điều chỉnh' },
{ hanzi: '挑战', pinyin: 'tiǎo zhàn', meaning: 'thách thức, thử thách, thách' },
{ hanzi: '通常', pinyin: 'tōng cháng', meaning: 'thông thường' },
{ hanzi: '统一', pinyin: 'tǒng yī', meaning: 'thống nhất' },
{ hanzi: '痛苦', pinyin: 'tòng kǔ', meaning: 'đau khổ' },
{ hanzi: '痛快', pinyin: 'tòng kuài', meaning: 'sung sướng' },
{ hanzi: '偷', pinyin: 'tōu', meaning: 'ăn trộm' },
{ hanzi: '投入', pinyin: 'tóu rù', meaning: 'đút vào, đầu tư vào,' },
{ hanzi: '投资', pinyin: 'tóu zī', meaning: 'đầu tư' },
{ hanzi: '透明', pinyin: 'tòu míng', meaning: 'trong suốt' },
{ hanzi: '突出', pinyin: 'tū chū', meaning: 'làm nổi bật' },
{ hanzi: '土地', pinyin: 'tǔ dì', meaning: 'đất đai' },
{ hanzi: '土豆', pinyin: 'tǔ dòu', meaning: 'khoai tây' },
{ hanzi: '吐', pinyin: 'tǔ/tù', meaning: 'nhổ, nôn' },
{ hanzi: '兔子', pinyin: 'tù zi', meaning: 'con thỏ' },
{ hanzi: '团', pinyin: 'tuán', meaning: 'cuộn (danh từ)' },
{ hanzi: '推辞', pinyin: 'tuī cí', meaning: 'từ chối' },
{ hanzi: '推广', pinyin: 'tuī guǎng', meaning: 'quảng bá' },
{ hanzi: '推荐', pinyin: 'tuī jiàn', meaning: 'tiến cử' },
{ hanzi: '退', pinyin: 'tuì', meaning: 'lùi' },
{ hanzi: '退步', pinyin: 'tuì bù', meaning: 'lùi bước' },
{ hanzi: '退休', pinyin: 'tuì xiū', meaning: 'nghỉ hưu' },
{ hanzi: '歪', pinyin: 'wāi', meaning: 'xiên (nghiêng)' },
{ hanzi: '外公', pinyin: 'wài gōng', meaning: 'ông ngoại' },
{ hanzi: '外交', pinyin: 'wài jiāo', meaning: 'ngoại giao' },
{ hanzi: '完美', pinyin: 'wán měi', meaning: 'hoàn hảo' },
{ hanzi: '完善', pinyin: 'wán shàn', meaning: 'hoàn thiện' },
{ hanzi: '完整', pinyin: 'wán zhěng', meaning: 'hoàn chỉnh' },
{ hanzi: '玩具', pinyin: 'wán jù', meaning: 'đồ chơi' },
{ hanzi: '万一', pinyin: 'wàn yī', meaning: 'vạn nhất, nhỡ' },
{ hanzi: '王子', pinyin: 'wáng zǐ', meaning: 'vua' },
{ hanzi: '网络', pinyin: 'wǎng luò', meaning: 'mạng internet' },
{ hanzi: '往返', pinyin: 'wǎng fǎn', meaning: 'khứ hồi' },
{ hanzi: '危害', pinyin: 'wēi hài', meaning: 'nguy hại' },
{ hanzi: '威胁', pinyin: 'wēi xié', meaning: 'uy hiếp' },
{ hanzi: '微笑', pinyin: 'wēi xiào', meaning: 'mỉm cười' },
{ hanzi: '违反', pinyin: 'wéi fǎn', meaning: 'vi phạm' },
{ hanzi: '围巾', pinyin: 'wéi jīn', meaning: 'khăn' },
{ hanzi: '围绕', pinyin: 'wéi rào', meaning: 'xoay quanh, bao quanh, quay quanh' },
{ hanzi: '唯一', pinyin: 'wéi yī', meaning: 'duy nhất' },
{ hanzi: '维修', pinyin: 'wéi xiū', meaning: 'sửa chữa' },
{ hanzi: '伟大', pinyin: 'wěi dà', meaning: 'vĩ đại' },
{ hanzi: '尾巴', pinyin: 'wěi bā', meaning: 'cái đuôi' },
{ hanzi: '委屈', pinyin: 'wěi qu', meaning: 'tủi thân' },
{ hanzi: '未必', pinyin: 'wèi bì', meaning: 'chưa chắc' },
{ hanzi: '未来', pinyin: 'wèi lái', meaning: 'tương lai' },
{ hanzi: '位于', pinyin: 'wèi yú', meaning: 'nằm ở (vị trí địa lý)' },
{ hanzi: '位置', pinyin: 'wèi zhì', meaning: 'vị trí' },
{ hanzi: '胃', pinyin: 'wèi', meaning: 'dạ dày' },
{ hanzi: '胃口', pinyin: 'wèi kǒu', meaning: 'khẩu vị' },
{ hanzi: '温暖', pinyin: 'wēn nuǎn', meaning: 'ấm áp' },
{ hanzi: '温柔', pinyin: 'wēn róu', meaning: 'hiền dịu' },
{ hanzi: '文件', pinyin: 'wén jiàn', meaning: 'tài liệu' },
{ hanzi: '文具', pinyin: 'wén jù', meaning: 'đồ dùng học tập' },
{ hanzi: '文明', pinyin: 'wén míng', meaning: 'văn minh' },
{ hanzi: '文学', pinyin: 'wén xué', meaning: 'văn học' },
{ hanzi: '文字', pinyin: 'wén zì', meaning: 'văn tự' },
{ hanzi: '闻', pinyin: 'wén', meaning: 'ngửi' },
{ hanzi: '吻', pinyin: 'wěn', meaning: 'hôn' },
{ hanzi: '稳定', pinyin: 'wěn dìng', meaning: 'ổn định' },
{ hanzi: '问候', pinyin: 'wèn hòu', meaning: 'hỏi thăm' },
{ hanzi: '卧室', pinyin: 'wò shì', meaning: 'phòng ngủ' },
{ hanzi: '握手', pinyin: 'wò shǒu', meaning: 'bắt tay' },
{ hanzi: '屋子', pinyin: 'wū zi', meaning: 'căn nhà' },
{ hanzi: '无奈', pinyin: 'wú nài', meaning: 'bó tay, không có cách nào, bất lực' },
{ hanzi: '无数', pinyin: 'wú shù', meaning: 'vô số' },
{ hanzi: '无所谓', pinyin: 'wú suǒ wèi', meaning: 'không quan tâm, không để ý' },
{ hanzi: '武术', pinyin: 'wǔ shù', meaning: 'võ thuật' },
{ hanzi: '勿', pinyin: 'wù', meaning: 'đừng' },
{ hanzi: '物理', pinyin: 'wù lǐ', meaning: 'vật lý' },
{ hanzi: '物质', pinyin: 'wù zhì', meaning: 'vật chất' },
{ hanzi: '雾', pinyin: 'wù', meaning: 'sương mù' },
{ hanzi: '吸取', pinyin: 'xī qǔ', meaning: 'hút, rút ra (bài học kinh nghiệm)' },
{ hanzi: '吸收', pinyin: 'xī shōu', meaning: 'thẩm thấu, ngấm' },
{ hanzi: '戏剧', pinyin: 'xì jù', meaning: 'kịch' },
{ hanzi: '系', pinyin: 'xì', meaning: 'thắt, buộc' },
{ hanzi: '系统', pinyin: 'xì tǒng', meaning: 'hệ thống' },
{ hanzi: '细节', pinyin: 'xì jié', meaning: 'tình tiết' },
{ hanzi: '瞎', pinyin: 'xiā', meaning: 'mù' },
{ hanzi: '下载', pinyin: 'xià zǎi', meaning: 'tải' },
{ hanzi: '吓', pinyin: 'xià', meaning: 'dọa' },
{ hanzi: '夏令营', pinyin: 'xià lìng yíng', meaning: 'trại' },
{ hanzi: '鲜艳', pinyin: 'xiān yàn', meaning: 'tươi tắn' },
{ hanzi: '显得', pinyin: 'xiǎn dé', meaning: 'lộ rõ' },
{ hanzi: '显然', pinyin: 'xiǎn rán', meaning: 'hiển nhiên, rõ ràng' },
{ hanzi: '显示', pinyin: 'xiǎn shì', meaning: 'hiển thị, cho thấy, tôn lên' },
{ hanzi: '县', pinyin: 'xiàn', meaning: 'huyện' },
{ hanzi: '现代', pinyin: 'xiàn dài', meaning: 'hiện đại' },
{ hanzi: '现实', pinyin: 'xiàn shí', meaning: 'hiện thực' },
{ hanzi: '现象', pinyin: 'xiàn xiàng', meaning: 'hiện tượng' },
{ hanzi: '限制', pinyin: 'xiàn zhì', meaning: 'hạn chế, giới hạn' },
{ hanzi: '相处', pinyin: 'xiāng chǔ', meaning: 'ở cùng nhau, tiếp xúc nhiều' },
{ hanzi: '相当', pinyin: 'xiāng dāng', meaning: 'tương đối' },
{ hanzi: '相对', pinyin: 'xiāng duì', meaning: 'tương đối' },
{ hanzi: '相关', pinyin: 'xiāng guān', meaning: 'liên quan' },
{ hanzi: '相似', pinyin: 'xiāng sì', meaning: 'giống' },
{ hanzi: '香肠', pinyin: 'xiāng cháng', meaning: 'xúc xích' },
{ hanzi: '享受', pinyin: 'xiǎng shòu', meaning: 'hưởng thụ' },
{ hanzi: '想念', pinyin: 'xiǎng niàn', meaning: 'nhớ nhung' },
{ hanzi: '想象', pinyin: 'xiǎng xiàng', meaning: 'tưởng tượng' },
{ hanzi: '项', pinyin: 'xiàng', meaning: 'hạng, môn (thể thao)' },
{ hanzi: '项链', pinyin: 'xiàng liàn', meaning: 'dây chuyền' },
{ hanzi: '项目', pinyin: 'xiàng mù', meaning: 'hạng mục' },
{ hanzi: '象棋', pinyin: 'xiàng qí', meaning: 'cờ tướng' },
{ hanzi: '象征', pinyin: 'xiàng zhēng', meaning: 'tượng trưng' },
{ hanzi: '消费', pinyin: 'xiāo fèi', meaning: 'tiêu dùng' },
{ hanzi: '消化', pinyin: 'xiāo huà', meaning: 'tiêu hóa' },
{ hanzi: '消极', pinyin: 'xiāo jí', meaning: 'tiêu cực' },
{ hanzi: '消失', pinyin: 'xiāo shī', meaning: 'biến mất' },
{ hanzi: '销售', pinyin: 'xiāo shòu', meaning: 'bán' },
{ hanzi: '小麦', pinyin: 'xiǎo mài', meaning: 'lúa mạch' },
{ hanzi: '小气', pinyin: 'xiǎo qì', meaning: 'keo kiệt' },
{ hanzi: '孝顺', pinyin: 'xiào shùn', meaning: 'hiếu thảo' },
{ hanzi: '效率', pinyin: 'xiào lǜ', meaning: 'hiệu suất' },
{ hanzi: '歇', pinyin: 'xiē', meaning: 'nghỉ ngơi' },
{ hanzi: '斜', pinyin: 'xié', meaning: 'nghiêng, chéo' },
{ hanzi: '写作', pinyin: 'xiě zuò', meaning: 'viết' },
{ hanzi: '血', pinyin: 'xiě', meaning: 'máu' },
{ hanzi: '心理', pinyin: 'xīn lǐ', meaning: 'tâm lý' },
{ hanzi: '心脏', pinyin: 'xīn zàng', meaning: 'tim' },
{ hanzi: '欣赏', pinyin: 'xīn shǎng', meaning: 'thưởng thức, đánh giá cao' },
{ hanzi: '信号', pinyin: 'xìn hào', meaning: 'tín hiệu' },
{ hanzi: '信任', pinyin: 'xìn rèn', meaning: 'tín nhiệm' },
{ hanzi: '行动', pinyin: 'xíng dòng', meaning: 'hành động' },
{ hanzi: '行人', pinyin: 'xíng rén', meaning: 'người đi đường' },
{ hanzi: '行为', pinyin: 'xíng wéi', meaning: 'hành vi' },
{ hanzi: '形成', pinyin: 'xíng chéng', meaning: 'hình thành' },
{ hanzi: '形容', pinyin: 'xíng róng', meaning: 'hình dung' },
{ hanzi: '形式', pinyin: 'xíng shì', meaning: 'hình thức' },
{ hanzi: '形势', pinyin: 'xíng shì', meaning: 'tình hình' },
{ hanzi: '形象', pinyin: 'xíng xiàng', meaning: 'hình tượng' },
{ hanzi: '形状', pinyin: 'xíng zhuàng', meaning: 'hình dáng, dáng' },
{ hanzi: '幸亏', pinyin: 'xìng kuī', meaning: 'may mà' },
{ hanzi: '幸运', pinyin: 'xìng yùn', meaning: 'may mắn' },
{ hanzi: '性质', pinyin: 'xìng zhì', meaning: 'tính chất' },
{ hanzi: '兄弟', pinyin: 'xiōng dì', meaning: 'huynh đệ' },
{ hanzi: '胸', pinyin: 'xiōng', meaning: 'ngực' },
{ hanzi: '休闲', pinyin: 'xiū xián', meaning: 'nhàn hạ, thoải mái' },
{ hanzi: '修改', pinyin: 'xiū gǎi', meaning: 'sửa lỗi (văn bản)' },
{ hanzi: '虚心', pinyin: 'xū xīn', meaning: 'khiêm tốn' },
{ hanzi: '叙述', pinyin: 'xù shù', meaning: 'kể, thuật' },
{ hanzi: '宣布', pinyin: 'xuān bù', meaning: 'tuyên bố' },
{ hanzi: '宣传', pinyin: 'xuān chuán', meaning: 'tuyên truyền' },
{ hanzi: '学历', pinyin: 'xué lì', meaning: 'trình độ' },
{ hanzi: '学术', pinyin: 'xué shù', meaning: 'học thuật' },
{ hanzi: '学问', pinyin: 'xué wèn', meaning: 'học vấn' },
{ hanzi: '寻找', pinyin: 'xún zhǎo', meaning: 'tìm kiếm' },
{ hanzi: '询问', pinyin: 'xún wèn', meaning: 'hỏi han' },
{ hanzi: '训练', pinyin: 'xùn liàn', meaning: 'huấn luyện' },
{ hanzi: '迅速', pinyin: 'xùn sù', meaning: 'nhanh chóng, nhanh' },
{ hanzi: '押金', pinyin: 'yā jīn', meaning: 'tiền cọc' },
{ hanzi: '牙齿', pinyin: 'yá chǐ', meaning: 'răng' },
{ hanzi: '延长', pinyin: 'yán cháng', meaning: 'kéo dài (thời gian)' },
{ hanzi: '严肃', pinyin: 'yán sù', meaning: 'nghiêm túc' },
{ hanzi: '演讲', pinyin: 'yǎn jiǎng', meaning: 'diễn thuyết' },
{ hanzi: '宴会', pinyin: 'yàn huì', meaning: 'yến tiệc' },
{ hanzi: '阳台', pinyin: 'yáng tái', meaning: 'ban công' },
{ hanzi: '痒', pinyin: 'yǎng', meaning: 'ngứa' },
{ hanzi: '样式', pinyin: 'yàng shì', meaning: 'kiểu dáng' },
{ hanzi: '腰', pinyin: 'yāo', meaning: 'lưng' },
{ hanzi: '摇', pinyin: 'yáo', meaning: 'lắc' },
{ hanzi: '咬', pinyin: 'yǎo', meaning: 'cắn' },
{ hanzi: '要不', pinyin: 'yào bù', meaning: 'nếu không thì' },
{ hanzi: '业务', pinyin: 'yè wù', meaning: 'nghiệp vụ' },
{ hanzi: '业余', pinyin: 'yè yú', meaning: 'nghiệp dư' },
{ hanzi: '夜', pinyin: 'yè', meaning: 'đêm' },
{ hanzi: '一辈子', pinyin: 'yí bèi zi', meaning: 'một đời người' },
{ hanzi: '一旦', pinyin: 'yí dàn', meaning: 'một khi' },
{ hanzi: '一律', pinyin: 'yí lǜ', meaning: 'nhất loạt' },
{ hanzi: '一再', pinyin: 'yí zài', meaning: 'nhiều lần' },
{ hanzi: '一致', pinyin: 'yí zhì', meaning: 'thống nhất' },
{ hanzi: '依然', pinyin: 'yī rán', meaning: 'vẫn như xưa' },
{ hanzi: '移动', pinyin: 'yí dòng', meaning: 'di động' },
{ hanzi: '移民', pinyin: 'yí mín', meaning: 'di dân' },
{ hanzi: '遗憾', pinyin: 'yí hàn', meaning: 'hối tiếc' },
{ hanzi: '疑问', pinyin: 'yí wèn', meaning: 'nghi vấn, nghi ngờ' },
{ hanzi: '乙', pinyin: 'yǐ', meaning: 'ất' },
{ hanzi: '以及', pinyin: 'yǐ jí', meaning: 'và' },
{ hanzi: '以来', pinyin: 'yǐ lái', meaning: 'trở lại đây (thời gian)' },
{ hanzi: '亿', pinyin: 'yì', meaning: 'trăm triệu' },
{ hanzi: '义务', pinyin: 'yì wù', meaning: 'nghĩa vụ' },
{ hanzi: '议论', pinyin: 'yì lùn', meaning: 'nghị luận' },
{ hanzi: '意外', pinyin: 'yì wài', meaning: 'ngoài ý muốn' },
{ hanzi: '意义', pinyin: 'yì yì', meaning: 'ý nghĩa' },
{ hanzi: '因而', pinyin: 'yīn ér', meaning: 'cho nên' },
{ hanzi: '因素', pinyin: 'yīn sù', meaning: 'nhân tố' },
{ hanzi: '银', pinyin: 'yín', meaning: 'bạc' },
{ hanzi: '印刷', pinyin: 'yìn shuā', meaning: 'in ấn' },
{ hanzi: '英俊', pinyin: 'yīng jùn', meaning: 'tuấn tú' },
{ hanzi: '英雄', pinyin: 'yīng xióng', meaning: 'anh hùng' },
{ hanzi: '迎接', pinyin: 'yíng jiē', meaning: 'nghênh đón' },
{ hanzi: '营养', pinyin: 'yíng yǎng', meaning: 'dinh dưỡng' },
{ hanzi: '营业', pinyin: 'yíng yè', meaning: 'kinh doanh' },
{ hanzi: '影子', pinyin: 'yǐng zi', meaning: 'cái bóng' },
{ hanzi: '应付', pinyin: 'yìng fù', meaning: 'ứng phó' },
{ hanzi: '应用', pinyin: 'yìng yòng', meaning: 'ứng dụng' },
{ hanzi: '硬', pinyin: 'yìng', meaning: 'cứng' },
{ hanzi: '硬件', pinyin: 'yìng jiàn', meaning: 'phần cứng' },
{ hanzi: '拥抱', pinyin: 'yōng bào', meaning: 'ôm, ôm ấp' },
{ hanzi: '拥挤', pinyin: 'yōng jǐ', meaning: 'chen chúc, đông đúc' },
{ hanzi: '勇气', pinyin: 'yǒng qì', meaning: 'dũng khí' },
{ hanzi: '用功', pinyin: 'yòng gōng', meaning: 'dụng công, công phu' },
{ hanzi: '用途', pinyin: 'yòng tú', meaning: 'cách dùng' },
{ hanzi: '优惠', pinyin: 'yōu huì', meaning: 'ưu đãi' },
{ hanzi: '优美', pinyin: 'yōu měi', meaning: 'trang nhã, thanh lịch, thanh nhã, đẹp, xinh xắn' },
{ hanzi: '优势', pinyin: 'yōu shì', meaning: 'ưu thế' },
{ hanzi: '悠久', pinyin: 'yōu jiǔ', meaning: 'lâu đời' },
{ hanzi: '犹豫', pinyin: 'yóu yù', meaning: 'do dự' },
{ hanzi: '油炸', pinyin: 'yóu zhá', meaning: 'chiên giòn' },
{ hanzi: '游览', pinyin: 'yóu lǎn', meaning: 'du ngoạn, thưởng ngoạn' },
{ hanzi: '有利', pinyin: 'yǒu lì', meaning: 'có lợi' },
{ hanzi: '幼儿园', pinyin: 'yòu ér yuán', meaning: 'nhà trẻ' },
{ hanzi: '娱乐', pinyin: 'yú lè', meaning: 'giải trí' },
{ hanzi: '与其', pinyin: 'yǔ qí', meaning: 'thay vì' },
{ hanzi: '语气', pinyin: 'yǔ qì', meaning: 'ngữ khí' },
{ hanzi: '玉米', pinyin: 'yù mǐ', meaning: 'ngô' },
{ hanzi: '预报', pinyin: 'yù bào', meaning: 'dự báo' },
{ hanzi: '预订', pinyin: 'yù dìng', meaning: 'đặt trước, dự định trước' },
{ hanzi: '预防', pinyin: 'yù fáng', meaning: 'phòng, phòng chống' },
{ hanzi: '元旦', pinyin: 'yuán dàn', meaning: 'nguyên đán' },
{ hanzi: '员工', pinyin: 'yuán gōng', meaning: 'nhân công' },
{ hanzi: '原料', pinyin: 'yuán liào', meaning: 'nguyên liệu' },
{ hanzi: '原则', pinyin: 'yuán zé', meaning: 'nguyên tắc' },
{ hanzi: '圆', pinyin: 'yuán', meaning: 'hình tròn' },
{ hanzi: '愿望', pinyin: 'yuàn wàng', meaning: 'nguyện vọng' },
{ hanzi: '乐器', pinyin: 'yuè qì', meaning: 'nhạc cụ' },
{ hanzi: '晕', pinyin: 'yūn', meaning: 'say (xe)' },
{ hanzi: '运气', pinyin: 'yùn qì', meaning: 'vận may' },
{ hanzi: '运输', pinyin: 'yùn shū', meaning: 'vận tải' },
{ hanzi: '运用', pinyin: 'yùn yòng', meaning: 'vận dụng' },
{ hanzi: '灾害', pinyin: 'zāi hài', meaning: 'thiên tai' },
{ hanzi: '再三', pinyin: 'zài sān', meaning: 'hết lần này đến lần khác' },
{ hanzi: '在乎', pinyin: 'zài hū', meaning: 'để ý' },
{ hanzi: '在于', pinyin: 'zài yú', meaning: 'ở chỗ' },
{ hanzi: '赞成', pinyin: 'zàn chéng', meaning: 'tán thành' },
{ hanzi: '赞美', pinyin: 'zàn měi', meaning: 'ca tụng' },
{ hanzi: '糟糕', pinyin: 'zāo gāo', meaning: 'tồi tệ' },
{ hanzi: '造成', pinyin: 'zào chéng', meaning: 'gây nên' },
{ hanzi: '则', pinyin: 'zé', meaning: 'nhưng' },
{ hanzi: '责备', pinyin: 'zé bèi', meaning: 'trách cứ' },
{ hanzi: '摘', pinyin: 'zhāi', meaning: 'hái' },
{ hanzi: '窄', pinyin: 'zhǎi', meaning: 'hẹp' },
{ hanzi: '粘贴', pinyin: 'zhān tiē', meaning: 'dính, dán' },
{ hanzi: '展开', pinyin: 'zhǎn kāi', meaning: 'xòe ra, triển khai' },
{ hanzi: '展览', pinyin: 'zhǎn lǎn', meaning: 'triển lãm' },
{ hanzi: '占', pinyin: 'zhàn', meaning: 'chiếm' },
{ hanzi: '战争', pinyin: 'zhàn zhēng', meaning: 'chiến tranh' },
{ hanzi: '长辈', pinyin: 'zhǎng bèi', meaning: 'tiền bối' },
{ hanzi: '涨', pinyin: 'zhàng', meaning: 'tăng lên (giá cả, lương)' },
{ hanzi: '掌握', pinyin: 'zhǎng wò', meaning: 'nắm vững' },
{ hanzi: '账户', pinyin: 'zhàng hù', meaning: 'tài khoản' },
{ hanzi: '招待', pinyin: 'zhāo dài', meaning: 'chiêu đãi' },
{ hanzi: '着火', pinyin: 'zháo huǒ', meaning: 'bắt lửa, bén lửa' },
{ hanzi: '着凉', pinyin: 'zháo liáng', meaning: 'nhiễm lạnh' },
{ hanzi: '召开', pinyin: 'zhào kāi', meaning: 'triệu tập (cuộc họp)' },
{ hanzi: '照常', pinyin: 'zhào cháng', meaning: 'như thường lệ' },
{ hanzi: '哲学', pinyin: 'zhé xué', meaning: 'triết học' },
{ hanzi: '针对', pinyin: 'zhēn duì', meaning: 'nhằm (tổ chức, người, vấn đề)' },
{ hanzi: '珍惜', pinyin: 'zhēn xī', meaning: 'trân trọng' },
{ hanzi: '真实', pinyin: 'zhēn shí', meaning: 'chân thực' },
{ hanzi: '诊断', pinyin: 'zhěn duàn', meaning: 'chẩn đoán' },
{ hanzi: '阵', pinyin: 'zhèn', meaning: 'trận (chiến đấu, chiến tranh), khoảng thời gian, mùi hương' },
{ hanzi: '振动', pinyin: 'zhèn dòng', meaning: 'trấn động' },
{ hanzi: '争论', pinyin: 'zhēng lùn', meaning: 'tranh luận' },
{ hanzi: '争取', pinyin: 'zhēng qǔ', meaning: 'tranh thủ (ủng hộ, ý kiến)' },
{ hanzi: '征求', pinyin: 'zhēng qiú', meaning: 'trưng cầu (ý kiến, ý kiến phản hồi), xin (ý kiến lãnh đạo, đồng ý)' },
{ hanzi: '睁', pinyin: 'zhēng', meaning: 'mở to mắt, trợn mắt' },
{ hanzi: '整个', pinyin: 'zhěng gè', meaning: 'cả, toàn bộ' },
{ hanzi: '整齐', pinyin: 'zhěng qí', meaning: 'gọn gàng, ngăn nắp' },
{ hanzi: '整体', pinyin: 'zhěng tǐ', meaning: 'tổng thể' },
{ hanzi: '正', pinyin: 'zhèng', meaning: 'đứng (trái )' },
{ hanzi: '证件', pinyin: 'zhèng jiàn', meaning: 'giấy tờ' },
{ hanzi: '证据', pinyin: 'zhèng jù', meaning: 'chứng cứ' },
{ hanzi: '政府', pinyin: 'zhèng fǔ', meaning: 'chính phủ' },
{ hanzi: '政治', pinyin: 'zhèng zhì', meaning: 'chính trị' },
{ hanzi: '挣', pinyin: 'zhèng', meaning: 'tranh, giành' },
{ hanzi: '支', pinyin: 'zhī', meaning: 'chiếc (lượng từ cho bút…)' },
{ hanzi: '支票', pinyin: 'zhī piào', meaning: 'ngân phiếu' },
{ hanzi: '执照', pinyin: 'zhí zhào', meaning: 'giấy phép' },
{ hanzi: '直', pinyin: 'zhí', meaning: 'thẳng' },
{ hanzi: '指导', pinyin: 'zhǐ dǎo', meaning: 'chỉ đạo' },
{ hanzi: '指挥', pinyin: 'zhǐ huī', meaning: 'chỉ huy' },
{ hanzi: '至今', pinyin: 'zhì jīn', meaning: 'đến nay' },
{ hanzi: '至于', pinyin: 'zhì yú', meaning: 'còn như…..' },
{ hanzi: '志愿者', pinyin: 'zhì yuàn zhě', meaning: 'tình nguyện viên' },
{ hanzi: '制定', pinyin: 'zhì dìng', meaning: 'lập ra, thiết lập, xây dựng, lập (chính sách, qui định, kế hoạch, sách lược, phương án)' },
{ hanzi: '制度', pinyin: 'zhì dù', meaning: 'chế độ, chính sách' },
{ hanzi: '制造', pinyin: 'zhì zào', meaning: 'sản xuất' },
{ hanzi: '制作', pinyin: 'zhì zuò', meaning: 'làm, chế tạo' },
{ hanzi: '治疗', pinyin: 'zhì liáo', meaning: 'điều trị' },
{ hanzi: '秩序', pinyin: 'zhì xù', meaning: 'trật tự' },
{ hanzi: '智慧', pinyin: 'zhì huì', meaning: 'trí tuệ' },
{ hanzi: '中介', pinyin: 'zhōng jiè', meaning: 'môi giới, trung gian' },
{ hanzi: '中心', pinyin: 'zhōng xīn', meaning: 'trung tâm' },
{ hanzi: '中旬', pinyin: 'zhōng xún', meaning: 'trung tuần' },
{ hanzi: '种类', pinyin: 'zhǒng lèi', meaning: 'chủng loại' },
{ hanzi: '重大', pinyin: 'zhòng dà', meaning: 'trọng đại, lớn' },
{ hanzi: '重量', pinyin: 'zhòng liàng', meaning: 'trọng lượng' },
{ hanzi: '周到', pinyin: 'zhōu dào', meaning: 'chu đáo' },
{ hanzi: '猪', pinyin: 'zhū', meaning: 'con lợn' },
{ hanzi: '竹子', pinyin: 'zhú zi', meaning: 'cây trúc' },
{ hanzi: '逐步', pinyin: 'zhú bù', meaning: 'từng bước' },
{ hanzi: '逐渐', pinyin: 'zhú jiàn', meaning: 'dần dần' },
{ hanzi: '主持', pinyin: 'zhǔ chí', meaning: 'dẫn (chương trình),' },
{ hanzi: '主动', pinyin: 'zhǔ dòng', meaning: 'chủ động' },
{ hanzi: '主观', pinyin: 'zhǔ guān', meaning: 'chủ quan' },
{ hanzi: '主人', pinyin: 'zhǔ rén', meaning: 'chủ nhân' },
{ hanzi: '主任', pinyin: 'zhǔ rèn', meaning: 'chủ nhiệm' },
{ hanzi: '主题', pinyin: 'zhǔ tí', meaning: 'chủ đề' },
{ hanzi: '主席', pinyin: 'zhǔ xí', meaning: 'chủ tịch' },
{ hanzi: '主张', pinyin: 'zhǔ zhāng', meaning: 'ý tưởng, ý kiến' },
{ hanzi: '煮', pinyin: 'zhǔ', meaning: 'luộc, đun' },
{ hanzi: '注册', pinyin: 'zhù cè', meaning: 'đăng kí' },
{ hanzi: '祝福', pinyin: 'zhù fú', meaning: 'chúc phúc' },
{ hanzi: '抓', pinyin: 'zhuā', meaning: 'bắt, véo' },
{ hanzi: '抓紧', pinyin: 'zhuā jǐn', meaning: '(tay) nắm chắc, tranh thủ (thời gian)' },
{ hanzi: '专家', pinyin: 'zhuān jiā', meaning: 'chuyên gia' },
{ hanzi: '专心', pinyin: 'zhuān xīn', meaning: 'chuyên tâm' },
{ hanzi: '转变', pinyin: 'zhuǎn biàn', meaning: 'chuyển biến' },
{ hanzi: '转告', pinyin: 'zhuǎn gào', meaning: 'chuyển lời' },
{ hanzi: '装', pinyin: 'zhuāng', meaning: 'đựng, chứa' },
{ hanzi: '装饰', pinyin: 'zhuāng shì', meaning: 'trang hoàng, trang trí' },
{ hanzi: '装修', pinyin: 'zhuāng xiū', meaning: 'sửa nội thất' },
{ hanzi: '状况', pinyin: 'zhuàng kuàng', meaning: 'tình trạng' },
{ hanzi: '状态', pinyin: 'zhuàng tài', meaning: 'trạng thái' },
{ hanzi: '撞', pinyin: 'zhuàng', meaning: 'va vào, đâm vào' },
{ hanzi: '追', pinyin: 'zhuī', meaning: 'đuổi theo' },
{ hanzi: '追求', pinyin: 'zhuī qiú', meaning: 'theo đuổi' },
{ hanzi: '咨询', pinyin: 'zī xún', meaning: 'tư vấn' },
{ hanzi: '姿势', pinyin: 'zī shì', meaning: 'tư thế' },
{ hanzi: '资格', pinyin: 'zī gé', meaning: 'tư cách' },
{ hanzi: '资金', pinyin: 'zī jīn', meaning: 'vốn (tiền)' },
{ hanzi: '资料', pinyin: 'zī liào', meaning: 'tư liệu' },
{ hanzi: '资源', pinyin: 'zī yuán', meaning: 'nguồn tài nguyên' },
{ hanzi: '紫', pinyin: 'zǐ', meaning: 'màu tím' },
{ hanzi: '自从', pinyin: 'zì cóng', meaning: 'từ khi….' },
{ hanzi: '自动', pinyin: 'zì dòng', meaning: 'tự động' },
{ hanzi: '自豪', pinyin: 'zì háo', meaning: 'tự hào, kiêu ngạo' },
{ hanzi: '自觉', pinyin: 'zì jué', meaning: 'tự giác' },
{ hanzi: '自私', pinyin: 'zì sī', meaning: 'ích kỉ' },
{ hanzi: '自由', pinyin: 'zì yóu', meaning: 'tự do' },
{ hanzi: '自愿', pinyin: 'zì yuàn', meaning: 'tình nguyện, tự nguyện' },
{ hanzi: '字母', pinyin: 'zì mǔ', meaning: 'chữ cái' },
{ hanzi: '字幕', pinyin: 'zì mù', meaning: 'phụ đề' },
{ hanzi: '综合', pinyin: 'zōng hé', meaning: 'tổng hợp' },
{ hanzi: '总裁', pinyin: 'zǒng cái', meaning: 'giám đốc' },
{ hanzi: '总共', pinyin: 'zǒng gòng', meaning: 'tổng cộng' },
{ hanzi: '总理', pinyin: 'zǒng lǐ', meaning: 'thủ tướng' },
{ hanzi: '总算', pinyin: 'zǒng suàn', meaning: 'rốt cuộc' },
{ hanzi: '总统', pinyin: 'zǒng tǒng', meaning: 'tổng thống' },
{ hanzi: '总之', pinyin: 'zǒng zhī', meaning: 'tóm lại' },
{ hanzi: '阻止', pinyin: 'zǔ zhī', meaning: 'ngăn chặn, ngăn cản' },
{ hanzi: '组', pinyin: 'zǔ', meaning: 'tổ, cụm, nhóm' },
{ hanzi: '组成', pinyin: 'zǔ chéng', meaning: 'tổ thành' },
{ hanzi: '组合', pinyin: 'zǔ hé', meaning: 'tổ hợp, tổ hợp thành, nhóm' },
{ hanzi: '组织', pinyin: 'zǔ zhī', meaning: 'tổ chức' },
{ hanzi: '最初', pinyin: 'zuì chū', meaning: 'ban đầu' },
{ hanzi: '醉', pinyin: 'zuì', meaning: 'say, say đắm' },
{ hanzi: '尊敬', pinyin: 'zūn jìng', meaning: 'tôn kính, kính trọng' },
{ hanzi: '遵守', pinyin: 'zūn shǒu', meaning: 'tuân thủ' },
{ hanzi: '作品', pinyin: 'zuò pǐn', meaning: 'tác phẩm' },
{ hanzi: '作为', pinyin: 'zuò wéi', meaning: 'coi là, làm, là' },
{ hanzi: '作文', pinyin: 'zuò wén', meaning: 'bài viết' },

];